Waterloop Wlib: memory/New.h File Reference
New.h File Reference
New operators defined for Arduino boards and for other boards use the normal new.
#include <stdlib.h>
Functions
void * operator new (decltype(sizeof(0)) n) noexcept(false)
void * operator new (decltype(sizeof(0)), void *ptr) noexcept(false)
void operator delete (void *p) throw ()
void * operator new[] (decltype(sizeof(0)) n) noexcept(false)
void operator delete[] (void *p) throw ()
Detailed Description
New operators defined for Arduino boards and for other boards use the normal new.
Some versions of Arduino provide a
new.h
but these do not include a definition for placement new. In debug mode, for Wlib develop, the standard C++
<new>
is included, and for all other cases, these operators fall back on the C allocation functions.
Author
Deep Dhillon
Jeff Niu
Date
December 4, 2017
Bug:
No known bugs.
Definition in file New.h.
Function Documentation
void operator delete (void * p) throw () inline
Definition at line 38 of file New.h.
References free().
{
     free(p);
 }
void operator delete[] (void * p) throw () inline
Definition at line 47 of file New.h.
References free().
{
     free(p);
 }
void* operator new (decltype(sizeof(0)) n) inline noexcept
Definition at line 29 of file New.h.
References malloc().
{
     void *memory = malloc(n);
     return memory;
 }
void* operator new (decltype(sizeof(0)) , void * ptr) inline noexcept
Definition at line 34 of file New.h.
{
     return ptr;
 }
void* operator new[] (decltype(sizeof(0)) n) inline noexcept
Definition at line 42 of file New.h.
References malloc().
{
     void *memory = malloc(n);
     return memory;
 }