Waterloop Wlib: wlp::hash_set< Key, Hasher, Equals > Class Template Reference
wlp::hash_set< Key, Hasher, Equals > Class Template Reference
#include <HashSet.h>
Public Types
typedef hash_set< Key, Hasher,
Equals > set_type
typedef hash_table< Key, Key,
Key, SetGetKey< Key >
, SetGetVal< Key >, Hasher,
Equals > table_type
typedef table_type::iterator iterator
typedef table_type::const_iterator const_iterator
typedef table_type::size_type size_type
typedef table_type::percent_type percent_type
typedef Key key_type
Public Member Functions
hash_set (size_type n=12, percent_type max_load=75)
hash_set (const set_type &)=delete
hash_set (set_type &&set)
size_type size () const
size_type capacity () const
percent_type max_load () const
bool empty () const
const table_type * get_backing_table () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void clear () noexcept
template<typename K >
pair< iterator, bool > insert (K &&key)
bool contains (const key_type &key) const
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
iterator erase (const iterator &pos)
bool erase (const key_type &key)
set_type & operator= (const set_type &)=delete
set_type & operator= (set_type &&set)
Private Attributes
table_type m_table
Detailed Description
template<class Key, class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>>
class wlp::hash_set< Key, Hasher, Equals >
Hash set implementation using separate chaining. This implementation supports removal operations, unlike the open addressed set.
Template Parameters
Key the element type
Hash the hash function
Equal the equality function
Definition at line 34 of file HashSet.h.
Member Typedef Documentation
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> typedef table_type::const_iterator wlp::hash_set< Key, Hasher, Equals >::const_iterator
Definition at line 40 of file HashSet.h.
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> typedef table_type::iterator wlp::hash_set< Key, Hasher, Equals >::iterator
Definition at line 39 of file HashSet.h.
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> typedef Key wlp::hash_set< Key, Hasher, Equals >::key_type
Definition at line 44 of file HashSet.h.
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> typedef table_type::percent_type wlp::hash_set< Key, Hasher, Equals >::percent_type
Definition at line 42 of file HashSet.h.
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> typedef hash_set<Key, Hasher, Equals> wlp::hash_set< Key, Hasher, Equals >::set_type
Definition at line 36 of file HashSet.h.
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> typedef table_type::size_type wlp::hash_set< Key, Hasher, Equals >::size_type
Definition at line 41 of file HashSet.h.
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> typedef hash_table<Key, Key, Key, SetGetKey<Key>, SetGetVal<Key>, Hasher, Equals> wlp::hash_set< Key, Hasher, Equals >::table_type
Definition at line 37 of file HashSet.h.
Constructor & Destructor Documentation
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> wlp::hash_set< Key, Hasher, Equals >::hash_set (size_type n = 12, percent_type max_load = 75) inline explicit
Construct a chained hash set, which creates the backing chain hash map instance.
Parameters
n the initial size of the backing array
max_load the maximum load factor before rehash
Definition at line 57 of file HashSet.h.
                 : m_table(n, max_load) {
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> wlp::hash_set< Key, Hasher, Equals >::hash_set (const set_type &) delete
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> wlp::hash_set< Key, Hasher, Equals >::hash_set (set_type && set) inline
Definition at line 63 of file HashSet.h.
                 : m_table(move(set.m_table)) {
         }
Member Function Documentation
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> iterator wlp::hash_set< Key, Hasher, Equals >::begin () inline
Definition at line 87 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::begin(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.begin();
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> const_iterator wlp::hash_set< Key, Hasher, Equals >::begin () const inline
Definition at line 95 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::begin(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.begin();
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> size_type wlp::hash_set< Key, Hasher, Equals >::capacity () const inline
Definition at line 71 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::capacity(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.capacity();
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> void wlp::hash_set< Key, Hasher, Equals >::clear () inline noexcept
Definition at line 103 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::clear(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             m_table.clear();
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> bool wlp::hash_set< Key, Hasher, Equals >::contains (const key_type & key) const inline
Definition at line 112 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::end(), wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.find(key) != m_table.end();
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> bool wlp::hash_set< Key, Hasher, Equals >::empty () const inline
Definition at line 79 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::empty(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.empty();
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> iterator wlp::hash_set< Key, Hasher, Equals >::end () inline
Definition at line 91 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::end(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.end();
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> const_iterator wlp::hash_set< Key, Hasher, Equals >::end () const inline
Definition at line 99 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::end(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.end();
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> iterator wlp::hash_set< Key, Hasher, Equals >::erase (const iterator & pos) inline
Definition at line 124 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::erase(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             iterator tmp = pos;
             ++tmp;
             m_table.erase(pos);
             return tmp;
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> bool wlp::hash_set< Key, Hasher, Equals >::erase (const key_type & key) inline
Definition at line 131 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::erase(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.erase(key) > 0;
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> iterator wlp::hash_set< Key, Hasher, Equals >::find (const key_type & key) inline
Definition at line 116 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.find(key);
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> const_iterator wlp::hash_set< Key, Hasher, Equals >::find (const key_type & key) const inline
Definition at line 120 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.find(key);
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> const table_type* wlp::hash_set< Key, Hasher, Equals >::get_backing_table () const inline
Definition at line 83 of file HashSet.h.
References wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return &m_table;
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> template<typename K > pair<iterator, bool> wlp::hash_set< Key, Hasher, Equals >::insert (K && key) inline
Definition at line 108 of file HashSet.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::insert_unique(), and wlp::hash_set< Key, Hasher, Equals >::m_table.
{
             return m_table.insert_unique(key);
         };
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> percent_type wlp::hash_set< Key, Hasher, Equals >::max_load () const inline
Definition at line 75 of file HashSet.h.
References wlp::hash_set< Key, Hasher, Equals >::m_table, and wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::max_load().
{
             return m_table.max_load();
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> set_type& wlp::hash_set< Key, Hasher, Equals >::operator= (const set_type &) delete
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> set_type& wlp::hash_set< Key, Hasher, Equals >::operator= (set_type && set) inline
Definition at line 137 of file HashSet.h.
References wlp::hash_set< Key, Hasher, Equals >::m_table, and wlp::move().
{
             m_table = move(set.m_table);
             return *this;
         }
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> size_type wlp::hash_set< Key, Hasher, Equals >::size () const inline
Definition at line 67 of file HashSet.h.
References wlp::hash_set< Key, Hasher, Equals >::m_table, and wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::size().
{
             return m_table.size();
         }
Field Documentation
template<class Key , class Hasher = hash <Key, uint16_t>, class Equals = equals <Key>> table_type wlp::hash_set< Key, Hasher, Equals >::m_table private
Definition at line 47 of file HashSet.h.
Referenced by wlp::hash_set< Key, Hasher, Equals >::begin(), wlp::hash_set< Key, Hasher, Equals >::capacity(), wlp::hash_set< Key, Hasher, Equals >::clear(), wlp::hash_set< Key, Hasher, Equals >::contains(), wlp::hash_set< Key, Hasher, Equals >::empty(), wlp::hash_set< Key, Hasher, Equals >::end(), wlp::hash_set< Key, Hasher, Equals >::erase(), wlp::hash_set< Key, Hasher, Equals >::find(), wlp::hash_set< Key, Hasher, Equals >::get_backing_table(), wlp::hash_set< Key, Hasher, Equals >::insert(), wlp::hash_set< Key, Hasher, Equals >::max_load(), wlp::hash_set< Key, Hasher, Equals >::operator=(), and wlp::hash_set< Key, Hasher, Equals >::size().
The documentation for this class was generated from the following file:
wlib/stl/HashSet.h