Waterloop Wlib: wlp::TupleImpl< IndexSequence< Indices... >, Types... > Struct Template Reference
wlp::TupleImpl< IndexSequence< Indices... >, Types... > Struct Template Reference
#include <Tuple.h>
Public Member Functions
template<typename... OtherTypes, typename = typename enable_if< sizeof...(Types) == sizeof...(OtherTypes) >::type>
TupleImpl< IndexSequence< Indices... >, Types... > & operator= (TupleImpl< IndexSequence< Indices... >, OtherTypes... > const &tuple)
template<typename... OtherTypes, typename = typename enable_if< sizeof...(Types) == sizeof...(OtherTypes) >::type>
TupleImpl< IndexSequence< Indices... >, Types... > & operator= (TupleImpl< IndexSequence< Indices... >, OtherTypes... > &&tuple)
template<typename... OtherTypes, typename = typename enable_if< !is_any_of<IsTupleImpl, decay_type<OtherTypes>...>() >::type>
TupleImpl (OtherTypes &&... elements)
Public Member Functions inherited from wlp::TupleElement< Indices, Types >
TupleElement< I, Types > & operator= (TupleElement< J, Q > const &te)
TupleElement< I, Types > & operator= (TupleElement< J, Q > &&te)
TupleElement (U &&u)
Additional Inherited Members
Data Fields inherited from wlp::TupleElement< Indices, Types >
Types value
Detailed Description
template<size_type... Indices, typename... Types>
struct wlp::TupleImpl< IndexSequence< Indices... >, Types... >
The TupleImpl is the base type for tuple that contains the type pack and the index pack, and will inherit from each tuple element.
Template Parameters
Indices the index pack
Types the type pack
Definition at line 205 of file Tuple.h.
Constructor & Destructor Documentation
TupleImpl()
template<size_type... Indices, typename... Types> template<typename... OtherTypes, typename = typename enable_if< !is_any_of<IsTupleImpl, decay_type<OtherTypes>...>() >::type> wlp::TupleImpl< IndexSequence< Indices... >, Types... >::TupleImpl (OtherTypes &&... elements) inline explicit
TupleImpl constructor will instantiate each of its inherit types. This is a universal constructor.
Template Parameters
OtherTypes type pack of the constructed types
Parameters
elements values for each tuple element
Definition at line 256 of file Tuple.h.
                 : TupleElement<Indices, Types>(forward<OtherTypes>(elements))... {
         }
Member Function Documentation
operator=() [1/2]
template<size_type... Indices, typename... Types> template<typename... OtherTypes, typename = typename enable_if< sizeof...(Types) == sizeof...(OtherTypes) >::type> TupleImpl<IndexSequence<Indices...>, Types...>& wlp::TupleImpl< IndexSequence< Indices... >, Types... >::operator= (TupleImpl< IndexSequence< Indices... >, OtherTypes... > const & tuple) inline
Assignment operator to another TupleImpl will expand the assignment operator on each individual tuple element from which this class inherits.
Template Parameters
OtherTypes type pack of the assigned TupleImpl
Parameters
tuple the TupleImpl to assign
Returns
a reference to this tuple
Definition at line 221 of file Tuple.h.
References wlp::swallow().
{
             swallow(static_cast<TupleElement<Indices, TypeAtIndexType<Indices, Types...>> &>(*this).operator=(
                     static_cast<TupleElement<Indices, TypeAtIndexType<Indices, OtherTypes...>> const &>(tuple))...
             );
             return *this;
         }
operator=() [2/2]
template<size_type... Indices, typename... Types> template<typename... OtherTypes, typename = typename enable_if< sizeof...(Types) == sizeof...(OtherTypes) >::type> TupleImpl<IndexSequence<Indices...>, Types...>& wlp::TupleImpl< IndexSequence< Indices... >, Types... >::operator= (TupleImpl< IndexSequence< Indices... >, OtherTypes... > && tuple) inline
Move assignment operator for TupleImpl.
Template Parameters
OtherTypes type pack of the assigned TupleImpl
Parameters
tuple the TupleImpl to assign
Returns
a reference to this tuple
Definition at line 239 of file Tuple.h.
References wlp::move(), and wlp::swallow().
{
             swallow(static_cast<TupleElement<Indices, TypeAtIndexType<Indices, Types...>> &>(*this).operator=(move(
                     static_cast<TupleElement<Indices, TypeAtIndexType<Indices, OtherTypes...>> &&>(tuple)))...
             );
             return *this;
         };
The documentation for this struct was generated from the following file:
stl/Tuple.h