Waterloop Wlib: wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal > Struct Template Reference
wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal > Struct Template Reference
#include <RedBlackTree.h>
Public Types
typedef RedBlackTreeNode< Element > node_type
typedef RedBlackTreeIterator
< Element, Val, Val &, Val
*, GetVal > iterator
typedef RedBlackTreeIterator
< Element, Val, const Val
&, const Val *, GetVal > const_iterator
typedef RedBlackTreeColor color
typedef Ref reference
typedef Ptr pointer
typedef Element element_type
typedef GetVal get_value
Public Member Functions
RedBlackTreeIterator (node_type *node)
RedBlackTreeIterator (const self_type &it)
void increment ()
void decrement ()
bool operator== (const self_type &it) const
bool operator!= (const self_type &it) const
reference operator* () const
pointer operator-> () const
self_type & operator++ ()
self_type operator++ (int)
self_type & operator-- ()
self_type operator-- (int)
self_type & operator= (const self_type &it)
Data Fields
node_type * m_node
get_value m_get_value {}
Private Types
typedef RedBlackTreeIterator
< Element, Val, Ref, Ptr,
GetVal > self_type
Detailed Description
template<typename Element, typename Val, typename Ref, typename Ptr, typename GetVal>
struct wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >
Tree iterator class, templated to enable constant and non-constant derived types. This class should not be used directly.
Template Parameters
Element element type which contains the key and value
Key the node key type
Ref reference to value type, which may be a constant reference
Ptr pointer to value type, which may be a constant pointer
GetVal struct which returns the value of an element
Definition at line 123 of file RedBlackTree.h.
Member Typedef Documentation
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > typedef RedBlackTreeColor wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::color
Definition at line 127 of file RedBlackTree.h.
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > typedef RedBlackTreeIterator<Element, Val, const Val &, const Val *, GetVal> wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::const_iterator
Definition at line 126 of file RedBlackTree.h.
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > typedef Element wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::element_type
Definition at line 130 of file RedBlackTree.h.
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > typedef GetVal wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::get_value
Definition at line 131 of file RedBlackTree.h.
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > typedef RedBlackTreeIterator<Element, Val, Val &, Val *, GetVal> wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::iterator
Definition at line 125 of file RedBlackTree.h.
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > typedef RedBlackTreeNode<Element> wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::node_type
Definition at line 124 of file RedBlackTree.h.
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > typedef Ptr wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::pointer
Definition at line 129 of file RedBlackTree.h.
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > typedef Ref wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::reference
Definition at line 128 of file RedBlackTree.h.
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > typedef RedBlackTreeIterator<Element, Val, Ref, Ptr, GetVal> wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::self_type private
Definition at line 134 of file RedBlackTree.h.
Constructor & Destructor Documentation
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::RedBlackTreeIterator (node_type * node) inline
Constructor from node.
Parameters
node to point to
Definition at line 152 of file RedBlackTree.h.
                 : m_node(node) {
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::RedBlackTreeIterator (const self_type & it) inline
Constructor from constant reference.
Parameters
it iterator to copy
Definition at line 161 of file RedBlackTree.h.
                 : m_node(it.m_node) {
         }
Member Function Documentation
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > void wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::decrement () inline
Move the iterator to the previous ordered node in the tree.
Definition at line 189 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_color, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node, wlp::RedBlackTreeNode< Element >::m_parent, wlp::RedBlackTreeNode< Element >::m_right, and wlp::RedBlackTreeColor::RED.
Referenced by wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator--().
{
             if (m_node->m_color == color::RED && m_node->m_parent->m_parent == m_node) {
                 m_node = m_node->m_right;
             } else if (m_node->m_left) {
                 node_type *child = m_node->m_left;
                 while (child->m_right) {
                     child = child->m_right;
                 }
                 m_node = child;
             } else {
                 node_type *parent = m_node->m_parent;
                 while (m_node == parent->m_left) {
                     m_node = parent;
                     parent = parent->m_parent;
                 }
                 m_node = parent;
             }
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > void wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::increment () inline
Move the iterator to the next ordered node in the tree.
Definition at line 168 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
Referenced by wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator++().
{
             if (m_node->m_right) {
                 m_node = m_node->m_right;
                 while (m_node->m_left) {
                     m_node = m_node->m_left;
                 }
             } else {
                 node_type *parent = m_node->m_parent;
                 while (m_node == parent->m_right) {
                     m_node = parent;
                     parent = parent->m_parent;
                 }
                 if (m_node->m_right != parent) {
                     m_node = parent;
                 }
             }
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > bool wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator!= (const self_type & it) const inline
Iterator inequality operator.
Parameters
it iterator to compare
Returns
true if they point to different nodes
Definition at line 224 of file RedBlackTree.h.
References wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node.
{
             return m_node != it.m_node;
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > reference wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator* () const inline
Deference operator.
Returns
reference to the value of the node pointed to by the iterator
Definition at line 234 of file RedBlackTree.h.
References KEY_EXCEPTION, wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_get_value, wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node, and THROW.
{
             if (m_node == nullptr) {
                 THROW(KEY_EXCEPTION("Accessing invalid iterator"))
             }
             return m_get_value(m_node->m_element);
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > self_type& wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator++ () inline
Prefix increment operator moves the iterator to the next ordered node in the tree, or pass-the-end if the iterator has reached the rightmost end of the tree.
Returns
reference to this iterator
Definition at line 261 of file RedBlackTree.h.
References wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::increment().
{
             increment();
             return *this;
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > self_type wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator++ (int) inline
Postfix increment operator moves the iterator to the next ordered node in the tree, or pass-the-end if the iterator has reached the rightmost end of the tree.
Returns
a copy of the iterator before the increment
Definition at line 273 of file RedBlackTree.h.
References wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::increment().
{
             iterator tmp = *this;
             increment();
             return tmp;
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > self_type& wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator-- () inline
Prefix decrement operator moves the iterator to the previous ordered node in the tree. Iterator does not move past the begin.
Returns
reference to this iterator
Definition at line 285 of file RedBlackTree.h.
References wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::decrement().
{
             decrement();
             return *this;
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > self_type wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator-- (int) inline
Postfix decrement operator moves the iterator to the previous ordered node in the tree. Iterator does not move past the begin.
Returns
a copy of the iterator before the increment
Definition at line 296 of file RedBlackTree.h.
References wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::decrement().
{
             iterator tmp = *this;
             decrement();
             return tmp;
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > pointer wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator-> () const inline
Pointer operator.
Returns
pointer to the value of the node pointer to by the iterator
Definition at line 247 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_get_value, and wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node.
{
             if (m_node == nullptr) {
                 return nullptr;
             }
             return &m_get_value(m_node->m_element);
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > self_type& wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator= (const self_type & it) inline
Copy assignment operator.
Parameters
it iterator to assign
Returns
reference to this iterator
Definition at line 308 of file RedBlackTree.h.
References wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node.
{
             m_node = it.m_node;
             return *this;
         }
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > bool wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator== (const self_type & it) const inline
Iterator equality operator.
Parameters
it iterator to compare
Returns
true if they point to the same node
Definition at line 214 of file RedBlackTree.h.
References wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node.
{
             return m_node == it.m_node;
         }
Field Documentation
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > get_value wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_get_value {}
Functor used to obtain element value.
Definition at line 145 of file RedBlackTree.h.
Referenced by wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator*(), and wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator->().
template<typename Element , typename Val , typename Ref , typename Ptr , typename GetVal > node_type* wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node
The tree node pointed to by this iterator.
Definition at line 140 of file RedBlackTree.h.
Referenced by wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::decrement(), wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::erase(), wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::increment(), wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_unique(), wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator!=(), wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator*(), wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator->(), wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator=(), and wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::operator==().
The documentation for this struct was generated from the following file:
wlib/stl/RedBlackTree.h