Waterloop Wlib: wlp::initializer_list< val_t > Class Template Reference
wlp::initializer_list< val_t > Class Template Reference
#include <InitializerList.h>
Public Types
typedef val_t value_type
typedef const val_t & reference
typedef const val_t & const_reference
typedef wlp::size_type size_type
typedef const val_t * iterator
typedef const val_t * const_iterator
Public Member Functions
constexpr initializer_list () noexcept
constexpr size_type size () const noexcept
constexpr const_iterator begin () const noexcept
constexpr const_iterator end () const noexcept
Private Member Functions
constexpr initializer_list (const_iterator arr, size_type len)
Private Attributes
iterator m_arr
size_type m_len
Detailed Description
template<typename val_t>
class wlp::initializer_list< val_t >
Definition at line 9 of file InitializerList.h.
Member Typedef Documentation
template<typename val_t> typedef const val_t* wlp::initializer_list< val_t >::const_iterator
Definition at line 16 of file InitializerList.h.
template<typename val_t> typedef const val_t& wlp::initializer_list< val_t >::const_reference
Definition at line 13 of file InitializerList.h.
template<typename val_t> typedef const val_t* wlp::initializer_list< val_t >::iterator
Definition at line 15 of file InitializerList.h.
template<typename val_t> typedef const val_t& wlp::initializer_list< val_t >::reference
Definition at line 12 of file InitializerList.h.
template<typename val_t> typedef wlp::size_type wlp::initializer_list< val_t >::size_type
Definition at line 14 of file InitializerList.h.
template<typename val_t> typedef val_t wlp::initializer_list< val_t >::value_type
Definition at line 11 of file InitializerList.h.
Constructor & Destructor Documentation
template<typename val_t> constexpr wlp::initializer_list< val_t >::initializer_list (const_iterator arr, size_type len) inline private
Definition at line 22 of file InitializerList.h.
             : m_arr(arr), m_len(len) {}
template<typename val_t> constexpr wlp::initializer_list< val_t >::initializer_list () inline noexcept
Definition at line 26 of file InitializerList.h.
             : m_arr(0), m_len(0) {}
Member Function Documentation
template<typename val_t> constexpr const_iterator wlp::initializer_list< val_t >::begin () const inline noexcept
Definition at line 35 of file InitializerList.h.
References wlp::initializer_list< val_t >::m_arr.
Referenced by wlp::initializer_list< val_t >::end(), and wlp::vector2d< val_t >::operator=().
{
             return m_arr;
         }
template<typename val_t> constexpr const_iterator wlp::initializer_list< val_t >::end () const inline noexcept
Definition at line 40 of file InitializerList.h.
References wlp::initializer_list< val_t >::begin(), and wlp::initializer_list< val_t >::size().
{
             return begin() + size();
         }
template<typename val_t> constexpr size_type wlp::initializer_list< val_t >::size () const inline noexcept
Definition at line 30 of file InitializerList.h.
References wlp::initializer_list< val_t >::m_len.
Referenced by wlp::initializer_list< val_t >::end().
{
             return m_len;
         }
Field Documentation
template<typename val_t> iterator wlp::initializer_list< val_t >::m_arr private
Definition at line 19 of file InitializerList.h.
Referenced by wlp::initializer_list< val_t >::begin().
template<typename val_t> size_type wlp::initializer_list< val_t >::m_len private
Definition at line 20 of file InitializerList.h.
Referenced by wlp::initializer_list< val_t >::size().
The documentation for this class was generated from the following file:
wlib/stl/InitializerList.h