Waterloop Wlib: wlp::array_heap< T, Cmp > Class Template Reference
wlp::array_heap< T, Cmp > Class Template Reference
#include <ArrayHeap.h>
Public Types
typedef Cmp comparator
typedef array_heap< T > heap_t
typedef array_list< T >::val_type val_type
typedef array_list< T >::size_type size_type
typedef array_list< T >::list_type array_list_t
typedef array_list< T >::iterator iterator
typedef array_list< T >
::const_iterator const_iterator
Public Member Functions
array_heap (size_type initial_capacity=12)
array_heap (const heap_t &)=delete
array_heap (heap_t &&heap)
void push (const val_type &value)
void push (val_type &&value)
void pop ()
const val_type & top ()
bool empty () const
size_type size () const
size_type capacity () const
array_list_t * get_array_list ()
heap_t & operator= (const heap_t &)=delete
heap_t & operator= (heap_t &&heap)
Private Attributes
array_list_t m_list
comparator m_cmp
Detailed Description
template<typename T, class Cmp = comparator<T>>
class wlp::array_heap< T, Cmp >
A basic heap implementation using
ArrayList
as the backing structure. May be used as a priority queue.
Template Parameters
T data type
Cmp comparator type, which uses the default
Definition at line 483 of file ArrayHeap.h.
Member Typedef Documentation
template<typename T , class Cmp = comparator<T>> typedef array_list<T>::list_type wlp::array_heap< T, Cmp >::array_list_t
Definition at line 489 of file ArrayHeap.h.
template<typename T , class Cmp = comparator<T>> typedef Cmp wlp::array_heap< T, Cmp >::comparator
Definition at line 485 of file ArrayHeap.h.
template<typename T , class Cmp = comparator<T>> typedef array_list<T>::const_iterator wlp::array_heap< T, Cmp >::const_iterator
Definition at line 491 of file ArrayHeap.h.
template<typename T , class Cmp = comparator<T>> typedef array_heap<T> wlp::array_heap< T, Cmp >::heap_t
Definition at line 486 of file ArrayHeap.h.
template<typename T , class Cmp = comparator<T>> typedef array_list<T>::iterator wlp::array_heap< T, Cmp >::iterator
Definition at line 490 of file ArrayHeap.h.
template<typename T , class Cmp = comparator<T>> typedef array_list<T>::size_type wlp::array_heap< T, Cmp >::size_type
Definition at line 488 of file ArrayHeap.h.
template<typename T , class Cmp = comparator<T>> typedef array_list<T>::val_type wlp::array_heap< T, Cmp >::val_type
Definition at line 487 of file ArrayHeap.h.
Constructor & Destructor Documentation
template<typename T , class Cmp = comparator<T>> wlp::array_heap< T, Cmp >::array_heap (size_type initial_capacity = 12) inline explicit
Constructor with a specified initial capacity for the backing array list.
Parameters
initial_capacity initial capacity of the backing array
Definition at line 510 of file ArrayHeap.h.
                 : m_list(initial_capacity),
                   m_cmp(Cmp()) {
         }
template<typename T , class Cmp = comparator<T>> wlp::array_heap< T, Cmp >::array_heap (const heap_t &) delete
Disable copy construction.
template<typename T , class Cmp = comparator<T>> wlp::array_heap< T, Cmp >::array_heap (heap_t && heap) inline
Move copy constructor.
Parameters
heap array heap whose resources to transfer
Definition at line 525 of file ArrayHeap.h.
                 : m_list(move(heap.m_list)),
                   m_cmp(move(heap.m_cmp)) {
         }
Member Function Documentation
template<typename T , class Cmp = comparator<T>> size_type wlp::array_heap< T, Cmp >::capacity () const inline
Returns
the size of the backing array
Definition at line 586 of file ArrayHeap.h.
References wlp::array_list< T >::capacity().
{
             return m_list.capacity();
         }
template<typename T , class Cmp = comparator<T>> bool wlp::array_heap< T, Cmp >::empty () const inline
Returns
whether the heap is empty
Definition at line 572 of file ArrayHeap.h.
References wlp::array_list< T >::empty().
{
             return m_list.empty();
         }
template<typename T , class Cmp = comparator<T>> array_list_t* wlp::array_heap< T, Cmp >::get_array_list () inline
Returns
a pointer to the backing array list
Definition at line 593 of file ArrayHeap.h.
{
             return &m_list;
         }
template<typename T , class Cmp = comparator<T>> heap_t& wlp::array_heap< T, Cmp >::operator= (const heap_t &) delete
Disable copy assignment.
Returns
reference to this heap
template<typename T , class Cmp = comparator<T>> heap_t& wlp::array_heap< T, Cmp >::operator= (heap_t && heap) inline
Move assignment operator.
Parameters
heap array heap whose resources to transfer
Returns
reference to this heap
Definition at line 610 of file ArrayHeap.h.
References wlp::move().
{
             m_list = move(heap.m_list);
             return *this;
         }
template<typename T , class Cmp = comparator<T>> void wlp::array_heap< T, Cmp >::pop () inline
Pop the top element from the heap.
Definition at line 553 of file ArrayHeap.h.
References wlp::array_list< T >::begin(), wlp::array_list< T >::end(), wlp::array_list< T >::pop_back(), and wlp::pop_heap().
                    {
             pop_heap(m_list.begin(), m_list.end(), m_cmp);
             m_list.pop_back();
         }
template<typename T , class Cmp = comparator<T>> void wlp::array_heap< T, Cmp >::push (const val_type & value) inline
Push an element onto the heap.
Parameters
value value to insert
Definition at line 535 of file ArrayHeap.h.
References wlp::array_list< T >::begin(), wlp::array_list< T >::end(), wlp::array_list< T >::push_back(), and wlp::push_heap().
{
             m_list.push_back(value);
             push_heap(m_list.begin(), m_list.end(), m_cmp);
         }
template<typename T , class Cmp = comparator<T>> void wlp::array_heap< T, Cmp >::push (val_type && value) inline
Push an rvalue onto the heap.
Parameters
value rvalue to insert
Definition at line 545 of file ArrayHeap.h.
References wlp::array_list< T >::begin(), wlp::array_list< T >::end(), wlp::array_list< T >::push_back(), and wlp::push_heap().
{
             m_list.push_back(forward<val_type>(value));
             push_heap(m_list.begin(), m_list.end(), m_cmp);
         }
template<typename T , class Cmp = comparator<T>> size_type wlp::array_heap< T, Cmp >::size () const inline
Returns
the number of elements in the heap
Definition at line 579 of file ArrayHeap.h.
References wlp::array_list< T >::size().
{
             return m_list.size();
         }
template<typename T , class Cmp = comparator<T>> const val_type& wlp::array_heap< T, Cmp >::top () inline
Get a reference to the top element on the heap. Modification of the element is disabled in order to preserve heap property.
Returns
reference to the top element
Definition at line 565 of file ArrayHeap.h.
References wlp::array_list< T >::front().
{
             return m_list.front();
         }
Field Documentation
template<typename T , class Cmp = comparator<T>> comparator wlp::array_heap< T, Cmp >::m_cmp private
The comparator instance.
Definition at line 501 of file ArrayHeap.h.
template<typename T , class Cmp = comparator<T>> array_list_t wlp::array_heap< T, Cmp >::m_list private
The backing array list.
Definition at line 497 of file ArrayHeap.h.
The documentation for this class was generated from the following file:
wlib/stl/ArrayHeap.h