Waterloop Wlib: wlp::hash_map< Key, Val, Hasher, Equals > Class Template Reference
wlp::hash_map< Key, Val, Hasher, Equals > Class Template Reference
#include <HashMap.h>
Public Types
typedef hash_map< Key, Val,
Hasher, Equals > map_type
typedef hash_table< tuple< Key,
Val >, Key, Val, MapGetKey
< Key, Val >, MapGetVal< Key,
Val >, Hasher, Equals > table_type
typedef table_type::iterator iterator
typedef table_type::const_iterator const_iterator
typedef table_type::size_type size_type
typedef table_type::percent_type percent_type
typedef Key key_type
typedef Val val_type
Public Member Functions
hash_map (size_type n=12, percent_type max_load=75)
hash_map (const map_type &)=delete
hash_map (map_type &&map)
size_type size () const
size_type capacity () const
percent_type max_load () const
bool empty () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
void clear () noexcept
template<typename K , typename V >
pair< iterator, bool > insert (K &&key, V &&val)
template<typename K , typename V >
pair< iterator, bool > insert_or_assign (K &&key, V &&val)
iterator erase (const iterator &pos)
bool erase (const key_type &key)
val_type & at (const key_type &key)
const val_type & at (const key_type &key) const
bool contains (const key_type &key) const
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
template<typename K >
val_type & operator[] (K &&key)
map_type & operator= (const map_type &)=delete
map_type & operator= (map_type &&map)
Private Attributes
table_type m_table
Detailed Description
template<typename Key, typename Val, typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>>
class wlp::hash_map< Key, Val, Hasher, Equals >
Hash map implemented using separate chaining, in the spirit of std::unordered_map.
Template Parameters
Key key type
Val value type
Hasher hash function
Equals key equality function
Definition at line 39 of file HashMap.h.
Member Typedef Documentation
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> typedef table_type::const_iterator wlp::hash_map< Key, Val, Hasher, Equals >::const_iterator
Definition at line 48 of file HashMap.h.
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> typedef table_type::iterator wlp::hash_map< Key, Val, Hasher, Equals >::iterator
Definition at line 47 of file HashMap.h.
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> typedef Key wlp::hash_map< Key, Val, Hasher, Equals >::key_type
Definition at line 52 of file HashMap.h.
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> typedef hash_map<Key, Val, Hasher, Equals> wlp::hash_map< Key, Val, Hasher, Equals >::map_type
Definition at line 41 of file HashMap.h.
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> typedef table_type::percent_type wlp::hash_map< Key, Val, Hasher, Equals >::percent_type
Definition at line 50 of file HashMap.h.
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> typedef table_type::size_type wlp::hash_map< Key, Val, Hasher, Equals >::size_type
Definition at line 49 of file HashMap.h.
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> typedef hash_table<tuple<Key, Val>, Key, Val, MapGetKey<Key, Val>, MapGetVal<Key, Val>, Hasher, Equals > wlp::hash_map< Key, Val, Hasher, Equals >::table_type
Definition at line 46 of file HashMap.h.
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> typedef Val wlp::hash_map< Key, Val, Hasher, Equals >::val_type
Definition at line 53 of file HashMap.h.
Constructor & Destructor Documentation
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> wlp::hash_map< Key, Val, Hasher, Equals >::hash_map (size_type n = 12, percent_type max_load = 75) inline explicit
Definition at line 59 of file HashMap.h.
                 : m_table(n, max_load) {
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> wlp::hash_map< Key, Val, Hasher, Equals >::hash_map (const map_type &) delete
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> wlp::hash_map< Key, Val, Hasher, Equals >::hash_map (map_type && map) inline
Definition at line 65 of file HashMap.h.
                 : m_table(move(map.m_table)) {
         }
Member Function Documentation
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> val_type& wlp::hash_map< Key, Val, Hasher, Equals >::at (const key_type & key) inline
Definition at line 130 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return *m_table.find(key);
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> const val_type& wlp::hash_map< Key, Val, Hasher, Equals >::at (const key_type & key) const inline
Definition at line 134 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return *m_table.find(key);
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> iterator wlp::hash_map< Key, Val, Hasher, Equals >::begin () inline
Definition at line 85 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::begin(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.begin();
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> const_iterator wlp::hash_map< Key, Val, Hasher, Equals >::begin () const inline
Definition at line 89 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::begin(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.begin();
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> size_type wlp::hash_map< Key, Val, Hasher, Equals >::capacity () const inline
Definition at line 73 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::capacity(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.capacity();
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> void wlp::hash_map< Key, Val, Hasher, Equals >::clear () inline noexcept
Definition at line 101 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::clear(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             m_table.clear();
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> bool wlp::hash_map< Key, Val, Hasher, Equals >::contains (const key_type & key) const inline
Definition at line 138 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::end(), wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.find(key) != m_table.end();
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> bool wlp::hash_map< Key, Val, Hasher, Equals >::empty () const inline
Definition at line 81 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::empty(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.empty();
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> iterator wlp::hash_map< Key, Val, Hasher, Equals >::end () inline
Definition at line 93 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::end(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.end();
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> const_iterator wlp::hash_map< Key, Val, Hasher, Equals >::end () const inline
Definition at line 97 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::end(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.end();
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> iterator wlp::hash_map< Key, Val, Hasher, Equals >::erase (const iterator & pos) inline
Definition at line 119 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::erase(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             iterator tmp = pos;
             ++tmp;
             m_table.erase(pos);
             return tmp;
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> bool wlp::hash_map< Key, Val, Hasher, Equals >::erase (const key_type & key) inline
Definition at line 126 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::erase(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.erase(key) > 0;
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> iterator wlp::hash_map< Key, Val, Hasher, Equals >::find (const key_type & key) inline
Definition at line 142 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.find(key);
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> const_iterator wlp::hash_map< Key, Val, Hasher, Equals >::find (const key_type & key) const inline
Definition at line 146 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find(), and wlp::hash_map< Key, Val, Hasher, Equals >::m_table.
{
             return m_table.find(key);
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> template<typename K , typename V > pair<iterator, bool> wlp::hash_map< Key, Val, Hasher, Equals >::insert (K && key, V && val) inline
Definition at line 106 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::insert_unique(), wlp::hash_map< Key, Val, Hasher, Equals >::m_table, and wlp::make_tuple().
{
             return m_table.insert_unique(make_tuple(forward<K>(key), forward<V>(val)));
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> template<typename K , typename V > pair<iterator, bool> wlp::hash_map< Key, Val, Hasher, Equals >::insert_or_assign (K && key, V && val) inline
Definition at line 111 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::insert_unique(), wlp::pair< First, Second >::m_first, wlp::pair< First, Second >::m_second, wlp::hash_map< Key, Val, Hasher, Equals >::m_table, and wlp::make_tuple().
{
             pair<iterator, bool> result = m_table.insert_unique(make_tuple(forward<K>(key), forward<V>(val)));
             if (!result.m_second) {
                 *result.m_first = forward<V>(val);
             }
             return result;
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> percent_type wlp::hash_map< Key, Val, Hasher, Equals >::max_load () const inline
Definition at line 77 of file HashMap.h.
References wlp::hash_map< Key, Val, Hasher, Equals >::m_table, and wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::max_load().
{
             return m_table.max_load();
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> map_type& wlp::hash_map< Key, Val, Hasher, Equals >::operator= (const map_type &) delete
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> map_type& wlp::hash_map< Key, Val, Hasher, Equals >::operator= (map_type && map) inline
Definition at line 157 of file HashMap.h.
References wlp::hash_map< Key, Val, Hasher, Equals >::m_table, and wlp::move().
{
             m_table = move(map.m_table);
             return *this;
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> template<typename K > val_type& wlp::hash_map< Key, Val, Hasher, Equals >::operator[] (K && key) inline
Definition at line 151 of file HashMap.h.
References wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find_or_insert(), wlp::hash_map< Key, Val, Hasher, Equals >::m_table, and wlp::make_tuple().
{
             return get<1>(m_table.find_or_insert(make_tuple(forward<K>(key), val_type())));
         }
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> size_type wlp::hash_map< Key, Val, Hasher, Equals >::size () const inline
Definition at line 69 of file HashMap.h.
References wlp::hash_map< Key, Val, Hasher, Equals >::m_table, and wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::size().
{
             return m_table.size();
         }
Field Documentation
template<typename Key , typename Val , typename Hasher = hash<Key, uint16_t>, typename Equals = equals<Key>> table_type wlp::hash_map< Key, Val, Hasher, Equals >::m_table private
Definition at line 56 of file HashMap.h.
Referenced by wlp::hash_map< Key, Val, Hasher, Equals >::at(), wlp::hash_map< Key, Val, Hasher, Equals >::begin(), wlp::hash_map< Key, Val, Hasher, Equals >::capacity(), wlp::hash_map< Key, Val, Hasher, Equals >::clear(), wlp::hash_map< Key, Val, Hasher, Equals >::contains(), wlp::hash_map< Key, Val, Hasher, Equals >::empty(), wlp::hash_map< Key, Val, Hasher, Equals >::end(), wlp::hash_map< Key, Val, Hasher, Equals >::erase(), wlp::hash_map< Key, Val, Hasher, Equals >::find(), wlp::hash_map< Key, Val, Hasher, Equals >::insert(), wlp::hash_map< Key, Val, Hasher, Equals >::insert_or_assign(), wlp::hash_map< Key, Val, Hasher, Equals >::max_load(), wlp::hash_map< Key, Val, Hasher, Equals >::operator=(), wlp::hash_map< Key, Val, Hasher, Equals >::operator[](), and wlp::hash_map< Key, Val, Hasher, Equals >::size().
The documentation for this class was generated from the following file:
wlib/stl/HashMap.h