Waterloop Wlib: wlp::unique_ptr< T > Class Template Reference
wlp::unique_ptr< T > Class Template Reference
#include <UniquePtr.h>
Public Types
typedef T * pointer
typedef T val_type
Public Member Functions
unique_ptr ()
unique_ptr (pointer ptr)
unique_ptr (unique_ptr_t &&ptr)
template<typename U >
unique_ptr (unique_ptr< U > &&ptr)
~unique_ptr ()
unique_ptr_t & operator= (unique_ptr_t &&ptr)
template<typename U >
unique_ptr_t & operator= (unique_ptr< U > &&ptr)
unique_ptr_t & operator= (unspecified_pointer_type)
add_lvalue_reference< val_type >
::type operator* () const
pointer operator-> () const
pointer get () const
operator unspecified_bool_type () const
pointer release ()
void reset (pointer ptr=pointer())
void swap (unique_ptr_t &&ptr)
Private Types
typedef T *unique_ptr::* unspecified_bool_type
typedef T *unique_ptr::* unspecified_pointer_type
typedef unique_ptr< T > unique_ptr_t
Private Member Functions
unique_ptr (const unique_ptr_t &)=delete
template<typename U >
unique_ptr (const unique_ptr< U > &)=delete
unique_ptr_t & operator= (const unique_ptr_t &)=delete
template<typename U >
unique_ptr_t & operator= (const unique_ptr< U > &)=delete
Private Attributes
val_type * m_ptr
Detailed Description
template<typename T>
class wlp::unique_ptr< T >
A unique pointer is a smart pointer that handles exactly one pointer that cannot and should not at any moment be shared with another class.
This class is an object that wraps a usual pointer. This means that the object cannot escape local variable scopes. To escape a pointer from the local variable scope,
release
can be called to remove ownership of the pointer.
The unique pointer automatically handles the deletion of the pointer and associated resources in its destructor when the class reaches the end of scope.
Supplying a non-dynamically allocated pointer or sharing a provided pointer with different unique pointer leads to undefined behaviour, and with Memory, segmentation faults.
Construction is recommended with
make_unique
.
Unique pointer class does not currently support multiple deleter types, and uses only functions in Memory. Adding deleters for other Memory solutions can be a future feature, but makes the class more complex.
Template Parameters
T the type pointed to by this unique pointer
T_Deleter deleter type used to free the pointer
Definition at line 48 of file UniquePtr.h.
Member Typedef Documentation
template<typename T> typedef T* wlp::unique_ptr< T >::pointer
Definition at line 54 of file UniquePtr.h.
template<typename T> typedef unique_ptr<T> wlp::unique_ptr< T >::unique_ptr_t private
Definition at line 51 of file UniquePtr.h.
template<typename T> typedef T* unique_ptr::* wlp::unique_ptr< T >::unspecified_bool_type private
Definition at line 49 of file UniquePtr.h.
template<typename T> typedef T* unique_ptr::* wlp::unique_ptr< T >::unspecified_pointer_type private
Definition at line 50 of file UniquePtr.h.
template<typename T> typedef T wlp::unique_ptr< T >::val_type
Definition at line 55 of file UniquePtr.h.
Constructor & Destructor Documentation
template<typename T> wlp::unique_ptr< T >::unique_ptr () inline
Definition at line 62 of file UniquePtr.h.
                 : m_ptr(pointer()) {
         }
template<typename T> wlp::unique_ptr< T >::unique_ptr (pointer ptr) inline explicit
Definition at line 67 of file UniquePtr.h.
                 : m_ptr(ptr) {
         }
template<typename T> wlp::unique_ptr< T >::unique_ptr (unique_ptr_t && ptr) inline
Definition at line 72 of file UniquePtr.h.
                 : m_ptr(ptr.release()) {
         }
template<typename T> template<typename U > wlp::unique_ptr< T >::unique_ptr (unique_ptr< U > && ptr) inline
Definition at line 77 of file UniquePtr.h.
                 : m_ptr(ptr.release()) {
         };
template<typename T> wlp::unique_ptr< T >::~unique_ptr () inline
Definition at line 81 of file UniquePtr.h.
References wlp::unique_ptr< T >::reset().
                       {
             reset();
         }
template<typename T> wlp::unique_ptr< T >::unique_ptr (const unique_ptr_t &) private delete
template<typename T> template<typename U > wlp::unique_ptr< T >::unique_ptr (const unique_ptr< U > &) private delete
Member Function Documentation
template<typename T> pointer wlp::unique_ptr< T >::get () const inline
Definition at line 112 of file UniquePtr.h.
References wlp::unique_ptr< T >::m_ptr.
Referenced by wlp::operator!=(), wlp::operator<(), wlp::operator==(), wlp::operator>(), and wlp::operator>=().
{
             return m_ptr;
         }
template<typename T> wlp::unique_ptr< T >::operator unspecified_bool_type () const inline
Definition at line 117 of file UniquePtr.h.
References wlp::unique_ptr< T >::m_ptr.
{
             return m_ptr == nullptr ? 0 : &unique_ptr::m_ptr;
         }
template<typename T> add_lvalue_reference<val_type>::type wlp::unique_ptr< T >::operator* () const inline
Definition at line 101 of file UniquePtr.h.
References wlp::unique_ptr< T >::m_ptr, NULLPTR_EXCEPTION, and THROW.
{
             if (m_ptr == nullptr) {
                 THROW(NULLPTR_EXCEPTION("Unique pointer is null"))
             }
             return *m_ptr;
         };
template<typename T> pointer wlp::unique_ptr< T >::operator-> () const inline
Definition at line 108 of file UniquePtr.h.
References wlp::unique_ptr< T >::m_ptr.
{
             return m_ptr;
         }
template<typename T> unique_ptr_t& wlp::unique_ptr< T >::operator= (unique_ptr_t && ptr) inline
Definition at line 85 of file UniquePtr.h.
References wlp::unique_ptr< T >::reset().
{
             reset(ptr.release());
             return *this;
         }
template<typename T> template<typename U > unique_ptr_t& wlp::unique_ptr< T >::operator= (unique_ptr< U > && ptr) inline
Definition at line 91 of file UniquePtr.h.
References wlp::unique_ptr< T >::reset().
{
             reset(ptr.release());
             return *this;
         };
template<typename T> unique_ptr_t& wlp::unique_ptr< T >::operator= (unspecified_pointer_type) inline
Definition at line 96 of file UniquePtr.h.
References wlp::unique_ptr< T >::reset().
{
             reset();
             return *this;
         }
template<typename T> unique_ptr_t& wlp::unique_ptr< T >::operator= (const unique_ptr_t &) private delete
template<typename T> template<typename U > unique_ptr_t& wlp::unique_ptr< T >::operator= (const unique_ptr< U > &) private delete
template<typename T> pointer wlp::unique_ptr< T >::release () inline
Definition at line 121 of file UniquePtr.h.
References wlp::unique_ptr< T >::m_ptr.
{
             pointer ptr = m_ptr;
             m_ptr = nullptr;
             return ptr;
         }
template<typename T> void wlp::unique_ptr< T >::reset (pointer ptr = pointer()) inline
Definition at line 127 of file UniquePtr.h.
References wlp::unique_ptr< T >::m_ptr.
Referenced by wlp::unique_ptr< T >::operator=(), wlp::unique_ptr< T[]>::operator=(), wlp::unique_ptr< T >::~unique_ptr(), and wlp::unique_ptr< T[]>::~unique_ptr().
{
             if (ptr != m_ptr) {
                 free<val_type>(m_ptr);
                 m_ptr = ptr;
             }
         }
template<typename T> void wlp::unique_ptr< T >::swap (unique_ptr_t && ptr) inline
Definition at line 134 of file UniquePtr.h.
References wlp::unique_ptr< T >::m_ptr, and wlp::swap().
Referenced by wlp::swap().
{
             wlp::swap(m_ptr, ptr.m_ptr);
         }
Field Documentation
template<typename T> val_type* wlp::unique_ptr< T >::m_ptr private
Definition at line 58 of file UniquePtr.h.
Referenced by wlp::unique_ptr< T >::get(), wlp::unique_ptr< T[]>::get(), wlp::unique_ptr< T >::operator unspecified_bool_type(), wlp::unique_ptr< T[]>::operator unspecified_bool_type(), wlp::unique_ptr< T >::operator*(), wlp::unique_ptr< T >::operator->(), wlp::unique_ptr< T[]>::operator[](), wlp::unique_ptr< T >::release(), wlp::unique_ptr< T[]>::release(), wlp::unique_ptr< T >::reset(), wlp::unique_ptr< T[]>::reset(), wlp::unique_ptr< T >::swap(), and wlp::unique_ptr< T[]>::swap().
The documentation for this class was generated from the following file:
wlib/stl/UniquePtr.h