Waterloop Wlib: wlp::array2d< val_t, size_t > Class Template Reference
wlp::array2d< val_t, size_t > Class Template Reference
#include <Array2D.h>
Public Member Functions
array2d (size_t x, size_t y)
array2d (wlp::initializer_list< wlp::initializer_list< val_t >> l)
array2d (array2d< val_t, size_t > &&arr) noexcept
~array2d ()
size_t x () const
size_t y () const
size_t xy () const
void zero_clear ()
array2d< val_t, size_t > & operator= (array2d< val_t, size_t > &&arr) noexcept
val_t ** get ()
__array2d_access< val_t, size_t > operator[] (size_t x)
array2d (const array2d< val_t, size_t > &)=delete
array2d< val_t, size_t > & operator= (const array2d< val_t, size_t > &)=delete
Private Member Functions
void make_array (int x, int y)
void delete_array () noexcept
Private Attributes
val_t ** m_arr = nullptr
size_t m_x = 0
size_t m_y = 0
Detailed Description
template<typename val_t, typename size_t = size_t>
class wlp::array2d< val_t, size_t >
Definition at line 32 of file Array2D.h.
Constructor & Destructor Documentation
template<typename val_t , typename size_t = size_t> wlp::array2d< val_t, size_t >::array2d (size_t x, size_t y) inline
Definition at line 35 of file Array2D.h.
References wlp::array2d< val_t, size_t >::make_array().
             : m_x(x),
               m_y(y) {
             make_array(x, y);
         }
template<typename val_t , typename size_t = size_t> wlp::array2d< val_t, size_t >::array2d (wlp::initializer_list< wlp::initializer_list< val_t >> l) inline
Definition at line 41 of file Array2D.h.
References wlp::array2d< val_t, size_t >::m_arr, wlp::array2d< val_t, size_t >::m_x, wlp::array2d< val_t, size_t >::m_y, and wlp::array2d< val_t, size_t >::make_array().
{
             m_x = static_cast<size_t>(l.size());
             m_y = static_cast<size_t>(l.begin()->size());
             make_array(m_x, m_y);
             int i = 0;
             for (auto &array : l) {
                 int j = 0;
                 for (auto &e : array) {
                     m_arr[i][j] = wlp::move(e);
                     j++;
                 }
                 i++;
             }
         }
template<typename val_t , typename size_t = size_t> wlp::array2d< val_t, size_t >::array2d (array2d< val_t, size_t > && arr) inline noexcept
Definition at line 57 of file Array2D.h.
             : m_arr(arr.m_arr),
               m_x(arr.m_x),
               m_y(arr.m_y) {
             arr.m_x = 0;
             arr.m_y = 0;
             arr.m_arr = nullptr;
         }
template<typename val_t , typename size_t = size_t> wlp::array2d< val_t, size_t >::~array2d () inline
Definition at line 66 of file Array2D.h.
References wlp::array2d< val_t, size_t >::delete_array(), and wlp::array2d< val_t, size_t >::m_arr.
                    {
             if (m_arr) {
                 delete_array();
             }
         }
template<typename val_t , typename size_t = size_t> wlp::array2d< val_t, size_t >::array2d (const array2d< val_t, size_t > &) delete
Member Function Documentation
template<typename val_t , typename size_t = size_t> void wlp::array2d< val_t, size_t >::delete_array () inline private noexcept
Definition at line 125 of file Array2D.h.
References wlp::array2d< val_t, size_t >::m_arr, wlp::array2d< val_t, size_t >::m_x, and wlp::array2d< val_t, size_t >::x().
Referenced by wlp::array2d< val_t, size_t >::make_array(), and wlp::array2d< val_t, size_t >::~array2d().
{
             for (size_t x = 0; x < m_x; ++x) {
                 delete[] m_arr[x];
             }
             delete[] m_arr;
         }
template<typename val_t , typename size_t = size_t> val_t** wlp::array2d< val_t, size_t >::get () inline
Definition at line 100 of file Array2D.h.
References wlp::array2d< val_t, size_t >::m_arr.
                       {
             return m_arr;
         }
template<typename val_t , typename size_t = size_t> void wlp::array2d< val_t, size_t >::make_array (int x, int y) inline private
Definition at line 114 of file Array2D.h.
References wlp::array2d< val_t, size_t >::delete_array(), wlp::array2d< val_t, size_t >::m_arr, wlp::array2d< val_t, size_t >::x(), and wlp::array2d< val_t, size_t >::y().
Referenced by wlp::array2d< val_t, size_t >::array2d().
{
             if (m_arr) {
                 delete_array();
             }
             m_arr = new val_t *[x];
             for (int tx = 0; tx < x; ++tx) {
                 m_arr[tx] = new val_t[y];
                 memset(m_arr[tx], 0, y * sizeof(val_t));
             }
         }
template<typename val_t , typename size_t = size_t> array2d<val_t, size_t>& wlp::array2d< val_t, size_t >::operator= (array2d< val_t, size_t > && arr) inline noexcept
Definition at line 90 of file Array2D.h.
References wlp::array2d< val_t, size_t >::m_arr, wlp::array2d< val_t, size_t >::m_x, and wlp::array2d< val_t, size_t >::m_y.
{
             m_x = arr.m_x;
             m_y = arr.m_y;
             m_arr = arr.m_arr;
             arr.m_x = 0;
             arr.m_y = 0;
             arr.m_arr = nullptr;
             return *this;
         };
template<typename val_t , typename size_t = size_t> array2d<val_t, size_t>& wlp::array2d< val_t, size_t >::operator= (const array2d< val_t, size_t > &) delete
template<typename val_t , typename size_t = size_t> __array2d_access<val_t, size_t> wlp::array2d< val_t, size_t >::operator[] (size_t x) inline
Definition at line 104 of file Array2D.h.
References wlp::array2d< val_t, size_t >::m_arr, wlp::array2d< val_t, size_t >::m_y, and wlp::array2d< val_t, size_t >::x().
{
             return __array2d_access<val_t, size_t>(m_arr[x], m_y);
         };
template<typename val_t , typename size_t = size_t> size_t wlp::array2d< val_t, size_t >::x () const inline
Definition at line 72 of file Array2D.h.
References wlp::array2d< val_t, size_t >::m_x.
Referenced by wlp::array2d< val_t, size_t >::delete_array(), wlp::array2d< val_t, size_t >::make_array(), wlp::array2d< val_t, size_t >::operator[](), and wlp::array2d< val_t, size_t >::zero_clear().
{
             return m_x;
         }
template<typename val_t , typename size_t = size_t> size_t wlp::array2d< val_t, size_t >::xy () const inline
Definition at line 80 of file Array2D.h.
References wlp::array2d< val_t, size_t >::m_x, and wlp::array2d< val_t, size_t >::m_y.
{
             return m_x * m_y;
         }
template<typename val_t , typename size_t = size_t> size_t wlp::array2d< val_t, size_t >::y () const inline
Definition at line 76 of file Array2D.h.
References wlp::array2d< val_t, size_t >::m_y.
Referenced by wlp::array2d< val_t, size_t >::make_array().
{
             return m_y;
         }
template<typename val_t , typename size_t = size_t> void wlp::array2d< val_t, size_t >::zero_clear () inline
Definition at line 84 of file Array2D.h.
References wlp::array2d< val_t, size_t >::m_arr, wlp::array2d< val_t, size_t >::m_x, wlp::array2d< val_t, size_t >::m_y, and wlp::array2d< val_t, size_t >::x().
{
             for (size_t x = 0; x < m_x; ++x) {
                 memset(m_arr[x], 0, m_y * sizeof(val_t));
             }
         }
Field Documentation
template<typename val_t , typename size_t = size_t> val_t** wlp::array2d< val_t, size_t >::m_arr = nullptr private
Definition at line 132 of file Array2D.h.
Referenced by wlp::array2d< val_t, size_t >::array2d(), wlp::array2d< val_t, size_t >::delete_array(), wlp::array2d< val_t, size_t >::get(), wlp::array2d< val_t, size_t >::make_array(), wlp::array2d< val_t, size_t >::operator=(), wlp::array2d< val_t, size_t >::operator[](), wlp::array2d< val_t, size_t >::zero_clear(), and wlp::array2d< val_t, size_t >::~array2d().
template<typename val_t , typename size_t = size_t> size_t wlp::array2d< val_t, size_t >::m_x = 0 private
Definition at line 133 of file Array2D.h.
Referenced by wlp::array2d< val_t, size_t >::array2d(), wlp::array2d< val_t, size_t >::delete_array(), wlp::array2d< val_t, size_t >::operator=(), wlp::array2d< val_t, size_t >::x(), wlp::array2d< val_t, size_t >::xy(), and wlp::array2d< val_t, size_t >::zero_clear().
template<typename val_t , typename size_t = size_t> size_t wlp::array2d< val_t, size_t >::m_y = 0 private
Definition at line 134 of file Array2D.h.
Referenced by wlp::array2d< val_t, size_t >::array2d(), wlp::array2d< val_t, size_t >::operator=(), wlp::array2d< val_t, size_t >::operator[](), wlp::array2d< val_t, size_t >::xy(), wlp::array2d< val_t, size_t >::y(), and wlp::array2d< val_t, size_t >::zero_clear().
The documentation for this class was generated from the following file:
wlib/stl/Array2D.h