Waterloop Wlib: wlp::TreeSet< Key, Cmp > Class Template Reference
wlp::TreeSet< Key, Cmp > Class Template Reference
#include <TreeSet.h>
Public Types
typedef TreeSet< Key, Cmp > set_type
typedef RedBlackTree< Key, Key,
Key, SetGetKey< Key >
, SetGetVal< Key >, Cmp > table_type
typedef table_type::iterator iterator
typedef table_type::const_iterator const_iterator
typedef table_type::size_type size_type
typedef Key key_type
Public Member Functions
TreeSet ()
TreeSet (const set_type &)=delete
TreeSet (set_type &&set)
size_type size () const
size_type capacity () const
bool empty () const
const table_type * get_backing_table () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
void clear () noexcept
template<typename K >
Pair< iterator, bool > insert (K &&key)
bool contains (const key_type &key) const
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
iterator erase (const iterator &pos)
bool erase (const key_type &key)
set_type & operator= (const set_type &)=delete
set_type & operator= (set_type &&set)
Private Attributes
table_type m_table
Detailed Description
template<typename Key, typename Cmp = Comparator<Key>>
class wlp::TreeSet< Key, Cmp >
Set implementation using
RedBlackTree
as the backing data structure.
See Also
wlp::ChainHashSet
wlp::RedBlackTree
Template Parameters
Key stored value type
Cmp comparator for stored value, which uses the default comparator
Definition at line 29 of file TreeSet.h.
Member Typedef Documentation
template<typename Key , typename Cmp = Comparator<Key>> typedef table_type::const_iterator wlp::TreeSet< Key, Cmp >::const_iterator
Definition at line 38 of file TreeSet.h.
template<typename Key , typename Cmp = Comparator<Key>> typedef table_type::iterator wlp::TreeSet< Key, Cmp >::iterator
Definition at line 37 of file TreeSet.h.
template<typename Key , typename Cmp = Comparator<Key>> typedef Key wlp::TreeSet< Key, Cmp >::key_type
Definition at line 41 of file TreeSet.h.
template<typename Key , typename Cmp = Comparator<Key>> typedef TreeSet<Key, Cmp> wlp::TreeSet< Key, Cmp >::set_type
Definition at line 31 of file TreeSet.h.
template<typename Key , typename Cmp = Comparator<Key>> typedef table_type::size_type wlp::TreeSet< Key, Cmp >::size_type
Definition at line 39 of file TreeSet.h.
template<typename Key , typename Cmp = Comparator<Key>> typedef RedBlackTree<Key, Key, Key, SetGetKey<Key>, SetGetVal<Key>, Cmp > wlp::TreeSet< Key, Cmp >::table_type
Definition at line 36 of file TreeSet.h.
Constructor & Destructor Documentation
template<typename Key , typename Cmp = Comparator<Key>> wlp::TreeSet< Key, Cmp >::TreeSet () inline explicit
Definition at line 47 of file TreeSet.h.
                 : m_table() {
         }
template<typename Key , typename Cmp = Comparator<Key>> wlp::TreeSet< Key, Cmp >::TreeSet (const set_type &) delete
template<typename Key , typename Cmp = Comparator<Key>> wlp::TreeSet< Key, Cmp >::TreeSet (set_type && set) inline
Definition at line 53 of file TreeSet.h.
                 : m_table(move(set.m_table)) {
         }
Member Function Documentation
template<typename Key , typename Cmp = Comparator<Key>> iterator wlp::TreeSet< Key, Cmp >::begin () inline
Definition at line 73 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::begin(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.begin();
         }
template<typename Key , typename Cmp = Comparator<Key>> const_iterator wlp::TreeSet< Key, Cmp >::begin () const inline
Definition at line 77 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::begin(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.begin();
         }
template<typename Key , typename Cmp = Comparator<Key>> size_type wlp::TreeSet< Key, Cmp >::capacity () const inline
Definition at line 61 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::capacity(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.capacity();
         }
template<typename Key , typename Cmp = Comparator<Key>> void wlp::TreeSet< Key, Cmp >::clear () inline noexcept
Definition at line 89 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::clear(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             m_table.clear();
         }
template<typename Key , typename Cmp = Comparator<Key>> bool wlp::TreeSet< Key, Cmp >::contains (const key_type & key) const inline
Definition at line 98 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::end(), wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.find(key) != m_table.end();
         }
template<typename Key , typename Cmp = Comparator<Key>> bool wlp::TreeSet< Key, Cmp >::empty () const inline
Definition at line 65 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::empty(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.empty();
         }
template<typename Key , typename Cmp = Comparator<Key>> iterator wlp::TreeSet< Key, Cmp >::end () inline
Definition at line 81 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::end(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.end();
         }
template<typename Key , typename Cmp = Comparator<Key>> const_iterator wlp::TreeSet< Key, Cmp >::end () const inline
Definition at line 85 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::end(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.end();
         }
template<typename Key , typename Cmp = Comparator<Key>> iterator wlp::TreeSet< Key, Cmp >::erase (const iterator & pos) inline
Definition at line 110 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::erase(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             iterator tmp = pos;
             ++tmp;
             m_table.erase(pos);
             return tmp;
         }
template<typename Key , typename Cmp = Comparator<Key>> bool wlp::TreeSet< Key, Cmp >::erase (const key_type & key) inline
Definition at line 117 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::erase(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.erase(key) > 0;
         }
template<typename Key , typename Cmp = Comparator<Key>> iterator wlp::TreeSet< Key, Cmp >::find (const key_type & key) inline
Definition at line 102 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.find(key);
         }
template<typename Key , typename Cmp = Comparator<Key>> const_iterator wlp::TreeSet< Key, Cmp >::find (const key_type & key) const inline
Definition at line 106 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.find(key);
         }
template<typename Key , typename Cmp = Comparator<Key>> const table_type* wlp::TreeSet< Key, Cmp >::get_backing_table () const inline
Definition at line 69 of file TreeSet.h.
References wlp::TreeSet< Key, Cmp >::m_table.
{
             return &m_table;
         }
template<typename Key , typename Cmp = Comparator<Key>> template<typename K > Pair<iterator, bool> wlp::TreeSet< Key, Cmp >::insert (K && key) inline
Definition at line 94 of file TreeSet.h.
References wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_unique(), and wlp::TreeSet< Key, Cmp >::m_table.
{
             return m_table.insert_unique(key);
         };
template<typename Key , typename Cmp = Comparator<Key>> set_type& wlp::TreeSet< Key, Cmp >::operator= (const set_type &) delete
template<typename Key , typename Cmp = Comparator<Key>> set_type& wlp::TreeSet< Key, Cmp >::operator= (set_type && set) inline
Definition at line 123 of file TreeSet.h.
References wlp::TreeSet< Key, Cmp >::m_table, and wlp::move().
{
             m_table = move(set.m_table);
             return *this;
         }
template<typename Key , typename Cmp = Comparator<Key>> size_type wlp::TreeSet< Key, Cmp >::size () const inline
Definition at line 57 of file TreeSet.h.
References wlp::TreeSet< Key, Cmp >::m_table, and wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::size().
{
             return m_table.size();
         }
Field Documentation
template<typename Key , typename Cmp = Comparator<Key>> table_type wlp::TreeSet< Key, Cmp >::m_table private
Definition at line 44 of file TreeSet.h.
Referenced by wlp::TreeSet< Key, Cmp >::begin(), wlp::TreeSet< Key, Cmp >::capacity(), wlp::TreeSet< Key, Cmp >::clear(), wlp::TreeSet< Key, Cmp >::contains(), wlp::TreeSet< Key, Cmp >::empty(), wlp::TreeSet< Key, Cmp >::end(), wlp::TreeSet< Key, Cmp >::erase(), wlp::TreeSet< Key, Cmp >::find(), wlp::TreeSet< Key, Cmp >::get_backing_table(), wlp::TreeSet< Key, Cmp >::insert(), wlp::TreeSet< Key, Cmp >::operator=(), and wlp::TreeSet< Key, Cmp >::size().
The documentation for this class was generated from the following file:
wlib/stl/TreeSet.h