Waterloop Wlib: wlp::dynamic_string Class Reference
wlp::dynamic_string Class Reference
#include <String.h>
Public Types
typedef wlp::size_type size_type
typedef wlp::diff_type diff_type
typedef StringIterator
< dynamic_string, char &, char * > iterator
typedef StringIterator< const
dynamic_string, const char
&, const char * > const_iterator
Public Member Functions
dynamic_string ()
dynamic_string (nullptr_t)
dynamic_string (const char *str)
template<size_type tSize>
dynamic_string (const static_string< tSize > &str)
dynamic_string (const char *str, size_type len)
dynamic_string (const dynamic_string &str)
dynamic_string (dynamic_string &&str) noexcept
~dynamic_string ()
void set_value (const char *str, size_type len)
dynamic_string & operator= (const dynamic_string &str)
template<size_type tSize>
dynamic_string & operator= (const static_string< tSize > &str)
dynamic_string & operator= (const char *str)
dynamic_string & operator= (dynamic_string &&str) noexcept
dynamic_string & operator= (char c)
size_type length () const
size_type capacity () const
void clear () noexcept
char & operator[] (size_type pos)
const char & operator[] (size_type pos) const
char & at (size_type pos)
const char & at (size_type pos) const
bool empty () const
char & front ()
const char & front () const
char & back ()
const char & back () const
dynamic_string & operator+= (char c)
dynamic_string & operator+= (const char *val)
dynamic_string & operator+= (const dynamic_string &other)
template<size_type tSize>
dynamic_string & operator+= (const static_string< tSize > &str)
dynamic_string & append (const char *str)
dynamic_string & append (const dynamic_string &str)
void push_back (char c)
void erase (size_type pos=0)
void pop_back ()
char * c_str ()
const char * c_str () const
void resize (size_type len)
void length_set (size_type len)
dynamic_string substr (size_type pos, size_type length) const
dynamic_string (const char *str1, const char *str2, size_type len1, size_type len2)
dynamic_string (size_type len, char *str)
dynamic_string & append (const char *c_str, size_type len)
Friends
dynamic_string operator+ (const dynamic_string &lhs, const dynamic_string &rhs)
dynamic_string operator+ (const char *lhs, const dynamic_string &rhs)
dynamic_string operator+ (const dynamic_string &lhs, const char *rhs)
dynamic_string operator+ (char lhs, const dynamic_string &rhs)
dynamic_string operator+ (const dynamic_string &lhs, char rhs)
Detailed Description
Definition at line 760 of file String.h.
Member Typedef Documentation
typedef StringIterator<const dynamic_string, const char &, const char *> wlp::dynamic_string::const_iterator
Definition at line 768 of file String.h.
typedef wlp::diff_type wlp::dynamic_string::diff_type
Definition at line 764 of file String.h.
typedef StringIterator<dynamic_string, char &, char *> wlp::dynamic_string::iterator
Definition at line 767 of file String.h.
typedef wlp::size_type wlp::dynamic_string::size_type
Definition at line 763 of file String.h.
Constructor & Destructor Documentation
wlp::dynamic_string::dynamic_string ()
Default constructor creates string with no characters.
Definition at line 15 of file String.cpp.
                                    :
         dynamic_string(nullptr, nullptr, 0, 0) {}
wlp::dynamic_string::dynamic_string (nullptr_t) explicit
Constructor of nullptr_t makes empty string.
Definition at line 18 of file String.cpp.
                                             :
         dynamic_string(nullptr, nullptr, 0, 0) {}
wlp::dynamic_string::dynamic_string (const char * str) explicit
Constructor creates string using character array.
Parameters
str char string
Definition at line 21 of file String.cpp.
             : dynamic_string(str, nullptr, static_cast<size_type>(strlen(str)), 0) {}
template<size_type tSize> wlp::dynamic_string::dynamic_string (const static_string< tSize > & str) inline explicit
Construct a dynamic string from a static string.
Parameters
str static string to copy
Definition at line 793 of file String.h.
                 : dynamic_string(str.c_str(), str.length()) {}
wlp::dynamic_string::dynamic_string (const char * str, size_type len)
Construct a dynamic string from a character array and a known length.
Parameters
str character array
len length of the array
Definition at line 24 of file String.cpp.
             : dynamic_string(str, nullptr, len, 0) {}
wlp::dynamic_string::dynamic_string (const dynamic_string & str)
Constructor creates string using DynamicString object.
Parameters
str@code DynamicString object
Definition at line 31 of file String.cpp.
 : dynamic_string(str.c_str()) {}
wlp::dynamic_string::dynamic_string (dynamic_string && str) noexcept
Move constructor will transfer the underlying string.
Parameters
str the
DynamicString
to move
Definition at line 33 of file String.cpp.
             : m_buffer(str.m_buffer),
               m_len(str.m_len) {
         str.m_len = 0;
         str.m_buffer = malloc<char[]>(1);
         str.m_buffer[0] = '\0';
     }
wlp::dynamic_string::~dynamic_string ()
Destructor for DynamicString object.
Definition at line 49 of file String.cpp.
{
         if (m_buffer) {
             free<char>(m_buffer);
         }
     }
wlp::dynamic_string::dynamic_string (const char * str1, const char * str2, size_type len1, size_type len2)
Compares two strings and return 0 if they are equal, less than 0 if given string is less than current string and greater than 0 if given string is greater than current string.
Parameters
str@code DynamicString string to compare against current string
Returns
a signed number based on how strings compare / diff_type compare(const dynamic_string &str) const;
template<size_type tSize> diff_type compare(const static_string<tSize> &str) const { return compare(str.c_str()); }
/**
Compares two strings and return 0 if they are equal, less than 0 if
given string is less than current string and greater than 0 if
given string is greater than current string.
Parameters
str character string to compare against current string
Returns
a signed number based on how strings compare */ diff_type compare(const char *str) const;
/**
Compares a string and character and return 0 if they are equal, less than 0 if
given string is less than current string and greater than 0 if
given string is greater than current string.
Parameters
c character to compare against current string
Returns
a signed number based on how strings compare */ diff_type compare(char c) const;
iterator begin() { return iterator(0, this); }
iterator end() { return iterator(m_len, this); }
const_iterator begin() const { return const_iterator(0, this); }
const_iterator end() const { return const_iterator(m_len, this); }
template<size_type tSize> dynamic_string operator+(const static_string<tSize> &str) { return {m_buffer, str.c_str(), m_len, str.length()}; }
private: char *m_buffer; size_type m_len;
/**
Constructor used by other String constructors to create
dynamic_string
.
Parameters
str1 first string to use in making
str2 second string to use in making
len1 length of first string
len2 length of second string
Definition at line 41 of file String.cpp.
{
         m_len = len1 + len2;
         m_buffer = malloc<char[]>(static_cast<size_type>(m_len + 1));
         memcpy(m_buffer, str1, len1);
         memcpy(m_buffer + len1, str2, len2);
         m_buffer[m_len] = '\0';
     }
wlp::dynamic_string::dynamic_string (size_type len, char * str)
Constructor for populating a dynamic_string with a dynamically allocated character array which the string takes ownership of and its length.
Parameters
str dynamically allocated character array filled with characters
len length of the string
Definition at line 27 of file String.cpp.
             : m_buffer(str),
               m_len(len) {}
Member Function Documentation
dynamic_string & wlp::dynamic_string::append (const char * str)
Appends a character string to the current string.
Parameters
str character string to add
Returns
the current string
Definition at line 166 of file String.cpp.
Referenced by append(), operator+=(), and push_back().
{
         return append(str, static_cast<size_type>(strlen(str)));
     }
dynamic_string & wlp::dynamic_string::append (const dynamic_string & str)
Appends a DynamicString string to the current string.
Parameters
str DynamicString string to add
Returns
the current string
Definition at line 170 of file String.cpp.
References append(), c_str(), and length().
{
         return append(str.c_str(), str.length());
     }
dynamic_string & wlp::dynamic_string::append (const char * c_str, size_type len)
Append method used by other public append methods.
Parameters
c_str c style string to append
len length of c_str
Returns
the
DynamicString
with c_str append to it
Definition at line 154 of file String.cpp.
{
         auto newLength = static_cast<size_type>(m_len + len);
         m_buffer = realloc<char>(m_buffer, static_cast<size_type>(newLength + 1));
         memcpy(m_buffer + m_len, c_str, newLength);
         m_buffer[newLength] = '\0';
         m_len = newLength;
         return *this;
     }
char & wlp::dynamic_string::at (size_type pos)
Provides access to character at
 pos with bounds checking.
@param pos the position of the character
@return character at @code position
Definition at line 113 of file String.cpp.
Referenced by wlp::StringIterator< String, Ref, Ptr >::operator*().
{
         return pos < m_len ? m_buffer[pos] : m_buffer[m_len];
     }
const char & wlp::dynamic_string::at (size_type pos) const
Provides access to character at
pos
with bounds checking. Character is constant.
Parameters
pos the position of the character
Returns
character at
position
Definition at line 117 of file String.cpp.
{
         return pos < m_len ? m_buffer[pos] : m_buffer[m_len];
     }
char & wlp::dynamic_string::back ()
Provides access to the last character in the string.
Returns
the last character
Definition at line 133 of file String.cpp.
References empty().
{
         return empty() ? m_buffer[0] : m_buffer[m_len - 1];
     }
const char & wlp::dynamic_string::back () const
Provides access to the last character in the string. Character is constant.
Returns
the last character
Definition at line 137 of file String.cpp.
References empty().
{
         return empty() ? m_buffer[0] : m_buffer[m_len - 1];
     }
char * wlp::dynamic_string::c_str ()
Provides access to the backing character array.
Returns
character array
Definition at line 193 of file String.cpp.
Referenced by wlp::static_string< tSize >::append(), append(), wlp::static_string< tSize >::compare(), wlp::equals< dynamic_string >::operator()(), wlp::equals< const dynamic_string >::operator()(), wlp::hash< dynamic_string, IntType >::operator()(), wlp::operator+(), wlp::static_string< tSize >::operator+(), operator+=(), wlp::StringIterator< String, Ref, Ptr >::operator->(), wlp::static_string< tSize >::operator=(), and operator=().
{
         return m_buffer;
     }
const char * wlp::dynamic_string::c_str () const
Provides access to the backing character array.
Returns
character array
Definition at line 197 of file String.cpp.
{
         return m_buffer;
     }
size_type wlp::dynamic_string::capacity () const
The DynamicString has capacity equal to the maximum possible value of
size_type
.
Returns
the maximum dynamic string capcacity
Definition at line 96 of file String.cpp.
{
         return static_cast<size_type>(-1);
     }
void wlp::dynamic_string::clear () noexcept
Clears the string such that there are no characters left in it.
Definition at line 100 of file String.cpp.
{
         m_buffer[0] = '\0';
         m_len = 0;
     }
bool wlp::dynamic_string::empty () const
Checks if string is empty or not.
Returns
if string is empty or not
Definition at line 121 of file String.cpp.
Referenced by back().
{
         return m_len == 0;
     }
void wlp::dynamic_string::erase (size_type pos = 0)
Deletes the element pos from the String.
Parameters
pos position of the element to be deleted
Returns
the modified String
Definition at line 179 of file String.cpp.
{
         if (m_len == 0 || pos >= m_len) { return; }
         m_len--;
         memmove(m_buffer + pos, m_buffer + pos + 1, m_len - pos);
         m_buffer[m_len] = '\0';
     }
char & wlp::dynamic_string::front ()
Provides access to the first character in the string.
Returns
the first character
Definition at line 125 of file String.cpp.
{
         return m_buffer[0];
     }
const char & wlp::dynamic_string::front () const
Provides access to the first character in the string. Character is constant.
Returns
the first character
Definition at line 129 of file String.cpp.
{
         return m_buffer[0];
     }
size_type wlp::dynamic_string::length () const
Provides current length of string.
Returns
string length
Definition at line 92 of file String.cpp.
Referenced by wlp::static_string< tSize >::append(), append(), wlp::StringIterator< String, Ref, Ptr >::check_bounds(), wlp::operator+(), wlp::static_string< tSize >::operator+(), operator+=(), wlp::static_string< tSize >::operator=(), operator=(), and substr().
{
         return m_len;
     }
void wlp::dynamic_string::length_set (size_type len)
Directly set the length of the string. Used with
resize
for direct writes to the string.
Parameters
len the actual length of the string
Definition at line 208 of file String.cpp.
{
         m_len = len;
     }
dynamic_string & wlp::dynamic_string::operator+= (char c)
Modifier operator adds character to the current string.
Parameters
c character to add
Returns
the current string
Definition at line 141 of file String.cpp.
References append().
{
         const char array[2] = {c, '\0'};
         return append(array, 1);
     }
dynamic_string & wlp::dynamic_string::operator+= (const char * val)
Modifier operator adds char string to the current string.
Parameters
val char string to add
Returns
the current string
Definition at line 146 of file String.cpp.
References append().
{
         return append(val, static_cast<size_type>(strlen(val)));
     }
dynamic_string & wlp::dynamic_string::operator+= (const dynamic_string & other)
Modifier operator adds
dynamic_string
object to the current string.
Parameters
other@code DynamicString string to add
Returns
the current string
Definition at line 150 of file String.cpp.
References append(), c_str(), and length().
{
         return append(other.c_str(), other.length());
     }
template<size_type tSize> dynamic_string& wlp::dynamic_string::operator+= (const static_string< tSize > & str) inline
Definition at line 978 of file String.h.
References append().
{
             return append(str.c_str(), str.length());
         }
dynamic_string & wlp::dynamic_string::operator= (const dynamic_string & str)
Assign operator assigns current object to given object.
Parameters
str@code DynamicString object
Returns
current object
Definition at line 65 of file String.cpp.
References c_str(), length(), and set_value().
{
         set_value(str.c_str(), str.length());
         return *this;
     }
template<size_type tSize> dynamic_string& wlp::dynamic_string::operator= (const static_string< tSize > & str) inline
Definition at line 835 of file String.h.
References set_value().
{
             set_value(str.c_str(), str.length());
             return *this;
         }
dynamic_string & wlp::dynamic_string::operator= (const char * str)
Assign operator assigns current object to given character string.
Parameters
str
Returns
current object
Definition at line 70 of file String.cpp.
References set_value().
{
         set_value(str, static_cast<size_type>(strlen(str)));
         return *this;
     }
dynamic_string & wlp::dynamic_string::operator= (dynamic_string && str) noexcept
Move assignment operator transfers the underlying character array.
Parameters
str the
DynamicString
to move
Definition at line 75 of file String.cpp.
{
         free<char>(m_buffer);
         m_buffer = str.m_buffer;
         m_len = str.m_len;
         str.m_len = 0;
         str.m_buffer = malloc<char[]>(1);
         str.m_buffer[0] = '\0';
         return *this;
     }
dynamic_string & wlp::dynamic_string::operator= (char c)
Assignment operator for a single character.
Parameters
c character to assign
Returns
reference to this string
Definition at line 85 of file String.cpp.
{
         free<char>(m_buffer);
         m_buffer = malloc<char[]>(2);
         reinterpret_cast<uint16_t *>(m_buffer)[0] = static_cast<uint16_t>(c);
         return *this;
     }
char & wlp::dynamic_string::operator[] (size_type pos)
Element access operator gives access to character at
 pos.
@param pos the position of the character
@return character at @code position
Definition at line 105 of file String.cpp.
{
         return m_buffer[pos];
     }
const char & wlp::dynamic_string::operator[] (size_type pos) const
Element access operator gives access to character at
 pos.
Character is constant.
@param pos the position of the character
@return character at @code position
Definition at line 109 of file String.cpp.
{
         return m_buffer[pos];
     }
void wlp::dynamic_string::pop_back ()
Deletes the last character in the String.
Definition at line 186 of file String.cpp.
{
         if (m_len != 0) {
             m_buffer[m_len - 1] = '\0';
             m_len--;
         }
     }
void wlp::dynamic_string::push_back (char c)
Appends a character to the current string.
Parameters
c character to add
Returns
the current string
Definition at line 174 of file String.cpp.
References append().
{
         const char array[2] = {c, '\0'};
         append(array, 1);
     }
void wlp::dynamic_string::resize (size_type len)
Discard current contents and replace the backing array with one of size
len + 1
. The first character is set to null and the length is zero to zero.
Used for direct writing to the underlying array.
Parameters
len the number of characters to hold
Definition at line 201 of file String.cpp.
{
         if (m_buffer) { free<char>(m_buffer); }
         m_buffer = malloc<char[]>(static_cast<size_type>(len + 1));
         m_buffer[0] = '\0';
         m_len = 0;
     }
void wlp::dynamic_string::set_value (const char * str, size_type len)
Definition at line 55 of file String.cpp.
References free().
Referenced by operator=().
{
         if (len > m_len) {
             free(m_buffer);
             m_buffer = malloc<char[]>(static_cast<size_type>(len + 1));
         }
         m_len = len;
         memcpy(m_buffer, str, len);
         m_buffer[len] = '\0';
     }
dynamic_string wlp::dynamic_string::substr (size_type pos, size_type length) const
Makes substring of the current string.
Parameters
pos starting position
length length of the new string
Returns
new string which is a substring of current string
Definition at line 212 of file String.cpp.
References length().
{
         char *newBuffer = malloc<char[]>(static_cast<size_type>(length + 1));
         memcpy(newBuffer, m_buffer + pos, length);
         newBuffer[length] = '\0';
         return {length, newBuffer};
     }
Friends And Related Function Documentation
dynamic_string operator+ (const dynamic_string & lhs, const dynamic_string & rhs) friend
Definition at line 312 of file String.cpp.
{
         return {lhs.c_str(), rhs.c_str(), lhs.length(), rhs.length()};
     }
dynamic_string operator+ (const char * lhs, const dynamic_string & rhs) friend
Definition at line 316 of file String.cpp.
{
         return {lhs, rhs.c_str(), static_cast<size_type>(strlen(lhs)), rhs.length()};
     }
dynamic_string operator+ (const dynamic_string & lhs, const char * rhs) friend
Definition at line 320 of file String.cpp.
{
         return {lhs.c_str(), rhs, lhs.length(), static_cast<size_type>(strlen(rhs))};
     }
dynamic_string operator+ (char lhs, const dynamic_string & rhs) friend
Definition at line 324 of file String.cpp.
{
         const char temp[2] = {lhs, '\0'};
         return {temp, rhs.c_str(), 1, rhs.length()};
     }
dynamic_string operator+ (const dynamic_string & lhs, char rhs) friend
Definition at line 329 of file String.cpp.
{
         const char temp[2] = {rhs, '\0'};
         return {lhs.c_str(), temp, lhs.length(), 1};
     }
The documentation for this class was generated from the following files:
wlib/strings/String.h
wlib/strings/String.cpp