Waterloop Wlib: wlp::SharedPtr< T > Class Template Reference
wlp::SharedPtr< T > Class Template Reference
#include <SharedPtr.h>
Public Types
typedef T val_type
typedef ReferenceCount< T * >::ptr_use_count ptr_use_count
Public Member Functions
constexpr SharedPtr ()
template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type>
SharedPtr (U *ptr)
template<typename U >
SharedPtr (const SharedPtr< U > &sp, T *ptr)
template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type>
SharedPtr (const SharedPtr< U > &sp)
SharedPtr (const SharedPtr< T > &sp)
SharedPtr (SharedPtr< T > &&sp)
template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type>
SharedPtr (SharedPtr< U > &&sp)
template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type>
SharedPtr (const WeakPtr< U > &wp)
template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type>
SharedPtr (UniquePtr< U > &&up)
constexpr SharedPtr (nullptr_t)
SharedPtr< T > & operator= (const SharedPtr< T > &sp)
template<typename U >
SharedPtr< T > & operator= (const SharedPtr< U > &sp)
SharedPtr< T > & operator= (SharedPtr< T > &&sp)
template<typename U >
SharedPtr< T > & operator= (SharedPtr< U > &&sp)
template<typename U >
SharedPtr< T > & operator= (UniquePtr< U > &&up)
void reset ()
template<typename U >
void reset (U *ptr)
add_lvalue_reference< T >::type operator* () const
val_type * operator-> () const
val_type * get () const
operator bool () const
bool unique () const
ptr_use_count use_count () const
void swap (SharedPtr< T > &sp)
template<typename U >
bool owner_before (const SharedPtr< U > &sp) const
template<typename U >
bool owner_before (const WeakPtr< U > &wp) const
WeakPtr< T > weak () const
Private Attributes
val_type * m_ptr
SharedCount< T * > m_refcount
Friends
template<typename U >
class SharedPtr
template<typename U >
class WeakPtr
Detailed Description
template<typename T>
class wlp::SharedPtr< T >
Definition at line 180 of file SharedPtr.h.
Member Typedef Documentation
ptr_use_count
template<typename T> typedef ReferenceCount<T *>::ptr_use_count wlp::SharedPtr< T >::ptr_use_count
Definition at line 460 of file SharedPtr.h.
val_type
template<typename T> typedef T wlp::SharedPtr< T >::val_type
Definition at line 459 of file SharedPtr.h.
Constructor & Destructor Documentation
SharedPtr() [1/10]
template<typename T> constexpr wlp::SharedPtr< T >::SharedPtr () inline
Definition at line 471 of file SharedPtr.h.
           :
         constexpr SharedPtr()
                 : m_ptr(nullptr),
SharedPtr() [2/10]
template<typename T> template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type> wlp::SharedPtr< T >::SharedPtr (U * ptr) inline explicit
Definition at line 479 of file SharedPtr.h.
                 : m_ptr(ptr),
                   m_refcount(ptr) {
SharedPtr() [3/10]
template<typename T> template<typename U > wlp::SharedPtr< T >::SharedPtr (const SharedPtr< U > & sp, T * ptr) inline
Definition at line 486 of file SharedPtr.h.
                 : m_ptr(ptr),
SharedPtr() [4/10]
template<typename T> template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type> wlp::SharedPtr< T >::SharedPtr (const SharedPtr< U > & sp) inline
Definition at line 494 of file SharedPtr.h.
                 : m_ptr(sp.m_ptr),
SharedPtr() [5/10]
template<typename T> wlp::SharedPtr< T >::SharedPtr (const SharedPtr< T > & sp) inline
Definition at line 499 of file SharedPtr.h.
                 : m_ptr(sp.m_ptr),
SharedPtr() [6/10]
template<typename T> wlp::SharedPtr< T >::SharedPtr (SharedPtr< T > && sp) inline
Definition at line 504 of file SharedPtr.h.
References wlp::SharedCount< Ptr >::swap().
                 : m_ptr(sp.m_ptr),
                   m_refcount() {
             m_refcount.swap(sp.m_refcount);
SharedPtr() [7/10]
template<typename T> template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type> wlp::SharedPtr< T >::SharedPtr (SharedPtr< U > && sp) inline
Definition at line 514 of file SharedPtr.h.
References wlp::SharedCount< Ptr >::swap().
                 : m_ptr(sp.m_ptr),
                   m_refcount() {
             m_refcount.swap(sp.m_refcount);
SharedPtr() [8/10]
template<typename T> template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type> wlp::SharedPtr< T >::SharedPtr (const WeakPtr< U > & wp) inline explicit
Definition at line 524 of file SharedPtr.h.
                 : m_ptr(wp.m_ptr),
SharedPtr() [9/10]
template<typename T> template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type> wlp::SharedPtr< T >::SharedPtr (UniquePtr< U > && up) inline
Definition at line 532 of file SharedPtr.h.
References wlp::move().
                 : m_ptr(up.get()),
                   m_refcount() {
             U *tmp = up.get();
SharedPtr() [10/10]
template<typename T> constexpr wlp::SharedPtr< T >::SharedPtr (nullptr_t) inline
Definition at line 539 of file SharedPtr.h.
                 : m_ptr(nullptr),
Member Function Documentation
get()
template<typename T> val_type* wlp::SharedPtr< T >::get () const inline
Definition at line 591 of file SharedPtr.h.
Referenced by wlp::const_pointer_cast(), wlp::dynamic_pointer_cast(), wlp::reinterpret_pointer_cast(), and wlp::static_pointer_cast().
{
operator bool()
template<typename T> wlp::SharedPtr< T >::operator bool () const inline explicit
Definition at line 595 of file SharedPtr.h.
{
operator*()
template<typename T> add_lvalue_reference<T>::type wlp::SharedPtr< T >::operator* () const inline
Definition at line 583 of file SharedPtr.h.
{
operator->()
template<typename T> val_type* wlp::SharedPtr< T >::operator-> () const inline
Definition at line 587 of file SharedPtr.h.
{
operator=() [1/5]
template<typename T> SharedPtr<T>& wlp::SharedPtr< T >::operator= (const SharedPtr< T > & sp) inline
Definition at line 544 of file SharedPtr.h.
References wlp::SharedPtr< T >::m_ptr, and wlp::SharedPtr< T >::m_refcount.
{
             m_ptr = sp.m_ptr;
             m_refcount = sp.m_refcount;
operator=() [2/5]
template<typename T> template<typename U > SharedPtr<T>& wlp::SharedPtr< T >::operator= (const SharedPtr< U > & sp) inline
Definition at line 551 of file SharedPtr.h.
References wlp::SharedPtr< T >::m_ptr, and wlp::SharedPtr< T >::m_refcount.
{
             m_ptr = sp.m_ptr;
             m_refcount = sp.m_refcount;
operator=() [3/5]
template<typename T> SharedPtr<T>& wlp::SharedPtr< T >::operator= (SharedPtr< T > && sp) inline
Definition at line 557 of file SharedPtr.h.
References wlp::move(), and wlp::SharedPtr< T >::swap().
{
             SharedPtr(move(sp)).swap(*this);
operator=() [4/5]
template<typename T> template<typename U > SharedPtr<T>& wlp::SharedPtr< T >::operator= (SharedPtr< U > && sp) inline
Definition at line 563 of file SharedPtr.h.
References wlp::move(), and wlp::SharedPtr< T >::swap().
{
             SharedPtr(move(sp)).swap(*this);
operator=() [5/5]
template<typename T> template<typename U > SharedPtr<T>& wlp::SharedPtr< T >::operator= (UniquePtr< U > && up) inline
Definition at line 569 of file SharedPtr.h.
References wlp::move(), and wlp::SharedPtr< T >::swap().
{
             SharedPtr(move(up)).swap(*this);
owner_before() [1/2]
template<typename T> template<typename U > bool wlp::SharedPtr< T >::owner_before (const SharedPtr< U > & sp) const inline
Definition at line 613 of file SharedPtr.h.
References wlp::SharedCount< Ptr >::less(), and wlp::SharedPtr< T >::m_refcount.
{
owner_before() [2/2]
template<typename T> template<typename U > bool wlp::SharedPtr< T >::owner_before (const WeakPtr< U > & wp) const inline
Definition at line 618 of file SharedPtr.h.
References wlp::SharedCount< Ptr >::less(), and wlp::WeakPtr< T >::m_refcount.
{
reset() [1/2]
template<typename T> void wlp::SharedPtr< T >::reset () inline
Definition at line 574 of file SharedPtr.h.
References wlp::SharedPtr< T >::swap().
                      {
reset() [2/2]
template<typename T> template<typename U > void wlp::SharedPtr< T >::reset (U * ptr) inline
Definition at line 579 of file SharedPtr.h.
References wlp::SharedPtr< T >::swap().
{
swap()
template<typename T> void wlp::SharedPtr< T >::swap (SharedPtr< T > & sp) inline
Definition at line 607 of file SharedPtr.h.
References wlp::SharedPtr< T >::m_ptr, wlp::SharedPtr< T >::m_refcount, wlp::SharedCount< Ptr >::swap(), and wlp::swap().
Referenced by wlp::SharedPtr< T >::operator=(), wlp::SharedPtr< T >::reset(), and wlp::swap().
{
             wlp::swap(m_ptr, sp.m_ptr);
unique()
template<typename T> bool wlp::SharedPtr< T >::unique () const inline
Definition at line 599 of file SharedPtr.h.
References wlp::SharedCount< Ptr >::unique().
{
use_count()
template<typename T> ptr_use_count wlp::SharedPtr< T >::use_count () const inline
Definition at line 603 of file SharedPtr.h.
References wlp::SharedCount< Ptr >::use_count().
{
weak()
template<typename T> WeakPtr<T> wlp::SharedPtr< T >::weak () const inline
Definition at line 622 of file SharedPtr.h.
{
Friends And Related Function Documentation
SharedPtr
template<typename T> template<typename U > friend class SharedPtr friend
Definition at line 463 of file SharedPtr.h.
WeakPtr
template<typename T> template<typename U > friend class WeakPtr friend
Definition at line 465 of file SharedPtr.h.
Field Documentation
m_ptr
template<typename T> val_type* wlp::SharedPtr< T >::m_ptr private
Definition at line 467 of file SharedPtr.h.
Referenced by wlp::SharedPtr< T >::operator=(), wlp::WeakPtr< T >::operator=(), and wlp::SharedPtr< T >::swap().
m_refcount
template<typename T> SharedCount<T *> wlp::SharedPtr< T >::m_refcount private
Definition at line 468 of file SharedPtr.h.
Referenced by wlp::SharedPtr< T >::operator=(), wlp::WeakPtr< T >::operator=(), wlp::SharedPtr< T >::owner_before(), wlp::WeakPtr< T >::owner_before(), and wlp::SharedPtr< T >::swap().
The documentation for this class was generated from the following file:
stl/SharedPtr.h