Waterloop Wlib: wlp::linked_list< T > Class Template Reference
wlp::linked_list< T > Class Template Reference
#include <LinkedList.h>
Public Types
typedef T val_type
typedef wlp::size_type size_type
typedef linked_list< T > list_type
typedef LinkedListNode< T > node_type
typedef LinkedListIterator< T,
T &, T * > iterator
typedef LinkedListIterator< T,
const T &, const T * > const_iterator
Public Member Functions
linked_list ()
linked_list (const list_type &)=delete
linked_list (list_type &&list)
~linked_list ()
bool empty () const
size_type size () const
size_type capacity () const
val_type & at (size_type i)
const val_type & at (size_type i) const
val_type & operator[] (size_type index)
const val_type & operator[] (size_type index) const
val_type & front ()
const val_type & front () const
val_type & back ()
const val_type & back () const
void clear () noexcept
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
template<typename V >
iterator insert (size_type i, V &&val)
template<typename V >
iterator insert (const iterator &it, V &&val)
iterator erase (size_type i)
iterator erase (const iterator &it)
template<typename V >
void push_back (V &&val)
template<typename V >
void push_front (V &&val)
void pop_back ()
void pop_front ()
size_type index_of (const val_type &val) const
iterator find (const val_type &val)
const_iterator find (const val_type &val) const
list_type & operator= (const list_type &)=delete
list_type & operator= (list_type &&list)
Private Attributes
node_type * m_head
node_type * m_tail
size_type m_size
Friends
struct LinkedListIterator< T, T &, T * >
struct LinkedListIterator< T, const T &, const T * >
Detailed Description
template<typename T>
class wlp::linked_list< T >
List implementation as a Doubly-Linked list.
Template Parameters
T value type
Definition at line 35 of file LinkedList.h.
Member Typedef Documentation
template<typename T> typedef LinkedListIterator<T, const T &, const T *> wlp::linked_list< T >::const_iterator
Definition at line 205 of file LinkedList.h.
template<typename T> typedef LinkedListIterator<T, T &, T *> wlp::linked_list< T >::iterator
Definition at line 204 of file LinkedList.h.
template<typename T> typedef linked_list<T> wlp::linked_list< T >::list_type
Definition at line 202 of file LinkedList.h.
template<typename T> typedef LinkedListNode<T> wlp::linked_list< T >::node_type
Definition at line 203 of file LinkedList.h.
template<typename T> typedef wlp::size_type wlp::linked_list< T >::size_type
Definition at line 201 of file LinkedList.h.
template<typename T> typedef T wlp::linked_list< T >::val_type
Definition at line 200 of file LinkedList.h.
Constructor & Destructor Documentation
template<typename T> wlp::linked_list< T >::linked_list () inline
Default Constructor creates an empty List.
Definition at line 228 of file LinkedList.h.
                 : m_head(nullptr),
                   m_tail(nullptr),
                   m_size(0) {}
template<typename T> wlp::linked_list< T >::linked_list (const list_type &) delete
Disable copy construction.
template<typename T> wlp::linked_list< T >::linked_list (list_type && list) inline
Move constructor takes the pointers to the head and tail nodes and copies them into this list. The transferred list is set to an empty list.
Parameters
list the list to move
Definition at line 245 of file LinkedList.h.
                                       :
             m_head(move(list.m_head)),
             m_tail(move(list.m_tail)),
             m_size(move(list.m_size)) {
             list.m_size = 0;
             list.m_head = nullptr;
             list.m_tail = nullptr;
         }
template<typename T> wlp::linked_list< T >::~linked_list () inline
Default Destructor deallocates all the nodes.
Definition at line 257 of file LinkedList.h.
References wlp::linked_list< T >::clear().
{
             clear();
         }
Member Function Documentation
template<typename T > linked_list< T >::val_type & wlp::linked_list< T >::at (size_type i) inline
Return a reference to the value stored at the index
Parameters
i to get
Returns
reference to the value at that index
Definition at line 686 of file LinkedList.h.
References INDEX_EXCEPTION, wlp::LinkedListNode< T >::m_next, wlp::LinkedListNode< T >::m_val, and THROW.
Referenced by wlp::linked_list< T >::operator[]().
{
         if (i >= m_size) {
             if (m_size) { i %= m_size; }
             else { THROW(INDEX_EXCEPTION("Accessing empty list")) }
         }
         node_type *pTmp = m_head;
         while (i-- > 0) {
             pTmp = pTmp->m_next;
         }
         return pTmp->m_val;
     }
template<typename T > const linked_list< T >::val_type & wlp::linked_list< T >::at (size_type i) const inline
Return a reference to the value stored at the index (const variant)
Parameters
i to get
Returns
reference to the value at that index
Definition at line 700 of file LinkedList.h.
References INDEX_EXCEPTION, wlp::LinkedListNode< T >::m_next, wlp::LinkedListNode< T >::m_val, and THROW.
{
         if (i >= m_size) {
             if (m_size) { i %= m_size; }
             else { THROW(INDEX_EXCEPTION("Accessing empty list")) }
         }
         node_type *pTmp = m_head;
         while (i-- > 0) {
             pTmp = pTmp->m_next;
         }
         return pTmp->m_val;
     }
template<typename T> val_type& wlp::linked_list< T >::back () inline
Returns
a reference to the value at the end of the List
Definition at line 343 of file LinkedList.h.
References INDEX_EXCEPTION, wlp::linked_list< T >::m_tail, wlp::LinkedListNode< T >::m_val, and THROW.
{
             if (m_tail == nullptr) {
                 THROW(INDEX_EXCEPTION("Accessing empty list"))
             }
             return m_tail->m_val;
         }
template<typename T> const val_type& wlp::linked_list< T >::back () const inline
Returns
a const reference to the value at the end of the List
Definition at line 353 of file LinkedList.h.
References INDEX_EXCEPTION, wlp::linked_list< T >::m_tail, wlp::LinkedListNode< T >::m_val, and THROW.
{
             if (m_tail == nullptr) {
                 THROW(INDEX_EXCEPTION("Accessing empty list"))
             }
             return m_tail->m_val;
         }
template<typename T> iterator wlp::linked_list< T >::begin () inline
Obtain an iterator to the first element in the list. Returns pass-the-end iterator (nullptr) if there are no elements (m_pStart == nullptr)
Returns
iterator the first element
Definition at line 372 of file LinkedList.h.
References wlp::linked_list< T >::m_head.
{
             return iterator(m_head, this);
         }
template<typename T> const_iterator wlp::linked_list< T >::begin () const inline
See Also
List<T>::begin()
Returns
a constant iterator to the first element in the list
Definition at line 387 of file LinkedList.h.
References wlp::linked_list< T >::m_head.
{
             return const_iterator(m_head, this);
         }
template<typename T> size_type wlp::linked_list< T >::capacity () const inline
Returns
the maximum number of elements storable in the list
Definition at line 278 of file LinkedList.h.
{
             return static_cast<size_type>(-1);
         }
template<typename T > void wlp::linked_list< T >::clear () inline noexcept
Removes all the elements in the list.
Definition at line 643 of file LinkedList.h.
References wlp::LinkedListNode< T >::m_next.
Referenced by wlp::linked_list< T >::operator=(), and wlp::linked_list< T >::~linked_list().
{
         node_type *pTmp;
         while (m_head != nullptr) {
             pTmp = m_head;
             m_head = m_head->m_next;
             free<node_type>(pTmp);
         }
         m_size = 0;
         m_tail = nullptr;
         m_head = nullptr;
     }
template<typename T> bool wlp::linked_list< T >::empty () const inline
Returns
whether the list has no elements
Definition at line 264 of file LinkedList.h.
References wlp::linked_list< T >::m_size.
{
             return m_size == 0;
         };
template<typename T> iterator wlp::linked_list< T >::end () inline
Returns
a pass-the-end iterator for this map
Definition at line 379 of file LinkedList.h.
Referenced by wlp::linked_list< T >::erase(), wlp::linked_list< T >::find(), and wlp::linked_list< T >::insert().
{
             return iterator(nullptr, this);
         }
template<typename T> const_iterator wlp::linked_list< T >::end () const inline
See Also
List<T>::end()
Returns
a constant pass-the-end iterator
Definition at line 395 of file LinkedList.h.
{
             return const_iterator(nullptr, this);
         }
template<typename T > linked_list< T >::iterator wlp::linked_list< T >::erase (size_type i)
Removes the value stored at the given index
Parameters
i the index to remove at
Returns
iterator to the next element, or pass-the-end
Definition at line 657 of file LinkedList.h.
References wlp::end(), wlp::LinkedListNode< T >::m_next, and wlp::LinkedListNode< T >::m_prev.
{
         if (!m_size) {
             return end();
         }
         if (i >= m_size) {
             i %= m_size;
         }
         node_type *pTmp = m_head;
         while (i-- > 0) {
             pTmp = pTmp->m_next;
         }
         if (pTmp->m_prev != nullptr) {
             pTmp->m_prev->m_next = pTmp->m_next;
         } else {
             m_head = pTmp->m_next;
         }
         if (pTmp->m_next != nullptr) {
             pTmp->m_next->m_prev = pTmp->m_prev;
         } else {
             m_tail = pTmp->m_prev;
         }
         node_type *next = pTmp->m_next;
         free<node_type>(pTmp);
         m_size--;
         return iterator(next, this);
     }
template<typename T> iterator wlp::linked_list< T >::erase (const iterator & it) inline
Removes the value pointed to by an iterator.
Parameters
it the iterator whose value to remove
Returns
iterator to the next element, or pass-the-end
Definition at line 471 of file LinkedList.h.
References wlp::linked_list< T >::end(), wlp::LinkedListIterator< T, Ref, Ptr >::m_current, wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_next, wlp::LinkedListNode< T >::m_prev, wlp::linked_list< T >::m_size, and wlp::linked_list< T >::m_tail.
{
             if (m_size == 0 || !it.m_current) {
                 return end();
             }
             node_type *pTmp = it.m_current;
             if (pTmp->m_prev != nullptr) {
                 pTmp->m_prev->m_next = pTmp->m_next;
             } else {
                 m_head = pTmp->m_next;
             }
             if (pTmp->m_next != nullptr) {
                 pTmp->m_next->m_prev = pTmp->m_prev;
             } else {
                 m_tail = pTmp->m_prev;
             }
             node_type *next = pTmp->m_next;
             free<node_type>(pTmp);
             --m_size;
             return iterator(next, this);
         }
template<typename T> iterator wlp::linked_list< T >::find (const val_type & val) inline
Find the first occurrence of a value in the list.
Parameters
val the value to find
Returns
iterator to the first occurrence of the element or pass-the-end if not found
Definition at line 588 of file LinkedList.h.
References wlp::linked_list< T >::end(), wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_next, and wlp::LinkedListNode< T >::m_val.
{
             node_type *pTmp = m_head;
             while(pTmp) {
                 if (pTmp->m_val == val) {
                     return iterator(pTmp, this);
                 }
                 pTmp = pTmp->m_next;
             }
             return end();
         }
template<typename T> const_iterator wlp::linked_list< T >::find (const val_type & val) const inline
Find the first occurrence of a value in the list.
Parameters
val the value to find
Returns
iterator to the first occurrence of the element or pass-the-end if not found
Definition at line 606 of file LinkedList.h.
References wlp::linked_list< T >::end(), wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_next, and wlp::LinkedListNode< T >::m_val.
{
             node_type *pTmp = m_head;
             while(pTmp) {
                 if (pTmp->m_val == val) {
                     return const_iterator(pTmp, this);
                 }
                 pTmp = pTmp->m_next;
             }
             return end();
         }
template<typename T> val_type& wlp::linked_list< T >::front () inline
Returns
a reference to the value at the start of the List
Definition at line 323 of file LinkedList.h.
References INDEX_EXCEPTION, wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_val, and THROW.
{
             if (m_head == nullptr) {
                 THROW(INDEX_EXCEPTION("Accessing empty list"))
             }
             return m_head->m_val;
         }
template<typename T> const val_type& wlp::linked_list< T >::front () const inline
Returns
a const reference to the value at the start of the List
Definition at line 333 of file LinkedList.h.
References INDEX_EXCEPTION, wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_val, and THROW.
{
             if (m_head == nullptr) {
                 THROW(INDEX_EXCEPTION("Accessing empty list"))
             }
             return m_head->m_val;
         }
template<typename T > linked_list< T >::size_type wlp::linked_list< T >::index_of (const val_type & val) const inline
Find the index of the first element from the beginning of the List that equals
val
. Returns the size of the list if not found.
Parameters
val value to search for
Returns
the index of the first occurrence of the element
Definition at line 714 of file LinkedList.h.
References wlp::LinkedListNode< T >::m_next, and wlp::LinkedListNode< T >::m_val.
{
         node_type *pTmp = m_head;
         for (size_type i = 0; i < m_size; i++) {
             if (pTmp->m_val == val) {
                 return i;
             }
             pTmp = pTmp->m_next;
         }
         return m_size;
     }
template<typename T> template<typename V > iterator wlp::linked_list< T >::insert (size_type i, V && val) inline
Insert a value at the given index.
Parameters
i the index of the node to insert
val the value to insert
Returns
iterator to the inserted element
Definition at line 407 of file LinkedList.h.
References wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_next, wlp::LinkedListNode< T >::m_prev, wlp::linked_list< T >::m_size, wlp::linked_list< T >::m_tail, and wlp::LinkedListNode< T >::m_val.
{
             if (!m_size) { i = 0; }
             else { i %= m_size; }
             node_type *node = malloc<node_type>();
             node->m_val = forward<V>(val);
             if (m_head == nullptr) {
                 node->m_next = nullptr;
                 node->m_prev = nullptr;
                 m_head = node;
                 m_tail = node;
                 ++m_size;
                 return iterator(m_head, this);
             }
             node_type *pTmp = m_head;
             while(i-- > 0) {
                 pTmp = pTmp->m_next;
             }
             node->m_next = pTmp;
             node->m_prev = pTmp->m_prev;
             node->m_next->m_prev = node;
             if (node->m_prev) { node->m_prev->m_next = node; }
             else { m_head = node; }
             ++m_size;
             return iterator(node, this);
         }
template<typename T> template<typename V > iterator wlp::linked_list< T >::insert (const iterator & it, V && val) inline
Insert a value at the given iterator.
Parameters
it the iterator to the node to insert
val the value to insert
Returns
iterator to the inserted value
Definition at line 441 of file LinkedList.h.
References wlp::linked_list< T >::end(), wlp::LinkedListIterator< T, Ref, Ptr >::m_current, wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_next, wlp::LinkedListNode< T >::m_prev, wlp::linked_list< T >::m_size, wlp::linked_list< T >::m_tail, wlp::LinkedListNode< T >::m_val, and wlp::linked_list< T >::push_back().
{
             if (it == end()) {
                 push_back(forward<V>(val));
                 return iterator(m_tail, this);
             }
             node_type *node = malloc<node_type>();
             node->m_val = forward<V>(val);
             node->m_next = it.m_current;
             node->m_prev = it.m_current->m_prev;
             node->m_next->m_prev = node;
             if (node->m_prev) { node->m_prev->m_next = node; }
             else { m_head = node; }
             ++m_size;
             return iterator(node, this);
         }
template<typename T> list_type& wlp::linked_list< T >::operator= (const list_type &) delete
Delete copy assignment.
Returns
reference to this list
template<typename T> list_type& wlp::linked_list< T >::operator= (list_type && list) inline
Move assignment operator.
Parameters
list the list to move
Returns
a reference to this list
Definition at line 630 of file LinkedList.h.
References wlp::linked_list< T >::clear(), wlp::linked_list< T >::m_head, wlp::linked_list< T >::m_size, and wlp::linked_list< T >::m_tail.
{
             clear();
             m_size = list.m_size;
             m_head = list.m_head;
             m_tail = list.m_tail;
             list.m_size = 0;
             list.m_head = nullptr;
             list.m_tail = nullptr;
             return *this;
         }
template<typename T> val_type& wlp::linked_list< T >::operator[] (size_type index) inline
Array indexing operator at behind the scenes
Parameters
index to get
Returns
reference to the value at that index
Definition at line 305 of file LinkedList.h.
References wlp::linked_list< T >::at().
{
             return at(index);
         }
template<typename T> const val_type& wlp::linked_list< T >::operator[] (size_type index) const inline
Array indexing operator const variant at behind the scenes
Parameters
index to get
Returns
reference to the value at that index
Definition at line 316 of file LinkedList.h.
References wlp::linked_list< T >::at().
{
             return at(index);
         }
template<typename T> void wlp::linked_list< T >::pop_back () inline
Remove the last element from the list.
Definition at line 538 of file LinkedList.h.
References wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_next, wlp::LinkedListNode< T >::m_prev, wlp::linked_list< T >::m_size, and wlp::linked_list< T >::m_tail.
{
             if (!m_tail) {
                 return;
             }
             node_type *pTmp = m_tail;
             m_tail = m_tail->m_prev;
             if (m_tail != nullptr) {
                 m_tail->m_next = nullptr;
             } else {
                 m_head = nullptr;
             }
             free<node_type>(pTmp);
             m_size--;
         }
template<typename T> void wlp::linked_list< T >::pop_front () inline
Remove the first element from the list.
Definition at line 556 of file LinkedList.h.
References wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_next, wlp::LinkedListNode< T >::m_prev, wlp::linked_list< T >::m_size, and wlp::linked_list< T >::m_tail.
{
             if (!m_head) {
                 return;
             }
             node_type *pTmp = m_head;
             m_head = m_head->m_next;
             if (m_head != nullptr) {
                 m_head->m_prev = nullptr;
             } else {
                 m_tail = nullptr;
             }
             free<node_type>(pTmp);
             m_size--;
         }
template<typename T> template<typename V > void wlp::linked_list< T >::push_back (V && val) inline
Creates a new node and pushes it to the back of the list.
Parameters
value the value to store at the new node
Definition at line 498 of file LinkedList.h.
References wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_next, wlp::LinkedListNode< T >::m_prev, wlp::linked_list< T >::m_size, wlp::linked_list< T >::m_tail, and wlp::LinkedListNode< T >::m_val.
Referenced by wlp::linked_list< T >::insert().
{
             node_type *node = malloc<node_type>();
             node->m_val = forward<V>(val);
             node->m_next = nullptr;
             if (m_head == nullptr) {
                 m_head = node;
                 node->m_prev = nullptr;
             } else {
                 m_tail->m_next = node;
                 node->m_prev = m_tail;
             }
             m_tail = node;
             ++m_size;
         }
template<typename T> template<typename V > void wlp::linked_list< T >::push_front (V && val) inline
Creates a new node and pushes it to the front of the list.
Parameters
value the value to store at the new node
Definition at line 519 of file LinkedList.h.
References wlp::linked_list< T >::m_head, wlp::LinkedListNode< T >::m_next, wlp::LinkedListNode< T >::m_prev, wlp::linked_list< T >::m_size, wlp::linked_list< T >::m_tail, and wlp::LinkedListNode< T >::m_val.
{
             node_type *node = malloc<node_type>();
             node->m_val = forward<V>(val);
             node->m_prev = nullptr;
             if (m_tail == nullptr) {
                 m_tail = node;
                 node->m_next = nullptr;
             } else {
                 m_head->m_prev = node;
                 node->m_next = m_head;
             }
             m_head = node;
             m_size++;
         }
template<typename T> size_type wlp::linked_list< T >::size () const inline
Returns
the length of the list
Definition at line 271 of file LinkedList.h.
References wlp::linked_list< T >::m_size.
{
             return m_size;
         }
Friends And Related Function Documentation
template<typename T> friend struct LinkedListIterator< T, const T &, const T * > friend
Definition at line 222 of file LinkedList.h.
template<typename T> friend struct LinkedListIterator< T, T &, T * > friend
Definition at line 221 of file LinkedList.h.
Field Documentation
template<typename T> node_type* wlp::linked_list< T >::m_head private
Pointer to first node in the list.
Definition at line 211 of file LinkedList.h.
Referenced by wlp::linked_list< T >::begin(), wlp::linked_list< T >::erase(), wlp::linked_list< T >::find(), wlp::linked_list< T >::front(), wlp::linked_list< T >::insert(), wlp::LinkedListIterator< T, Ref, Ptr >::operator--(), wlp::linked_list< T >::operator=(), wlp::linked_list< T >::pop_back(), wlp::linked_list< T >::pop_front(), wlp::linked_list< T >::push_back(), and wlp::linked_list< T >::push_front().
template<typename T> size_type wlp::linked_list< T >::m_size private
The number of elements in the list.
Definition at line 219 of file LinkedList.h.
Referenced by wlp::linked_list< T >::empty(), wlp::linked_list< T >::erase(), wlp::linked_list< T >::insert(), wlp::linked_list< T >::operator=(), wlp::linked_list< T >::pop_back(), wlp::linked_list< T >::pop_front(), wlp::linked_list< T >::push_back(), wlp::linked_list< T >::push_front(), and wlp::linked_list< T >::size().
template<typename T> node_type* wlp::linked_list< T >::m_tail private
Pointer to last node in the list.
Definition at line 215 of file LinkedList.h.
Referenced by wlp::linked_list< T >::back(), wlp::linked_list< T >::erase(), wlp::linked_list< T >::insert(), wlp::linked_list< T >::operator=(), wlp::linked_list< T >::pop_back(), wlp::linked_list< T >::pop_front(), wlp::linked_list< T >::push_back(), and wlp::linked_list< T >::push_front().
The documentation for this class was generated from the following file:
wlib/stl/LinkedList.h