Waterloop Wlib: wlp::tree_map< Key, Val, Cmp > Class Template Reference
wlp::tree_map< Key, Val, Cmp > Class Template Reference
#include <TreeMap.h>
Public Types
typedef tree_map< Key, Val, Cmp > map_type
typedef tree< tuple< Key, Val >
, Key, Val, MapGetKey< Key,
Val >, MapGetVal< Key, Val >
, Cmp > table_type
typedef table_type::iterator iterator
typedef table_type::const_iterator const_iterator
typedef table_type::size_type size_type
typedef Key key_type
typedef Val val_type
Public Member Functions
tree_map ()
tree_map (const map_type &)=delete
tree_map (map_type &&map)
size_type size () const
size_type capacity () const
bool empty () const
const table_type * get_backing_table () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
void clear () noexcept
template<typename K , typename V >
pair< iterator, bool > insert (K &&key, V &&val)
template<typename K , typename V >
pair< iterator, bool > insert_or_assign (K &&key, V &&val)
iterator erase (const iterator &pos)
bool erase (const key_type &key)
val_type & at (const key_type &key)
const val_type & at (const key_type &key) const
bool contains (const key_type &key) const
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
template<typename K >
val_type & operator[] (K &&key)
map_type & operator= (const map_type &)=delete
map_type & operator= (map_type &&map)
Private Attributes
table_type m_table
Detailed Description
template<typename Key, typename Val, typename Cmp = comparator<Key>>
class wlp::tree_map< Key, Val, Cmp >
Map implementation using
RedBlackTree
as the backing data structure.
See Also
wlp::ChainHashMap
wlp::RedBlackTree
Template Parameters
Key key type
Val value type
Cmp key comparator type, which uses the default comparator
Definition at line 32 of file TreeMap.h.
Member Typedef Documentation
template<typename Key , typename Val , typename Cmp = comparator<Key>> typedef table_type::const_iterator wlp::tree_map< Key, Val, Cmp >::const_iterator
Definition at line 41 of file TreeMap.h.
template<typename Key , typename Val , typename Cmp = comparator<Key>> typedef table_type::iterator wlp::tree_map< Key, Val, Cmp >::iterator
Definition at line 40 of file TreeMap.h.
template<typename Key , typename Val , typename Cmp = comparator<Key>> typedef Key wlp::tree_map< Key, Val, Cmp >::key_type
Definition at line 44 of file TreeMap.h.
template<typename Key , typename Val , typename Cmp = comparator<Key>> typedef tree_map<Key, Val, Cmp> wlp::tree_map< Key, Val, Cmp >::map_type
Definition at line 34 of file TreeMap.h.
template<typename Key , typename Val , typename Cmp = comparator<Key>> typedef table_type::size_type wlp::tree_map< Key, Val, Cmp >::size_type
Definition at line 42 of file TreeMap.h.
template<typename Key , typename Val , typename Cmp = comparator<Key>> typedef tree<tuple<Key, Val>, Key, Val, MapGetKey<Key, Val>, MapGetVal<Key, Val>, Cmp > wlp::tree_map< Key, Val, Cmp >::table_type
Definition at line 39 of file TreeMap.h.
template<typename Key , typename Val , typename Cmp = comparator<Key>> typedef Val wlp::tree_map< Key, Val, Cmp >::val_type
Definition at line 45 of file TreeMap.h.
Constructor & Destructor Documentation
template<typename Key , typename Val , typename Cmp = comparator<Key>> wlp::tree_map< Key, Val, Cmp >::tree_map () inline explicit
Definition at line 51 of file TreeMap.h.
                 : m_table() {
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> wlp::tree_map< Key, Val, Cmp >::tree_map (const map_type &) delete
template<typename Key , typename Val , typename Cmp = comparator<Key>> wlp::tree_map< Key, Val, Cmp >::tree_map (map_type && map) inline
Definition at line 57 of file TreeMap.h.
                 : m_table(move(map.m_table)) {
         }
Member Function Documentation
template<typename Key , typename Val , typename Cmp = comparator<Key>> val_type& wlp::tree_map< Key, Val, Cmp >::at (const key_type & key) inline
Definition at line 124 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return *m_table.find(key);
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> const val_type& wlp::tree_map< Key, Val, Cmp >::at (const key_type & key) const inline
Definition at line 128 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return *m_table.find(key);
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> iterator wlp::tree_map< Key, Val, Cmp >::begin () inline
Definition at line 77 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::begin(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.begin();
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> const_iterator wlp::tree_map< Key, Val, Cmp >::begin () const inline
Definition at line 81 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::begin(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.begin();
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> size_type wlp::tree_map< Key, Val, Cmp >::capacity () const inline
Definition at line 65 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::capacity(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.capacity();
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> void wlp::tree_map< Key, Val, Cmp >::clear () inline noexcept
Definition at line 93 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::clear(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             m_table.clear();
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> bool wlp::tree_map< Key, Val, Cmp >::contains (const key_type & key) const inline
Definition at line 132 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::end(), wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.find(key) != m_table.end();
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> bool wlp::tree_map< Key, Val, Cmp >::empty () const inline
Definition at line 69 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::empty(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.empty();
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> iterator wlp::tree_map< Key, Val, Cmp >::end () inline
Definition at line 85 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::end(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.end();
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> const_iterator wlp::tree_map< Key, Val, Cmp >::end () const inline
Definition at line 89 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::end(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.end();
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> iterator wlp::tree_map< Key, Val, Cmp >::erase (const iterator & pos) inline
Definition at line 113 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::erase(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             iterator tmp = pos;
             ++tmp;
             m_table.erase(pos);
             return tmp;
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> bool wlp::tree_map< Key, Val, Cmp >::erase (const key_type & key) inline
Definition at line 120 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::erase(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.erase(key) > 0;
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> iterator wlp::tree_map< Key, Val, Cmp >::find (const key_type & key) inline
Definition at line 136 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.find(key);
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> const_iterator wlp::tree_map< Key, Val, Cmp >::find (const key_type & key) const inline
Definition at line 140 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), and wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return m_table.find(key);
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> const table_type* wlp::tree_map< Key, Val, Cmp >::get_backing_table () const inline
Definition at line 73 of file TreeMap.h.
References wlp::tree_map< Key, Val, Cmp >::m_table.
{
             return &m_table;
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> template<typename K , typename V > pair<iterator, bool> wlp::tree_map< Key, Val, Cmp >::insert (K && key, V && val) inline
Definition at line 98 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_unique(), wlp::tree_map< Key, Val, Cmp >::m_table, and wlp::make_tuple().
{
             return m_table.insert_unique(make_tuple(forward<K>(key), forward<V>(val)));
         };
template<typename Key , typename Val , typename Cmp = comparator<Key>> template<typename K , typename V > pair<iterator, bool> wlp::tree_map< Key, Val, Cmp >::insert_or_assign (K && key, V && val) inline
Definition at line 103 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::end(), wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::find(), wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_unique(), wlp::tree_map< Key, Val, Cmp >::m_table, and wlp::make_tuple().
{
             iterator it = m_table.find(key);
             if (it == m_table.end()) {
                 return m_table.insert_unique(make_tuple(forward<K>(key), forward<V>(val)));
             } else {
                 *it = forward<V>(val);
                 return pair<iterator, bool>(it, false);
             }
         };
template<typename Key , typename Val , typename Cmp = comparator<Key>> map_type& wlp::tree_map< Key, Val, Cmp >::operator= (const map_type &) delete
template<typename Key , typename Val , typename Cmp = comparator<Key>> map_type& wlp::tree_map< Key, Val, Cmp >::operator= (map_type && map) inline
Definition at line 152 of file TreeMap.h.
References wlp::tree_map< Key, Val, Cmp >::m_table, and wlp::move().
{
             m_table = move(map.m_table);
             return *this;
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> template<typename K > val_type& wlp::tree_map< Key, Val, Cmp >::operator[] (K && key) inline
Definition at line 145 of file TreeMap.h.
References wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_unique(), wlp::pair< First, Second >::m_first, wlp::tree_map< Key, Val, Cmp >::m_table, and wlp::make_tuple().
{
             pair<iterator, bool> result = m_table.insert_unique(make_tuple(forward<K>(key), val_type()));
             return *result.m_first;
         }
template<typename Key , typename Val , typename Cmp = comparator<Key>> size_type wlp::tree_map< Key, Val, Cmp >::size () const inline
Definition at line 61 of file TreeMap.h.
References wlp::tree_map< Key, Val, Cmp >::m_table, and wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::size().
{
             return m_table.size();
         }
Field Documentation
template<typename Key , typename Val , typename Cmp = comparator<Key>> table_type wlp::tree_map< Key, Val, Cmp >::m_table private
Definition at line 48 of file TreeMap.h.
Referenced by wlp::tree_map< Key, Val, Cmp >::at(), wlp::tree_map< Key, Val, Cmp >::begin(), wlp::tree_map< Key, Val, Cmp >::capacity(), wlp::tree_map< Key, Val, Cmp >::clear(), wlp::tree_map< Key, Val, Cmp >::contains(), wlp::tree_map< Key, Val, Cmp >::empty(), wlp::tree_map< Key, Val, Cmp >::end(), wlp::tree_map< Key, Val, Cmp >::erase(), wlp::tree_map< Key, Val, Cmp >::find(), wlp::tree_map< Key, Val, Cmp >::get_backing_table(), wlp::tree_map< Key, Val, Cmp >::insert(), wlp::tree_map< Key, Val, Cmp >::insert_or_assign(), wlp::tree_map< Key, Val, Cmp >::operator=(), wlp::tree_map< Key, Val, Cmp >::operator[](), and wlp::tree_map< Key, Val, Cmp >::size().
The documentation for this class was generated from the following file:
wlib/stl/TreeMap.h