Waterloop Wlib: wlp::ChainHashMap< Key, Val, Hasher, Equals > Class Template Reference
wlp::ChainHashMap< Key, Val, Hasher, Equals > Class Template Reference
#include <ChainMap.h>
Public Types
typedef ChainHashMap< Key, Val,
Hasher, Equals > map_type
typedef ChainHashMapIterator
< Key, Val, Val &, Val
*, Hasher, Equals > iterator
typedef ChainHashMapIterator
< Key, Val, const Val &, const
Val *, Hasher, Equals > const_iterator
typedef ChainHashMapNode< Key,
Val > node_type
typedef Key key_type
typedef Val val_type
typedef wlp::size_type size_type
typedef uint8_t percent_type
Public Member Functions
ChainHashMap (size_type n=12, percent_type max_load=75)
ChainHashMap (const map_type &)=delete
ChainHashMap (map_type &&map)
~ChainHashMap ()
size_type size () const
size_type capacity () const
percent_type max_load () const
bool empty () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void clear () noexcept
template<typename K , typename V >
Pair< iterator, bool > insert (K &&key, V &&val)
template<typename K , typename V >
Pair< iterator, bool > insert_or_assign (K &&key, V &&val)
iterator erase (const iterator &pos)
bool erase (const key_type &key)
val_type & at (const key_type &key)
const val_type & at (const key_type &key) const
bool contains (const key_type &key) const
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
template<typename K >
val_type & operator[] (K &&key)
map_type & operator= (const map_type &)=delete
map_type & operator= (map_type &&map)
template<typename K , typename V >
Pair< typename ChainHashMap
< Key, Val, Hasher, Equals >
::iterator, bool > insert (K &&key, V &&val)
template<typename K , typename V >
Pair< typename ChainHashMap
< Key, Val, Hasher, Equals >
::iterator, bool > insert_or_assign (K &&key, V &&val)
template<typename K >
ChainHashMap< Key, Val, Hasher,
Equals >::val_type & operator[] (K &&key)
Private Member Functions
void init_buckets (size_type n)
size_type bucket_index (const key_type &key, size_type max_elements) const
size_type hash (const key_type &key) const
void ensure_capacity ()
Private Attributes
Hasher m_hash
Equals m_equal
node_type ** m_buckets
size_type m_num_elements
size_type m_capacity
percent_type m_max_load
Friends
struct ChainHashMapIterator< Key, Val, Val &, Val *, Hasher, Equals >
struct ChainHashMapIterator< Key, Val, const Val &, const Val *, Hasher, Equals >
Detailed Description
template<typename Key, typename Val, typename Hasher, typename Equals>
class wlp::ChainHashMap< Key, Val, Hasher, Equals >
Hasher map implemented using separate chaining, in the spirit of std::unordered_map.
Template Parameters
Key key type
Val value type
Hasher hash function
Equals key equality function
Definition at line 30 of file ChainMap.h.
Member Typedef Documentation
template<typename Key, typename Val, typename Hasher, typename Equals> typedef ChainHashMapIterator<Key, Val, const Val &, const Val *, Hasher, Equals> wlp::ChainHashMap< Key, Val, Hasher, Equals >::const_iterator
Definition at line 208 of file ChainMap.h.
template<typename Key, typename Val, typename Hasher, typename Equals> typedef ChainHashMapIterator<Key, Val, Val &, Val *, Hasher, Equals> wlp::ChainHashMap< Key, Val, Hasher, Equals >::iterator
Definition at line 207 of file ChainMap.h.
template<typename Key, typename Val, typename Hasher, typename Equals> typedef Key wlp::ChainHashMap< Key, Val, Hasher, Equals >::key_type
Definition at line 211 of file ChainMap.h.
template<typename Key, typename Val, typename Hasher, typename Equals> typedef ChainHashMap<Key, Val, Hasher, Equals> wlp::ChainHashMap< Key, Val, Hasher, Equals >::map_type
Definition at line 206 of file ChainMap.h.
template<typename Key, typename Val, typename Hasher, typename Equals> typedef ChainHashMapNode<Key, Val> wlp::ChainHashMap< Key, Val, Hasher, Equals >::node_type
Definition at line 209 of file ChainMap.h.
template<typename Key, typename Val, typename Hasher, typename Equals> typedef uint8_t wlp::ChainHashMap< Key, Val, Hasher, Equals >::percent_type
Definition at line 215 of file ChainMap.h.
template<typename Key, typename Val, typename Hasher, typename Equals> typedef wlp::size_type wlp::ChainHashMap< Key, Val, Hasher, Equals >::size_type
Definition at line 214 of file ChainMap.h.
template<typename Key, typename Val, typename Hasher, typename Equals> typedef Val wlp::ChainHashMap< Key, Val, Hasher, Equals >::val_type
Definition at line 212 of file ChainMap.h.
Constructor & Destructor Documentation
template<typename Key, typename Val, typename Hasher, typename Equals> wlp::ChainHashMap< Key, Val, Hasher, Equals >::ChainHashMap (size_type n = 12, percent_type max_load = 75) inline explicit
Create and initialize an empty hash map.
Precondition
the hash map requires definition of an initial bucket array size and a maximum load factor before rehashing
Parameters
n initial size of the bucket list; each bucket is initialized to nullptr
max_load an integer value denoting the max percent load factor, e.g. 100 = 1.00
hash hash function for the key type, default is
wlp::Hasher
equal equality function for the key type, default is
wlp::Equals
Definition at line 268 of file ChainMap.h.
                 : m_hash(Hasher()),
                   m_equal(Equals()),
                   m_num_elements(0),
                   m_capacity(n),
                   m_max_load(max_load) {
             init_buckets(n);
         }
template<typename Key, typename Val, typename Hasher, typename Equals> wlp::ChainHashMap< Key, Val, Hasher, Equals >::ChainHashMap (const map_type &) delete
Disable copy constructor.
template<typename Key, typename Val, typename Hasher, typename Equals> wlp::ChainHashMap< Key, Val, Hasher, Equals >::ChainHashMap (map_type && map) inline
Move constructor.
Parameters
map hash map to copy
Definition at line 289 of file ChainMap.h.
                                      :
                 m_hash(move(map.m_hash)),
                 m_equal(move(map.m_equal)),
                 m_buckets(move(map.m_buckets)),
                 m_num_elements(move(map.m_num_elements)),
                 m_capacity(move(map.m_capacity)),
                 m_max_load(move(map.m_max_load)) {
             map.m_num_elements = 0;
             map.m_capacity = 0;
             map.m_buckets = nullptr;
         }
template<typename Key , typename Val , typename Hasher , typename Equals > wlp::ChainHashMap< Key, Val, Hasher, Equals >::~ChainHashMap ()
Destroy the hash map, freeing allocated nodes and memory allocated for the array.
Definition at line 819 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::next.
{
         if (!m_buckets) {
             return;
         }
         for (size_type i = 0; i < m_capacity; ++i) {
             node_type *cur = m_buckets[i];
             if (cur) {
                 while (cur) {
                     node_type *next = cur->next;
                     free<node_type>(cur);
                     cur = next;
                 }
             }
         }
         free<node_type *>(m_buckets);
         m_buckets = nullptr;
     }
Member Function Documentation
template<typename Key, typename Val, typename Hasher, typename Equals> val_type& wlp::ChainHashMap< Key, Val, Hasher, Equals >::at (const key_type & key) inline
Returns the value corresponding to a provided key.
Parameters
key the key for which to find the value
Returns
the value mapped to by the key
Exceptions
KeyException if the key does not map to a value
Definition at line 490 of file ChainMap.h.
{
             return *find(key);
         }
template<typename Key, typename Val, typename Hasher, typename Equals> const val_type& wlp::ChainHashMap< Key, Val, Hasher, Equals >::at (const key_type & key) const inline
See Also
ChainHashMap<Key, Val, Hasher, Equals>::at()
Parameters
key key for which to find the value
Returns
the mapped value
Exceptions
KeyException if the key does not exist
Definition at line 500 of file ChainMap.h.
{
             return *find(key);
         }
template<typename Key, typename Val, typename Hasher, typename Equals> iterator wlp::ChainHashMap< Key, Val, Hasher, Equals >::begin () inline
Obtain an iterator to the first element in the hash map. Returns pass-the-end iterator if there are no elements in the hash map.
Returns
iterator the first element
Definition at line 389 of file ChainMap.h.
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::begin().
{
             if (m_num_elements == 0) {
                 return end();
             }
             for (size_type i = 0; i < m_capacity; ++i) {
                 if (m_buckets[i]) {
                     return iterator(m_buckets[i], this);
                 }
             }
             return end();
         }
template<typename Key, typename Val, typename Hasher, typename Equals> const_iterator wlp::ChainHashMap< Key, Val, Hasher, Equals >::begin () const inline
See Also
ChainHashMap<Key, Val, Hasher, Equals>::begin()
Returns
a constant iterator to the first element
Definition at line 412 of file ChainMap.h.
{
             if (m_num_elements == 0) {
                 return end();
             }
             for (size_type i = 0; i < m_capacity; ++i) {
                 if (m_buckets[i]) {
                     return const_iterator(m_buckets[i], this);
                 }
             }
             return end();
         }
template<typename Key, typename Val, typename Hasher, typename Equals> size_type wlp::ChainHashMap< Key, Val, Hasher, Equals >::bucket_index (const key_type & key, size_type max_elements) const inline private
Obtain the bucket index in an array with the specified number of maximum elements.
Parameters
key the key to hash
max_elements the maximum number of buckets
Returns
an index i such that 0 <= i < max_elements
Definition at line 325 of file ChainMap.h.
{
             return m_hash(key) % max_elements;
         }
template<typename Key, typename Val, typename Hasher, typename Equals> size_type wlp::ChainHashMap< Key, Val, Hasher, Equals >::capacity () const inline
Returns
the current size of the backing array
Definition at line 364 of file ChainMap.h.
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::capacity().
{
             return m_capacity;
         }
template<typename Key , typename Val , typename Hasher , typename Equals > void wlp::ChainHashMap< Key, Val, Hasher, Equals >::clear () noexcept
Erase all elements in the map, deallocating them and resetting the element count to zero.
Definition at line 596 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::next.
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::clear().
{
         for (size_type i = 0; i < m_capacity; ++i) {
             node_type *cur = m_buckets[i];
             node_type *next;
             while (cur) {
                 next = cur->next;
                 free<node_type>(cur);
                 cur = next;
             }
             m_buckets[i] = nullptr;
         }
         m_num_elements = 0;
     }
template<typename Key , typename Val , typename Hasher , typename Equals > bool wlp::ChainHashMap< Key, Val, Hasher, Equals >::contains (const key_type & key) const
Parameters
key key for which to check existence of a value
Returns
true if the key maps to a value
Definition at line 739 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::m_key, and wlp::ChainHashMapNode< Key, Val >::next.
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::contains().
{
         size_type i = hash(key);
         node_type *cur = m_buckets[i];
         if (!cur) {
             return false;
         }
         while (cur && !m_equal(key, cur->m_key)) {
             cur = cur->next;
         }
         return cur != nullptr;
     }
template<typename Key, typename Val, typename Hasher, typename Equals> bool wlp::ChainHashMap< Key, Val, Hasher, Equals >::empty () const inline
Returns
true if the map is empty
Definition at line 378 of file ChainMap.h.
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::empty().
{
             return m_num_elements == 0;
         }
template<typename Key, typename Val, typename Hasher, typename Equals> iterator wlp::ChainHashMap< Key, Val, Hasher, Equals >::end () inline
Returns
a pass-the-end iterator for this map
Definition at line 404 of file ChainMap.h.
Referenced by wlp::ChainHashMap< Key, Key, Hash, Equal >::begin(), and wlp::ChainHashSet< Key, Hash, Equal >::end().
{
             return iterator(nullptr, this);
         }
template<typename Key, typename Val, typename Hasher, typename Equals> const_iterator wlp::ChainHashMap< Key, Val, Hasher, Equals >::end () const inline
See Also
ChainHashMap<Key, Val, Hasher, Equals>::end()
Returns
a constant pass-the-end iterator
Definition at line 428 of file ChainMap.h.
{
             return const_iterator(nullptr, this);
         }
template<typename Key , typename Val , typename Hasher , typename Equals > void wlp::ChainHashMap< Key, Val, Hasher, Equals >::ensure_capacity () private
Resize and rehash the hash map if the current load factor exceeds or equals the maximum load factor. This function will double the size of the backing array, allocating a new array, and fully deallocating the previous array.
Precondition
this function will create a new array allocator, however the same node allocator will be used, which means that the node allocator will start drawing from heap memory if the number of elements exceeds the initial max elements
Definition at line 567 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::m_key, and wlp::ChainHashMapNode< Key, Val >::next.
{
         if (m_num_elements * 100 < m_max_load * m_capacity) {
             return;
         }
         size_type new_capacity = static_cast<size_type>(m_capacity * 2);
         node_type **new_buckets = malloc<node_type *[]>(new_capacity);
         for (size_type i = 0; i < new_capacity; ++i) {
             new_buckets[i] = nullptr;
         }
         for (size_type i = 0; i < m_capacity; ++i) {
             if (!m_buckets[i]) {
                 continue;
             }
             node_type *cur = m_buckets[i];
             while (cur) {
                 size_type k = bucket_index(cur->m_key, new_capacity);
                 node_type *first = new_buckets[k];
                 node_type *next = cur->next;
                 cur->next = first;
                 new_buckets[k] = cur;
                 cur = next;
             }
         }
         free<node_type *>(m_buckets);
         m_buckets = new_buckets;
         m_capacity = new_capacity;
     }
template<typename Key , typename Val , typename Hasher , typename Equals > ChainHashMap< Key, Val, Hasher, Equals >::iterator wlp::ChainHashMap< Key, Val, Hasher, Equals >::erase (const iterator & pos)
Erase an element pointed to by the provided pointer.
Parameters
pos element to erase
Returns
the iterator to the next element in the map or pass-the-end if there are no more elements afterwards
Definition at line 655 of file ChainMap.h.
References wlp::ChainHashMapIterator< Key, Val, Ref, Ptr, Hasher, Equals >::m_current, wlp::ChainHashMapNode< Key, Val >::m_key, wlp::ChainHashMapNode< Key, Val >::m_val, and wlp::ChainHashMapNode< Key, Val >::next.
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::erase().
{
         node_type *p_node = pos.m_current;
         if (p_node) {
             node_type *n_node = p_node->next;
             if (n_node) {
                 p_node->next = n_node->next;
                 p_node->m_key = n_node->m_key;
                 p_node->m_val = n_node->m_val;
                 free<node_type>(n_node);
                 --m_num_elements;
                 return pos;
             } else {
                 size_type i = hash(p_node->m_key);
                 node_type *c_node = m_buckets[i];
                 if (c_node == p_node) {
                     free<node_type>(c_node);
                     --m_num_elements;
                     m_buckets[i] = nullptr;
                     while (++i < m_capacity && !m_buckets[i]) {}
                     if (i == m_capacity) {
                         return end();
                     } else {
                         return iterator(m_buckets[i], this);
                     }
                 } else {
                     while (c_node->next != p_node) {
                         c_node = c_node->next;
                     }
                     free<node_type>(c_node->next);
                     --m_num_elements;
                     c_node->next = nullptr;
                     while (++i < m_capacity && !m_buckets[i]) {}
                     if (i == m_capacity) {
                         return end();
                     } else {
                         return iterator(m_buckets[i], this);
                     }
                 }
             }
         }
         return end();
     }
template<typename Key , typename Val , typename Hasher , typename Equals > bool wlp::ChainHashMap< Key, Val, Hasher, Equals >::erase (const key_type & key)
Erase the element with the corresponding key.
Parameters
key the key of the element to erase
Returns
true if erasure occured
Definition at line 699 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::m_key, wlp::ChainHashMapNode< Key, Val >::m_val, and wlp::ChainHashMapNode< Key, Val >::next.
{
         size_type i = hash(key);
         node_type *first = m_buckets[i];
         if (first) {
             node_type *cur = first;
             node_type *next = cur->next;
             if (next) {
                 if (m_equal(key, cur->m_key)) {
                     cur->m_key = next->m_key;
                     cur->m_val = next->m_val;
                     cur->next = next->next;
                     free<node_type>(next);
                     --m_num_elements;
                     return true;
                 }
                 while (next && !m_equal(key, next->m_key)) {
                     cur = next;
                     next = cur->next;
                 }
                 if (next) {
                     cur->next = next->next;
                     free<node_type>(next);
                     --m_num_elements;
                     return true;
                 }
                 return false;
             } else {
                 if (!m_equal(key, cur->m_key)) {
                     return false;
                 }
                 free<node_type>(cur);
                 --m_num_elements;
                 m_buckets[i] = nullptr;
                 return true;
             }
         }
         return false;
     }
template<typename Key , typename Val , typename Hasher , typename Equals > ChainHashMap< Key, Val, Hasher, Equals >::iterator wlp::ChainHashMap< Key, Val, Hasher, Equals >::find (const key_type & key)
Return an iterator to the map element corresponding to the provided key, or pass-the-end if the key does not map to any value in the map.
Parameters
key the key to map
Returns
an iterator to the element mapped by the key
Definition at line 786 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::m_key, and wlp::ChainHashMapNode< Key, Val >::next.
Referenced by wlp::ChainHashMap< Key, Key, Hash, Equal >::at(), and wlp::ChainHashSet< Key, Hash, Equal >::find().
{
         size_type i = hash(key);
         node_type *cur = m_buckets[i];
         if (!cur) {
             return end();
         }
         while (cur && !m_equal(key, cur->m_key)) {
             cur = cur->next;
         }
         if (!cur) {
             return end();
         }
         return iterator(cur, this);
     }
template<typename Key , typename Val , typename Hasher , typename Equals > ChainHashMap< Key, Val, Hasher, Equals >::const_iterator wlp::ChainHashMap< Key, Val, Hasher, Equals >::find (const key_type & key) const
See Also
ChainHashMap<Key, Val, Hasher, Equals>::find()
Parameters
key the key to map
Returns
a const iterator to the element mapped by the key
Definition at line 803 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::m_key, and wlp::ChainHashMapNode< Key, Val >::next.
{
         size_type i = hash(key);
         node_type *cur = m_buckets[i];
         if (!cur) {
             return end();
         }
         while (cur && !m_equal(key, cur->m_key)) {
             cur = cur->next;
         }
         if (!cur) {
             return end();
         }
         return const_iterator(cur, this);
     }
template<typename Key, typename Val, typename Hasher, typename Equals> size_type wlp::ChainHashMap< Key, Val, Hasher, Equals >::hash (const key_type & key) const inline private
Obtain the bucket index of a key in the backing array.
Parameters
key the key to hash
Returns
an index i such that 0 <= i < m_max_elements
Definition at line 335 of file ChainMap.h.
{
             return m_hash(key) % m_capacity;
         }
template<typename Key, typename Val, typename Hasher, typename Equals> void wlp::ChainHashMap< Key, Val, Hasher, Equals >::init_buckets (size_type n) private
Function called when creating the hash map. This function will allocate memory for the backing array and initialize each element to nullptr.
Parameters
n the size of the backing array
Definition at line 559 of file ChainMap.h.
Referenced by wlp::ChainHashMap< Key, Key, Hash, Equal >::ChainHashMap().
{
         m_buckets = malloc<node_type *[]>(n);
         for (size_type i = 0; i < n; ++i) {
             m_buckets[i] = nullptr;
         }
     }
template<typename Key, typename Val, typename Hasher, typename Equals> template<typename K , typename V > Pair<iterator, bool> wlp::ChainHashMap< Key, Val, Hasher, Equals >::insert (K && key, V && val)
Attempt to insert an element into the map. Insertion is prevented if there already exists an element with the provided key
Parameters
key inserted element key
val inserted element value
Returns
a pair consisting of an iterator pointing to the inserted element or the element that prevented insertion and a bool indicating whether insertion occurred
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::insert().
template<typename Key, typename Val, typename Hasher, typename Equals> template<typename K , typename V > Pair<typename ChainHashMap<Key, Val, Hasher, Equals>::iterator, bool> wlp::ChainHashMap< Key, Val, Hasher, Equals >::insert (K && key, V && val)
Definition at line 613 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::m_key, wlp::ChainHashMapNode< Key, Val >::m_val, and wlp::ChainHashMapNode< Key, Val >::next.
{
         ensure_capacity();
         size_type i = hash(key);
         node_type *first = m_buckets[i];
         for (node_type *cur = first; cur; cur = cur->next) {
             if (m_equal(cur->m_key, key)) {
                 return Pair<iterator, bool>(iterator(cur, this), false);
             }
         }
         node_type *tmp = malloc<node_type>();
         tmp->m_key = forward<K>(key);
         tmp->m_val = forward<V>(val);
         tmp->next = first;
         m_buckets[i] = tmp;
         ++m_num_elements;
         return Pair<iterator, bool>(iterator(tmp, this), true);
     };
template<typename Key, typename Val, typename Hasher, typename Equals> template<typename K , typename V > Pair<iterator, bool> wlp::ChainHashMap< Key, Val, Hasher, Equals >::insert_or_assign (K && key, V && val)
Attempt to insert an element into the map. If an element with the same key already exists, override the value mapped to by the provided key.
Parameters
key inserted element key
val inserted element value
Returns
a pair consisting of an iterator pointing to the inserted element or the assigned element, and a bool indicating whether insertion occurred
template<typename Key, typename Val, typename Hasher, typename Equals> template<typename K , typename V > Pair<typename ChainHashMap<Key, Val, Hasher, Equals>::iterator, bool> wlp::ChainHashMap< Key, Val, Hasher, Equals >::insert_or_assign (K && key, V && val)
Definition at line 634 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::m_key, wlp::ChainHashMapNode< Key, Val >::m_val, and wlp::ChainHashMapNode< Key, Val >::next.
{
         ensure_capacity();
         size_type i = hash(key);
         node_type *first = m_buckets[i];
         for (node_type *cur = first; cur; cur = cur->next) {
             if (m_equal(cur->m_key, key)) {
                 cur->m_val = val;
                 return Pair<iterator, bool>(iterator(cur, this), false);
             }
         }
         node_type *tmp = malloc<node_type>();
         tmp->m_key = forward<K>(key);
         tmp->m_val = forward<V>(val);
         tmp->next = first;
         m_buckets[i] = tmp;
         ++m_num_elements;
         return Pair<iterator, bool>(iterator(tmp, this), true);
     };
template<typename Key, typename Val, typename Hasher, typename Equals> percent_type wlp::ChainHashMap< Key, Val, Hasher, Equals >::max_load () const inline
Returns
the maximum load before before rehash
Definition at line 371 of file ChainMap.h.
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::max_load().
{
             return m_max_load;
         }
template<typename Key, typename Val, typename Hasher, typename Equals> map_type& wlp::ChainHashMap< Key, Val, Hasher, Equals >::operator= (const map_type &) delete
Disable copy assignment.
Returns
reference to this map
template<typename Key , typename Val , typename Hasher , typename Equals > ChainHashMap< Key, Val, Hasher, Equals > & wlp::ChainHashMap< Key, Val, Hasher, Equals >::operator= (map_type && map)
Assignment operator performs a deep copy of the contents of the assigned map. Therefore, one should use pass by reference or pointer unless assignment is absolutely necessary.
Parameters
map the map to copy
Returns
a reference to this map
Definition at line 839 of file ChainMap.h.
References wlp::move().
{
         clear();
         free<node_type *>(m_buckets);
         m_num_elements = move(map.m_num_elements);
         m_capacity = move(map.m_capacity);
         m_max_load = move(map.m_max_load);
         m_buckets = move(map.m_buckets);
         map.m_num_elements = 0;
         map.m_capacity = 0;
         map.m_buckets = nullptr;
         return *this;
     }
template<typename Key, typename Val, typename Hasher, typename Equals> template<typename K > val_type& wlp::ChainHashMap< Key, Val, Hasher, Equals >::operator[] (K && key)
Access an element in the hash map by the given key. If the key does not map to any value in the map, then a new value is created and inserted using the default constructor.
Parameters
key the key whose value to access
Returns
a reference to the mapped value
template<typename Key, typename Val, typename Hasher, typename Equals> template<typename K > ChainHashMap<Key, Val, Hasher, Equals>::val_type& wlp::ChainHashMap< Key, Val, Hasher, Equals >::operator[] (K && key)
Definition at line 754 of file ChainMap.h.
References wlp::ChainHashMapNode< Key, Val >::m_key, wlp::ChainHashMapNode< Key, Val >::m_val, and wlp::ChainHashMapNode< Key, Val >::next.
{
         ensure_capacity();
         size_type i = hash(key);
         node_type *first = m_buckets[i];
         node_type *cur = first;
         if (!cur) {
             node_type *ele = malloc<node_type>();
             ++m_num_elements;
             ele->m_key = forward<K>(key);
             ele->m_val = val_type();
             ele->next = nullptr;
             m_buckets[i] = ele;
             return ele->m_val;
         }
         while (cur && !m_equal(key, cur->m_key)) {
             cur = cur->next;
         }
         if (cur) {
             return cur->m_val;
         }
         cur = malloc<node_type>();
         ++m_num_elements;
         cur->m_key = forward<K>(key);
         cur->m_val = val_type();
         cur->next = nullptr;
         cur->next = first;
         m_buckets[i] = cur;
         return cur->m_val;
     }
template<typename Key, typename Val, typename Hasher, typename Equals> size_type wlp::ChainHashMap< Key, Val, Hasher, Equals >::size () const inline
Returns
the current number of elements that have been inserted into the map
Definition at line 357 of file ChainMap.h.
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::size().
{
             return m_num_elements;
         }
Friends And Related Function Documentation
template<typename Key, typename Val, typename Hasher, typename Equals> friend struct ChainHashMapIterator< Key, Val, const Val &, const Val *, Hasher, Equals > friend
Definition at line 218 of file ChainMap.h.
template<typename Key, typename Val, typename Hasher, typename Equals> friend struct ChainHashMapIterator< Key, Val, Val &, Val *, Hasher, Equals > friend
Definition at line 217 of file ChainMap.h.
Field Documentation
template<typename Key, typename Val, typename Hasher, typename Equals> node_type** wlp::ChainHashMap< Key, Val, Hasher, Equals >::m_buckets private
Hasher map backing array.
Definition at line 235 of file ChainMap.h.
Referenced by wlp::ChainHashMap< Key, Key, Hash, Equal >::begin().
template<typename Key, typename Val, typename Hasher, typename Equals> size_type wlp::ChainHashMap< Key, Val, Hasher, Equals >::m_capacity private
The size of the backing array. Note that the number of elements in the chained hash map may very well exceed the size fo the backing array if the load factor is greater than 100.
Definition at line 248 of file ChainMap.h.
Referenced by wlp::ChainHashMap< Key, Key, Hash, Equal >::begin(), wlp::ChainHashMap< Key, Key, Hash, Equal >::capacity(), and wlp::ChainHashMap< Key, Key, Hash, Equal >::hash().
template<typename Key, typename Val, typename Hasher, typename Equals> Equals wlp::ChainHashMap< Key, Val, Hasher, Equals >::m_equal private
Class key equality function. Used to test equality of element keys.
Definition at line 230 of file ChainMap.h.
template<typename Key, typename Val, typename Hasher, typename Equals> Hasher wlp::ChainHashMap< Key, Val, Hasher, Equals >::m_hash private
Class hash function instance. Used to hash element keys.
Definition at line 225 of file ChainMap.h.
Referenced by wlp::ChainHashMap< Key, Key, Hash, Equal >::bucket_index(), and wlp::ChainHashMap< Key, Key, Hash, Equal >::hash().
template<typename Key, typename Val, typename Hasher, typename Equals> percent_type wlp::ChainHashMap< Key, Val, Hasher, Equals >::m_max_load private
The maximum load factor as an integer percent before the map performs a rehash. This number may exceed 100.
Definition at line 254 of file ChainMap.h.
Referenced by wlp::ChainHashMap< Key, Key, Hash, Equal >::max_load().
template<typename Key, typename Val, typename Hasher, typename Equals> size_type wlp::ChainHashMap< Key, Val, Hasher, Equals >::m_num_elements private
The number of elements currently in the map.
Definition at line 241 of file ChainMap.h.
Referenced by wlp::ChainHashMap< Key, Key, Hash, Equal >::begin(), wlp::ChainHashMap< Key, Key, Hash, Equal >::empty(), and wlp::ChainHashMap< Key, Key, Hash, Equal >::size().
The documentation for this class was generated from the following file:
stl/ChainMap.h