Waterloop Wlib: wlp::SharedCount< Ptr > Class Template Reference
wlp::SharedCount< Ptr > Class Template Reference
#include <SharedPtr.h>
Public Types
typedef Ptr pointer
typedef ReferenceCount< Ptr >::ptr_use_count ptr_use_count
Public Member Functions
constexpr SharedCount ()
template<typename PtrType >
SharedCount (PtrType ptr)
template<typename U >
SharedCount (UniquePtr< U > &&up)
SharedCount (const WeakCount< Ptr > &)
~SharedCount ()
SharedCount (const SharedCount< Ptr > &sc)
SharedCount< Ptr > & operator= (const SharedCount< Ptr > &sc)
void swap (SharedCount< Ptr > &sc)
ptr_use_count use_count () const
bool unique () const
bool less (const SharedCount< Ptr > &) const
bool less (const WeakCount< Ptr > &) const
Private Attributes
ReferenceCount< Ptr > * m_pi
Friends
class WeakCount< Ptr >
template<typename PtrType >
bool operator== (const SharedCount< PtrType > &sc1, const SharedCount< PtrType > &sc2)
Detailed Description
template<typename Ptr>
class wlp::SharedCount< Ptr >
This class is responsible for managing a reference count object shared among all classes which refer to the same underlying pointer, for shared pointers.
Template Parameters
Ptr the type of the managed pointer
Definition at line 186 of file SharedPtr.h.
Member Typedef Documentation
pointer
template<typename Ptr> typedef Ptr wlp::SharedCount< Ptr >::pointer
Definition at line 201 of file SharedPtr.h.
ptr_use_count
template<typename Ptr> typedef ReferenceCount<Ptr>::ptr_use_count wlp::SharedCount< Ptr >::ptr_use_count
Definition at line 202 of file SharedPtr.h.
Constructor & Destructor Documentation
SharedCount() [1/5]
template<typename Ptr> constexpr wlp::SharedCount< Ptr >::SharedCount () inline
Definition at line 210 of file SharedPtr.h.
                 : m_pi(nullptr) {}
SharedCount() [2/5]
template<typename Ptr> template<typename PtrType > wlp::SharedCount< Ptr >::SharedCount (PtrType ptr) inline explicit
Constructor called upon first creation of a strong reference to a pointer. The reference count object is created here.
The caller must relinquish control of the pointer to the class, or else undefined behaviour may result.
Template Parameters
PtrType the supplied pointer type
Parameters
ptr the new underlying pointer
Definition at line 224 of file SharedPtr.h.
                 : m_pi(nullptr) {
             m_pi = malloc<ReferenceCount<PtrType>>(ptr);
         }
SharedCount() [3/5]
template<typename Ptr> template<typename U > wlp::SharedCount< Ptr >::SharedCount (UniquePtr< U > && up) inline
Constructor from a unique pointer. This class assumes ownership of the pointer managed from the unique pointer such that the latter no longer controls any pointers.
Template Parameters
U unique pointer type
Parameters
up the unique pointer to take
Definition at line 238 of file SharedPtr.h.
                 : m_pi(nullptr) {
             m_pi = malloc<ReferenceCount<U *>>(up.get());
             up.release();
         }
SharedCount() [4/5]
template<typename Ptr> wlp::SharedCount< Ptr >::SharedCount (const WeakCount< Ptr > & wc) inline explicit
Creation of a shared count from a weak count, means that the weak pointer is locking its reference to a shared pointer.
Template Parameters
Ptr pointer type
Parameters
wc weak count to copy
Definition at line 450 of file SharedPtr.h.
             : m_pi(wc.m_pi) {
         if (m_pi) { m_pi->add_locked_reference(); }
         // Else bad weak pointer
     }
~SharedCount()
template<typename Ptr> wlp::SharedCount< Ptr >::~SharedCount () inline
Upon destruction, the shared pointer managing this object has been destroyed, thus decrement the number of strong references. The
release
function handles freeing resources.
Definition at line 252 of file SharedPtr.h.
{
             if (m_pi) { m_pi->release(); }
         }
SharedCount() [5/5]
template<typename Ptr> wlp::SharedCount< Ptr >::SharedCount (const SharedCount< Ptr > & sc) inline
When copy-constructing this object, another reference to the underlying pointer is created, thus the reference count object has its use count incremented.
Parameters
sc shared count to copy
Definition at line 263 of file SharedPtr.h.
                 : m_pi(sc.m_pi) {
             if (m_pi) { m_pi->add_copied_reference(); }
         }
Member Function Documentation
less() [1/2]
template<typename Ptr> bool wlp::SharedCount< Ptr >::less (const SharedCount< Ptr > & sc) const inline
Definition at line 428 of file SharedPtr.h.
Referenced by wlp::SharedPtr< T >::owner_before().
{
         return m_pi < sc.m_pi;
     }
less() [2/2]
template<typename Ptr> bool wlp::SharedCount< Ptr >::less (const WeakCount< Ptr > & wc) const inline
Definition at line 423 of file SharedPtr.h.
{
         return m_pi < wc.m_pi;
     }
operator=()
template<typename Ptr> SharedCount<Ptr>& wlp::SharedCount< Ptr >::operator= (const SharedCount< Ptr > & sc) inline
When copy-assigning this object, another reference to the underlying pointer is created, thus the reference count object has its use count incremented. If this shared count refers to a different existing pointer, that pointer has one strong reference released.
Parameters
sc shared count to copy
Returns
reference to this shared count
Definition at line 278 of file SharedPtr.h.
{
             ReferenceCount<Ptr> *tmp = sc.m_pi;
             if (tmp != m_pi) {
                 if (tmp) { tmp->add_copied_reference(); }
                 if (m_pi) { m_pi->release(); }
                 m_pi = tmp;
             }
             return *this;
         }
swap()
template<typename Ptr> void wlp::SharedCount< Ptr >::swap (SharedCount< Ptr > & sc) inline
Definition at line 288 of file SharedPtr.h.
Referenced by wlp::SharedPtr< T >::SharedPtr(), and wlp::SharedPtr< T >::swap().
{
             wlp::swap(m_pi, sc.m_pi);
         }
unique()
template<typename Ptr> bool wlp::SharedCount< Ptr >::unique () const inline
Returns
whether there is exactly one shared pointer which claims ownership to the underlying pointer.
Definition at line 304 of file SharedPtr.h.
Referenced by wlp::SharedPtr< T >::unique().
{
             return use_count() == 1;
         }
use_count()
template<typename Ptr> ptr_use_count wlp::SharedCount< Ptr >::use_count () const inline
Returns
the current number of strong references to the underlying pointer, or zero if the reference is null.
Definition at line 296 of file SharedPtr.h.
Referenced by wlp::SharedPtr< T >::use_count().
{
             return m_pi ? m_pi->use_count() : static_cast<ptr_use_count>(0);
         }
Friends And Related Function Documentation
operator==
template<typename Ptr> template<typename PtrType > bool operator== (const SharedCount< PtrType > & sc1, const SharedCount< PtrType > & sc2) friend
Definition at line 313 of file SharedPtr.h.
{
             return sc1.m_pi == sc2.m_pi;
         }
WeakCount< Ptr >
template<typename Ptr> friend class WeakCount< Ptr > friend
Definition at line 205 of file SharedPtr.h.
Field Documentation
m_pi
template<typename Ptr> ReferenceCount<Ptr>* wlp::SharedCount< Ptr >::m_pi private
Definition at line 207 of file SharedPtr.h.
Referenced by wlp::SharedCount< T *>::less(), wlp::WeakCount< T *>::less(), wlp::SharedCount< T *>::operator=(), wlp::WeakCount< T *>::operator=(), and wlp::SharedCount< T *>::swap().
The documentation for this class was generated from the following file:
stl/SharedPtr.h