Waterloop Wlib: memory/New.cpp File Reference
New.cpp File Reference
#include <stdlib.h>
#include "New.h"
Functions
void * operator new (decltype(sizeof(0)) n) noexcept(false)
void * operator new (decltype(sizeof(0)), void *ptr) noexcept
void operator delete (void *ptr) throw ()
void * operator new[] (decltype(sizeof(0)) n) noexcept(false)
void operator delete[] (void *ptr) throw ()
Function Documentation
void operator delete (void * ptr) throw ()
Definition at line 30 of file New.cpp.
References free().
{
     free(ptr);
 }
void operator delete[] (void * ptr) throw ()
Definition at line 38 of file New.cpp.
References free().
{
     free(ptr);
 }
void* operator new (decltype(sizeof(0)) n) noexcept
Definition at line 22 of file New.cpp.
References malloc().
{
     return malloc(n);
 }
void* operator new (decltype(sizeof(0)) , void * ptr) noexcept
Definition at line 26 of file New.cpp.
{
     return ptr;
 }
void* operator new[] (decltype(sizeof(0)) n) noexcept
Definition at line 34 of file New.cpp.
References malloc().
{
     return malloc(n);
 }