Waterloop Wlib: wlp::tuple< Types > Class Template Reference
wlp::tuple< Types > Class Template Reference
#include <Tuple.h>
Public Types
using base_type = TupleImpl< typename MakeIndexSequence< sizeof...(Types)>::type, Types...>
Public Member Functions
template<typename... OtherTypes>
tuple< Types...> & operator= (tuple< OtherTypes...> const &tuple)
template<typename... OtherTypes>
tuple< Types...> & operator= (tuple< OtherTypes...> &&tuple)
template<typename A , typename B >
tuple< Types...> & operator= (pair< A, B > const &pair)
template<typename A , typename B >
tuple< Types...> & operator= (pair< A, B > &&pair)
tuple ()
template<typename... OtherTypes, typename = typename enable_if< sizeof...(OtherTypes) == sizeof...(Types) >::type>
tuple (OtherTypes &&...elements)
template<typename... OtherTypes, typename = typename enable_if< sizeof...(OtherTypes) == sizeof...(Types) >::type>
tuple (tuple< OtherTypes...> const &tuple)
template<typename... OtherTypes, typename = typename enable_if< sizeof...(OtherTypes) == sizeof...(Types) >::type>
tuple (tuple< OtherTypes...> &&tuple)
Detailed Description
template<typename... Types>
class wlp::tuple< Types >
Main Tuple class. Inherits from TupleImpl and hides the index parameter.
Template Parameters
Types the tuple types
Definition at line 269 of file Tuple.h.
Member Typedef Documentation
template<typename... Types> using wlp::tuple< Types >::base_type = TupleImpl<typename MakeIndexSequence<sizeof...(Types)>::type, Types...>
Shorthand for the inherited TupleImpl type.
Definition at line 277 of file Tuple.h.
Constructor & Destructor Documentation
template<typename... Types> wlp::tuple< Types >::tuple () inline explicit
Default constructor initializes with empty values.
Definition at line 341 of file Tuple.h.
Referenced by wlp::tuple< Types >::operator=().
                 : base_type(forward<Types>(Types())...) {
         }
template<typename... Types> template<typename... OtherTypes, typename = typename enable_if< sizeof...(OtherTypes) == sizeof...(Types) >::type> wlp::tuple< Types >::tuple (OtherTypes &&... elements) inline explicit
Constructor for a tuple of each its elements. Enabled only if the correct number of element values have been provided.
Template Parameters
OtherTypes types of the element values
Parameters
elements element values pack
Definition at line 356 of file Tuple.h.
                 : base_type(forward<OtherTypes>(elements)...) {
         }
template<typename... Types> template<typename... OtherTypes, typename = typename enable_if< sizeof...(OtherTypes) == sizeof...(Types) >::type> wlp::tuple< Types >::tuple (tuple< OtherTypes...> const & tuple) inline explicit
Copy constructor for tuple defers to inherited copy constructor.
Template Parameters
OtherTypes types of the copied tuple
Parameters
tuple copied tuple
Definition at line 370 of file Tuple.h.
                 : base_type(tuple) {
         }
template<typename... Types> template<typename... OtherTypes, typename = typename enable_if< sizeof...(OtherTypes) == sizeof...(Types) >::type> wlp::tuple< Types >::tuple (tuple< OtherTypes...> && tuple) inline explicit
Move copy constructor for tuple defers to inherited move copy constructor.
Template Parameters
OtherTypes types of the copied tuple
Parameters
tuple copied tuple
Definition at line 384 of file Tuple.h.
                 : base_type(move(tuple)) {
         }
Member Function Documentation
template<typename... Types> template<typename... OtherTypes> tuple<Types...>& wlp::tuple< Types >::operator= (tuple< OtherTypes...> const & tuple) inline
Assignment operator for tuple casts to the inherited type and defers the operation there.
Template Parameters
OtherTypes types of the assigned tuple
Parameters
tuple assigned tuple
Returns
a reference to this tuple
Definition at line 288 of file Tuple.h.
References wlp::tuple< Types >::tuple().
{
             static_cast<base_type &>(*this) = tuple;
             return *this;
         }
template<typename... Types> template<typename... OtherTypes> tuple<Types...>& wlp::tuple< Types >::operator= (tuple< OtherTypes...> && tuple) inline
Move assignment operator.
Template Parameters
OtherTypes types of assigned tuple
Parameters
tuple assigned tuple
Returns
a reference to this tuple
Definition at line 301 of file Tuple.h.
References wlp::move().
{
             static_cast<base_type &>(*this) = move(tuple);
             return *this;
         }
template<typename... Types> template<typename A , typename B > tuple<Types...>& wlp::tuple< Types >::operator= (pair< A, B > const & pair) inline
Assignment operator for a pair. Currently, a pair can be assigned to any tuple with at least two elements, and will assign to the first two of the elements.
Template Parameters
A pair first type
B pair second type
Parameters
pair the pair to assign
Returns
a reference to this tuple
Definition at line 317 of file Tuple.h.
References wlp::pair< First, Second >::m_first, and wlp::pair< First, Second >::m_second.
{
             static_cast<TupleElement<0, TypeAtIndexType<0, Types...>> &>(*this).value = pair.m_first;
             static_cast<TupleElement<1, TypeAtIndexType<1, Types...>> &>(*this).value = pair.m_second;
             return *this;
         }
template<typename... Types> template<typename A , typename B > tuple<Types...>& wlp::tuple< Types >::operator= (pair< A, B > && pair) inline
Pair move assignment operator.
Template Parameters
A pair first type
B pair second type
Parameters
pair the pair to assign
Returns
a reference to this tuple
Definition at line 332 of file Tuple.h.
References wlp::pair< First, Second >::m_first, wlp::pair< First, Second >::m_second, and wlp::move().
{
             static_cast<TupleElement<0, TypeAtIndexType<0, Types...>> &>(*this).value = move(pair.m_first);
             static_cast<TupleElement<1, TypeAtIndexType<1, Types...>> &>(*this).value = move(pair.m_second);
             return *this;
         }
The documentation for this class was generated from the following file:
wlib/stl/Tuple.h