Waterloop Wlib: wlp::ReferenceCount< Ptr > Class Template Reference
wlp::ReferenceCount< Ptr > Class Template Reference
#include <SharedPtr.h>
Public Types
typedef uint16_t ptr_use_count
typedef Ptr pointer
Public Member Functions
ReferenceCount (pointer ptr)
~ReferenceCount ()
void dispose ()
void destroy ()
void add_copied_reference ()
void add_locked_reference ()
void release ()
void add_weak_reference ()
void weak_release ()
ptr_use_count use_count () const
ptr_use_count weak_count () const
template<>
void dispose ()
Private Member Functions
ReferenceCount (const ReferenceCount &)=delete
ReferenceCount & operator= (const ReferenceCount &)=delete
Private Attributes
ptr_use_count m_use_count
ptr_use_count m_weak_count
pointer m_ptr
Detailed Description
template<typename Ptr>
class wlp::ReferenceCount< Ptr >
This class tracks the number of weak references and strong references to an underlying pointer. That is, the number of weak pointers and shared pointers which refer to the managed pointer, respectively.
This class is dynamically allocated by using classes once per managed pointer and is shared between all classes which refer to the managed pointer. The class frees the managed pointer when there are no more strong references to the pointer and destroys itself when there are no references at all.
Template Parameters
Ptr
Definition at line 41 of file SharedPtr.h.
Member Typedef Documentation
pointer
template<typename Ptr> typedef Ptr wlp::ReferenceCount< Ptr >::pointer
Definition at line 44 of file SharedPtr.h.
ptr_use_count
template<typename Ptr> typedef uint16_t wlp::ReferenceCount< Ptr >::ptr_use_count
Definition at line 43 of file SharedPtr.h.
Constructor & Destructor Documentation
ReferenceCount() [1/2]
template<typename Ptr> wlp::ReferenceCount< Ptr >::ReferenceCount (pointer ptr) inline
A reference count is created with a copy of the underlying pointer and with the use count and weak count set to 1. There is always exactly one shared pointer referring to the pointer when this class is constructed for the first time. The choice of 1 for weak count is to avoid underflow.
Parameters
ptr the underlying pointer
Definition at line 74 of file SharedPtr.h.
Referenced by wlp::ReferenceCount< T *>::weak_count().
                 : m_use_count(1),
                   m_weak_count(1),
                   m_ptr(ptr) {}
~ReferenceCount()
template<typename Ptr> wlp::ReferenceCount< Ptr >::~ReferenceCount () inline
Definition at line 79 of file SharedPtr.h.
 {}
ReferenceCount() [2/2]
template<typename Ptr> wlp::ReferenceCount< Ptr >::ReferenceCount (const ReferenceCount< Ptr > &) private delete
Member Function Documentation
add_copied_reference()
template<typename Ptr> void wlp::ReferenceCount< Ptr >::add_copied_reference () inline
A shared pointer has been copied through construction or assignment, thus increment the use count.
Definition at line 100 of file SharedPtr.h.
Referenced by wlp::SharedCount< T *>::operator=(), and wlp::SharedCount< T *>::SharedCount().
{
             ++m_use_count;
         }
add_locked_reference()
template<typename Ptr> void wlp::ReferenceCount< Ptr >::add_locked_reference () inline
A weak pointer is locking its reference to the underlying pointer, but if the actual strong reference count is zero, then the underlying pointer has expired.
Definition at line 109 of file SharedPtr.h.
{
             if (exchange_and_add<ptr_use_count>(&m_use_count, 1) == 0) {
                 m_use_count = 0;
                 // Bad weak pointer
             }
         }
add_weak_reference()
template<typename Ptr> void wlp::ReferenceCount< Ptr >::add_weak_reference () inline
A weak reference has been created to the underlying pointer, that reference must be locked before accessing the pointer, thus increment the weak reference count.
Definition at line 136 of file SharedPtr.h.
Referenced by wlp::WeakCount< T *>::operator=(), and wlp::WeakCount< T *>::WeakCount().
{
             ++m_weak_count;
         }
destroy()
template<typename Ptr> void wlp::ReferenceCount< Ptr >::destroy () inline
Destroy the reference count instance. The instance must be dynamically allocated.
Definition at line 92 of file SharedPtr.h.
Referenced by wlp::ReferenceCount< T *>::release(), and wlp::ReferenceCount< T *>::weak_release().
{
             free(this);
         }
dispose() [1/2]
template<typename Ptr> void wlp::ReferenceCount< Ptr >::dispose () inline
Free the underlying pointer.
Definition at line 84 of file SharedPtr.h.
Referenced by wlp::ReferenceCount< T *>::release().
{
             free(m_ptr);
         }
dispose() [2/2]
template<> void wlp::ReferenceCount< nullptr_t >::dispose () inline
Specialization for null pointers which avoid freeing null pointers upon destruction.
Definition at line 177 of file SharedPtr.h.
 {}
operator=()
template<typename Ptr> ReferenceCount& wlp::ReferenceCount< Ptr >::operator= (const ReferenceCount< Ptr > &) private delete
Referenced by wlp::ReferenceCount< T *>::weak_count().
release()
template<typename Ptr> void wlp::ReferenceCount< Ptr >::release () inline
Method called when a strong reference is releasing ownership of the underlying pointer. If all strong references have been released, then the underlying pointer is freed. If there are no more weak references, then this object is also destroyed.
Definition at line 122 of file SharedPtr.h.
Referenced by wlp::SharedCount< T *>::operator=(), wlp::SharedCount< T *>::SharedCount(), and wlp::SharedCount< T *>::~SharedCount().
{
             if (exchange_and_sub<ptr_use_count>(&m_use_count, 1) == 1) {
                 dispose();
                 if (exchange_and_sub<ptr_use_count>(&m_weak_count, 1) == 1) {
                     destroy();
                 }
             }
         }
use_count()
template<typename Ptr> ptr_use_count wlp::ReferenceCount< Ptr >::use_count () const inline
Returns
the number of active strong references
Definition at line 155 of file SharedPtr.h.
Referenced by wlp::SharedCount< T *>::unique(), wlp::SharedCount< T *>::use_count(), and wlp::WeakCount< T *>::use_count().
{
             return m_use_count;
         }
weak_count()
template<typename Ptr> ptr_use_count wlp::ReferenceCount< Ptr >::weak_count () const inline
Returns
the number of active weak references
Definition at line 162 of file SharedPtr.h.
{
             return m_weak_count;
         }
weak_release()
template<typename Ptr> void wlp::ReferenceCount< Ptr >::weak_release () inline
Method called when a weak reference is releasing its temporary ownership of the underlying pointer. If the weak reference is the last remaining reference which claims ownership of the (now-expired) underlying pointer, then this object is subsequently destroyed.
Definition at line 146 of file SharedPtr.h.
Referenced by wlp::WeakCount< T *>::operator=(), and wlp::WeakCount< T *>::~WeakCount().
{
             if (exchange_and_sub<ptr_use_count>(&m_weak_count, 1) == 1) {
                 destroy();
             }
         }
Field Documentation
m_ptr
template<typename Ptr> pointer wlp::ReferenceCount< Ptr >::m_ptr private
The managed underlying pointer. This class cannot be used to access the pointe directly; it only has a copy to manage its deletion.
Definition at line 62 of file SharedPtr.h.
m_use_count
template<typename Ptr> ptr_use_count wlp::ReferenceCount< Ptr >::m_use_count private
The number of shared pointers which claim ownership of the underlying pointer.
Definition at line 51 of file SharedPtr.h.
Referenced by wlp::ReferenceCount< T *>::add_copied_reference(), and wlp::ReferenceCount< T *>::use_count().
m_weak_count
template<typename Ptr> ptr_use_count wlp::ReferenceCount< Ptr >::m_weak_count private
The number of weak pointers which have a view of the underlying pointer.
Definition at line 56 of file SharedPtr.h.
Referenced by wlp::ReferenceCount< T *>::add_weak_reference(), and wlp::ReferenceCount< T *>::weak_count().
The documentation for this class was generated from the following file:
stl/SharedPtr.h