Waterloop Wlib: wlp::OpenHashSet< Key, Hash, Equal > Class Template Reference
wlp::OpenHashSet< Key, Hash, Equal > Class Template Reference
#include <OpenSet.h>
Public Types
typedef OpenHashSet< Key, Hash, Equal > set_type
typedef OpenHashMap< Key, Key, Hash, Equal > table_type
typedef OpenHashMap< Key, Key, Hash, Equal >::iterator iterator
typedef OpenHashMap< Key, Key, Hash, Equal >::const_iterator const_iterator
typedef table_type::size_type size_type
typedef table_type::percent_type percent_type
typedef table_type::key_type key_type
Public Member Functions
OpenHashSet (size_type n=12, percent_type max_load=75)
OpenHashSet (const set_type &)=delete
OpenHashSet (set_type &&set)
size_type size () const
size_type capacity () const
percent_type max_load () const
bool empty () const
const table_type * get_backing_hash_map () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void clear () noexcept
template<typename K >
Pair< iterator, bool > insert (K &&key)
bool contains (const key_type &key) const
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
iterator erase (const iterator &pos)
bool erase (const key_type &key)
set_type & operator= (const set_type &)=delete
set_type & operator= (set_type &&set)
Private Attributes
table_type m_hash_map
Detailed Description
template<class Key, class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>>
class wlp::OpenHashSet< Key, Hash, Equal >
An open hash set is created using a backing hash map, and all available functions are a subset of the functions of the hash map. The set contains unique elements.
Template Parameters
Key the unique element type
Hash the hash function of the stored elements
Equal test for equality function of the stored elements
Definition at line 33 of file OpenSet.h.
Member Typedef Documentation
const_iterator
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef OpenHashMap<Key, Key, Hash, Equal>::const_iterator wlp::OpenHashSet< Key, Hash, Equal >::const_iterator
Definition at line 38 of file OpenSet.h.
iterator
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef OpenHashMap<Key, Key, Hash, Equal>::iterator wlp::OpenHashSet< Key, Hash, Equal >::iterator
Definition at line 37 of file OpenSet.h.
key_type
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef table_type::key_type wlp::OpenHashSet< Key, Hash, Equal >::key_type
Definition at line 41 of file OpenSet.h.
percent_type
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef table_type::percent_type wlp::OpenHashSet< Key, Hash, Equal >::percent_type
Definition at line 40 of file OpenSet.h.
set_type
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef OpenHashSet<Key, Hash, Equal> wlp::OpenHashSet< Key, Hash, Equal >::set_type
Definition at line 35 of file OpenSet.h.
size_type
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef table_type::size_type wlp::OpenHashSet< Key, Hash, Equal >::size_type
Definition at line 39 of file OpenSet.h.
table_type
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef OpenHashMap<Key, Key, Hash, Equal> wlp::OpenHashSet< Key, Hash, Equal >::table_type
Definition at line 36 of file OpenSet.h.
Constructor & Destructor Documentation
OpenHashSet() [1/3]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> wlp::OpenHashSet< Key, Hash, Equal >::OpenHashSet (size_type n = 12, percent_type max_load = 75) inline explicit
Constructor creates a new hash map, and instantiates the backing hash map.
See also
OpenHashMap
Parameters
n the initial size of the backing array
max_load the maximum load factor before rehash
Definition at line 58 of file OpenSet.h.
                                             :
                 m_hash_map(n, max_load) {
         }
OpenHashSet() [2/3]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> wlp::OpenHashSet< Key, Hash, Equal >::OpenHashSet (const set_type &) delete
Disable copy constructor.
OpenHashSet() [3/3]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> wlp::OpenHashSet< Key, Hash, Equal >::OpenHashSet (set_type && set) inline
Move constructor.
Parameters
set hash set to move
Definition at line 74 of file OpenSet.h.
                 : m_hash_map(move(set.m_hash_map)) {
         }
Member Function Documentation
begin() [1/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> iterator wlp::OpenHashSet< Key, Hash, Equal >::begin () inline
An iterator instance to the beginning of the hash set. The iterator order of the set is not guaranteed to be in any particular order.
Returns
iterator to the first element, or
end
if the set is empty
Definition at line 120 of file OpenSet.h.
{
             return m_hash_map.begin();
         }
begin() [2/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> const_iterator wlp::OpenHashSet< Key, Hash, Equal >::begin () const inline
Returns
a constant iterator to the first element
Definition at line 137 of file OpenSet.h.
{
             return m_hash_map.begin();
         }
capacity()
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> size_type wlp::OpenHashSet< Key, Hash, Equal >::capacity () const inline
Returns
the size of the backing array
Definition at line 88 of file OpenSet.h.
{
             return m_hash_map.capacity();
         }
clear()
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> void wlp::OpenHashSet< Key, Hash, Equal >::clear () inline noexcept
Empty the elements in the set, such that its size is now zero.
Definition at line 152 of file OpenSet.h.
{
             m_hash_map.clear();
         }
contains()
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> bool wlp::OpenHashSet< Key, Hash, Equal >::contains (const key_type & key) const inline
Check if an element is in the set.
Parameters
key element whose existence to check
Returns
true if the element is contained in the set
Definition at line 175 of file OpenSet.h.
{
             return m_hash_map.contains(key);
         }
empty()
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> bool wlp::OpenHashSet< Key, Hash, Equal >::empty () const inline
Returns
whether the hash map is empty
Definition at line 102 of file OpenSet.h.
{
             return m_hash_map.empty();
         }
end() [1/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> iterator wlp::OpenHashSet< Key, Hash, Equal >::end () inline
A pass-the-end iterator instance. This iterator means that an iterator has read past the end of the set and has become invalid.
Returns
a pass-the-end iterator
Definition at line 130 of file OpenSet.h.
{
             return m_hash_map.end();
         }
end() [2/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> const_iterator wlp::OpenHashSet< Key, Hash, Equal >::end () const inline
Returns
a constant pass-the-end iterator
Definition at line 144 of file OpenSet.h.
{
             return m_hash_map.end();
         }
erase() [1/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> iterator wlp::OpenHashSet< Key, Hash, Equal >::erase (const iterator & pos) inline
Erase the element in the set pointed to by the iterator.
Parameters
pos iterator whose element to erase
Returns
iterator to the next element in the set
Definition at line 206 of file OpenSet.h.
{
             return m_hash_map.erase(pos);
         }
erase() [2/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> bool wlp::OpenHashSet< Key, Hash, Equal >::erase (const key_type & key) inline
Remove an element from the set.
Parameters
key the element to remove
Returns
true if removal occured
Definition at line 216 of file OpenSet.h.
References wlp::OpenHashSet< Key, Hash, Equal >::operator=().
{
             return m_hash_map.erase(key);
         }
find() [1/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> iterator wlp::OpenHashSet< Key, Hash, Equal >::find (const key_type & key) inline
Obtain an iterator to an element in the set.
Parameters
key the element to find
Returns
iterator to the element or pass-the-end if the element is not in the set
Definition at line 185 of file OpenSet.h.
{
             return m_hash_map.find(key);
         }
find() [2/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> const_iterator wlp::OpenHashSet< Key, Hash, Equal >::find (const key_type & key) const inline
Obtain a const iterator to an element in the set
Parameters
key the element to find
Returns
const iterator to the element or pass-the-end if the element is not in the set
Definition at line 195 of file OpenSet.h.
{
             return m_hash_map.find(key);
         }
get_backing_hash_map()
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> const table_type* wlp::OpenHashSet< Key, Hash, Equal >::get_backing_hash_map () const inline
Returns
a pointer to the backing hash map
Definition at line 109 of file OpenSet.h.
References wlp::OpenHashSet< Key, Hash, Equal >::m_hash_map.
{
             return &m_hash_map;
         }
insert()
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> template<typename K > Pair<iterator, bool> wlp::OpenHashSet< Key, Hash, Equal >::insert (K && key) inline
Insert an element into the set. This function returns a pair consistent of the iterator to the element that was inserted or to the element that prevented insertion. The second boolean value indicates whether insertion took place.
Parameters
key the element to insert
Returns
a pair of an iterator and boolean
Definition at line 166 of file OpenSet.h.
{
             return m_hash_map.insert(forward<K>(key), forward<K>(key));
         };
max_load()
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> percent_type wlp::OpenHashSet< Key, Hash, Equal >::max_load () const inline
Returns
the maximum load factor
Definition at line 95 of file OpenSet.h.
{
             return m_hash_map.max_load();
         }
operator=() [1/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> set_type& wlp::OpenHashSet< Key, Hash, Equal >::operator= (const set_type &) delete
Disable copy assignment.
Returns
reference to this set
Referenced by wlp::OpenHashSet< Key, Hash, Equal >::erase().
operator=() [2/2]
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> set_type& wlp::OpenHashSet< Key, Hash, Equal >::operator= (set_type && set) inline
Move assignment operator.
Parameters
set hash set to move
Returns
reference to this set
Definition at line 233 of file OpenSet.h.
References wlp::move().
{
             m_hash_map = move(set.m_hash_map);
             return *this;
         }
size()
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> size_type wlp::OpenHashSet< Key, Hash, Equal >::size () const inline
Returns
the current number of elements in the set
Definition at line 81 of file OpenSet.h.
{
             return m_hash_map.size();
         }
Field Documentation
m_hash_map
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> table_type wlp::OpenHashSet< Key, Hash, Equal >::m_hash_map private
The backing hash map.
Definition at line 47 of file OpenSet.h.
Referenced by wlp::OpenHashSet< Key, Hash, Equal >::get_backing_hash_map().
The documentation for this class was generated from the following file:
stl/OpenSet.h