Waterloop Wlib: wlp::__packet_maker Struct Reference
wlp::__packet_maker Struct Reference
#include <PacketConstructor.h>
Static Public Member Functions
static packet64 build (const float data[3], const packet_type &type, const packet_name &name)
Detailed Description
Definition at line 23 of file PacketConstructor.h.
Member Function Documentation
packet64 __packet_maker::build (const float data[3], const packet_type & type, const packet_name & name) static
Definition at line 53 of file PacketConstructor.cpp.
References __encode_float18(), __join_data(), __set_bulk_data(), __set_packet_name(), and __set_packet_type().
Referenced by wlp::make_packet64().
{
     packet64 packet;
     // type and name are less than or equal to a byte
     // so byte order does not matter
     __set_packet_type(packet, type);
     __set_packet_name(packet, name);
     __set_bulk_data(packet, __join_data(
             __encode_float18(data[0]),
             __encode_float18(data[1]),
             __encode_float18(data[2])
     ));
     return packet;
 }
The documentation for this struct was generated from the following files:
comm/PacketConstructor.h
comm/PacketConstructor.cpp