Waterloop Wlib: memory/Memory.cpp File Reference
Memory.cpp File Reference
Implementation of Memory functions.
#include <string.h>
#include "Memory.h"
#include "StaticAllocatorPool.h"
#include "DynamicAllocatorPool.h"
#include "../Wlib.h"
#include "../utility/Math.h"
Data Structures
class RestrictSize
struct insert< powStart, from, to >
struct insert< powStart, from, from >
Functions
void memory_init ()
void memory_destroy ()
static __Allocator * find_allocator (size32_type size)
static bool insert_allocator (__Allocator *new_allocator)
static void * set_block_allocator (void *block, __Allocator *allocator)
template<typename T >
T nextHigher (T k)
__Allocator * memory_get_allocator (size32_type size, bool anObject)
void * __memory_alloc (size32_type size, bool anObject)
static __Allocator * get_block_allocator (void *block)
static void * get_block_ptr (void *block)
void __memory_free (void *ptr)
size32_type getTotalMemoryUsed ()
wlp::size32_type getTotalMemoryFree ()
size32_type getTotalMemoryAvailable ()
bool isSizeAvailable (size32_type blockSize)
bool isSizeMemAvailable (size32_type blockSize)
uint16_t getNumBlocksAvailable (size32_type blockSize)
uint16_t getNumBlocks ()
uint16_t getMaxAllocations ()
size_type getSmallestBlockSize ()
size32_type getFixedMemorySize (void *ptr)
Variables
static constexpr uint8_t OBJECT_INFO_BUFFER = 2
static constexpr size_type REQUIRED_EXTRA_BUFFER = sizeof(__Allocator *)
static __Allocator * __allocators [MAX_ALLOCATORS]
Detailed Description
Implementation of Memory functions.
Author
Deep Dhillon
Date
November 19, 2017
Bug:
No known bugs
Definition in file Memory.cpp.
Function Documentation
void* __memory_alloc (size32_type size, bool anObject)
Allocates a memory block of the requested size. The blocks are created from the fixed block allocators
Parameters
size the client's requested size of the block
anObject specify if the memory will be used object(s) or fundamental types
Returns
a pointer to the memory block
Definition at line 278 of file Memory.cpp.
References __allocators, __memory_alloc(), wlp::__Allocator::allocate(), wlp::__Allocator::getBlockSize(), memory_get_allocator(), and set_block_allocator().
Referenced by __memory_alloc(), and malloc().
{
     // Allocate a raw memory block
     __Allocator *allocator = memory_get_allocator(size, anObject);
     // if not enough sizes available
     if (allocator == nullptr) {
         return nullptr;
     }
     void *blockMemoryPtr = allocator->allocate();
     // if not enough quantity of that particular size available
     if (blockMemoryPtr == nullptr) {
         // check if higher sizes have some blocks available and
         // give a block from them if available
         size32_type currBlockSize = allocator->getBlockSize();
         if (currBlockSize < __allocators[MAX_ALLOCATORS - 1]->getBlockSize()) {
             return __memory_alloc(currBlockSize + 1, anObject);
         }
         return nullptr;
     }
     // Set the block Allocator* within the raw memory block region
     void *clientsMemoryPtr = set_block_allocator(blockMemoryPtr, allocator);
     return clientsMemoryPtr;
 }
void __memory_free (void * ptr)
Frees a memory block previously allocated with
__memory_alloc
. The blocks are returned to the fixed block allocator that originally created it
Parameters
ptr a pointer to a block created with __memory_alloc
Definition at line 343 of file Memory.cpp.
References wlp::__Allocator::deallocate(), get_block_allocator(), and get_block_ptr().
Referenced by free().
{
     if (ptr == nullptr) {
         return;
     }
     // Extract the original allocator instance from the caller's block pointer
     __Allocator *allocator = get_block_allocator(ptr);
     // Convert the client pointer into the original raw block pointer
     void *blockPtr = get_block_ptr(ptr);
     // Deallocate the block
     allocator->deallocate(blockPtr);
 }
static __Allocator* find_allocator (size32_type size) inline static
Return an allocator instance matching the size provided
Parameters
size allocator blocks size
Returns
Allocator instance or nullptr if no allocator exists
Definition at line 149 of file Memory.cpp.
References __allocators.
Referenced by memory_get_allocator().
{
     for (auto &allocator : __allocators) {
         if (allocator == nullptr) {
             break;
         }
 #if defined(DYNAMIC_POOL) || defined(STATIC_POOL)
         if (allocator->getBlockSize() >= size) {
             return allocator;
         }
 #else
         if (allocator->getBlockSize() == size)
             return allocator;
 #endif
     }
     return nullptr;
 }
static __Allocator* get_block_allocator (void * block) inline static
Gets the size of the memory block stored within the block
Parameters
block a pointer to the client's memory block
Returns
The original allocator instance stored in the memory block
Definition at line 312 of file Memory.cpp.
Referenced by __memory_free(), and getFixedMemorySize().
{
     // Cast the client memory to a Allocator pointer
     auto **pAllocatorInBlock = static_cast<__Allocator **>(block);
     // Back up one Allocator* position to get the stored allocator instance
     pAllocatorInBlock--;
     // Return the allocator instance stored within the memory block
     return *pAllocatorInBlock;
 }
static void* get_block_ptr (void * block) inline static
The raw memory block pointer given a client's memory pointer
Parameters
block a pointer to the client's memory block
Returns
A pointer to the original raw memory block
Definition at line 329 of file Memory.cpp.
Referenced by __memory_free().
{
     // Cast the client memory to a Allocator* pointer
     auto **pAllocatorInBlock = static_cast<__Allocator **>(block);
     // Back up one Allocator* position and return the original raw memory block pointer
     return --pAllocatorInBlock;
 }
size32_type getFixedMemorySize (void * ptr)
Returns the size of fixed sized block that was provided for ptr
Parameters
ptr memory address for which memory block is being searched
Returns
the size of fixed size block
Definition at line 433 of file Memory.cpp.
References get_block_allocator(), and wlp::__Allocator::getBlockSize().
Referenced by realloc().
{
     if (ptr == nullptr)
         return 0;
     __Allocator *allocator = get_block_allocator(ptr);
     return allocator->getBlockSize();
 }
uint16_t getMaxAllocations ()
Returns the number Allocators (sizes) there are available in total
Returns
the number of allocators (sizes)
Definition at line 422 of file Memory.cpp.
{
     return MAX_ALLOCATORS;
 }
uint16_t getNumBlocks ()
Returns the number of blocks per Allocator if a pool is used
Returns
the number of blocks per Allocator
Definition at line 418 of file Memory.cpp.
{
     return NUM_BLOCKS;
 }
uint16_t getNumBlocksAvailable (wlp::size32_type blockSize)
Returns the total number of blocks that are available for blockSize. if blockSize does not exist then number will be 0
Parameters
blockSize blockSize size of the block being queried
Returns
the number blocks available for blockSize
Definition at line 404 of file Memory.cpp.
References __allocators.
{
     uint16_t numBlockAvail = 0;
     for (auto &allocator : __allocators) {
         if (allocator->getBlockSize() == blockSize) {
             uint32_t totalMemAvail = allocator->getTotalBlocks() * allocator->getBlockSize();
             uint32_t totalMemUsed = allocator->getNumAllocations() * allocator->getBlockSize();
             numBlockAvail += (totalMemAvail - totalMemUsed) / blockSize;
         }
     }
     return numBlockAvail;
 }
size_type getSmallestBlockSize ()
Returns the smallest block of memory that is given
Returns
the smallest block of memory
Definition at line 426 of file Memory.cpp.
References wlp::pow_const(), and REQUIRED_EXTRA_BUFFER.
Referenced by realloc().
{
     return static_cast<size_type>(pow_const(
             static_cast<size_type>(2),
             static_cast<size_type>(log2_const<size_type>(REQUIRED_EXTRA_BUFFER) + 1))
     );
 }
size32_type getTotalMemoryAvailable ()
Returns the total memory available to use (in bytes). If no pool is being used, this number can grow as more memory is borrowed otherwise this is the constant number
Returns
the total memory available
Definition at line 373 of file Memory.cpp.
References __allocators.
Referenced by getTotalMemoryFree().
{
     size32_type totalMemory = 0;
     for (auto &allocator : __allocators) {
         totalMemory += allocator->getTotalBlocks() * allocator->getBlockSize();
     }
     return totalMemory;
 }
wlp::size32_type getTotalMemoryFree ()
Returns the total memory that is free for use(in bytes)
Returns
the total memory usage
Definition at line 368 of file Memory.cpp.
References getTotalMemoryAvailable(), and getTotalMemoryUsed().
{
     return getTotalMemoryAvailable() - getTotalMemoryUsed();
 }
size32_type getTotalMemoryUsed ()
Returns the total memory being used by the program (in bytes)
Returns
the total memory usage
Definition at line 358 of file Memory.cpp.
References __allocators.
Referenced by getTotalMemoryFree().
{
     size32_type totalMemory = 0;
     for (auto &allocator : __allocators) {
         totalMemory += allocator->getNumAllocations() * allocator->getBlockSize();
     }
     return totalMemory;
 }
static bool insert_allocator (__Allocator * new_allocator) inline static
Insert an Allocator instance into the array
Parameters
new_allocator an Allocator instance
Returns
true or false based on if insertion is successful
Definition at line 174 of file Memory.cpp.
References __allocators.
Referenced by memory_get_allocator().
{
     for (auto &allocator : __allocators) {
         if (allocator == nullptr) {
             allocator = new_allocator;
             return true;
         }
     }
     return false;
 }
bool isSizeAvailable (wlp::size32_type blockSize)
Returns if this blockSize is available as a size that can be borrowed. If no pool is being used, this size will be created even if it does not exist but if a pool is used, this size's availability is fixed.
Precondition
note if this size does not exist in a pool a higher size can be provided
Parameters
blockSize size of the block being queried
Returns
true or false based on if the block exists
Definition at line 383 of file Memory.cpp.
References __allocators.
{
     for (auto &allocator : __allocators) {
         if (allocator->getBlockSize() == blockSize) {
             return true;
         }
     }
     return false;
 }
bool isSizeMemAvailable (wlp::size32_type blockSize)
Returns if this blockSize is available as a size that can be borrowed but it also has some blocks left that the user can borrow. Rest it functions the same as
isSizeAvailable()
Parameters
blockSize size of the block being queried
Returns
true or false based on if the block exists and has some blocks left
Definition at line 393 of file Memory.cpp.
References __allocators.
{
     for (auto &allocator : __allocators) {
         if (allocator->getBlockSize() == blockSize) {
             uint32_t totalMemAvail = allocator->getTotalBlocks() * allocator->getBlockSize();
             uint32_t totalMemUsed = allocator->getNumAllocations() * allocator->getBlockSize();
             return totalMemAvail - totalMemUsed != 0;
         }
     }
     return false;
 }
void memory_destroy ()
Deletes and disposes the allocations done internally. If a pool is used it promises to deallocates any pending allocations even if
free
is not used
Definition at line 133 of file Memory.cpp.
References __allocators.
Referenced by MemoryInitDestroy::~MemoryInitDestroy().
                       {
     for (auto &allocator : __allocators) {
         if (allocator == nullptr) {
             break;
         }
         delete allocator;
         allocator = nullptr;
     }
 }
__Allocator* memory_get_allocator (size32_type size, bool anObject)
Get an Allocator instance based upon the client's requested block size. If there is no such Allocator available, create a new one
Parameters
size client's requested block size
anObject specify if the memory will be used object(s) or fundamental types
Returns
an allocator instance that handles the block size
Definition at line 229 of file Memory.cpp.
References find_allocator(), insert_allocator(), OBJECT_INFO_BUFFER, and REQUIRED_EXTRA_BUFFER.
Referenced by __memory_alloc().
{
     // Based on the size, find the next higher powers of two value.
     // Add REQUIRED_EXTRA_BUFFER to the requested block size to hold the size
     // of an Allocator* within the block memory region. Most blocks are powers of two,
     // however some common allocator block sizes can be explicitly defined
     // to minimize wasted storage. This offers application specific tuning.
     // These restrictions can only imposed if no pool is being used
     size32_type blockSize = size + REQUIRED_EXTRA_BUFFER;
     if (anObject)
         blockSize += OBJECT_INFO_BUFFER;
 #if !defined(DYNAMIC_POOL) && !defined(STATIC_POOL)
     // set custom blocks if pool is not used
     if (blockSize > 256 && blockSize <= 396)
         blockSize = 396;
     else if (blockSize > 512 && blockSize <= 768)
         blockSize = 768;
     else
         blockSize = nextHigher<size_t>(blockSize);
 #endif
     __Allocator *allocator = find_allocator(blockSize);
 #if !defined(DYNAMIC_POOL) && !defined(STATIC_POOL)
     if (allocator == nullptr){
         // Create a new allocator to handle blocks of the size required
         allocator = new __Allocator(blockSize);
         // Insert allocator into array
         if (!insert_allocator(allocator))
             return nullptr;
     }
 #endif
     return allocator;
 }
void memory_init ()
Creates and initializes the memory management. It creates the memory based on configurations set up in
MemoryConfiguration.h
file
Definition at line 127 of file Memory.cpp.
References insert< powStart, from, to >::apply(), and REQUIRED_EXTRA_BUFFER.
Referenced by MemoryInitDestroy::MemoryInitDestroy().
                    {
     // smallest pow of 2 a block can be created
     constexpr auto powStart = log2_const<size_type>(REQUIRED_EXTRA_BUFFER) + 1;
     insert<powStart, 0, MAX_ALLOCATORS - 1>::apply();
 }
template<typename T > T nextHigher (T k)
Returns the next higher powers of two. For instance, pass in 12 and the value returned would be 16
Template Parameters
T is any class
Parameters
k value for which the higher power of two will be returned
Returns
the next higher power of two based on the input k
Definition at line 213 of file Memory.cpp.
References BYTE_SIZE.
                   {
     k--;
     for (size_t i = 1; i < sizeof(T) * BYTE_SIZE; i <<= 1) {
         k |= (k >> i);
     }
     return k + 1;
 }
static void* set_block_allocator (void * block, __Allocator * allocator) inline static
Stored a pointer to the Allocator instance within the block region
Parameters
block a pointer to the raw memory block
allocator allocator to set
Returns
a pointer to the client's area within the block
Definition at line 192 of file Memory.cpp.
Referenced by __memory_alloc().
{
     // Cast the raw block memory to a Allocator pointer
     auto **pAllocatorInBlock = static_cast<__Allocator **>(block);
     // Write the size into the memory block
     *pAllocatorInBlock = allocator;
     // Advance the pointer past the Allocator* block size and return a pointer to
     // the client's memory region
     return ++pAllocatorInBlock;
 }
Variable Documentation
__Allocator* __allocators[MAX_ALLOCATORS] static
Definition at line 52 of file Memory.cpp.
Referenced by __memory_alloc(), insert< powStart, from, to >::apply(), insert< powStart, from, from >::apply(), find_allocator(), getNumBlocksAvailable(), getTotalMemoryAvailable(), getTotalMemoryUsed(), insert_allocator(), isSizeAvailable(), isSizeMemAvailable(), and memory_destroy().
constexpr uint8_t OBJECT_INFO_BUFFER = 2 static
Definition at line 21 of file Memory.cpp.
Referenced by memory_get_allocator().
constexpr size_type REQUIRED_EXTRA_BUFFER = sizeof(__Allocator *) static
Definition at line 22 of file Memory.cpp.
Referenced by getSmallestBlockSize(), memory_get_allocator(), and memory_init().