Waterloop Wlib: wlp::array_list< T > Class Template Reference
wlp::array_list< T > Class Template Reference
#include <ArrayList.h>
Public Types
typedef T val_type
typedef wlp::size_type size_type
typedef array_list< T > list_type
typedef ArrayListIterator< T,
T &, T * > iterator
typedef ArrayListIterator< T,
const T &, const T * > const_iterator
Public Member Functions
array_list (size_type initial_capacity=12)
array_list (const list_type &)=delete
array_list (list_type &&list)
array_list (const val_type *values, size_type length, size_type initial_capacity)
array_list (const val_type *values, size_type length)
~array_list ()
bool empty () const
size_type size () const
size_type capacity () const
void reserve (size_type new_capacity)
void shrink ()
val_type & at (size_type i)
val_type const & at (size_type i) const
val_type & operator[] (size_type i)
val_type const & operator[] (size_type i) const
val_type & front ()
const val_type & front () const
val_type & back ()
const val_type & back () const
val_type * data ()
const val_type * data () const
void clear () noexcept
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
template<typename V >
iterator insert (size_type i, V &&val)
template<typename V >
iterator insert (const iterator &it, V &&val)
iterator erase (size_type i)
iterator erase (const iterator &it)
template<typename V >
void push_back (V &&val)
template<typename V >
void push_front (V &&val)
void pop_back ()
void pop_front ()
size_type index_of (const val_type &val) const
iterator find (const val_type &val)
const_iterator find (const val_type &val) const
list_type & operator= (const list_type &)=delete
list_type & operator= (list_type &&list)
Private Member Functions
void init_array (size_type initial_size)
void normalize (size_type &i) const
void ensure_capacity ()
void shift_right (size_type i)
void shift_left (size_type i)
Private Attributes
val_type * m_data
size_type m_size
size_type m_capacity
Friends
class ArrayListIterator< T, T &, T * >
class ArrayListIterator< T, const T &, const T * >
Detailed Description
template<typename T>
class wlp::array_list< T >
List implementation using an array. This implementation will resize if attempting to insert into a full array.
Template Parameters
T value type
Definition at line 25 of file ArrayList.h.
Member Typedef Documentation
template<typename T> typedef ArrayListIterator<T, const T &, const T *> wlp::array_list< T >::const_iterator
Definition at line 282 of file ArrayList.h.
template<typename T> typedef ArrayListIterator<T, T &, T *> wlp::array_list< T >::iterator
Definition at line 281 of file ArrayList.h.
template<typename T> typedef array_list<T> wlp::array_list< T >::list_type
Definition at line 280 of file ArrayList.h.
template<typename T> typedef wlp::size_type wlp::array_list< T >::size_type
Definition at line 279 of file ArrayList.h.
template<typename T> typedef T wlp::array_list< T >::val_type
Definition at line 278 of file ArrayList.h.
Constructor & Destructor Documentation
template<typename T> wlp::array_list< T >::array_list (size_type initial_capacity = 12) inline explicit
Constructor with an initial capacity for the backing array.
Parameters
initial_capacity the initial size of the backing array
Definition at line 309 of file ArrayList.h.
References wlp::array_list< T >::init_array().
                 : m_size(0),
                   m_capacity(initial_capacity) {
             init_array(initial_capacity);
         }
template<typename T> wlp::array_list< T >::array_list (const list_type &) delete
Disable copy constructor.
template<typename T> wlp::array_list< T >::array_list (list_type && list) inline
Move constructor.
Parameters
list array list whose resources to transfer
Definition at line 325 of file ArrayList.h.
                 : m_data(move(list.m_data)),
                   m_size(move(list.m_size)),
                   m_capacity(move(list.m_capacity)) {
             list.m_data = nullptr;
             list.m_size = 0;
             list.m_capacity = 0;
         }
template<typename T> wlp::array_list< T >::array_list (const val_type * values, size_type length, size_type initial_capacity) inline
Constructor from array. The caller may specify a desired initial capacity, but if the capacity is shorter than the length, then the capacity will be set to the length of the array.
Parameters
values array of values
length length of the array
Definition at line 343 of file ArrayList.h.
References wlp::array_list< T >::init_array(), wlp::array_list< T >::m_capacity, and wlp::array_list< T >::m_data.
                 : m_size(length),
                   m_capacity(initial_capacity) {
             if (m_capacity < length) {
                 m_capacity = length;
             }
             init_array(m_capacity);
             for (size_type i = 0; i < length; i++) {
                 m_data[i] = values[i];
             }
         }
template<typename T> wlp::array_list< T >::array_list (const val_type * values, size_type length) inline
Constructor from array. This constructor will set the backing array capacity to be equal to the array length.
Parameters
values array of values
length length of the array
Definition at line 363 of file ArrayList.h.
                 : array_list(values, length, length) {
         }
template<typename T> wlp::array_list< T >::~array_list () inline
Free the memory for the array unless it has already been deallocated elsewhere.
Definition at line 371 of file ArrayList.h.
References wlp::array_list< T >::m_data.
                       {
             if (!m_data) {
                 return;
             }
             free<val_type>(m_data);
             m_data = nullptr;
         }
Member Function Documentation
template<typename T> val_type& wlp::array_list< T >::at (size_type i) inline
Get the element at position
i
.
Parameters
i the index of the element to get
Returns
reference to the element
Definition at line 477 of file ArrayList.h.
References INDEX_EXCEPTION, wlp::array_list< T >::m_data, wlp::array_list< T >::m_size, wlp::array_list< T >::normalize(), and THROW.
{
             if (i == 0 && m_size == 0) {
                 THROW(INDEX_EXCEPTION("Accessing empty list"))
             }
             normalize(i);
             return m_data[i];
         }
template<typename T> val_type const& wlp::array_list< T >::at (size_type i) const inline
Get the element at position
i
.
Parameters
i the index of the element to get
Returns
reference to the element
Definition at line 491 of file ArrayList.h.
References INDEX_EXCEPTION, wlp::array_list< T >::m_data, wlp::array_list< T >::m_size, wlp::array_list< T >::normalize(), and THROW.
{
             if (i == 0 && m_size == 0) {
                 THROW(INDEX_EXCEPTION("Accessing empty list"))
             }
             normalize(i);
             return m_data[i];
         }
template<typename T> val_type& wlp::array_list< T >::back () inline
Returns
reference to the last element in the list
Definition at line 540 of file ArrayList.h.
References wlp::array_list< T >::m_data, and wlp::array_list< T >::m_size.
{
             if (m_size == 0) {
                 return m_data[0];
             }
             return m_data[m_size - 1];
         }
template<typename T> const val_type& wlp::array_list< T >::back () const inline
Returns
reference to the last element in the list
Definition at line 550 of file ArrayList.h.
References wlp::array_list< T >::m_data, and wlp::array_list< T >::m_size.
{
             if (m_size == 0) {
                 return m_data[0];
             }
             return m_data[m_size - 1];
         }
template<typename T> iterator wlp::array_list< T >::begin () inline
Returns
iterator to the start of the array
Definition at line 582 of file ArrayList.h.
Referenced by wlp::heap_sort(), wlp::array_heap< T, Cmp >::pop(), and wlp::array_heap< T, Cmp >::push().
{
             return iterator(0, this);
         }
template<typename T> const_iterator wlp::array_list< T >::begin () const inline
Returns
iterator to the start of the array
Definition at line 589 of file ArrayList.h.
{
             return const_iterator(0, this);
         }
template<typename T> size_type wlp::array_list< T >::capacity () const inline
Returns
the size of the backing array
Definition at line 449 of file ArrayList.h.
References wlp::array_list< T >::m_capacity.
Referenced by wlp::array_heap< T, Cmp >::capacity().
{
             return m_capacity;
         }
template<typename T> void wlp::array_list< T >::clear () inline noexcept
Clear the contents of the array list such that it is empty.
Definition at line 575 of file ArrayList.h.
References wlp::array_list< T >::m_size.
{
             m_size = 0;
         }
template<typename T> val_type* wlp::array_list< T >::data () inline
Returns
a pointer to the beginning of the backing array
Definition at line 560 of file ArrayList.h.
References wlp::array_list< T >::m_data.
{
             return m_data;
         }
template<typename T> const val_type* wlp::array_list< T >::data () const inline
Returns
a pointer to the beginning of the backing array
Definition at line 567 of file ArrayList.h.
References wlp::array_list< T >::m_data.
{
             return m_data;
         }
template<typename T> bool wlp::array_list< T >::empty () const inline
Returns
whether the list is empty
Definition at line 435 of file ArrayList.h.
References wlp::array_list< T >::m_size.
Referenced by wlp::array_heap< T, Cmp >::empty().
{
             return m_size == 0;
         }
template<typename T> iterator wlp::array_list< T >::end () inline
Returns
iterator to the end of the array
Definition at line 596 of file ArrayList.h.
References wlp::array_list< T >::m_size.
Referenced by wlp::array_list< T >::erase(), wlp::heap_sort(), wlp::array_list< T >::insert(), wlp::array_heap< T, Cmp >::pop(), and wlp::array_heap< T, Cmp >::push().
{
             return iterator(m_size, this);
         }
template<typename T> const_iterator wlp::array_list< T >::end () const inline
Returns
iterator to the end of the array
Definition at line 603 of file ArrayList.h.
References wlp::array_list< T >::m_size.
{
             return const_iterator(m_size, this);
         }
template<typename T > void wlp::array_list< T >::ensure_capacity () private
Called before any insertion operation, this function will extend the size of the array to twice its capacity and copy the elements of the previous array.
Definition at line 777 of file ArrayList.h.
Referenced by wlp::array_list< T >::insert(), wlp::array_list< T >::push_back(), and wlp::array_list< T >::push_front().
{
         if (m_size < m_capacity) {
             return;
         }
         size_type new_capacity = static_cast<size_type>(2 * m_capacity);
         val_type *new_data = malloc<val_type[]>(new_capacity);
         for (size_type i = 0; i < m_size; i++) {
             new_data[i] = m_data[i];
         }
         free<val_type>(m_data);
         m_data = new_data;
         m_capacity = new_capacity;
     }
template<typename T> iterator wlp::array_list< T >::erase (size_type i) inline
Remove the element at the specified position.
Parameters
i position whose element to erase.
Returns
iterator to the next element in the list
Definition at line 652 of file ArrayList.h.
References wlp::array_list< T >::end(), wlp::array_list< T >::m_size, wlp::array_list< T >::normalize(), and wlp::array_list< T >::shift_left().
{
             if (m_size == 0) {
                 return end();
             }
             normalize(i);
             shift_left(i);
             --m_size;
             return iterator(i, this);
         }
template<typename T> iterator wlp::array_list< T >::erase (const iterator & it) inline
Remove the element at the specified position.
Parameters
it position whose element to erase.
Returns
iterator to the next element in the list
Definition at line 668 of file ArrayList.h.
References wlp::array_list< T >::end(), wlp::ArrayListIterator< T, Ref, Ptr >::m_i, wlp::array_list< T >::m_size, and wlp::array_list< T >::shift_left().
{
             if (m_size == 0 || it.m_i >= m_size) {
                 return end();
             }
             shift_left(it.m_i);
             --m_size;
             return it;
         }
template<typename T> iterator wlp::array_list< T >::find (const val_type & val) inline
Parameters
val the value to find
Returns
iterator to the value, or pass-the-end if not found
Definition at line 738 of file ArrayList.h.
References wlp::array_list< T >::index_of().
{
             return iterator(index_of(val), this);
         }
template<typename T> const_iterator wlp::array_list< T >::find (const val_type & val) const inline
Parameters
val the value to find
Returns
iterator to the value, or pass-the-end if not found
Definition at line 746 of file ArrayList.h.
References wlp::array_list< T >::index_of().
{
             return const_iterator(index_of(val), this);
         }
template<typename T> val_type& wlp::array_list< T >::front () inline
Returns
reference to the first element in the list
Definition at line 526 of file ArrayList.h.
References wlp::array_list< T >::m_data.
Referenced by wlp::array_heap< T, Cmp >::top().
{
             return m_data[0];
         }
template<typename T> const val_type& wlp::array_list< T >::front () const inline
Returns
reference to the first element in the list
Definition at line 533 of file ArrayList.h.
References wlp::array_list< T >::m_data.
{
             return m_data[0];
         }
template<typename T> size_type wlp::array_list< T >::index_of (const val_type & val) const inline
Parameters
val the value to find
Returns
the index of the value, or the size of the list if the value is not found
Definition at line 726 of file ArrayList.h.
References wlp::array_list< T >::m_data, and wlp::array_list< T >::m_size.
Referenced by wlp::array_list< T >::find().
{
             size_type i = 0;
             for (; i < m_size; ++i) {
                 if (val == m_data[i]) { return i; }
             }
             return i;
         }
template<typename T> void wlp::array_list< T >::init_array (size_type initial_size) inline private
Initialize the backing array. This function performs no initialization of the contents of the array itself.
Parameters
initial_size the initial capacity for the backing array
Definition at line 387 of file ArrayList.h.
References wlp::array_list< T >::m_data.
Referenced by wlp::array_list< T >::array_list().
{
             m_data = malloc<val_type[]>(initial_size);
         }
template<typename T> template<typename V > iterator wlp::array_list< T >::insert (size_type i, V && val) inline
Insert an element in the array at the specified position such that the previous element at the position and all elements after are shifted to the right.
Parameters
i position to insert
t element to insert
Returns
iterator to the inserted element
Definition at line 617 of file ArrayList.h.
References wlp::array_list< T >::ensure_capacity(), wlp::array_list< T >::m_data, wlp::array_list< T >::m_size, wlp::array_list< T >::normalize(), and wlp::array_list< T >::shift_right().
{
             ensure_capacity();
             normalize(i);
             shift_right(i);
             m_data[i] = forward<V>(val);
             ++m_size;
             return iterator(i, this);
         }
template<typename T> template<typename V > iterator wlp::array_list< T >::insert (const iterator & it, V && val) inline
Insert an element at the position pointed to by the iterator.
Parameters
it iterator to the inserted position
t element to insert
Returns
iterator to the inserted element
Definition at line 635 of file ArrayList.h.
References wlp::array_list< T >::end(), wlp::array_list< T >::ensure_capacity(), wlp::array_list< T >::m_data, wlp::ArrayListIterator< T, Ref, Ptr >::m_i, wlp::array_list< T >::m_size, and wlp::array_list< T >::shift_right().
{
             if (it.m_i > m_size) {
                 return end();
             }
             ensure_capacity();
             shift_right(it.m_i);
             m_data[it.m_i] = forward<V>(val);
             ++m_size;
             return it;
         }
template<typename T> void wlp::array_list< T >::normalize (size_type & i) const inline private
Normalize an index such that it is within the range
[0, length)
.
Parameters
i integer to normalize
Definition at line 397 of file ArrayList.h.
References wlp::array_list< T >::m_size.
Referenced by wlp::array_list< T >::at(), wlp::array_list< T >::erase(), and wlp::array_list< T >::insert().
{
             if (m_size == 0) {
                 i = 0;
                 return;
             }
             i %= m_size;
         }
template<typename T> list_type& wlp::array_list< T >::operator= (const list_type &) delete
Disable copy assignment.
Returns
reference to this list
template<typename T> list_type& wlp::array_list< T >::operator= (list_type && list) inline
Move assignment operator.
Parameters
list array list to transfer
Returns
reference to this list
Definition at line 763 of file ArrayList.h.
References wlp::array_list< T >::m_capacity, wlp::array_list< T >::m_data, wlp::array_list< T >::m_size, and wlp::move().
{
             free<val_type>(m_data);
             m_data = move(list.m_data);
             m_size = move(list.m_size);
             m_capacity = move(list.m_capacity);
             list.m_data = nullptr;
             list.m_size = 0;
             list.m_capacity = 0;
             return *this;
         }
template<typename T> val_type& wlp::array_list< T >::operator[] (size_type i) inline
Access operator returns the element at the specified position without bounds checking.
Parameters
i position to access
Returns
reference to the element there
Definition at line 507 of file ArrayList.h.
References wlp::array_list< T >::m_data.
{
             return m_data[i];
         }
template<typename T> val_type const& wlp::array_list< T >::operator[] (size_type i) const inline
Access operator returns the element at the specified position without bounds checking.
Parameters
i position to access
Returns
reference to the element there
Definition at line 519 of file ArrayList.h.
References wlp::array_list< T >::m_data.
{
             return m_data[i];
         }
template<typename T> void wlp::array_list< T >::pop_back () inline
Remove the last element from the list.
Definition at line 705 of file ArrayList.h.
References wlp::array_list< T >::m_size.
Referenced by wlp::array_heap< T, Cmp >::pop().
{
             if (m_size > 0) {
                 --m_size;
             }
         }
template<typename T> void wlp::array_list< T >::pop_front () inline
Remove the first element from the list.
Definition at line 714 of file ArrayList.h.
References wlp::array_list< T >::m_size, and wlp::array_list< T >::shift_left().
{
             if (m_size > 0) {
                 shift_left(0);
                 --m_size;
             }
         }
template<typename T> template<typename V > void wlp::array_list< T >::push_back (V && val) inline
Insert an element to the back of the list.
Parameters
val element to insert
Definition at line 683 of file ArrayList.h.
References wlp::array_list< T >::ensure_capacity(), wlp::array_list< T >::m_data, and wlp::array_list< T >::m_size.
Referenced by wlp::array_heap< T, Cmp >::push().
{
             ensure_capacity();
             m_data[m_size] = forward<V>(val);
             ++m_size;
         }
template<typename T> template<typename V > void wlp::array_list< T >::push_front (V && val) inline
Insert an element at the front of the list.
Parameters
val element to insert
Definition at line 695 of file ArrayList.h.
References wlp::array_list< T >::ensure_capacity(), wlp::array_list< T >::m_data, wlp::array_list< T >::m_size, and wlp::array_list< T >::shift_right().
{
             ensure_capacity();
             shift_right(0);
             m_data[0] = forward<V>(val);
             ++m_size;
         }
template<typename T > void wlp::array_list< T >::reserve (size_type new_capacity)
Copy the elements in the current array into a new array such that the new array has a size corresponding to the new capacity. If the new capacity is smaller than the current capacity, nothing happens.
Parameters
new_capacity the size of backing array to reserve
Definition at line 792 of file ArrayList.h.
{
         if (new_capacity <= m_capacity) {
             return;
         }
         val_type *new_data = malloc<val_type>(new_capacity);
         for (size_type i = 0; i < m_size; i++) {
             new_data[i] = m_data[i];
         }
         free<val_type>(m_data);
         m_data = new_data;
         m_capacity = new_capacity;
     }
template<typename T > void wlp::array_list< T >::shift_left (size_type i) inline private
Shift elements in the array at position
i
to the left once, such that the element at position
i
is erased.
Parameters
i the shift begin position
Definition at line 827 of file ArrayList.h.
Referenced by wlp::array_list< T >::erase(), and wlp::array_list< T >::pop_front().
{
         for (size_type j = i; j < m_size - 1; j++) {
             m_data[j] = m_data[j + 1];
         }
     }
template<typename T > void wlp::array_list< T >::shift_right (size_type i) inline private
Shift elements in the array at position
i
to the right once, such that the element at position
i
is now present twice in the array.
Parameters
i the shift begin position
Definition at line 820 of file ArrayList.h.
Referenced by wlp::array_list< T >::insert(), and wlp::array_list< T >::push_front().
{
         for (size_type j = m_size; j > i; j--) {
             m_data[j] = m_data[j - 1];
         }
     }
template<typename T > void wlp::array_list< T >::shrink ()
Copy the elements of the array into a new array whose capacity is equal to the number of elements in the array.
Definition at line 806 of file ArrayList.h.
{
         if (m_size == m_capacity) {
             return;
         }
         val_type *new_data = malloc<val_type>(m_size);
         for (size_type i = 0; i < m_size; i++) {
             new_data[i] = m_data[i];
         }
         free<val_type>(m_data);
         m_data = new_data;
         m_capacity = m_size;
     }
template<typename T> size_type wlp::array_list< T >::size () const inline
Returns
the current number of elements in the list
Definition at line 442 of file ArrayList.h.
References wlp::array_list< T >::m_size.
Referenced by wlp::array_heap< T, Cmp >::size().
{
             return m_size;
         }
Friends And Related Function Documentation
template<typename T> friend class ArrayListIterator< T, const T &, const T * > friend
Definition at line 300 of file ArrayList.h.
template<typename T> friend class ArrayListIterator< T, T &, T * > friend
Definition at line 298 of file ArrayList.h.
Field Documentation
template<typename T> size_type wlp::array_list< T >::m_capacity private
The current size of the backing array.
Definition at line 296 of file ArrayList.h.
Referenced by wlp::array_list< T >::array_list(), wlp::array_list< T >::capacity(), and wlp::array_list< T >::operator=().
template<typename T> val_type* wlp::array_list< T >::m_data private
The backing array.
Definition at line 288 of file ArrayList.h.
Referenced by wlp::array_list< T >::array_list(), wlp::array_list< T >::at(), wlp::array_list< T >::back(), wlp::array_list< T >::data(), wlp::array_list< T >::front(), wlp::array_list< T >::index_of(), wlp::array_list< T >::init_array(), wlp::array_list< T >::insert(), wlp::ArrayListIterator< T, Ref, Ptr >::operator*(), wlp::array_list< T >::operator=(), wlp::array_list< T >::operator[](), wlp::array_list< T >::push_back(), wlp::array_list< T >::push_front(), and wlp::array_list< T >::~array_list().
template<typename T> size_type wlp::array_list< T >::m_size private
The current number of elements in the list.
Definition at line 292 of file ArrayList.h.
Referenced by wlp::array_list< T >::at(), wlp::array_list< T >::back(), wlp::ArrayListIterator< T, Ref, Ptr >::check_bounds(), wlp::array_list< T >::clear(), wlp::array_list< T >::empty(), wlp::array_list< T >::end(), wlp::array_list< T >::erase(), wlp::array_list< T >::index_of(), wlp::array_list< T >::insert(), wlp::array_list< T >::normalize(), wlp::ArrayListIterator< T, Ref, Ptr >::operator*(), wlp::ArrayListIterator< T, Ref, Ptr >::operator++(), wlp::ArrayListIterator< T, Ref, Ptr >::operator+=(), wlp::array_list< T >::operator=(), wlp::array_list< T >::pop_back(), wlp::array_list< T >::pop_front(), wlp::array_list< T >::push_back(), wlp::array_list< T >::push_front(), and wlp::array_list< T >::size().
The documentation for this class was generated from the following file:
wlib/stl/ArrayList.h