Waterloop Wlib: wlp::StringIterator< String, Ref, Ptr > Class Template Reference
wlp::StringIterator< String, Ref, Ptr > Class Template Reference
#include <StringIterator.h>
Public Types
typedef char val_type
typedef wlp::size_type size_type
typedef wlp::diff_type diff_type
typedef String string_type
typedef Ref reference
typedef Ptr pointer
Public Member Functions
StringIterator (size_type i, string_type *string)
StringIterator (const self_type &it)
reference operator* () const
pointer operator-> () const
self_type & operator++ ()
self_type operator++ (int)
self_type & operator-- ()
self_type operator-- (int)
bool operator== (const self_type &it) const
bool operator!= (const self_type &it) const
self_type & operator= (const self_type &it)
self_type operator+ (const size_type &d) const
self_type operator- (const size_type &d) const
diff_type operator- (const self_type &it) const
self_type & operator+= (const size_type &d)
self_type & operator-= (const size_type &d)
Private Types
typedef StringIterator< String, Ref, Ptr > self_type
Private Member Functions
void check_bounds ()
Private Attributes
size_type m_i
string_type * m_string
Detailed Description
template<typename String, typename Ref, typename Ptr>
class wlp::StringIterator< String, Ref, Ptr >
Definition at line 10 of file StringIterator.h.
Member Typedef Documentation
diff_type
template<typename String , typename Ref , typename Ptr > typedef wlp::diff_type wlp::StringIterator< String, Ref, Ptr >::diff_type
Definition at line 14 of file StringIterator.h.
pointer
template<typename String , typename Ref , typename Ptr > typedef Ptr wlp::StringIterator< String, Ref, Ptr >::pointer
Definition at line 17 of file StringIterator.h.
reference
template<typename String , typename Ref , typename Ptr > typedef Ref wlp::StringIterator< String, Ref, Ptr >::reference
Definition at line 16 of file StringIterator.h.
self_type
template<typename String , typename Ref , typename Ptr > typedef StringIterator<String, Ref, Ptr> wlp::StringIterator< String, Ref, Ptr >::self_type private
Definition at line 20 of file StringIterator.h.
size_type
template<typename String , typename Ref , typename Ptr > typedef wlp::size_type wlp::StringIterator< String, Ref, Ptr >::size_type
Definition at line 13 of file StringIterator.h.
string_type
template<typename String , typename Ref , typename Ptr > typedef String wlp::StringIterator< String, Ref, Ptr >::string_type
Definition at line 15 of file StringIterator.h.
val_type
template<typename String , typename Ref , typename Ptr > typedef char wlp::StringIterator< String, Ref, Ptr >::val_type
Definition at line 12 of file StringIterator.h.
Constructor & Destructor Documentation
StringIterator() [1/2]
template<typename String , typename Ref , typename Ptr > wlp::StringIterator< String, Ref, Ptr >::StringIterator (size_type i, string_type * string) inline
Definition at line 32 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::check_bounds().
                 : m_i(i),
                   m_string(string) {
             check_bounds();
         }
StringIterator() [2/2]
template<typename String , typename Ref , typename Ptr > wlp::StringIterator< String, Ref, Ptr >::StringIterator (const self_type & it) inline
Definition at line 38 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::check_bounds().
                 : m_i(it.m_i),
                   m_string(it.m_string) {
             check_bounds();
         }
Member Function Documentation
check_bounds()
template<typename String , typename Ref , typename Ptr > void wlp::StringIterator< String, Ref, Ptr >::check_bounds () inline private
Definition at line 25 of file StringIterator.h.
Referenced by wlp::StringIterator< String, Ref, Ptr >::operator+=(), and wlp::StringIterator< String, Ref, Ptr >::StringIterator().
{
             if (m_i > m_string->length()) {
                 m_i = m_string->length();
             }
         }
operator!=()
template<typename String , typename Ref , typename Ptr > bool wlp::StringIterator< String, Ref, Ptr >::operator!= (const self_type & it) const inline
Definition at line 82 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::m_i.
{
             return m_i != it.m_i;
         }
operator*()
template<typename String , typename Ref , typename Ptr > reference wlp::StringIterator< String, Ref, Ptr >::operator* () const inline
Definition at line 44 of file StringIterator.h.
{
             return m_string->at(m_i);
         }
operator+()
template<typename String , typename Ref , typename Ptr > self_type wlp::StringIterator< String, Ref, Ptr >::operator+ (const size_type & d) const inline
Definition at line 91 of file StringIterator.h.
{
             return self_type(static_cast<size_type>(m_i + d), m_string);
         }
operator++() [1/2]
template<typename String , typename Ref , typename Ptr > self_type& wlp::StringIterator< String, Ref, Ptr >::operator++ () inline
Definition at line 52 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::m_i.
{
             if (m_i < m_string->length()) {
                 ++m_i;
             }
             return *this;
         }
operator++() [2/2]
template<typename String , typename Ref , typename Ptr > self_type wlp::StringIterator< String, Ref, Ptr >::operator++ (int) inline
Definition at line 59 of file StringIterator.h.
{
             self_type it = *this;
             ++*this;
             return it;
         }
operator+=()
template<typename String , typename Ref , typename Ptr > self_type& wlp::StringIterator< String, Ref, Ptr >::operator+= (const size_type & d) inline
Definition at line 103 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::check_bounds().
{
             m_i = static_cast<size_type>(m_i + d);
             check_bounds();
             return *this;
         }
operator-() [1/2]
template<typename String , typename Ref , typename Ptr > self_type wlp::StringIterator< String, Ref, Ptr >::operator- (const size_type & d) const inline
Definition at line 95 of file StringIterator.h.
{
             return self_type(static_cast<size_type>(m_i - d), m_string);
         }
operator-() [2/2]
template<typename String , typename Ref , typename Ptr > diff_type wlp::StringIterator< String, Ref, Ptr >::operator- (const self_type & it) const inline
Definition at line 99 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::m_i.
{
             return static_cast<diff_type>(m_i - it.m_i);
         }
operator--() [1/2]
template<typename String , typename Ref , typename Ptr > self_type& wlp::StringIterator< String, Ref, Ptr >::operator-- () inline
Definition at line 65 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::m_i.
{
             if (m_i > 0) {
                 --m_i;
             }
             return *this;
         }
operator--() [2/2]
template<typename String , typename Ref , typename Ptr > self_type wlp::StringIterator< String, Ref, Ptr >::operator-- (int) inline
Definition at line 72 of file StringIterator.h.
{
             self_type it = *this;
             --*this;
             return it;
         }
operator-=()
template<typename String , typename Ref , typename Ptr > self_type& wlp::StringIterator< String, Ref, Ptr >::operator-= (const size_type & d) inline
Definition at line 109 of file StringIterator.h.
{
             if (d >= m_i) {
                 m_i = 0;
             } else {
                 m_i = static_cast<size_type>(m_i - d);
             }
             return *this;
         }
operator->()
template<typename String , typename Ref , typename Ptr > pointer wlp::StringIterator< String, Ref, Ptr >::operator-> () const inline
Definition at line 48 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::m_i.
{
             return m_string->c_str() + m_i;
         }
operator=()
template<typename String , typename Ref , typename Ptr > self_type& wlp::StringIterator< String, Ref, Ptr >::operator= (const self_type & it) inline
Definition at line 86 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::m_i.
{
             m_i = it.m_i;
             return *this;
         }
operator==()
template<typename String , typename Ref , typename Ptr > bool wlp::StringIterator< String, Ref, Ptr >::operator== (const self_type & it) const inline
Definition at line 78 of file StringIterator.h.
References wlp::StringIterator< String, Ref, Ptr >::m_i.
{
             return m_i == it.m_i;
         }
Field Documentation
m_i
template<typename String , typename Ref , typename Ptr > size_type wlp::StringIterator< String, Ref, Ptr >::m_i private
Definition at line 22 of file StringIterator.h.
Referenced by wlp::StringIterator< String, Ref, Ptr >::operator!=(), wlp::StringIterator< String, Ref, Ptr >::operator++(), wlp::StringIterator< String, Ref, Ptr >::operator-(), wlp::StringIterator< String, Ref, Ptr >::operator--(), wlp::StringIterator< String, Ref, Ptr >::operator->(), wlp::StringIterator< String, Ref, Ptr >::operator=(), and wlp::StringIterator< String, Ref, Ptr >::operator==().
m_string
template<typename String , typename Ref , typename Ptr > string_type* wlp::StringIterator< String, Ref, Ptr >::m_string private
Definition at line 23 of file StringIterator.h.
The documentation for this class was generated from the following file:
strings/StringIterator.h