Waterloop Wlib: wlp Namespace Reference
wlp Namespace Reference
Data Structures
class sm_event_data
class state_base
class state_action
class guard_base
class guard_condition
class entry_base
class entry_action
class exit_base
class exit_action
struct state_map_row
struct state_map_row_ex
class state_machine
class __Allocator
class DynamicAllocatorPool
class StaticAllocatorPool
class __array2d_access
class array2d
class array_heap
class array_list
class ArrayListIterator
struct comparator
struct reverse_comparator
struct comparator< const char * >
struct comparator< static_string< tSize > >
struct comparator_concept
struct iterator_concept
struct iterator_concept< C, true >
struct random_access_iterator_concept
struct random_access_iterator_concept< C, true >
struct map_concept
struct map_concept< C, true >
struct set_concept
struct set_concept< C, true >
struct list_concept
struct list_concept< C, true >
struct string_concept
struct string_concept< C, true >
struct equals
struct equals< static_string< tSize > >
struct equals< const static_string< tSize > >
struct equals< char * >
struct equals< const char * >
struct hash
struct hash< static_string< tSize >, IntType >
struct hash< char *, IntType >
struct hash< const char *, IntType >
class hash_map
class hash_set
class hash_table
struct HashTableNode
struct HashTableIterator
class initializer_list
struct LinkedListNode
class linked_list
struct LinkedListIterator
class open_map
class open_set
struct pair
struct RedBlackTreeColor
struct RedBlackTreeNode
struct RedBlackTreeIterator
class tree
class ReferenceCount
class shared_ptr
class weak_ptr
class SharedCount
class WeakCount
struct MapGetKey
struct MapGetVal
struct SetGetKey
struct SetGetVal
class tree_map
class tree_set
struct TupleElement
struct IndexSequence
struct AppendIndexSequence
struct AppendIndexSequence< I, IndexSequence< Indices...> >
struct MakeIndexSequence
struct MakeIndexSequence< 1 >
struct TypeAtIndex
struct TypeAtIndex< 0, Head, Tail...>
struct TupleImpl
struct IsTupleImpl
struct IsTupleImpl< TupleImpl< IndexSequence< Indices...>, Types...> >
struct TupleImpl< IndexSequence< Indices...>, Types...>
class tuple
struct tuple_size
struct tuple_size< tuple< Types...> >
struct ignore_type
struct repeat_tuple_type_hopper
struct repeat_tuple_type_sub
struct repeat_tuple_type_sub< Type, IndexSequence< Indices...> >
struct repeat_tuple_type
struct TypeAtTuple
struct TypeAtTuple< I, tuple< Types...> >
struct cat_pair_type_sub
struct cat_pair_type_sub< TupleA, IndexSequence< IndicesA...>, TupleB, IndexSequence< IndicesB...> >
struct cat_pair_type
struct tuple_cat_type
struct tuple_cat_type< Tuple >
struct tuple_cat_type< TupleA, TupleB >
struct tuple_cat_type< TupleA, TupleB, Tuples...>
struct has_size_type
struct has_val_type
struct has_key_type
struct has_iterator
struct has_const_iterator
struct has_map_type
struct has_node_type
struct has_diff_type
struct obtain_size_type
struct obtain_val_type
struct obtain_key_type
struct obtain_iterator
struct obtain_const_iterator
struct obtain_map_type
struct obtain_node_type
struct obtain_diff_type
class unique_ptr
class unique_ptr< T[]>
class vector2d
class static_string
class dynamic_string
class StringIterator
struct is_one_of_ct
struct is_one_of_ct< comp_t, target, head >
struct isnt_any_of_ct
struct isnt_any_of_ct< comp_t, target, head >
struct is_one_of
struct is_one_of< comp_t, head >
struct isnt_any_of
struct isnt_any_of< comp_t, head >
struct is_function
struct integral_constant
struct conditional
struct conditional< false, IfTrue, IfFalse >
struct remove_const
struct remove_const< T const >
struct remove_volatile
struct remove_volatile< T volatile >
struct remove_cv
struct or_
struct or_<>
struct or_< Q1 >
struct or_< Q1, Q2 >
struct or_< Q1, Q2, Q3, Qn...>
struct and_
struct and_<>
struct and_< Q1 >
struct and_< Q1, Q2 >
struct and_< Q1, Q2, Q3, Qn...>
struct not_
struct __void__
struct __void__< void >
struct is_void
struct is_lvalue_reference
struct is_lvalue_reference< T & >
struct is_rvalue_reference
struct is_rvalue_reference< T && >
struct is_reference
struct __remove_pointer__
struct __remove_pointer__< T, U * >
struct remove_pointer
struct remove_reference
struct remove_reference< T & >
struct remove_reference< T && >
struct remove_extent
struct remove_extent< T[size]>
struct remove_extent< T[]>
struct is_object
struct is_referenceable
struct is_referenceable< Result(Arguments...)>
struct __lpointer__
struct __lpointer__< T, true >
struct add_pointer
struct is_array
struct is_array< T[_Size]>
struct is_array< T[]>
struct is_sized_array
struct is_sized_array< T[]>
struct is_sized_array< T[size]>
struct is_unsized_array
struct is_unsized_array< T[]>
struct is_unsized_array< T[size]>
struct get_array_size
struct get_array_size< T[size]>
struct __decay__
struct __decay__< U, false, false >
struct __decay__< U, true, false >
struct __decay__< U, false, true >
class decay
struct enable_if
struct enable_if< true, T >
struct is_function< Result(ArgTypes...)>
struct is_function< Result(ArgTypes...)& >
struct is_function< Result(ArgTypes...)&& >
struct is_function< Result(ArgTypes...) const >
struct is_function< Result(ArgTypes...) const & >
struct is_function< Result(ArgTypes...) const && >
struct is_same
struct is_same< T, T >
struct __lvalue__
struct __lvalue__< T, true >
struct add_lvalue_reference
struct __rvalue__
struct __rvalue__< T, true >
struct add_rvalue_reference
struct add_const
struct __declval__
struct __is_null_pointer_helper
struct __is_null_pointer_helper< nullptr_t >
struct is_null_pointer
struct __is_nullptr_t
struct __is_integral_helper
struct __is_integral_helper< bool >
struct __is_integral_helper< char >
struct __is_integral_helper< signed char >
struct __is_integral_helper< unsigned char >
struct __is_integral_helper< wchar_t >
struct __is_integral_helper< char16_t >
struct __is_integral_helper< char32_t >
struct __is_integral_helper< short >
struct __is_integral_helper< unsigned short >
struct __is_integral_helper< int >
struct __is_integral_helper< unsigned int >
struct __is_integral_helper< long >
struct __is_integral_helper< unsigned long >
struct __is_integral_helper< long long >
struct __is_integral_helper< unsigned long long >
struct is_integral
struct __is_floating_point_helper
struct __is_floating_point_helper< float >
struct __is_floating_point_helper< double >
struct __is_floating_point_helper< long double >
struct __is_pointer_helper
struct __is_pointer_helper< _Tp * >
struct is_pointer
struct is_floating_point
struct is_arithmetic
struct is_fundamental
struct __convertible__
struct __convertible__< From, To, false >
struct is_convertible
struct __storage__
struct aligned_storage
struct alignment_of
Typedefs
typedef uint8_t state_type
typedef sm_event_data sm_no_data
template<size_type I, typename... Types>
using TypeAtIndexType = typename TypeAtIndex< I, Types...>::type
template<typename Type , size_type Repeat>
using RepeatTuple = typename repeat_tuple_type< Type, Repeat >::type
typedef static_string< 8u > String8
typedef static_string< 16u > String16
typedef static_string< 32u > String32
typedef static_string< 64u > String64
typedef static_string< 128u > String128
typedef static_string< 256u > String256
typedef wlp::dynamic_string String
typedef uint16_t size_type
typedef int16_t diff_type
typedef uint32_t size32_type
typedef int32_t diff32_type
typedef integral_constant
< bool, true > true_type
typedef integral_constant
< bool, false > false_type
template<bool t>
using boolean_constant = integral_constant< bool, t >
template<typename T >
using remove_pointer_type = typename remove_pointer< T >::type
template<typename T >
using remove_reference_type = typename remove_reference< T >::type
template<typename T >
using decay_type = typename decay< T >::type
Functions
template<typename RandomAccessIterator , typename SizeType , typename ValType , typename Cmp >
void __push_heap (RandomAccessIterator first, SizeType hole_index, SizeType top_index, ValType value, Cmp cmp)
template<typename RandomAccessIterator , typename SizeType , typename ValType >
void __push_heap (RandomAccessIterator first, SizeType hole_index, SizeType top_index, ValType value)
template<typename RandomAccessIterator , typename Cmp , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type, typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() && is_comparator<Cmp, ValType>() >::type>
void push_heap (RandomAccessIterator first, RandomAccessIterator last, Cmp cmp)
template<typename RandomAccessIterator , typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() >::type, typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type>
void push_heap (RandomAccessIterator first, RandomAccessIterator last)
template<typename RandomAccessIterator , typename SizeType , typename ValType , typename Cmp >
void __adjust_heap (RandomAccessIterator first, SizeType hole_index, SizeType length, ValType value, Cmp cmp)
template<typename RandomAccessIterator , typename SizeType , typename ValType >
void __adjust_heap (RandomAccessIterator first, SizeType hole_index, SizeType length, ValType value)
template<typename RandomAccessIterator , typename Cmp , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType >
void __pop_heap (RandomAccessIterator first, RandomAccessIterator last, RandomAccessIterator result, ValType value, Cmp cmp)
template<typename RandomAccessIterator , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType >
void __pop_heap (RandomAccessIterator first, RandomAccessIterator last, RandomAccessIterator result, ValType value)
template<typename RandomAccessIterator , typename Cmp , typename ValType = typename obtain_val_type<RandomAccessIterator>::type, typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() && is_comparator<Cmp, ValType>() >::type>
void pop_heap (RandomAccessIterator first, RandomAccessIterator last, Cmp cmp)
template<typename RandomAccessIterator , typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() >::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type>
void pop_heap (RandomAccessIterator first, RandomAccessIterator last)
template<typename RandomAccessIterator , typename Cmp , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type, typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() && is_comparator<Cmp, ValType>() >::type>
void make_heap (RandomAccessIterator first, RandomAccessIterator last, Cmp cmp)
template<typename RandomAccessIterator , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type, typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() >::type>
void make_heap (RandomAccessIterator first, RandomAccessIterator last)
template<typename RandomAccessIterator , typename Cmp , typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() && is_comparator<Cmp, typename obtain_val_type<RandomAccessIterator>::type>() >::type>
void sort_heap (RandomAccessIterator first, RandomAccessIterator last, Cmp cmp)
template<typename RandomAccessIterator , typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() >::type>
void sort_heap (RandomAccessIterator first, RandomAccessIterator last)
template<typename T >
void heap_sort (array_list< T > &list)
template<typename T , typename Cmp >
void heap_sort (array_list< T > &list, Cmp cmp)
template<typename C , typename T >
static constexpr bool is_comparator ()
template<typename C >
static constexpr bool is_iterator ()
template<typename C >
static constexpr bool is_random_access_iterator ()
template<typename C >
static constexpr bool is_map ()
template<typename C >
static constexpr bool is_set ()
template<typename C >
static constexpr bool is_list ()
template<typename C >
static constexpr bool is_string ()
template<class IntType , uint16_t tSize>
IntType hash_static_string (const static_string< tSize > &static_string)
template<class IntType >
IntType hash_string (const char *s)
template<class Val >
constexpr const Val * begin (initializer_list< Val > il) noexcept
template<class _Tp >
constexpr const _Tp * end (initializer_list< _Tp > il) noexcept
template<typename T >
void swap (shared_ptr< T > &sp1, shared_ptr< T > &sp2)
template<typename T , typename U >
shared_ptr< T > static_pointer_cast (const shared_ptr< U > &sp)
template<typename T , typename U >
shared_ptr< T > const_pointer_cast (const shared_ptr< U > &sp)
template<typename T , typename U >
shared_ptr< T > dynamic_pointer_cast (const shared_ptr< U > &sp)
template<typename T , typename U >
shared_ptr< T > reinterpret_pointer_cast (const shared_ptr< U > &sp)
template<typename T >
void swap (weak_ptr< T > &wp1, weak_ptr< T > &wp2)
template<size_type I, typename... Types>
TypeAtIndexType< I, Types...>
const & get (tuple< Types...> const &tuple)
template<size_type I, typename... Types>
TypeAtIndexType< I, Types...> & get (tuple< Types...> &tuple)
template<size_type I, typename... Types>
remove_reference_type
< TypeAtIndexType< I, Types...> > && get (tuple< Types...> &&tuple)
template<typename >
constexpr int count ()
template<typename T , typename Head , typename... Tail>
constexpr int count ()
template<typename >
constexpr int find (int)
template<typename T , typename Head , typename... Tail>
constexpr int find (int index=0)
template<typename T , typename... Types>
T & get (tuple< Types...> const &tuple)
template<typename T , typename... Types>
T & get (tuple< Types...> &tuple)
template<typename T , typename... Types>
T & get (tuple< Types...> &&tuple)
template<typename... Types>
constexpr size_type get_tuple_size (tuple< Types...>)
template<typename... Types>
tuple< Types &&...> forward_as_tuple (Types &&...elements)
template<typename... Types>
tuple< Types &...> tie (Types &...elements)
template<typename... Types>
tuple< decay_type< Types >...> make_tuple (Types &&...elements)
template<typename TupleA , size_type... IndicesA, typename TupleB , size_type... IndicesB>
tuple< typename TypeAtTuple
< IndicesA, decay_type< TupleA >
>::type..., typename
TypeAtTuple< IndicesB,
decay_type< TupleB >
>::type... > tuple_cat_pair_sub (TupleA &&tupleA, TupleB &&tupleB, IndexSequence< IndicesA...>, IndexSequence< IndicesB...>)
template<typename TupleA , typename TupleB >
cat_pair_type< TupleA, TupleB >
::type tuple_cat_pair (TupleA &&tupleA, TupleB &&tupleB)
template<typename HeadTuple >
HeadTuple && tuple_cat (HeadTuple &&tuple)
template<typename HeadTupleA , typename HeadTupleB >
cat_pair_type< HeadTupleA,
HeadTupleB >::type tuple_cat (HeadTupleA &&tupleA, HeadTupleB &&tupleB)
template<typename HeadTupleA , typename HeadTupleB , typename... TailTuples>
tuple_cat_type< HeadTupleA,
HeadTupleB, TailTuples...>
::type tuple_cat (HeadTupleA &&tupleA, HeadTupleB &&tupleB, TailTuples &&...tail)
template<typename T >
void swap (unique_ptr< T > &x, unique_ptr< T > &y)
template<typename T >
void swap (unique_ptr< T > &&x, unique_ptr< T > &y)
template<typename T >
void swap (unique_ptr< T > &x, unique_ptr< T > &&y)
template<typename T , typename U >
bool operator== (const unique_ptr< T > &x, const unique_ptr< U > &y)
template<typename T , typename U >
bool operator!= (const unique_ptr< T > &x, const unique_ptr< U > &y)
template<typename T , typename U >
bool operator< (const unique_ptr< T > &x, const unique_ptr< U > &y)
template<typename T , typename U >
bool operator<= (const unique_ptr< T > &x, const unique_ptr< U > &y)
template<typename T , typename U >
bool operator> (const unique_ptr< T > &x, const unique_ptr< U > &y)
template<typename T , typename U >
bool operator>= (const unique_ptr< T > &x, const unique_ptr< U > &y)
template<typename T , typename... Args>
unique_ptr< T > make_unique (Args &&...args)
bool operator== (const dynamic_string &lhs, const dynamic_string &rhs)
bool operator!= (const dynamic_string &lhs, const dynamic_string &rhs)
bool operator> (const dynamic_string &lhs, const dynamic_string &rhs)
bool operator>= (const dynamic_string &lhs, const dynamic_string &rhs)
bool operator< (const dynamic_string &lhs, const dynamic_string &rhs)
bool operator<= (const dynamic_string &lhs, const dynamic_string &rhs)
bool operator== (const char *lhs, const dynamic_string &rhs)
bool operator!= (const char *lhs, const dynamic_string &rhs)
bool operator> (const char *lhs, const dynamic_string &rhs)
bool operator>= (const char *lhs, const dynamic_string &rhs)
bool operator< (const char *lhs, const dynamic_string &rhs)
bool operator<= (const char *lhs, const dynamic_string &rhs)
bool operator== (const dynamic_string &lhs, const char *rhs)
bool operator!= (const dynamic_string &lhs, const char *rhs)
bool operator> (const dynamic_string &lhs, const char *rhs)
bool operator>= (const dynamic_string &lhs, const char *rhs)
bool operator< (const dynamic_string &lhs, const char *rhs)
bool operator<= (const dynamic_string &lhs, const char *rhs)
bool operator== (char lhs, const dynamic_string &rhs)
bool operator== (const dynamic_string &lhs, char rhs)
dynamic_string operator+ (const dynamic_string &lhs, const dynamic_string &rhs)
dynamic_string operator+ (const char *lhs, const dynamic_string &rhs)
dynamic_string operator+ (const dynamic_string &lhs, const char *rhs)
dynamic_string operator+ (char lhs, const dynamic_string &rhs)
dynamic_string operator+ (const dynamic_string &lhs, char rhs)
template<size_type tSize>
bool operator== (const char *lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator!= (const char *lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator> (const char *lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator>= (const char *lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator< (const char *lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator<= (const char *lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator== (const static_string< tSize > &lhs, const char *rhs)
template<size_type tSize>
bool operator!= (const static_string< tSize > &lhs, const char *rhs)
template<size_type tSize>
bool operator> (const static_string< tSize > &lhs, const char *rhs)
template<size_type tSize>
bool operator>= (const static_string< tSize > &lhs, const char *rhs)
template<size_type tSize>
bool operator< (const static_string< tSize > &lhs, const char *rhs)
template<size_type tSize>
bool operator<= (const static_string< tSize > &lhs, const char *rhs)
template<size_type tSize>
bool operator== (const static_string< tSize > &lhs, const char rhs)
template<size_type tSize>
bool operator!= (const static_string< tSize > &lhs, const char rhs)
template<size_type tSize>
bool operator> (const static_string< tSize > &lhs, const char rhs)
template<size_type tSize>
bool operator>= (const static_string< tSize > &lhs, const char rhs)
template<size_type tSize>
bool operator< (const static_string< tSize > &lhs, const char rhs)
template<size_type tSize>
bool operator<= (const static_string< tSize > &lhs, const char rhs)
template<size_type tSize>
bool operator== (const char lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator!= (const char lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator> (const char lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator>= (const char lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator< (const char lhs, const static_string< tSize > &rhs)
template<size_type tSize>
bool operator<= (const char lhs, const static_string< tSize > &rhs)
template<size_type tSize>
static_string< tSize > operator+ (const char *lhs, const static_string< tSize > &rhs)
template<size_type tSize>
static_string< tSize > operator+ (const static_string< tSize > &lhs, const char *rhs)
template<size_type tSize>
static_string< tSize > operator+ (const static_string< tSize > &lhs, const char rhs)
template<size_type tSize>
static_string< tSize > operator+ (const char lhs, const static_string< tSize > &rhs)
template<typename int_type >
constexpr int_type log2_const (int_type n)
template<typename int_type >
constexpr int_type pow_const (int_type a, int_type b)
template<typename int_type >
int_type int_div_round (int_type n, int_type d)
template<typename... Types>
void swallow (Types &&...)
template<template< class > class>
constexpr bool is_any_of ()
template<template< class > class Op, typename Head , typename... Tail>
constexpr bool is_any_of ()
template<typename T >
add_rvalue_reference< T >::type declval () noexcept
template<typename T >
constexpr remove_reference< T >
::type && move (T &&t) noexcept
template<typename T >
constexpr T && forward (typename remove_reference< T >::type &t) noexcept
template<typename T >
constexpr T && forward (typename remove_reference< T >::type &&t) noexcept
template<typename T >
void swap (T &v1, T &v2)
template<typename IntType >
static IntType exchange_and_add (IntType *mem, IntType val)
template<typename IntType >
static IntType exchange_and_sub (IntType *mem, IntType val)
Variables
const ignore_type ignore {}
decltype(nullptr) typedef nullptr_t
Typedef Documentation
template<bool t> using wlp::boolean_constant = typedef integral_constant<bool, t>
A boolean constant contains a value that is either true or false.
Definition at line 83 of file Tmp.h.
template<typename T > using wlp::decay_type = typedef typename decay<T>::type
Shorthand for type decay.
Template Parameters
T type to strip
Definition at line 564 of file Tmp.h.
typedef int32_t wlp::diff32_type
Definition at line 23 of file Types.h.
typedef int16_t wlp::diff_type
Definition at line 19 of file Types.h.
typedef integral_constant<bool, false> wlp::false_type
Container for
false
.
Definition at line 76 of file Tmp.h.
template<typename T > using wlp::remove_pointer_type = typedef typename remove_pointer<T>::type
Definition at line 311 of file Tmp.h.
template<typename T > using wlp::remove_reference_type = typedef typename remove_reference<T>::type
Shorthand for remove reference type.
Definition at line 344 of file Tmp.h.
template<typename Type , size_type Repeat> using wlp::RepeatTuple = typedef typename repeat_tuple_type<Type, Repeat>::type
Definition at line 599 of file Tuple.h.
typedef uint32_t wlp::size32_type
Definition at line 22 of file Types.h.
typedef uint16_t wlp::size_type
Definition at line 18 of file Types.h.
typedef sm_event_data wlp::sm_no_data
Definition at line 22 of file StateMachine.h.
typedef uint8_t wlp::state_type
Definition at line 21 of file StateMachine.h.
typedef wlp::dynamic_string wlp::String
Definition at line 1234 of file String.h.
typedef static_string<128u> wlp::String128
Definition at line 1230 of file String.h.
typedef static_string<16u> wlp::String16
Definition at line 1227 of file String.h.
typedef static_string<256u> wlp::String256
Definition at line 1231 of file String.h.
typedef static_string<32u> wlp::String32
Definition at line 1228 of file String.h.
typedef static_string<64u> wlp::String64
Definition at line 1229 of file String.h.
typedef static_string<8u> wlp::String8
Definition at line 1226 of file String.h.
typedef integral_constant<bool, true> wlp::true_type
Container for
true
.
Definition at line 72 of file Tmp.h.
template<size_type I, typename... Types> using wlp::TypeAtIndexType = typedef typename TypeAtIndex<I, Types...>::type
Shorthand to obtain the type at an index.
Definition at line 167 of file Tuple.h.
Function Documentation
template<typename RandomAccessIterator , typename SizeType , typename ValType , typename Cmp > void wlp::__adjust_heap (RandomAccessIterator first, SizeType hole_index, SizeType length, ValType value, Cmp cmp)
Helper function performs heapify at the specified index.
Template Parameters
RandomAccessIterator random access iterator type
SizeType integer size type
ValType value type for insertion
Cmp comparator type
Parameters
first iterator to first element in the random access structure
hole_index index of the value to be heapified
length length of the heap section of the structure
value value to heapify
cmp comparator to use
Definition at line 173 of file ArrayHeap.h.
References __push_heap().
Referenced by __pop_heap(), and make_heap().
       {
         SizeType top_index = hole_index;
         SizeType second_child = static_cast<SizeType>(2 * hole_index + 2);
         while (second_child < length) {
             if (cmp.__lt__(*(first + second_child), *(first + second_child - 1))) {
                 --second_child;
             }
             *(first + hole_index) = *(first + second_child);
             hole_index = second_child;
             second_child = static_cast<SizeType>(2 * (second_child + 1));
         }
         if (second_child == length) {
             *(first + hole_index) = *(first + second_child - 1);
             hole_index = static_cast<SizeType>(second_child - 1);
         }
         __push_heap(first, hole_index, top_index, value, cmp);
     };
template<typename RandomAccessIterator , typename SizeType , typename ValType > void wlp::__adjust_heap (RandomAccessIterator first, SizeType hole_index, SizeType length, ValType value)
Helper function performs heapify at the specified index.
Template Parameters
RandomAccessIterator random access iterator type
SizeType integer size type
ValType value type for insertion
Parameters
first iterator to first element in the random access structure
hole_index index of the value to be heapified
length length of the heap section of the structure
value value to heapify
Definition at line 213 of file ArrayHeap.h.
References __push_heap().
       {
         SizeType top_index = hole_index;
         SizeType second_child = static_cast<SizeType>(2 * hole_index + 2);
         while (second_child < length) {
             if (*(first + second_child) < *(first + second_child - 1)) {
                 --second_child;
             }
             *(first + hole_index) = *(first + second_child);
             hole_index = second_child;
             second_child = static_cast<SizeType>(2 * (second_child + 1));
         }
         if (second_child == length) {
             *(first + hole_index) = *(first + second_child - 1);
             hole_index = static_cast<SizeType>(second_child - 1);
         }
         __push_heap(first, hole_index, top_index, value);
     };
template<typename RandomAccessIterator , typename Cmp , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType > void wlp::__pop_heap (RandomAccessIterator first, RandomAccessIterator last, RandomAccessIterator result, ValType value, Cmp cmp)
Helper function to pop an element from the heap.
Template Parameters
RandomAccessIterator random access iterator type
Cmp comparator type
SizeType integer size type
ValType value type
Parameters
first iterator to first element in random access structure
last iterator to last element in random access structure
result iterator to the location where the popped element will be stored
value the value that is popped
cmp comparator to use
Definition at line 255 of file ArrayHeap.h.
References __adjust_heap().
Referenced by pop_heap().
       {
         *result = *first;
         __adjust_heap(first, (SizeType) 0, (SizeType) (last - first), value, cmp);
     };
template<typename RandomAccessIterator , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType > void wlp::__pop_heap (RandomAccessIterator first, RandomAccessIterator last, RandomAccessIterator result, ValType value)
Helper function to pop an element from the heap.
Template Parameters
RandomAccessIterator random access iterator type
SizeType integer size type
ValType value type
Parameters
first iterator to first element in random access structure
last iterator to last element in random access structure
result iterator to the location where the popped element will be stored
value the value that is popped
Definition at line 282 of file ArrayHeap.h.
References __adjust_heap().
       {
         *result = *first;
         __adjust_heap(first, (SizeType) 0, (SizeType) (last - first), value);
     };
template<typename RandomAccessIterator , typename SizeType , typename ValType , typename Cmp > void wlp::__push_heap (RandomAccessIterator first, SizeType hole_index, SizeType top_index, ValType value, Cmp cmp)
Push heap helper function. Takes a value located at
hole_index
and inserts into the heap, preserving heap property. This version uses a supplied comparator.
Template Parameters
RandomAccessIterator random access iterator type
SizeType integer size type
ValType the type of the inserted value
Cmp a comparator type
Parameters
first iterator to the first element in the backing structure
hole_index the index of the inserted element
top_index the index of the first element in the heap
value the value to insert
cmp the comparator use for
__lt__
Definition at line 48 of file ArrayHeap.h.
Referenced by __adjust_heap(), and push_heap().
       {
         SizeType parent = static_cast<SizeType>((hole_index - 1) / 2);
         while (hole_index > top_index && cmp.__lt__(*(first + parent), value)) {
             *(first + hole_index) = *(first + parent);
             hole_index = parent;
             parent = static_cast<SizeType>((hole_index - 1) / 2);
         }
         *(first + hole_index) = value;
     };
template<typename RandomAccessIterator , typename SizeType , typename ValType > void wlp::__push_heap (RandomAccessIterator first, SizeType hole_index, SizeType top_index, ValType value)
Push heap helper function. Takes a value located at
hole_index
and inserts into the heap, preserving heap property.
Template Parameters
RandomAccessIterator random access iterator type
SizeType integer size type
ValType the type of the inserted value
Parameters
first iterator to the first element in the backing structure
hole_index the index of the inserted element
top_index the index of the first element in the heap
value the value to insert
Definition at line 82 of file ArrayHeap.h.
       {
         SizeType parent = static_cast<SizeType>((hole_index - 1) / 2);
         while (hole_index > top_index && *(first + parent) < value) {
             *(first + hole_index) = *(first + parent);
             hole_index = parent;
             parent = static_cast<SizeType>((hole_index - 1) / 2);
         }
         *(first + hole_index) = value;
     };
template<class Val > constexpr const Val* wlp::begin (initializer_list< Val > il) noexcept
Definition at line 47 of file InitializerList.h.
Referenced by wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::erase(), and wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_unique().
{
         return il.begin();
     }
template<typename T , typename U > shared_ptr<T> wlp::const_pointer_cast (const shared_ptr< U > & sp) inline
Definition at line 644 of file SharedPtr.h.
References wlp::shared_ptr< T >::get().
{
         return shared_ptr<T>(sp, const_cast<T *>(sp.get()));
     };
template<typename > constexpr int wlp::count ()
Base case for count is zero.
Returns
Definition at line 436 of file Tuple.h.
Referenced by count(), wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::count(), and wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::erase().
{
         return 0;
     }
template<typename T , typename Head , typename... Tail> constexpr int wlp::count ()
This function counts the number of times a particular type appears in a tuple type pack.
Template Parameters
T the type to count
Head tuple head type
Tail tuple tail types
Returns
the number of types
Definition at line 449 of file Tuple.h.
References count().
{
         return (is_same<T, Head>::value ? 1 : 0) + count<T, Tail...>();
     };
template<typename T > add_rvalue_reference<T>::type wlp::declval () inline noexcept
Obtain a static declared value to the specified type. This function should only be used in metafunction contexts as the actual return value is undefined. This is usually used in conjunction with
decltype
build-in function to obtain the type of an unknown type.
Template Parameters
T type whose value to obtain
Returns
a value of the type
Definition at line 783 of file Tmp.h.
References wlp::__declval__< T >::__delegate__().
{
         static_assert(__declval__<T>::__stop__, "declval is not callable");
         return __declval__<T>::__delegate__();
     }
template<typename T , typename U > shared_ptr<T> wlp::dynamic_pointer_cast (const shared_ptr< U > & sp) inline
Definition at line 649 of file SharedPtr.h.
References wlp::shared_ptr< T >::get().
{
         if (T *ptr = dynamic_cast<T *>(sp.get())) {
             return shared_ptr<T>(sp, ptr);
         }
         return shared_ptr<T>();
     };
template<class _Tp > constexpr const _Tp* wlp::end (initializer_list< _Tp > il) noexcept
Definition at line 53 of file InitializerList.h.
Referenced by wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::equal_range(), wlp::linked_list< T >::erase(), wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::erase(), and wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::find().
{
         return il.end();
     }
template<typename IntType > static IntType wlp::exchange_and_add (IntType * mem, IntType val) inline static
Definition at line 70 of file Utility.h.
{
         IntType res = *mem;
         *mem = static_cast<IntType>(*mem + val);
         return res;
     }
template<typename IntType > static IntType wlp::exchange_and_sub (IntType * mem, IntType val) inline static
Definition at line 77 of file Utility.h.
{
         IntType res = *mem;
         *mem = static_cast<IntType>(*mem - val);
         return res;
     }
template<typename > constexpr int wlp::find (int)
Grab the index of a type. Base case is not found.
Returns
not found index
Definition at line 459 of file Tuple.h.
Referenced by find(), and get().
{
         return -1;
     }
template<typename T , typename Head , typename... Tail> constexpr int wlp::find (int index = 0)
Find the index of a type in a tuple's type pack.
Template Parameters
T the type to find
Head tuple head type
Tail tuple tail types
Parameters
index the current search index
Returns
the index of the type
Definition at line 472 of file Tuple.h.
References find().
{
         return is_same<T, Head>::value ? index : find<T, Tail...>(index + 1);
     };
template<typename T > constexpr T&& wlp::forward (typename remove_reference< T >::type & t) noexcept
Forward consumes either an lvalue and rvalue and returns a universal rvalue type that maintains its properties. This overloads for lvalues.
Template Parameters
T lvalue type
Parameters
t type value
Returns
rvalue capture
Definition at line 40 of file Utility.h.
Referenced by get().
{
         return static_cast<T &&>(t);
     }
template<typename T > constexpr T&& wlp::forward (typename remove_reference< T >::type && t) noexcept
Overloads for rvalues.
Template Parameters
T rvalue type
Parameters
t type value
Returns
rvalue capture
Definition at line 51 of file Utility.h.
{
         return static_cast<T &&>(t);
     }
template<typename... Types> tuple<Types &&...> wlp::forward_as_tuple (Types &&... elements)
Forwards elements into a tuple.
Template Parameters
Types types to forward
Parameters
elements element values to forward
Returns
a tuple of lvalues or rvalues
Definition at line 548 of file Tuple.h.
{
         return tuple<Types &&...>(forward<Types>(elements)...);
     }
template<size_type I, typename... Types> TypeAtIndexType<I, Types...> const& wlp::get (tuple< Types...> const & tuple)
Get function for const lvalue tuple. Returns the tuple element value at the specified index.
Template Parameters
I the index of the element to get
Types the tuple types
Parameters
tuple the tuple from which to get
Returns
the element value at the index
Definition at line 399 of file Tuple.h.
{
         TupleElement<I, TypeAtIndexType<I, Types...>> const &base = tuple;
         return base.value;
     };
template<size_type I, typename... Types> TypeAtIndexType<I, Types...>& wlp::get (tuple< Types...> & tuple)
Get function for lvalue tuple.
Template Parameters
I index of the element to get
Types the tuple types
Parameters
tuple the tuple from which to get
Returns
the element value at the index
Definition at line 412 of file Tuple.h.
{
         TupleElement<I, TypeAtIndexType<I, Types...>> &base = tuple;
         return base.value;
     };
template<size_type I, typename... Types> remove_reference_type<TypeAtIndexType<I, Types...> >&& wlp::get (tuple< Types...> && tuple)
Get function for rvalue tuple returns an rvalue value type.
Template Parameters
I index of the element to get
Types the tuple types
Parameters
tuple the tuple from which to get
Returns
the element value at the index
Definition at line 426 of file Tuple.h.
References forward().
{
         TupleElement<I, TypeAtIndexType<I, Types...>> base = tuple;
         return forward<TypeAtIndexType<I, Types...>>(base.value);
     };
template<typename T , typename... Types> T& wlp::get (tuple< Types...> const & tuple)
Get function for a tuple by type.
Template Parameters
T type to get
Types tuple types
Parameters
tuple tuple from which to get
Returns
the value of the type
Definition at line 484 of file Tuple.h.
References find().
{
         static_assert(count<T, Types...>() == 1, "Type must be unique in Tuple");
         return get<find<T, Types...>()>(tuple);
     }
template<typename T , typename... Types> T& wlp::get (tuple< Types...> & tuple)
Get function for a tuple by type.
Template Parameters
T type to get
Types tuple types
Parameters
tuple tuple from which to get
Returns
the value of the type
Definition at line 497 of file Tuple.h.
References find().
{
         static_assert(count<T, Types...>() == 1, "Type must be unique in Tuple");
         return get<find<T, Types...>()>(tuple);
     }
template<typename T , typename... Types> T& wlp::get (tuple< Types...> && tuple)
Get function for a tuple by type.
Template Parameters
T type to get
Types tuple types
Parameters
tuple tuple from which to get
Returns
the value of the type
Definition at line 510 of file Tuple.h.
References find().
{
         static_assert(count<T, Types...>() == 1, "Type must be unique in Tuple");
         return get<find<T, Types...>()>(tuple);
     }
template<typename... Types> constexpr size_type wlp::get_tuple_size (tuple< Types...>)
Shorthand to obtain the size of a tuple at runtime.
Template Parameters
Types the types to count
Returns
the number of types
Definition at line 537 of file Tuple.h.
{
         return sizeof...(Types);
     }
template<class IntType , uint16_t tSize> IntType wlp::hash_static_string (const static_string< tSize > & static_string) inline
Hash a static string by multiplying the character value by 127 and adding consecutively.
Template Parameters
IntType the integer return type
tSize the static string size
Parameters
static_string the string to hash
Returns
a hash code of the string
Definition at line 52 of file Hash.h.
References wlp::static_string< tSize >::length(), and MUL_127.
{
         IntType h = 0;
         for (size_type pos = 0; pos < static_string.length(); ++pos) {
             h = (IntType) (MUL_127(h) + static_string[pos]);
         }
         return h;
     };
template<class IntType > IntType wlp::hash_string (const char * s) inline
Hash a C string by multiplying the character value by 127 and adding consecutively.
Template Parameters
IntType the integer return type value
Parameters
s the string to hash
Returns
a hash code of the string
Definition at line 69 of file Hash.h.
References MUL_127.
{
         IntType h = 0;
         for (; *s; ++s) {
             h = (IntType) (MUL_127(h) + *s);
         }
         return h;
     }
template<typename T > void wlp::heap_sort (array_list< T > & list)
Sort an array list using heap sort. This function uses the array list elements' default ordering operations, which may be overloaded.
Template Parameters
T list element type, inferred from array list
Parameters
list array list to sort
Definition at line 626 of file ArrayHeap.h.
References wlp::array_list< T >::begin(), wlp::array_list< T >::end(), make_heap(), and sort_heap().
{
         make_heap(list.begin(), list.end());
         sort_heap(list.begin(), list.end());
     }
template<typename T , typename Cmp > void wlp::heap_sort (array_list< T > & list, Cmp cmp)
Sort an array list using heap sort. This function uses a supplied comparator type for the array list element
Template Parameters
T list element type, inferred from array list
Cmp comparator type
Parameters
list array list to sort
cmp comparator to use
Definition at line 642 of file ArrayHeap.h.
References wlp::array_list< T >::begin(), wlp::array_list< T >::end(), make_heap(), and sort_heap().
{
         make_heap(list.begin(), list.end(), cmp);
         sort_heap(list.begin(), list.end(), cmp);
     };
template<typename int_type > int_type wlp::int_div_round (int_type n, int_type d) inline
Definition at line 26 of file Math.h.
{
         return ((n < 0) ^ (d < 0)) ? ((n - d / 2) / d) : ((n + d / 2) / d);
     }
template<template< class > class> constexpr bool wlp::is_any_of ()
Recursive function applies an operator to each type in a type pack.
Returns
false in the base case
Definition at line 678 of file Tmp.h.
Referenced by is_any_of().
{
         return false;
     }
template<template< class > class Op, typename Head , typename... Tail> constexpr bool wlp::is_any_of ()
Recursive function applies a boolean operator type to each value in the type pack
Template Parameters
Op a boolean operator type with a bool value
Head head type
Tail tail types
Returns
true if the operator is satisfied by any of the types
Definition at line 691 of file Tmp.h.
References is_any_of().
{
         return Op<Head>::value || is_any_of<Op, Tail...>();
     };
template<typename C , typename T > static constexpr bool wlp::is_comparator () static
Shorthand method to check whether a class fits the defined comparator concept.
Template Parameters
C class to check
T desired comparison type
Returns
true if the class is a comparator
Definition at line 120 of file Concept.h.
{
         return comparator_concept<C, T>::value;
     }
template<typename C > static constexpr bool wlp::is_iterator () static
Shorthand to check whether a class is a forward iterator.
Template Parameters
C candidate forward iterator type
Returns
true if the class is a forward iterator
Definition at line 182 of file Concept.h.
{
         return iterator_concept<C>::value;
     }
template<typename C > static constexpr bool wlp::is_list () static
Definition at line 455 of file Concept.h.
{
         return list_concept<C>::value;
     }
template<typename C > static constexpr bool wlp::is_map () static
Shorthand to check whether a class is a map.
Template Parameters
C candidate map type
Returns
true if the class is a map
Definition at line 336 of file Concept.h.
{
         return map_concept<C>::value;
     }
template<typename C > static constexpr bool wlp::is_random_access_iterator () static
Shorthand to check whether a class is a random access iterator.
Template Parameters
C candidate random access iterator
Returns
true if the class is a random access iterator
Definition at line 257 of file Concept.h.
{
         return random_access_iterator_concept<C>::value;
     }
template<typename C > static constexpr bool wlp::is_set () static
Definition at line 390 of file Concept.h.
{
         return set_concept<C>::value;
     }
template<typename C > static constexpr bool wlp::is_string () static
Definition at line 514 of file Concept.h.
{
         return string_concept<C>::value;
     }
template<typename int_type > constexpr int_type wlp::log2_const (int_type n) inline
Definition at line 16 of file Math.h.
{
         return ((n < 2) ? 0 : 1 + log2_const(n / 2));
     }
template<typename RandomAccessIterator , typename Cmp , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type, typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() && is_comparator<Cmp, ValType>() >::type> void wlp::make_heap (RandomAccessIterator first, RandomAccessIterator last, Cmp cmp)
Make heap will traverse a random access structure (typically an array or vector) and create a heap that ranges from
[first, last)
.
Template Parameters
RandomAccessIterator random access iterator type
Cmp comparator type
SizeType size type acquired from iterator type
ValType value type acquired from iterator type
Parameters
first iterator to first element in random access structure
last iterator to last element in random acces structure
cmp comparator to use
Definition at line 368 of file ArrayHeap.h.
References __adjust_heap().
Referenced by heap_sort().
       {
         SizeType length = static_cast<SizeType>(last - first);
         if (length < 2) {
             return;
         }
         SizeType parent = static_cast<SizeType>((length - 2) / 2);
         for (;;) {
             __adjust_heap(first, parent, length, (ValType) *(first + parent), cmp);
             if (parent == 0) {
                 return;
             }
             --parent;
         }
     };
template<typename RandomAccessIterator , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type, typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() >::type> void wlp::make_heap (RandomAccessIterator first, RandomAccessIterator last)
Make heap will traverse a random access structure (typically an array or vector) and create a heap that ranges from
[first, last)
.
Template Parameters
RandomAccessIterator random access iterator type
SizeType size type acquired from iterator type
ValType value type acquired from iterator type
Parameters
first iterator to first element in random access structure
last iterator to last element in random acces structure
Definition at line 406 of file ArrayHeap.h.
References __adjust_heap().
       {
         SizeType length = static_cast<SizeType>(last - first);
         if (length < 2) {
             return;
         }
         SizeType parent = static_cast<SizeType>((length - 2) / 2);
         for (;;) {
             __adjust_heap(first, parent, length, (ValType) *(first + parent));
             if (parent == 0) {
                 return;
             }
             --parent;
         }
     };
template<typename... Types> tuple<decay_type<Types>...> wlp::make_tuple (Types &&... elements)
Universal helper function to create a tuple from elements.
Template Parameters
Types the element types
Parameters
elements the element values
Returns
a tuple sized to the number of elements
Definition at line 668 of file Tuple.h.
Referenced by wlp::tree_map< Key, Val, Cmp >::insert(), wlp::hash_map< Key, Val, Hasher, Equals >::insert(), wlp::open_map< Key, Val, Hasher, Equals >::insert(), wlp::tree_map< Key, Val, Cmp >::insert_or_assign(), wlp::hash_map< Key, Val, Hasher, Equals >::insert_or_assign(), wlp::open_map< Key, Val, Hasher, Equals >::insert_or_assign(), wlp::tree_map< Key, Val, Cmp >::operator[](), wlp::hash_map< Key, Val, Hasher, Equals >::operator[](), wlp::open_map< Key, Val, Hasher, Equals >::operator[](), and tuple_cat_pair_sub().
{
         return tuple<decay_type<Types>...>(forward<Types>(elements)...);
     }
template<typename T , typename... Args> unique_ptr<T> wlp::make_unique (Args &&... args)
Definition at line 289 of file UniquePtr.h.
{
         return unique_ptr<T>(malloc<T>(forward<Args>(args)...));
     };
template<typename T > constexpr remove_reference<T>::type&& wlp::move (T && t) noexcept
Move function for move semantics. Transforms a universal type to an rvalue.
Template Parameters
T universal type
Parameters
t type value
Returns
rvalue of the type
Definition at line 28 of file Utility.h.
Referenced by wlp::array2d< val_t, size_t >::array2d(), wlp::TupleElement< Indices, Types >::operator=(), wlp::tree_set< Key, Cmp >::operator=(), wlp::hash_set< Key, Hasher, Equals >::operator=(), wlp::open_set< Key, Hasher, Equals >::operator=(), wlp::tree_map< Key, Val, Cmp >::operator=(), wlp::hash_map< Key, Val, Hasher, Equals >::operator=(), wlp::open_map< Key, Val, Hasher, Equals >::operator=(), wlp::__Allocator::operator=(), wlp::TupleImpl< IndexSequence< Indices...>, Types...>::operator=(), wlp::tuple< Types >::operator=(), wlp::shared_ptr< T >::operator=(), wlp::array_heap< T, Cmp >::operator=(), wlp::tree< tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::operator=(), wlp::array_list< T >::operator=(), wlp::shared_ptr< T >::shared_ptr(), and swap().
{
         return static_cast<typename remove_reference<T>::type &&>(t);
     }
bool wlp::operator!= (const dynamic_string & lhs, const dynamic_string & rhs)
Definition at line 238 of file String.cpp.
{
         return lhs.compare(rhs) != 0;
     }
bool wlp::operator!= (const char * lhs, const dynamic_string & rhs)
Definition at line 262 of file String.cpp.
{
         return rhs.compare(lhs) != 0;
     }
template<typename T , typename U > bool wlp::operator!= (const unique_ptr< T > & x, const unique_ptr< U > & y) inline
Definition at line 264 of file UniquePtr.h.
References wlp::unique_ptr< T >::get().
{
         return !(x.get() == y.get());
     }
bool wlp::operator!= (const dynamic_string & lhs, const char * rhs)
Definition at line 286 of file String.cpp.
{
         return lhs.compare(rhs) != 0;
     }
template<size_type tSize> bool wlp::operator!= (const char * lhs, const static_string< tSize > & rhs)
Definition at line 616 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return rhs.compare(lhs) != 0;
     }
template<size_type tSize> bool wlp::operator!= (const static_string< tSize > & lhs, const char * rhs)
Definition at line 647 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return lhs.compare(rhs) != 0;
     }
template<size_type tSize> bool wlp::operator!= (const static_string< tSize > & lhs, const char rhs)
Definition at line 678 of file String.h.
References wlp::static_string< tSize >::at(), and wlp::static_string< tSize >::length().
{
         return lhs.length() != 1 || lhs.at(0) != rhs;
     }
template<size_type tSize> bool wlp::operator!= (const char lhs, const static_string< tSize > & rhs)
Definition at line 709 of file String.h.
{
         return rhs != lhs;
     }
dynamic_string wlp::operator+ (const dynamic_string & lhs, const dynamic_string & rhs)
Definition at line 314 of file String.cpp.
References wlp::dynamic_string::c_str(), and wlp::dynamic_string::length().
{
         return {lhs.c_str(), rhs.c_str(), lhs.length(), rhs.length()};
     }
dynamic_string wlp::operator+ (const char * lhs, const dynamic_string & rhs)
Definition at line 318 of file String.cpp.
References wlp::dynamic_string::c_str(), and wlp::dynamic_string::length().
{
         return {lhs, rhs.c_str(), static_cast<size_type>(strlen(lhs)), rhs.length()};
     }
dynamic_string wlp::operator+ (const dynamic_string & lhs, const char * rhs)
Definition at line 322 of file String.cpp.
References wlp::dynamic_string::c_str(), and wlp::dynamic_string::length().
{
         return {lhs.c_str(), rhs, lhs.length(), static_cast<size_type>(strlen(rhs))};
     }
dynamic_string wlp::operator+ (char lhs, const dynamic_string & rhs)
Definition at line 326 of file String.cpp.
References wlp::dynamic_string::c_str(), and wlp::dynamic_string::length().
{
         const char temp[2] = {lhs, '\0'};
         return {temp, rhs.c_str(), 1, rhs.length()};
     }
dynamic_string wlp::operator+ (const dynamic_string & lhs, char rhs)
Definition at line 331 of file String.cpp.
References wlp::dynamic_string::c_str(), and wlp::dynamic_string::length().
{
         const char temp[2] = {rhs, '\0'};
         return {lhs.c_str(), temp, lhs.length(), 1};
     }
template<size_type tSize> static_string<tSize> wlp::operator+ (const char * lhs, const static_string< tSize > & rhs)
Definition at line 734 of file String.h.
References wlp::static_string< tSize >::c_str(), and wlp::static_string< tSize >::length().
{
         return {lhs, rhs.c_str(), static_cast<size_type>(strlen(lhs)), rhs.length()};
     }
template<size_type tSize> static_string<tSize> wlp::operator+ (const static_string< tSize > & lhs, const char * rhs)
Definition at line 739 of file String.h.
References wlp::static_string< tSize >::c_str(), and wlp::static_string< tSize >::length().
{
         return {lhs.c_str(), rhs, lhs.length(), static_cast<size_type>(strlen(rhs))};
     }
template<size_type tSize> static_string<tSize> wlp::operator+ (const static_string< tSize > & lhs, const char rhs)
Definition at line 744 of file String.h.
References wlp::static_string< tSize >::c_str(), and wlp::static_string< tSize >::length().
{
         return {lhs.c_str(), &rhs, lhs.length(), 1};
     }
template<size_type tSize> static_string<tSize> wlp::operator+ (const char lhs, const static_string< tSize > & rhs)
Definition at line 749 of file String.h.
References wlp::static_string< tSize >::c_str(), and wlp::static_string< tSize >::length().
{
         return {&lhs, rhs.c_str(), 1, rhs.length()};
     }
bool wlp::operator< (const dynamic_string & lhs, const dynamic_string & rhs)
Definition at line 250 of file String.cpp.
{
         return lhs.compare(rhs) < 0;
     }
template<typename T , typename U > bool wlp::operator< (const unique_ptr< T > & x, const unique_ptr< U > & y) inline
Definition at line 269 of file UniquePtr.h.
References wlp::unique_ptr< T >::get().
{
         return x.get() < y.get();
     }
bool wlp::operator< (const char * lhs, const dynamic_string & rhs)
Definition at line 274 of file String.cpp.
{
         return rhs.compare(lhs) >= 0;
     }
bool wlp::operator< (const dynamic_string & lhs, const char * rhs)
Definition at line 298 of file String.cpp.
{
         return lhs.compare(rhs) < 0;
     }
template<size_type tSize> bool wlp::operator< (const char * lhs, const static_string< tSize > & rhs)
Definition at line 631 of file String.h.
{
         return rhs.compare(lhs) >= 0;
     }
template<size_type tSize> bool wlp::operator< (const static_string< tSize > & lhs, const char * rhs)
Definition at line 662 of file String.h.
{
         return lhs.compare(rhs) < 0;
     }
template<size_type tSize> bool wlp::operator< (const static_string< tSize > & lhs, const char rhs)
Definition at line 693 of file String.h.
{
         return lhs.compare(rhs) < 0;
     }
template<size_type tSize> bool wlp::operator< (const char lhs, const static_string< tSize > & rhs)
Definition at line 724 of file String.h.
{
         return rhs >= lhs;
     }
bool wlp::operator<= (const dynamic_string & lhs, const dynamic_string & rhs)
Definition at line 254 of file String.cpp.
{
         return lhs.compare(rhs) <= 0;
     }
template<typename T , typename U > bool wlp::operator<= (const unique_ptr< T > & x, const unique_ptr< U > & y) inline
Definition at line 274 of file UniquePtr.h.
{
         return !(y.get() < x.get());
     }
bool wlp::operator<= (const char * lhs, const dynamic_string & rhs)
Definition at line 278 of file String.cpp.
{
         return rhs.compare(lhs) > 0;
     }
bool wlp::operator<= (const dynamic_string & lhs, const char * rhs)
Definition at line 302 of file String.cpp.
{
         return lhs.compare(rhs) <= 0;
     }
template<size_type tSize> bool wlp::operator<= (const char * lhs, const static_string< tSize > & rhs)
Definition at line 636 of file String.h.
{
         return rhs.compare(lhs) > 0;
     }
template<size_type tSize> bool wlp::operator<= (const static_string< tSize > & lhs, const char * rhs)
Definition at line 667 of file String.h.
{
         return lhs.compare(rhs) <= 0;
     }
template<size_type tSize> bool wlp::operator<= (const static_string< tSize > & lhs, const char rhs)
Definition at line 698 of file String.h.
{
         return lhs.compare(rhs) <= 0;
     }
template<size_type tSize> bool wlp::operator<= (const char lhs, const static_string< tSize > & rhs)
Definition at line 729 of file String.h.
{
         return rhs > lhs;
     }
bool wlp::operator== (const dynamic_string & lhs, const dynamic_string & rhs)
Definition at line 234 of file String.cpp.
{
         return lhs.compare(rhs) == 0;
     }
bool wlp::operator== (const char * lhs, const dynamic_string & rhs)
Definition at line 258 of file String.cpp.
{
         return rhs.compare(lhs) == 0;
     }
template<typename T , typename U > bool wlp::operator== (const unique_ptr< T > & x, const unique_ptr< U > & y) inline
Definition at line 259 of file UniquePtr.h.
References wlp::unique_ptr< T >::get().
{
         return x.get() == y.get();
     }
bool wlp::operator== (const dynamic_string & lhs, const char * rhs)
Definition at line 282 of file String.cpp.
{
         return lhs.compare(rhs) == 0;
     }
bool wlp::operator== (char lhs, const dynamic_string & rhs)
Definition at line 306 of file String.cpp.
{
         return rhs.compare(lhs) == 0;
     }
bool wlp::operator== (const dynamic_string & lhs, char rhs)
Definition at line 310 of file String.cpp.
{
         return lhs.compare(rhs) == 0;
     }
template<size_type tSize> bool wlp::operator== (const char * lhs, const static_string< tSize > & rhs)
Definition at line 611 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return rhs.compare(lhs) == 0;
     }
template<size_type tSize> bool wlp::operator== (const static_string< tSize > & lhs, const char * rhs)
Definition at line 642 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return lhs.compare(rhs) == 0;
     }
template<size_type tSize> bool wlp::operator== (const static_string< tSize > & lhs, const char rhs)
Definition at line 673 of file String.h.
References wlp::static_string< tSize >::at(), and wlp::static_string< tSize >::length().
{
         return lhs.length() == 1 && lhs.at(0) == rhs;
     }
template<size_type tSize> bool wlp::operator== (const char lhs, const static_string< tSize > & rhs)
Definition at line 704 of file String.h.
{
         return rhs == lhs;
     }
bool wlp::operator> (const dynamic_string & lhs, const dynamic_string & rhs)
Definition at line 242 of file String.cpp.
{
         return lhs.compare(rhs) > 0;
     }
bool wlp::operator> (const char * lhs, const dynamic_string & rhs)
Definition at line 266 of file String.cpp.
{
         return rhs.compare(lhs) <= 0;
     }
template<typename T , typename U > bool wlp::operator> (const unique_ptr< T > & x, const unique_ptr< U > & y) inline
Definition at line 279 of file UniquePtr.h.
References wlp::unique_ptr< T >::get().
{
         return y.get() < x.get();
     }
bool wlp::operator> (const dynamic_string & lhs, const char * rhs)
Definition at line 290 of file String.cpp.
{
         return lhs.compare(rhs) > 0;
     }
template<size_type tSize> bool wlp::operator> (const char * lhs, const static_string< tSize > & rhs)
Definition at line 621 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return rhs.compare(lhs) <= 0;
     }
template<size_type tSize> bool wlp::operator> (const static_string< tSize > & lhs, const char * rhs)
Definition at line 652 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return lhs.compare(rhs) > 0;
     }
template<size_type tSize> bool wlp::operator> (const static_string< tSize > & lhs, const char rhs)
Definition at line 683 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return lhs.compare(rhs) > 0;
     }
template<size_type tSize> bool wlp::operator> (const char lhs, const static_string< tSize > & rhs)
Definition at line 714 of file String.h.
{
         return rhs <= lhs;
     }
bool wlp::operator>= (const dynamic_string & lhs, const dynamic_string & rhs)
Definition at line 246 of file String.cpp.
{
         return lhs.compare(rhs) >= 0;
     }
bool wlp::operator>= (const char * lhs, const dynamic_string & rhs)
Definition at line 270 of file String.cpp.
{
         return rhs.compare(lhs) < 0;
     }
template<typename T , typename U > bool wlp::operator>= (const unique_ptr< T > & x, const unique_ptr< U > & y) inline
Definition at line 284 of file UniquePtr.h.
References wlp::unique_ptr< T >::get().
{
         return !(x.get() < y.get());
     }
bool wlp::operator>= (const dynamic_string & lhs, const char * rhs)
Definition at line 294 of file String.cpp.
{
         return lhs.compare(rhs) >= 0;
     }
template<size_type tSize> bool wlp::operator>= (const char * lhs, const static_string< tSize > & rhs)
Definition at line 626 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return rhs.compare(lhs) < 0;
     }
template<size_type tSize> bool wlp::operator>= (const static_string< tSize > & lhs, const char * rhs)
Definition at line 657 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return lhs.compare(rhs) >= 0;
     }
template<size_type tSize> bool wlp::operator>= (const static_string< tSize > & lhs, const char rhs)
Definition at line 688 of file String.h.
References wlp::static_string< tSize >::compare().
{
         return lhs.compare(rhs) >= 0;
     }
template<size_type tSize> bool wlp::operator>= (const char lhs, const static_string< tSize > & rhs)
Definition at line 719 of file String.h.
{
         return rhs < lhs;
     }
template<typename RandomAccessIterator , typename Cmp , typename ValType = typename obtain_val_type<RandomAccessIterator>::type, typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() && is_comparator<Cmp, ValType>() >::type> void wlp::pop_heap (RandomAccessIterator first, RandomAccessIterator last, Cmp cmp)
Pop an element from heap ranging from
[first, last)
such that the popped element is then stored at
last
and the heap now ranges
[first, last - 1)
.
Template Parameters
RandomAccessIterator random access iterator type
Cmp comparator type
ValType value type acquired from the iterator type
Parameters
first iterator to first element in random access structure
last iterator to last element in random access structure
cmp comparator to use
Definition at line 313 of file ArrayHeap.h.
References __pop_heap().
Referenced by wlp::array_heap< T, Cmp >::pop(), and sort_heap().
       {
         __pop_heap(first, last - 1, last - 1, (ValType) *(last - 1), cmp);
     };
template<typename RandomAccessIterator , typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() >::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type> void wlp::pop_heap (RandomAccessIterator first, RandomAccessIterator last)
Pop an element from heap ranging from
[first, last)
such that the popped element is then stored at
last
and the heap now ranges
[first, last - 1)
.
Template Parameters
RandomAccessIterator random access iterator type
ValType value type acquired from the iterator type
Parameters
first iterator to first element in random access structure
last iterator to last element in random access structure
Definition at line 338 of file ArrayHeap.h.
References __pop_heap().
       {
         __pop_heap(first, last - 1, last - 1, (ValType) *(last - 1));
     };
template<typename int_type > constexpr int_type wlp::pow_const (int_type a, int_type b) inline
Definition at line 21 of file Math.h.
Referenced by getSmallestBlockSize().
{
         return (b == 0) ? 1 : (a * pow_const<int_type>(a, b - 1));
     }
template<typename RandomAccessIterator , typename Cmp , typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type, typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() && is_comparator<Cmp, ValType>() >::type> void wlp::push_heap (RandomAccessIterator first, RandomAccessIterator last, Cmp cmp)
Insert a value located at the end of an array-type data structure into a heap structure at
[first, last)
. This function assumes the aforementioned range is already a heap.
Template Parameters
RandomAccessIterator random access iterator type
Cmp comparator type
SizeType integer size type, acquired from the iterator type
ValType type of the inserted value, acquired from the iterator type
Parameters
first iterator to the first element in the backing array
last iterator to the element to be inserted
cmp comparator to use
Definition at line 120 of file ArrayHeap.h.
References __push_heap().
Referenced by wlp::array_heap< T, Cmp >::push().
       {
         __push_heap(first, static_cast<SizeType>(last - first - 1), (SizeType) 0, ValType(*(last - 1)), cmp);
     }
template<typename RandomAccessIterator , typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() >::type, typename SizeType = typename obtain_size_type<RandomAccessIterator>::type, typename ValType = typename obtain_val_type<RandomAccessIterator>::type> void wlp::push_heap (RandomAccessIterator first, RandomAccessIterator last)
Insert a value located at the end of an array-type data structure into a heap structure at
[first, last)
. This function assumes the aforementioned range is already a heap.
Template Parameters
RandomAccessIterator random access iterator type
SizeType integer size type, acquired from the iterator type
ValType type of the inserted value, acquired from the iterator type
Parameters
first iterator to the first element in the backing array
last iterator to the element to be inserted
Definition at line 147 of file ArrayHeap.h.
References __push_heap().
       {
         __push_heap(first, static_cast<SizeType>(last - first - 1), (SizeType) 0, ValType(*(last - 1)));
     }
template<typename T , typename U > shared_ptr<T> wlp::reinterpret_pointer_cast (const shared_ptr< U > & sp) inline
Definition at line 657 of file SharedPtr.h.
References wlp::shared_ptr< T >::get().
{
         return shared_ptr<T>(sp, reinterpret_cast<T *>(sp.get()));
     };
template<typename RandomAccessIterator , typename Cmp , typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() && is_comparator<Cmp, typename obtain_val_type<RandomAccessIterator>::type>() >::type> void wlp::sort_heap (RandomAccessIterator first, RandomAccessIterator last, Cmp cmp)
Rearrange the elements in a heap from
[first, last)
such that they are ordered from smallest to largest between
[first, last)
. This eliminates the heap property.
Template Parameters
RandomAccessIterator random access iterator type
Cmp comparator type
Parameters
first iterator to first element in heap
last iterator to last element in heap
cmp comparator type
Definition at line 442 of file ArrayHeap.h.
References pop_heap().
Referenced by heap_sort().
       {
         while (last - first > 1) {
             pop_heap(first, last--, cmp);
         }
     };
template<typename RandomAccessIterator , typename = typename enable_if< is_random_access_iterator<RandomAccessIterator>() >::type> void wlp::sort_heap (RandomAccessIterator first, RandomAccessIterator last)
Rearrange the elements in a heap from
[first, last)
such that they are ordered from smallest to largest between
[first, last)
. This eliminates the heap property.
Template Parameters
RandomAccessIterator random access iterator type
Parameters
first iterator to first element in heap
last iterator to last element in heap
Definition at line 466 of file ArrayHeap.h.
References pop_heap().
       {
         while (last - first > 1) {
             pop_heap(first, last--);
         }
     };
template<typename T , typename U > shared_ptr<T> wlp::static_pointer_cast (const shared_ptr< U > & sp) inline
Definition at line 639 of file SharedPtr.h.
References wlp::shared_ptr< T >::get().
{
         return shared_ptr<T>(sp, static_cast<T *>(sp.get()));
     }
template<typename... Types> void wlp::swallow (Types && ...)
This function consumes, and does nothing with, the return values of parameter pack expanded function calls. This function enables individual functions to be called on each parameter pack item by consuming the expansion.
Template Parameters
Types parameter pack of arbitrary return types which may be void
Definition at line 32 of file Tmp.h.
Referenced by wlp::TupleImpl< IndexSequence< Indices...>, Types...>::operator=().
{
     }
template<typename T > void wlp::swap (T & v1, T & v2)
Swap two elements.
Template Parameters
T element type
Parameters
v1 first element
v2 second element
Definition at line 63 of file Utility.h.
References move().
{
         T tmp(move(v1));
         v1 = move(v2);
         v2 = move(tmp);
     }
template<typename T > void wlp::swap (unique_ptr< T > & x, unique_ptr< T > & y) inline
Definition at line 244 of file UniquePtr.h.
References wlp::unique_ptr< T >::swap().
{
         x.swap(y);
     };
template<typename T > void wlp::swap (unique_ptr< T > && x, unique_ptr< T > & y) inline
Definition at line 249 of file UniquePtr.h.
{
         x.swap(y);
     };
template<typename T > void wlp::swap (unique_ptr< T > & x, unique_ptr< T > && y) inline
Definition at line 254 of file UniquePtr.h.
References wlp::unique_ptr< T >::swap().
{
         x.swap(y);
     }
template<typename T > void wlp::swap (shared_ptr< T > & sp1, shared_ptr< T > & sp2) inline
Definition at line 634 of file SharedPtr.h.
References wlp::shared_ptr< T >::swap().
Referenced by wlp::tree< Element, Key, Val, GetKey, GetVal, Cmp >::erase_rebalance(), wlp::unique_ptr< T >::swap(), wlp::unique_ptr< T[]>::swap(), wlp::SharedCount< T * >::swap(), and wlp::WeakCount< T * >::swap().
{
         sp1.swap(sp2);
     }
template<typename T > void wlp::swap (weak_ptr< T > & wp1, weak_ptr< T > & wp2) inline
Definition at line 747 of file SharedPtr.h.
{
         wp1.swap(wp2);
     }
template<typename... Types> tuple<Types &...> wlp::tie (Types &... elements)
Tie creates a tuple of lvalues that can be used as a helper to quickly assign tuple values to variables.
Template Parameters
Types
Parameters
elements
Returns
Definition at line 575 of file Tuple.h.
{
         return tuple<Types &...>(elements...);
     }
template<typename HeadTuple > HeadTuple&& wlp::tuple_cat (HeadTuple && tuple)
Base case tuple concatenation for a single tuple returns the tuple.
Template Parameters
HeadTuple the tuple head
Parameters
tuple the singular tuple
Returns
forwarded tuple
Definition at line 723 of file Tuple.h.
Referenced by tuple_cat().
{
         return forward<HeadTuple>(tuple);
     }
template<typename HeadTupleA , typename HeadTupleB > cat_pair_type<HeadTupleA, HeadTupleB>::type wlp::tuple_cat (HeadTupleA && tupleA, HeadTupleB && tupleB)
Base case for the concatenation of two tuples calls the tuple pair concatenation function.
Template Parameters
HeadTupleA first tuple type
HeadTupleB second tuple type
Parameters
tupleA first tuple
tupleB second tuple
Returns
the concatenated tuples
Definition at line 738 of file Tuple.h.
References tuple_cat_pair().
{
         return tuple_cat_pair(
                 forward<HeadTupleA>(tupleA),
                 forward<HeadTupleB>(tupleB)
         );
     };
template<typename HeadTupleA , typename HeadTupleB , typename... TailTuples> tuple_cat_type<HeadTupleA, HeadTupleB, TailTuples...>::type wlp::tuple_cat (HeadTupleA && tupleA, HeadTupleB && tupleB, TailTuples &&... tail)
Concatenate an arbitrary number of tuples together. This concatenation method expands linearly.
Template Parameters
HeadTupleA first head tuple type
HeadTupleB second head tuple tye
TailTuples tail tuple types
Parameters
tupleA first tuple
tupleB second tuple
tail the tail tuples
Returns
concatenated tuples
Definition at line 779 of file Tuple.h.
References tuple_cat(), and tuple_cat_pair().
{
         auto tuple = tuple_cat_pair(
                 forward<HeadTupleA>(tupleA),
                 forward<HeadTupleB>(tupleB)
         );
         return tuple_cat(
                 tuple,
                 forward<TailTuples>(tail)...
         );
     };
template<typename TupleA , typename TupleB > cat_pair_type<TupleA, TupleB>::type wlp::tuple_cat_pair (TupleA && tupleA, TupleB && tupleB)
Concatenate exactly two tuples together.
Template Parameters
TupleA first tuple type
TupleB second tuple type
Parameters
tupleA first tuple to concate
tupleB second tuple to concate
Returns
the tuples combined
Definition at line 706 of file Tuple.h.
References tuple_cat_pair_sub().
Referenced by tuple_cat().
{
         return tuple_cat_pair_sub(
                 forward<TupleA>(tupleA),
                 forward<TupleB>(tupleB),
                 MakeIndexSequence<tuple_size<decay_type<TupleA>>::value>{},
                 MakeIndexSequence<tuple_size<decay_type<TupleB>>::value>{}
         );
     };
template<typename TupleA , size_type... IndicesA, typename TupleB , size_type... IndicesB> tuple< typename TypeAtTuple<IndicesA, decay_type<TupleA> >::type..., typename TypeAtTuple<IndicesB, decay_type<TupleB> >::type... > wlp::tuple_cat_pair_sub (TupleA && tupleA, TupleB && tupleB, IndexSequence< IndicesA...> , IndexSequence< IndicesB...>)
Tuple concatenation helper function.
Template Parameters
TupleA first tuple type
IndicesA first tuple index pack
TupleB second tuple type
IndicesB second tuple index pack
Parameters
tupleA first tuple
tupleB second tuple
Returns
concatenation of the two tuples
Definition at line 687 of file Tuple.h.
References make_tuple().
Referenced by tuple_cat_pair().
{
         return make_tuple(
                 get<IndicesA>(forward<TupleA>(tupleA))...,
                 get<IndicesB>(forward<TupleB>(tupleB))...
         );
     }
Variable Documentation
const ignore_type wlp::ignore {}
Definition at line 564 of file Tuple.h.
decltype(nullptr) typedef wlp::nullptr_t
Definition at line 20 of file Tmp.h.