Waterloop Wlib: memory/Memory.h File Reference
Memory.h File Reference
Memory is a class that provides dynamic fixed size memory.
#include <string.h>
#include "../utility/Utility.h"
#include "../Types.h"
#include "../utility/Tmp.h"
#include "New.h"
Data Structures
class MemoryInitDestroy
Helper for initializing and destroying memory management.
Functions
void * __memory_alloc (uint32_t size, bool anObject)
void __memory_free (void *ptr)
template<typename T , typename NonArrayType = typename wlp::remove_extent<T>::type, typename = typename wlp::enable_if<wlp::is_array<T>::value, bool>::type>
NonArrayType * malloc (wlp::size_type num)
template<typename T , typename = typename wlp::enable_if<!wlp::is_pointer<T>::value, bool>::type, typename = typename wlp::enable_if<wlp::is_arithmetic<T>::value, bool>::type>
T * calloc ()
template<typename T , typename NonArrayType = typename wlp::remove_extent<T>::type, typename = typename wlp::enable_if<!wlp::is_pointer<NonArrayType>::value, bool>::type, typename = typename wlp::enable_if<wlp::is_arithmetic<NonArrayType>::value, bool>::type, typename = typename wlp::enable_if<wlp::is_array<T>::value, bool>::type>
NonArrayType * calloc (wlp::size_type num=1)
template<typename Type >
void free (Type *&ptr)
template<typename Type >
void free (Type *&&ptr)
wlp::size32_type getFixedMemorySize (void *ptr)
wlp::size_type getSmallestBlockSize ()
template<typename Type , typename = typename wlp::enable_if<wlp::is_fundamental<Type>::value, bool>::type>
Type * realloc (Type *ptr, wlp::size_type num=1)
wlp::size32_type getTotalMemoryUsed ()
wlp::size32_type getTotalMemoryFree ()
wlp::size32_type getTotalMemoryAvailable ()
bool isSizeAvailable (wlp::size32_type blockSize)
bool isSizeMemAvailable (wlp::size32_type blockSize)
uint16_t getNumBlocksAvailable (wlp::size32_type blockSize)
uint16_t getNumBlocks ()
uint16_t getMaxAllocations ()
Variables
static MemoryInitDestroy __g_smemoryInitDestroy
Detailed Description
Memory is a class that provides dynamic fixed size memory.
It does not impose any restrictions on how many blocks can be borrowed and of what size can it be borrowed. This has an option to use a memory pool which has restrictions on how much memory we can use. When pool is filled, any call for memory will return
nullptr
Precondition
Number of memory block sizes will depend on
MAX_ALLOCATORS
Author
Deep Dhillon
Date
November 19, 2017
Bug:
No known bugs
Definition in file Memory.h.
Function Documentation
void* __memory_alloc (size32_type size, bool anObject)
Used internally not for client's use Use the
malloc
function
Allocates a memory block of the requested size. The blocks are created from the fixed block allocators
Parameters
size the client's requested size of the block
anObject specify if the memory will be used object(s) or fundamental types
Returns
a pointer to the memory block
Definition at line 278 of file Memory.cpp.
References __allocators, __memory_alloc(), wlp::__Allocator::allocate(), wlp::__Allocator::getBlockSize(), memory_get_allocator(), and set_block_allocator().
Referenced by __memory_alloc(), and malloc().
{
     // Allocate a raw memory block
     __Allocator *allocator = memory_get_allocator(size, anObject);
     // if not enough sizes available
     if (allocator == nullptr) {
         return nullptr;
     }
     void *blockMemoryPtr = allocator->allocate();
     // if not enough quantity of that particular size available
     if (blockMemoryPtr == nullptr) {
         // check if higher sizes have some blocks available and
         // give a block from them if available
         size32_type currBlockSize = allocator->getBlockSize();
         if (currBlockSize < __allocators[MAX_ALLOCATORS - 1]->getBlockSize()) {
             return __memory_alloc(currBlockSize + 1, anObject);
         }
         return nullptr;
     }
     // Set the block Allocator* within the raw memory block region
     void *clientsMemoryPtr = set_block_allocator(blockMemoryPtr, allocator);
     return clientsMemoryPtr;
 }
void __memory_free (void * ptr)
Used internally not for client's use Use the
free
function
Frees a memory block previously allocated with
__memory_alloc
. The blocks are returned to the fixed block allocator that originally created it
Parameters
ptr a pointer to a block created with __memory_alloc
Definition at line 343 of file Memory.cpp.
References wlp::__Allocator::deallocate(), get_block_allocator(), and get_block_ptr().
Referenced by free().
{
     if (ptr == nullptr) {
         return;
     }
     // Extract the original allocator instance from the caller's block pointer
     __Allocator *allocator = get_block_allocator(ptr);
     // Convert the client pointer into the original raw block pointer
     void *blockPtr = get_block_ptr(ptr);
     // Deallocate the block
     allocator->deallocate(blockPtr);
 }
template<typename T , typename = typename wlp::enable_if<!wlp::is_pointer<T>::value, bool>::type, typename = typename wlp::enable_if<wlp::is_arithmetic<T>::value, bool>::type> T* calloc ()
This allocates memory of the size of the type provided. Memory allocated could be greater than what has been asked in order to accommodate fixed memory allocations. If there is not a sufficient memory available, it returns a
nullptr
This is only used for creating multiple block of memory and hence should be used for arrays. This is a special case of
malloc
which supports creation of an array of objects where you can use non default ctor
Precondition
this creates number of blocks of given type and it does not allocate memory by providing it number of bytes
Warning
should be avoided and used only where this is must
Template Parameters
T pointer array type
Args Argument types for non-fundamental Types
Parameters
args the arguments for
 Args @end types
   @tparam NonArrayType pointer non array type
   @param num number of elements needed
   @return address to memory allocated
  /
template<
        typename T,
        typename... Args,
        typename NonArrayType = typename wlp::remove_extent<T>::type,
        typename = typename wlp::enable_if<wlp::is_array<T>::value, bool>::type>
NonArrayType *arg_array_malloc(wlp::size_type num, Args... args) {
    void *memory = __memory_alloc(static_cast<wlp::size32_type>(sizeof(NonArrayType)) * num, true);
    uint16_t *objInfo = static_cast<uint16_t *>(memory);
     objInfo = static_cast<uint16_t>(num);
    char *pointer = reinterpret_cast<char *>(++objInfo);
    for (wlp::size_type i = 0; i < num; ++i) {
        new(pointer) NonArrayType(wlp::forward<Args>(args)...);
        pointer += sizeof(NonArrayType);
    }
    return reinterpret_cast<NonArrayType *>(objInfo);
};
Template Parameters
Type pointer type
Parameters
num number of blocks of size Type
Returns
address to memory allocated
Definition at line 192 of file Memory.h.
             {
     T *memory = malloc<T>();
     for (wlp::size32_type i = 0; i < sizeof(T); ++i) {
         memory[i] = 0;
     }
     return memory;
 };
template<typename T , typename NonArrayType = typename wlp::remove_extent<T>::type, typename = typename wlp::enable_if<!wlp::is_pointer<NonArrayType>::value, bool>::type, typename = typename wlp::enable_if<wlp::is_arithmetic<NonArrayType>::value, bool>::type, typename = typename wlp::enable_if<wlp::is_array<T>::value, bool>::type> NonArrayType* calloc (wlp::size_type num = 1)
Works exactly like malloc but initializes the memory by filling it with 0. This is the array version of
calloc
Template Parameters
Type pointer type
Parameters
num number of blocks of size Type
Returns
address to memory allocated
Definition at line 216 of file Memory.h.
{
     NonArrayType *memory = malloc<T>(num);
     for (wlp::size32_type i = 0; i < num; ++i) {
         memory[i] = 0;
     }
     return memory;
 };
template<typename Type > void free (Type *& ptr)
This frees the memory allocated. Only memory allocated using Memory will be freed and if another type of memory is provided, results are undefined
If an array of Objects is to be freed then provide free with a number along with the pointer to specify how many objects
Template Parameters
Type pointer type
Parameters
ptr address to memory that will be freed
Definition at line 237 of file Memory.h.
References __memory_free().
Referenced by wlp::ReferenceCount< T * >::destroy(), wlp::ReferenceCount< T * >::dispose(), operator delete(), operator delete[](), and wlp::DynamicString::set_value().
                       {
     if (!wlp::is_fundamental<Type>::value) {
         uint16_t *objInfo = reinterpret_cast<uint16_t *>(ptr);
         wlp::size_type numObjects = *(--objInfo);
         Type *pointer = ptr + numObjects - 1;
         for (wlp::size_type i = 0; i < numObjects; ++i) {
             pointer->~Type();
             --pointer;
         }
         __memory_free(reinterpret_cast<Type *>(objInfo));
     } else {
         __memory_free(ptr);
     }
     ptr = nullptr;
 }
template<typename Type > void free (Type *&& ptr)
Overload for rvalue pointers.
See Also
free<Type>
Template Parameters
Type
Parameters
ptr
Definition at line 264 of file Memory.h.
References __memory_free().
{
     if (!wlp::is_fundamental<Type>::value) {
         uint16_t *objInfo = reinterpret_cast<uint16_t *>(ptr);
         wlp::size_type numObjects = *(--objInfo);
         Type *pointer = ptr + numObjects - 1;
         for (wlp::size_type i = 0; i < numObjects; ++i) {
             pointer->~Type();
             --pointer;
         }
         __memory_free(reinterpret_cast<Type *>(objInfo));
     } else {
         __memory_free(ptr);
     }
 }
wlp::size32_type getFixedMemorySize (void * ptr)
Returns the size of fixed sized block that was provided for ptr
Parameters
ptr memory address for which memory block is being searched
Returns
the size of fixed size block
Definition at line 433 of file Memory.cpp.
References get_block_allocator(), and wlp::__Allocator::getBlockSize().
Referenced by realloc().
{
     if (ptr == nullptr)
         return 0;
     __Allocator *allocator = get_block_allocator(ptr);
     return allocator->getBlockSize();
 }
uint16_t getMaxAllocations ()
Returns the number Allocators (sizes) there are available in total
Returns
the number of allocators (sizes)
Definition at line 422 of file Memory.cpp.
{
     return MAX_ALLOCATORS;
 }
uint16_t getNumBlocks ()
Returns the number of blocks per Allocator if a pool is used
Returns
the number of blocks per Allocator
Definition at line 418 of file Memory.cpp.
{
     return NUM_BLOCKS;
 }
uint16_t getNumBlocksAvailable (wlp::size32_type blockSize)
Returns the total number of blocks that are available for blockSize. if blockSize does not exist then number will be 0
Parameters
blockSize blockSize size of the block being queried
Returns
the number blocks available for blockSize
Definition at line 404 of file Memory.cpp.
References __allocators.
{
     uint16_t numBlockAvail = 0;
     for (auto &allocator : __allocators) {
         if (allocator->getBlockSize() == blockSize) {
             uint32_t totalMemAvail = allocator->getTotalBlocks() * allocator->getBlockSize();
             uint32_t totalMemUsed = allocator->getNumAllocations() * allocator->getBlockSize();
             numBlockAvail += (totalMemAvail - totalMemUsed) / blockSize;
         }
     }
     return numBlockAvail;
 }
wlp::size_type getSmallestBlockSize ()
Returns the smallest block of memory that is given
Returns
the smallest block of memory
Definition at line 426 of file Memory.cpp.
References wlp::pow_const(), and REQUIRED_EXTRA_BUFFER.
Referenced by realloc().
{
     return static_cast<size_type>(pow_const(
             static_cast<size_type>(2),
             static_cast<size_type>(log2_const<size_type>(REQUIRED_EXTRA_BUFFER) + 1))
     );
 }
wlp::size32_type getTotalMemoryAvailable ()
Returns the total memory available to use (in bytes). If no pool is being used, this number can grow as more memory is borrowed otherwise this is the constant number
Returns
the total memory available
Definition at line 373 of file Memory.cpp.
References __allocators.
Referenced by getTotalMemoryFree().
{
     size32_type totalMemory = 0;
     for (auto &allocator : __allocators) {
         totalMemory += allocator->getTotalBlocks() * allocator->getBlockSize();
     }
     return totalMemory;
 }
wlp::size32_type getTotalMemoryFree ()
Returns the total memory that is free for use(in bytes)
Returns
the total memory usage
Definition at line 368 of file Memory.cpp.
References getTotalMemoryAvailable(), and getTotalMemoryUsed().
{
     return getTotalMemoryAvailable() - getTotalMemoryUsed();
 }
wlp::size32_type getTotalMemoryUsed ()
Returns the total memory being used by the program (in bytes)
Returns
the total memory usage
Definition at line 358 of file Memory.cpp.
References __allocators.
Referenced by getTotalMemoryFree().
{
     size32_type totalMemory = 0;
     for (auto &allocator : __allocators) {
         totalMemory += allocator->getNumAllocations() * allocator->getBlockSize();
     }
     return totalMemory;
 }
bool isSizeAvailable (wlp::size32_type blockSize)
Returns if this blockSize is available as a size that can be borrowed. If no pool is being used, this size will be created even if it does not exist but if a pool is used, this size's availability is fixed.
Precondition
note if this size does not exist in a pool a higher size can be provided
Parameters
blockSize size of the block being queried
Returns
true or false based on if the block exists
Definition at line 383 of file Memory.cpp.
References __allocators.
{
     for (auto &allocator : __allocators) {
         if (allocator->getBlockSize() == blockSize) {
             return true;
         }
     }
     return false;
 }
bool isSizeMemAvailable (wlp::size32_type blockSize)
Returns if this blockSize is available as a size that can be borrowed but it also has some blocks left that the user can borrow. Rest it functions the same as
isSizeAvailable()
Parameters
blockSize size of the block being queried
Returns
true or false based on if the block exists and has some blocks left
Definition at line 393 of file Memory.cpp.
References __allocators.
{
     for (auto &allocator : __allocators) {
         if (allocator->getBlockSize() == blockSize) {
             uint32_t totalMemAvail = allocator->getTotalBlocks() * allocator->getBlockSize();
             uint32_t totalMemUsed = allocator->getNumAllocations() * allocator->getBlockSize();
             return totalMemAvail - totalMemUsed != 0;
         }
     }
     return false;
 }
template<typename T , typename NonArrayType = typename wlp::remove_extent<T>::type, typename = typename wlp::enable_if<wlp::is_array<T>::value, bool>::type> NonArrayType* malloc (wlp::size_type num)
This allocates memory of the size of the type provided. Memory allocated could be greater than what has been asked in order to accommodate fixed memory allocations. If there is not a sufficient memory available, it returns a
nullptr
This is only used for creating single block of memory and not for array
Precondition
malloc creates number of blocks of given type and it does not allocate memory by providing it number of bytes
Template Parameters
T pointer type
Args Argument types for non-fundamental Types
Parameters
args the arguments for
 Args @end types
   @return address to memory allocated
  /
template<
        typename T,
        typename... Args,
        typename = typename wlp::enable_if<!wlp::is_array<T>::value, bool>::type>
T *malloc(Args... args) {
    if (wlp::is_fundamental<typename wlp::remove_extent<T>::type>::value) {
        void *memory = __memory_alloc(static_cast<wlp::size32_type>(sizeof(T)), false);
        return new(memory) T(wlp::forward<Args>(args)...);
    }
    void *memory = __memory_alloc(static_cast<wlp::size32_type>(sizeof(T)), true);
    uint16_t *objInfo = static_cast<uint16_t *>(memory);
     objInfo = static_cast<uint16_t>(1);
    return new(reinterpret_cast<char *>(++objInfo)) T(wlp::forward<Args>(args)...);
}
This is only used for creating multiple block of memory and hence should be used for arrays. This only supports default Ctors for objects
Precondition
malloc creates number of blocks of given type and it does not allocate memory by providing it number of bytes
Template Parameters
T pointer array type
NonArrayType pointer non array type
Parameters
num number of elements needed
Returns
address to memory allocated
Definition at line 119 of file Memory.h.
References __memory_alloc().
Referenced by operator new(), and operator new[]().
{
     if (wlp::is_fundamental<typename wlp::remove_extent<T>::type>::value) {
         void *memory = __memory_alloc(static_cast<wlp::size32_type>(sizeof(NonArrayType)) * num, false);
         return static_cast<NonArrayType *>(memory);
     }
     void *memory = __memory_alloc(static_cast<wlp::size32_type>(sizeof(NonArrayType)) * num, true);
     uint16_t *objInfo = static_cast<uint16_t *>(memory);
     *objInfo = static_cast<uint16_t>(num);
     char *pointer = reinterpret_cast<char *>(++objInfo);
     for (wlp::size_type i = 0; i < num; ++i) {
         new(pointer) NonArrayType();
         pointer += sizeof(NonArrayType);
     }
     return reinterpret_cast<NonArrayType *>(objInfo);
 };
template<typename Type , typename = typename wlp::enable_if<wlp::is_fundamental<Type>::value, bool>::type> Type* realloc (Type * ptr, wlp::size_type num = 1)
This reallocates the memory to accommodate the new size provided. The memory address has to be allocation from Memory otherwise results are undefined. If there is not a sufficient memory available, it returns a
nullptr
Precondition
realloc creates number of blocks of given type and it does not allocate memory by proving it number of bytes
Template Parameters
Type pointer type
Parameters
ptr address to memory to be reallocated
size number of blocks of size Type
Returns
address to new memory address
Definition at line 312 of file Memory.h.
References getFixedMemorySize(), and getSmallestBlockSize().
{
     if (num == 0) {
         free<Type>(ptr);
         return ptr;
     }
     wlp::size32_type oldMemSize = getFixedMemorySize(ptr);
     wlp::size32_type newMemSize = static_cast<wlp::size32_type>(sizeof(Type)) * num;
     if (oldMemSize >= newMemSize + getSmallestBlockSize()) {
         return ptr;
     }
     Type *newPtr = malloc<Type[]>(num);
     wlp::size32_type copySize = (oldMemSize < newMemSize) ? oldMemSize : newMemSize;
     memcpy(newPtr, ptr, copySize);
     free<Type>(ptr);
     return newPtr;
 }
Variable Documentation
MemoryInitDestroy __g_smemoryInitDestroy static
This code should never be called and/or touched. It is used internally
Definition at line 52 of file Memory.h.