Waterloop Wlib: wlp::Comparator< StaticString< tSize > > Struct Template Reference
wlp::Comparator< StaticString< tSize > > Struct Template Reference
#include <Comparator.h>
Public Member Functions
bool __lt__ (const StaticString< tSize > &s1, const StaticString< tSize > &s2) const
bool __le__ (const StaticString< tSize > &s1, const StaticString< tSize > &s2) const
bool __eq__ (const StaticString< tSize > &s1, const StaticString< tSize > &s2) const
bool __ne__ (const StaticString< tSize > &s1, const StaticString< tSize > &s2) const
bool __gt__ (const StaticString< tSize > &s1, const StaticString< tSize > &s2) const
bool __ge__ (const StaticString< tSize > &s1, const StaticString< tSize > &s2) const
Detailed Description
template<uint16_t tSize>
struct wlp::Comparator< StaticString< tSize > >
Template specialization for static strings.
Template Parameters
tSize static string size
Definition at line 125 of file Comparator.h.
Member Function Documentation
__eq__()
template<uint16_t tSize> bool wlp::Comparator< StaticString< tSize > >::__eq__ (const StaticString< tSize > & s1, const StaticString< tSize > & s2) const inline
Definition at line 134 of file Comparator.h.
References wlp::StaticString< tSize >::c_str().
{
             return strcmp(s1.c_str(), s2.c_str()) == 0;
         }
__ge__()
template<uint16_t tSize> bool wlp::Comparator< StaticString< tSize > >::__ge__ (const StaticString< tSize > & s1, const StaticString< tSize > & s2) const inline
Definition at line 146 of file Comparator.h.
References wlp::StaticString< tSize >::c_str().
{
             return strcmp(s1.c_str(), s2.c_str()) >= 0;
         }
__gt__()
template<uint16_t tSize> bool wlp::Comparator< StaticString< tSize > >::__gt__ (const StaticString< tSize > & s1, const StaticString< tSize > & s2) const inline
Definition at line 142 of file Comparator.h.
References wlp::StaticString< tSize >::c_str().
{
             return strcmp(s1.c_str(), s2.c_str()) > 0;
         }
__le__()
template<uint16_t tSize> bool wlp::Comparator< StaticString< tSize > >::__le__ (const StaticString< tSize > & s1, const StaticString< tSize > & s2) const inline
Definition at line 130 of file Comparator.h.
References wlp::StaticString< tSize >::c_str().
{
             return strcmp(s1.c_str(), s2.c_str()) <= 0;
         }
__lt__()
template<uint16_t tSize> bool wlp::Comparator< StaticString< tSize > >::__lt__ (const StaticString< tSize > & s1, const StaticString< tSize > & s2) const inline
Definition at line 126 of file Comparator.h.
References wlp::StaticString< tSize >::c_str().
{
             return strcmp(s1.c_str(), s2.c_str()) < 0;
         }
__ne__()
template<uint16_t tSize> bool wlp::Comparator< StaticString< tSize > >::__ne__ (const StaticString< tSize > & s1, const StaticString< tSize > & s2) const inline
Definition at line 138 of file Comparator.h.
References wlp::StaticString< tSize >::c_str().
{
             return strcmp(s1.c_str(), s2.c_str()) != 0;
         }
The documentation for this struct was generated from the following file:
stl/Comparator.h