Waterloop Wlib: wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp > Class Template Reference
wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp > Class Template Reference
#include <RedBlackTree.h>
Public Types
typedef Key key_type
typedef Val val_type
typedef Cmp comparator
typedef wlp::size_type size_type
typedef RedBlackTreeNode< Element > node_type
typedef RedBlackTree< Element,
Key, Val, GetKey, GetVal, Cmp > tree_type
typedef RedBlackTreeIterator
< Element, Val, Val &, Val
*, GetVal > iterator
typedef RedBlackTreeIterator
< Element, Val, const Val
&, const Val *, GetVal > const_iterator
typedef GetKey get_key
typedef GetVal get_val
Public Member Functions
RedBlackTree ()
RedBlackTree (const tree_type &)=delete
RedBlackTree (tree_type &&tree)
~RedBlackTree ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
bool empty () const
size_type size () const
size_type capacity () const
void clear () noexcept
template<typename E >
Pair< iterator, bool > insert_unique (E &&element)
template<typename E >
iterator insert_equal (E &&element)
void erase (const iterator &pos)
size_type erase (const key_type &key)
size_type erase (const iterator &first, const iterator &last)
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
size_type count (const key_type &key) const
iterator lower_bound (const key_type &key)
iterator upper_bound (const key_type &key)
const_iterator lower_bound (const key_type &key) const
const_iterator upper_bound (const key_type &key) const
Pair< iterator, iterator > equal_range (const key_type &key)
Pair< const_iterator,
const_iterator > equal_range (const key_type &val) const
tree_type & operator= (const tree_type &)=delete
tree_type & operator= (tree_type &&tree)
template<typename E >
RedBlackTree< Element, Key,
Val, GetKey, GetVal, Cmp >
::iterator insert (node_type *cur, node_type *carry, E &&element)
template<typename E >
Pair< typename RedBlackTree
< Element, Key, Val, GetKey,
GetVal, Cmp >::iterator, bool > insert_unique (E &&element)
template<typename E >
RedBlackTree< Element, Key,
Val, GetKey, GetVal, Cmp >
::iterator insert_equal (E &&element)
Protected Types
typedef RedBlackTreeColor color
Protected Member Functions
node_type * create_node ()
node_type * copy_node (node_type *node)
void destroy_node (node_type *node)
void rotateLeft (node_type *node, node_type *&root)
void rotateRight (node_type *node, node_type *&root)
void rebalance (node_type *node, node_type *&root)
node_type * erase_rebalance (node_type *node, node_type *&root, node_type *&leftmost, node_type *&rightmost)
template<typename E >
iterator insert (node_type *node, node_type *piv, E &&element)
void erase (node_type *root)
void empty_initialize ()
Protected Attributes
node_type * m_header
size_type m_size
comparator m_cmp
get_key m_get_key {}
Detailed Description
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>>
class wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >
Red black tree implementation, designed for use in associative container implementation, e.g.
Map
and
Set
. The insertion and deletion operations are based on those in CLRS.
The provided
Element
type must provide functions
get_key()
which returns a type of
Key
and a function
get_val()
which returns a type of
Val
. These details are dealt by implementing data structures such as
Map
and
Set
.
Template Parameters
Element element type which contains the key and val
Key node key type
Val node value type
Cmp key comparator type, which uses the default comparator
GetKey functor type used to get element key
GetVal functor type used to get element value
Definition at line 339 of file RedBlackTree.h.
Member Typedef Documentation
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef RedBlackTreeColor wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::color protected
Definition at line 353 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef Cmp wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::comparator
Definition at line 343 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef RedBlackTreeIterator<Element, Val, const Val &, const Val *, GetVal> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::const_iterator
Definition at line 348 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef GetKey wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::get_key
Definition at line 349 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef GetVal wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::get_val
Definition at line 350 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef RedBlackTreeIterator<Element, Val, Val &, Val *, GetVal> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::iterator
Definition at line 347 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef Key wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::key_type
Definition at line 341 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef RedBlackTreeNode<Element> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::node_type
Definition at line 345 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef wlp::size_type wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::size_type
Definition at line 344 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef RedBlackTree<Element, Key, Val, GetKey, GetVal, Cmp> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::tree_type
Definition at line 346 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> typedef Val wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::val_type
Definition at line 342 of file RedBlackTree.h.
Constructor & Destructor Documentation
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::RedBlackTree () inline explicit
Create an empty red black tree.
Parameters
n reserved space for nodes
Definition at line 488 of file RedBlackTree.h.
                 : m_header(nullptr),
                   m_size(0),
                   m_cmp() {
             m_header = create_node();
             empty_initialize();
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::RedBlackTree (const tree_type &) delete
Disable copy construction.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::RedBlackTree (tree_type && tree) inline
Move constructor.
Parameters
tree tree to move
Definition at line 506 of file RedBlackTree.h.
                 : m_header(move(tree.m_header)),
                   m_size(move(tree.m_size)),
                   m_cmp() {
             tree.m_header = nullptr;
             tree.m_size = 0;
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::~RedBlackTree () inline
Destructor.
Definition at line 517 of file RedBlackTree.h.
{
             clear();
             if (m_header) {
                 destroy_node(m_header);
             }
         }
Member Function Documentation
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::begin () inline
Returns
an iterator to the leftmost node in the tree
Definition at line 527 of file RedBlackTree.h.
Referenced by wlp::TreeSet< Key, Cmp >::begin(), and wlp::TreeMap< Key, Val, Cmp >::begin().
{
             return iterator(m_header->m_left);
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> const_iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::begin () const inline
Returns
a const iterator to the leftmost node in the tree
Definition at line 534 of file RedBlackTree.h.
{
             return const_iterator(m_header->m_left);
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> size_type wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::capacity () const inline
The maximum number of nodes that can be held in the tree. The tree is not intrinsically limited by any limit except that its size cannot exceed the defined size type.
Returns
the maximum value of size_type
Definition at line 575 of file RedBlackTree.h.
Referenced by wlp::TreeSet< Key, Cmp >::capacity(), and wlp::TreeMap< Key, Val, Cmp >::capacity().
{
             return static_cast<size_type>(-1);
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> void wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::clear () inline noexcept
Delete all the nodes in the tree such that it is now empty.
Definition at line 582 of file RedBlackTree.h.
Referenced by wlp::TreeSet< Key, Cmp >::clear(), wlp::TreeMap< Key, Val, Cmp >::clear(), wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::operator=(), and wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::~RedBlackTree().
{
             if (m_size > 0) {
                 erase(m_header->m_parent);
                 m_header->m_parent = nullptr;
                 m_header->m_left = m_header;
                 m_header->m_right = m_header;
                 m_size = 0;
             }
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> node_type* wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::copy_node (node_type * node) inline protected
Copy the contents of a node except for its paremt.
Parameters
node the tree node to copy
Returns
a copy of the node
Definition at line 388 of file RedBlackTree.h.
{
             node_type *copy = create_node();
             copy->m_element = node->m_element;
             copy->m_color = node->m_color;
             copy->m_left = node->m_left;
             copy->m_right = node->m_right;
             return copy;
         }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::size_type wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::count (const key_type & key) const
Obtain the number of nodes in the tree that have the provided key as their keys.
Parameters
key the key whose nodes to count
Returns
the number of nodes with the key
Definition at line 1207 of file RedBlackTree.h.
References wlp::count(), wlp::Pair< First, Second >::m_first, and wlp::Pair< First, Second >::m_second.
{
         Pair<const_iterator, const_iterator> res = equal_range(key);
         size_type count = 0;
         while (res.m_first != res.m_second) {
             ++res.m_first;
             ++count;
         }
         return count;
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> node_type* wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::create_node () inline protected
Allocate a new node.
Returns
pointer to the new node
Definition at line 378 of file RedBlackTree.h.
Referenced by wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::copy_node(), and wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::RedBlackTree().
{
             return malloc<node_type>();
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> void wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::destroy_node (node_type * node) inline protected
Deallocate the given node.
Parameters
node node to deallocate
Definition at line 402 of file RedBlackTree.h.
Referenced by wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::operator=(), and wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::~RedBlackTree().
{
             free<node_type>(node);
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> bool wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::empty () const inline
Returns
whether the tree has no nodes
Definition at line 557 of file RedBlackTree.h.
Referenced by wlp::TreeSet< Key, Cmp >::empty(), and wlp::TreeMap< Key, Val, Cmp >::empty().
{
             return m_size == 0;
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> void wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::empty_initialize () inline protected
Initialize the tree as empty, where the header node children are itself and the parent is null.
Definition at line 475 of file RedBlackTree.h.
Referenced by wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::RedBlackTree().
{
             m_header->m_color = color::RED;
             m_header->m_parent = nullptr;
             m_header->m_left = m_header;
             m_header->m_right = m_header;
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::end () inline
Returns
an iterator to the header node, which is the pass-the-end node after the rightmost node
Definition at line 542 of file RedBlackTree.h.
Referenced by wlp::TreeSet< Key, Cmp >::contains(), wlp::TreeMap< Key, Val, Cmp >::contains(), wlp::TreeSet< Key, Cmp >::end(), and wlp::TreeMap< Key, Val, Cmp >::end().
{
             return iterator(m_header);
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> const_iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::end () const inline
Returns
a const iterator to the header node, which is the pass-the-end node after the rightmost node
Definition at line 550 of file RedBlackTree.h.
{
             return const_iterator(m_header);
         }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > Pair< typename RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::iterator, typename RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::iterator > wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::equal_range (const key_type & key) inline
Obtain the range of nodes whose keys are equal to the provided key as per
lower_bound
and
upper_bound
.
Parameters
key the key whose range to get
Returns
a pair of iterators to the lower and upper bounds
Definition at line 1298 of file RedBlackTree.h.
{
         return Pair<iterator, iterator>(lower_bound(key), upper_bound(key));
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > Pair< typename RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::const_iterator, typename RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::const_iterator > wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::equal_range (const key_type & val) const inline
Obtain the range of nodes whose keys are equal to the provided key as per
lower_bound
and
upper_bound
.
Parameters
key the key whose range to get
Returns
a pair of const iterators to the lower and upper bounds
Definition at line 1310 of file RedBlackTree.h.
{
         return Pair<const_iterator, const_iterator>(lower_bound(key), upper_bound(key));
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > void wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::erase (node_type * root) inline protected
Delete the supplied node from the tree and all nodes beneath it.
Parameters
root the node to delete
Definition at line 1096 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_left, and wlp::RedBlackTreeNode< Element >::m_right.
Referenced by wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::clear(), wlp::TreeSet< Key, Cmp >::erase(), and wlp::TreeMap< Key, Val, Cmp >::erase().
{
         node_type *current;
         node_type *pre;
         node_type *tmp;
         if (!root) {
             return;
         }
         current = root;
         while (current) {
             if (!current->m_left) {
                 tmp = current;
                 current = current->m_right;
                 destroy_node(tmp);
             } else {
                 pre = current->m_left;
                 while (pre->m_right && pre->m_right != current) {
                     pre = pre->m_right;
                 }
                 if (!pre->m_right) {
                     pre->m_right = current;
                     current = current->m_left;
                 } else {
                     pre->m_right = nullptr;
                     tmp = current;
                     current = current->m_right;
                     destroy_node(tmp);
                 }
             }
         }
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > void wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::erase (const iterator & pos) inline
Delete the node pointed to by the provided iterator.
Parameters
pos iterator whose node to delete
Definition at line 1130 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = erase_rebalance(pos.m_node, m_header->m_parent, m_header->m_left, m_header->m_right);
         destroy_node(carry);
         --m_size;
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::size_type wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::erase (const key_type & key) inline
Erase all nodes in the tree that have the provided key. For containers not allowing multiple keys, the returned value is never greater than 1.
Parameters
key the key all of whose associated nodes are to be deleted
Returns
the number of deleted nodes
Definition at line 1140 of file RedBlackTree.h.
References wlp::Pair< First, Second >::m_first, and wlp::Pair< First, Second >::m_second.
{
         Pair<iterator, iterator> res = equal_range(cur);
         return erase(res.m_first, res.m_second);
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > size_type wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::erase (const iterator & first, const iterator & last) inline
Erase all nodes starting from the first iterator to before the last iterator, such that the nodes
[first, last)
are deleted and the size of the tree is reduced by
last - first
.
Parameters
first iterator to the first nodes to delete
last iterator to the last nodes to delete
Returns
the number of deleted nodes
Definition at line 1149 of file RedBlackTree.h.
References wlp::count().
{
         size_type count;
         if (first == begin() && last == end()) {
             count = m_size;
             clear();
         } else {
             count = 0;
             iterator tmp = first;
             while (tmp != last) {
                 erase(tmp++);
                 ++count;
             }
         }
         return count;
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::node_type * wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::erase_rebalance (node_type * node, node_type *& root, node_type *& leftmost, node_type *& rightmost) inline protected
Rebalance for erasure the given node. The node is eliminated from the tree during the rebalance and is prepared for deletion.
Parameters
node the node to delete
root the root node in the tree
leftmost the leftmost node in the tree
rightmost the right most node in the tree
Returns
a pointer to the node that can be deleted
Definition at line 862 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_color, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, wlp::RedBlackTreeNode< Element >::m_right, and wlp::swap().
{
         node_type *carry = node;
         node_type *cur = 0;
         node_type *cur_parent = 0;
         if (!carry->m_left) {
             // node has at most one non-null child
             // carry == node and cur might be null
             cur = carry->m_right;
         } else if (!carry->m_right) {
             // node has exactly one non-null child
             // carry == node and cur is not null
             cur = carry->m_left;
         } else {
             // node has two non-null children
             // set cur to node's successor and cur might be null
             carry = carry->m_right;
             while (carry->m_left) {
                 carry = carry->m_left;
             }
             cur = carry->m_right;
         }
         if (carry != node) {
             // Relink cur in place of node
             // cur is node's successor
             node->m_left->m_parent = carry;
             carry->m_left = node->m_left;
             if (carry != node->m_right) {
                 cur_parent = carry->m_parent;
                 if (cur) {
                     // carry must be a child of m_left
                     cur->m_parent = carry->m_parent;
                 }
                 carry->m_parent->m_left = cur;
                 carry->m_right = node->m_right;
                 node->m_right->m_parent = carry;
             } else {
                 cur_parent = carry;
             }
             if (root == node) {
                 root = carry;
             } else if (node->m_parent->m_left == node) {
                 node->m_parent->m_left = carry;
             } else {
                 node->m_parent->m_right = carry;
             }
             carry->m_parent = node->m_parent;
             swap(carry->m_color, node->m_color);
             // carry now points to node that is deleted
             carry = node;
         } else {
             // here carry == node
             cur_parent = carry->m_parent;
             if (cur) {
                 cur->m_parent = carry->m_parent;
             }
             if (root == node) {
                 root = cur;
             } else if (node->m_parent->m_left == node) {
                 node->m_parent->m_left = cur;
             } else {
                 node->m_parent->m_right = cur;
             }
             if (leftmost == node) {
                 // node->m_left might also be null
                 if (!node->m_right) {
                     // makes leftmost == header if node == root
                     leftmost = node->m_parent;
                 } else {
                     leftmost = node_type::find_minimum(cur);
                 }
             }
             if (rightmost == node) {
                 // node->m_rught might also be null
                 if (!node->m_left) {
                     // makes rightmost == header if node == root
                     rightmost = node->m_parent;
                 } else {
                     // cur == node->m_left
                     rightmost = node_type::find_maximum(cur);
                 }
             }
         }
         if (carry->m_color != color::RED) {
             while (cur != root && (!cur || cur->m_color == color::BLACK)) {
                 if (cur == cur_parent->m_left) {
                     node_type *aux = cur_parent->m_right;
                     if (aux->m_color == color::RED) {
                         aux->m_color = color::BLACK;
                         cur_parent->m_color = color::RED;
                         rotateLeft(cur_parent, root);
                         aux = cur_parent->m_right;
                     }
                     if ((!aux->m_left || aux->m_left->m_color == color::BLACK) &&
                         (!aux->m_right || aux->m_right->m_color == color::BLACK)) {
                         aux->m_color = color::RED;
                         cur = cur_parent;
                         cur_parent = cur_parent->m_parent;
                     } else {
                         if (!aux->m_right || aux->m_right->m_color == color::BLACK) {
                             if (aux->m_left) {
                                 aux->m_left->m_color = color::BLACK;
                             }
                             aux->m_color = color::RED;
                             rotateRight(aux, root);
                             aux = cur_parent->m_right;
                         }
                         aux->m_color = cur_parent->m_color;
                         cur_parent->m_color = color::BLACK;
                         if (aux->m_right) {
                             aux->m_right->m_color = color::BLACK;
                         }
                         rotateLeft(cur_parent, root);
                         break;
                     }
                 } else {
                     // same as above but with left and right switched
                     node_type *aux = cur_parent->m_left;
                     if (aux->m_color == color::RED) {
                         aux->m_color = color::BLACK;
                         cur_parent->m_color = color::RED;
                         rotateRight(cur_parent, root);
                         aux = cur_parent->m_left;
                     }
                     if ((!aux->m_right || aux->m_right->m_color == color::BLACK) &&
                         (!aux->m_left || aux->m_left->m_color == color::BLACK)) {
                         aux->m_color = color::RED;
                         cur = cur_parent;
                         cur_parent = cur_parent->m_parent;
                     } else {
                         if (!aux->m_left || aux->m_left->m_color == color::BLACK) {
                             if (aux->m_right) {
                                 aux->m_right->m_color = color::BLACK;
                             }
                             aux->m_color = color::RED;
                             rotateLeft(aux, root);
                             aux = cur_parent->m_left;
                         }
                         aux->m_color = cur_parent->m_color;
                         cur_parent->m_color = color::BLACK;
                         if (aux->m_left) {
                             aux->m_left->m_color = color::BLACK;
                         }
                         rotateRight(cur_parent, root);
                         break;
                     }
                 }
             }
             if (cur) {
                 cur->m_color = color::BLACK;
             }
         }
         return carry;
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::find (const key_type & key)
Obtain an iterator to the first node in the tree whose key matches the provided key. Returns pass-the-end if no node in the tree has the provided key.
Parameters
key the key for which to obtain the first node
Returns
iterator to the first node with the key or pass-the-end
Definition at line 1169 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
Referenced by wlp::TreeMap< Key, Val, Cmp >::at(), wlp::TreeSet< Key, Cmp >::contains(), wlp::TreeMap< Key, Val, Cmp >::contains(), wlp::TreeSet< Key, Cmp >::find(), and wlp::TreeMap< Key, Val, Cmp >::find().
{
         node_type *carry = m_header;
         node_type *cur = m_header->m_parent;
         while (cur) {
             if (!m_cmp.__lt__(m_get_key(cur->m_element), key)) {
                 carry = cur;
                 cur = cur->m_left;
             } else {
                 cur = cur->m_right;
             }
         }
         iterator tmp = iterator(carry);
         return (tmp == end() || m_cmp.__lt__(key, m_get_key(tmp.m_node->m_element))) ? end() : tmp;
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::const_iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::find (const key_type & key) const
Obtain a const iterator to the first node in the tree whose key matches the provided key. Returns pass-the-end if no node in the tree has the provided key.
Parameters
key the key for which to obtain the first node
Returns
const iterator to the first node with the key or pass-the-end
Definition at line 1188 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = m_header;
         node_type *cur = m_header->m_parent;
         while (cur) {
             if (!m_cmp.__lt__(m_get_key(cur->m_element), key)) {
                 carry = cur;
                 cur = cur->m_left;
             } else {
                 cur = cur->m_right;
             }
         }
         const_iterator tmp = const_iterator(carry);
         return (tmp == end() || m_cmp.__lt__(key, m_get_key(tmp.m_node->m_element))) ? end() : tmp;
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> template<typename E > iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::insert (node_type * node, node_type * piv, E && element) protected
Insert a given node at the pivot position, which will become the parent node of the inserted node.
Parameters
node the node to insert
piv the insertion pivot node
key the key to insert
val the value to insert
Returns
iterator to the inserted node
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> template<typename E > RedBlackTree<Element, Key, Val, GetKey, GetVal, Cmp>::iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::insert (node_type * cur, node_type * carry, E && element)
Definition at line 1025 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *node = create_node();
         node->m_element = forward<E>(element);
         if (carry == m_header || cur || m_cmp.__lt__(m_get_key(element), m_get_key(carry->m_element))) {
             carry->m_left = node;
             if (carry == m_header) {
                 m_header->m_parent = node;
                 m_header->m_right = node;
             } else if (carry == m_header->m_left) {
                 m_header->m_left = node;
             }
         } else {
             carry->m_right = node;
             if (carry == m_header->m_right) {
                 m_header->m_right = node;
             }
         }
         node->m_parent = carry;
         node->m_left = nullptr;
         node->m_right = nullptr;
         rebalance(node, m_header->m_parent);
         ++m_size;
         return iterator(node);
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> template<typename E > iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_equal (E && element)
Insert a value with a given key into the tree. This function will always insert the value, allowing duplicate keys.
Parameters
key key to insert
val value to insert
Returns
iterator to the inserted node
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> template<typename E > RedBlackTree<Element, Key, Val, GetKey, GetVal, Cmp>::iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_equal (E && element)
Definition at line 1083 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = m_header;
         node_type *cur = m_header->m_parent;
         while (cur) {
             carry = cur;
             cur = m_cmp.__lt__(m_get_key(element), m_get_key(cur->m_element)) ? cur->m_left : cur->m_right;
         }
         return insert(cur, carry, forward<E>(element));
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> template<typename E > Pair<iterator, bool> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_unique (E && element)
Insert a value with a given key into the tree. This function will insert the value if its key does not exist and fail if the key already exists.
Parameters
key key to insert
val value to insert
Returns
a pair consisting of an iterator to the inserted node or the node that prevented insertion and a flag indicating whether insertion occurred
Referenced by wlp::TreeSet< Key, Cmp >::insert(), wlp::TreeMap< Key, Val, Cmp >::insert(), wlp::TreeMap< Key, Val, Cmp >::insert_or_assign(), and wlp::TreeMap< Key, Val, Cmp >::operator[]().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> template<typename E > Pair<typename RedBlackTree<Element, Key, Val, GetKey, GetVal, Cmp>::iterator, bool> wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::insert_unique (E && element)
Definition at line 1055 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeIterator< Element, Val, Ref, Ptr, GetVal >::m_node, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = m_header;
         node_type *cur = m_header->m_parent;
         bool compare = true;
         while (cur) {
             carry = cur;
             compare = m_cmp.__lt__(m_get_key(element), m_get_key(cur->m_element));
             cur = compare ? cur->m_left : cur->m_right;
         }
         iterator tmp = iterator(carry);
         if (compare) {
             if (tmp == begin()) {
                 return Pair<iterator, bool>(insert(cur, carry, forward<E>(element)), true);
             } else {
                 --tmp;
             }
         }
         if (m_cmp.__lt__(m_get_key(tmp.m_node->m_element), m_get_key(element))) {
             return Pair<iterator, bool>(insert(cur, carry, forward<E>(element)), true);
         }
         return Pair<iterator, bool>(tmp, false);
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::lower_bound (const key_type & key)
Obtain an iterator to the first node in the tree by natural order that has the provided key. Returns pass-the-end if there are no nodes with the provided key.
Precondition
The returned value is such that all nodes with the provided key are in the range
[lower_bound(key), upper_bound(key))
.
Parameters
key the key whose first node to find
Returns
iterator to the first node with the key
Definition at line 1221 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = m_header;
         node_type *cur = m_header->m_parent;
         while (cur) {
             if (!m_cmp.__lt__(m_get_key(cur->m_element), key)) {
                 carry = cur;
                 cur = cur->m_left;
             } else {
                 cur = cur->m_right;
             }
         }
         return iterator(carry);
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::const_iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::lower_bound (const key_type & key) const
Obtain a const iterator to the first node in the tree by natural order that has the provided key. Returns pass-the-end if there are no nodes with the provided key.
Precondition
The returned value is such that all nodes with the provided key are in the range
[lower_bound(key), upper_bound(key))
.
Parameters
key the key whose first node to find
Returns
const iterator to the first node with the key
Definition at line 1258 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = m_header;
         node_type *cur = m_header->m_parent;
         while (cur) {
             if (!m_cmp.__lt__(m_get_key(cur->m_element), key)) {
                 carry = cur;
                 cur = cur->m_left;
             } else {
                 cur = cur->m_right;
             }
         }
         return const_iterator(carry);
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> tree_type& wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::operator= (const tree_type &) delete
Disable copy assignemnt.
Returns
reference to this tree
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> tree_type& wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::operator= (tree_type && tree) inline
Move assignment operator. Resources in this tree are freed and replaced by moving those from the assigned tree. The assigned tree is prepared for destruction.
Parameters
tree the tree to move
Returns
reference to this tree
Definition at line 761 of file RedBlackTree.h.
{
             clear();
             destroy_node(m_header);
             m_size = move(tree.m_size);
             m_header = move(tree.m_header);
             tree.m_size = 0;
             tree.m_header = 0;
             return *this;
         }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > void wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::rebalance (node_type * node, node_type *& root) inline protected
Perform red-black tree rebalance of a potentially erroneous node starting from the given root.
Parameters
node the node to rebalance
root the rebalance root node
Definition at line 818 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_color, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node->m_color = color::RED;
         while (node != root && node->m_parent->m_color == color::RED) {
             if (node->m_parent == node->m_parent->m_parent->m_left) {
                 node_type *carry = node->m_parent->m_parent->m_right;
                 if (carry && carry->m_color == color::RED) {
                     node->m_parent->m_color = color::BLACK;
                     carry->m_color = color::BLACK;
                     node->m_parent->m_parent->m_color = color::RED;
                     node = node->m_parent->m_parent;
                 } else {
                     if (node == node->m_parent->m_right) {
                         node = node->m_parent;
                         rotateLeft(node, root);
                     }
                     node->m_parent->m_color = color::BLACK;
                     node->m_parent->m_parent->m_color = color::RED;
                     rotateRight(node->m_parent->m_parent, root);
                 }
             } else {
                 node_type *carry = node->m_parent->m_parent->m_left;
                 if (carry && carry->m_color == color::RED) {
                     node->m_parent->m_color = color::BLACK;
                     carry->m_color = color::BLACK;
                     node->m_parent->m_parent->m_color = color::RED;
                     node = node->m_parent->m_parent;
                 } else {
                     if (node == node->m_parent->m_left) {
                         node = node->m_parent;
                         rotateRight(node, root);
                     }
                     node->m_parent->m_color = color::BLACK;
                     node->m_parent->m_parent->m_color = color::RED;
                     rotateLeft(node->m_parent->m_parent, root);
                 }
             }
         }
         root->m_color = color::BLACK;
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > void wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::rotateLeft (node_type * node, node_type *& root) inline protected
Perform red-black tree left rotation of the specified node about the specified root.
Parameters
node the node to rotate
root the rotate root node
Definition at line 776 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = node->m_right;
         node->m_right = carry->m_left;
         if (carry->m_left) {
             carry->m_left->m_parent = node;
         }
         carry->m_parent = node->m_parent;
         if (node == root) {
             root = carry;
         } else if (node == node->m_parent->m_left) {
             node->m_parent->m_left = carry;
         } else {
             node->m_parent->m_right = carry;
         }
         carry->m_left = node;
         node->m_parent = carry;
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > void wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::rotateRight (node_type * node, node_type *& root) inline protected
Perform red-black tree right rotation of the specified node about the specified root.
Parameters
node the node to rotate
root the rotate root node
Definition at line 797 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = node->m_left;
         node->m_left = carry->m_right;
         if (carry->m_right) {
             carry->m_right->m_parent = node;
         }
         carry->m_parent = node->m_parent;
         if (node == root) {
             root = carry;
         } else if (node == node->m_parent->m_right) {
             node->m_parent->m_right = carry;
         } else {
             node->m_parent->m_left = carry;
         }
         carry->m_right = node;
         node->m_parent = carry;
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> size_type wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::size () const inline
Returns
the number of nodes in the tree
Definition at line 564 of file RedBlackTree.h.
Referenced by wlp::TreeSet< Key, Cmp >::size(), and wlp::TreeMap< Key, Val, Cmp >::size().
{
             return m_size;
         }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::upper_bound (const key_type & key)
Obtain an iterator to the node right after the last node in the tree by natural order that has the provided key. May return pass-the-end if the key is the largest key in the tree, or if the key is not found.
Precondition
The returned value is such that all nodes with the provided key are in the range
[lower_bound(key), upper_bound(key))
.
Parameters
key the key whose last node to find
Returns
iterator to the node right after the last node
Definition at line 1239 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = m_header;
         node_type *cur = m_header->m_parent;
         while (cur) {
             if (m_cmp.__lt__(key, m_get_key(cur->m_element))) {
                 carry = cur;
                 cur = cur->m_left;
             } else {
                 cur = cur->m_right;
             }
         }
         return iterator(carry);
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Cmp > RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::const_iterator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::upper_bound (const key_type & key) const
Obtain a const iterator to the node right after the last node in the tree by natural order that has the provided key. May return pass-the-end if the key is the largest key in the tree, or if the key is not found.
Precondition
The returned value is such that all nodes with the provided key are in the range
[lower_bound(key), upper_bound(key))
.
Parameters
key the key whose last node to find
Returns
const iterator to the node right after the last node
Definition at line 1276 of file RedBlackTree.h.
References wlp::RedBlackTreeNode< Element >::m_element, wlp::RedBlackTreeNode< Element >::m_left, wlp::RedBlackTreeNode< Element >::m_parent, and wlp::RedBlackTreeNode< Element >::m_right.
{
         node_type *carry = m_header;
         node_type *cur = m_header->m_parent;
         while (cur) {
             if (m_cmp.__lt__(key, m_get_key(cur->m_element))) {
                 carry = cur;
                 cur = cur->m_left;
             } else {
                 cur = cur->m_right;
             }
         }
         return const_iterator(carry);
     }
Field Documentation
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> comparator wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::m_cmp protected
Class comparator instance.
Definition at line 367 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> get_key wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::m_get_key {} protected
Functor used to obtain element key.
Definition at line 371 of file RedBlackTree.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> node_type* wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::m_header protected
Header node, which maintains reference to the leftmost node, the rightmost node, and the root node.
Definition at line 359 of file RedBlackTree.h.
Referenced by wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::begin(), wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::clear(), wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::empty_initialize(), wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::end(), wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::operator=(), wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::RedBlackTree(), and wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::~RedBlackTree().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Cmp = Comparator <Key>> size_type wlp::RedBlackTree< Element, Key, Val, GetKey, GetVal, Cmp >::m_size protected
The number of nodes currently in the tree.
Definition at line 363 of file RedBlackTree.h.
Referenced by wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::clear(), wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::empty(), wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::operator=(), and wlp::RedBlackTree< Tuple< Key, Val >, Key, Val, MapGetKey< Key, Val >, MapGetVal< Key, Val >, Cmp >::size().
The documentation for this class was generated from the following file:
stl/RedBlackTree.h