Waterloop Wlib: wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals > Class Template Reference
wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals > Class Template Reference
#include <HashTable.h>
Public Types
typedef hash_table< Element,
Key, Val, GetKey, GetVal,
Hasher, Equals > table_type
typedef HashTableNode< Element > node_type
typedef HashTableIterator
< Element, Key, Val, Val
&, Val *, GetKey, GetVal,
Hasher, Equals > iterator
typedef HashTableIterator
< Element, Key, Val, const Val
&, const Val *, GetKey, GetVal,
Hasher, Equals > const_iterator
typedef Element element_type
typedef Key key_type
typedef Val val_type
typedef GetKey get_key
typedef GetVal get_value
typedef wlp::size_type size_type
typedef uint8_t percent_type
typedef Hasher hash_function
typedef Equals key_equals
Public Member Functions
hash_table (size_type n=12, percent_type max_load=75)
hash_table (const table_type &)=delete
hash_table (table_type &&table)
~hash_table ()
size_type size () const
size_type capacity () const
percent_type max_load () const
bool empty () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
template<typename E >
pair< iterator, bool > insert_unique (E &&element)
template<typename E >
iterator insert_equal (E &&element)
template<typename E >
element_type & find_or_insert (E &&element)
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
size_type count (const key_type &key) const
pair< iterator, iterator > equal_range (const key_type &key)
pair< const_iterator,
const_iterator > equal_range (const key_type &key) const
void erase (const iterator &pos)
size_type erase (const key_type &key)
void clear () noexcept
table_type & operator= (const table_type &)=delete
table_type & operator= (table_type &&table)
template<typename E >
pair< typename hash_table
< Element, Key, Val, GetKey,
GetVal, Hasher, Equals >
::iterator, bool > insert_unique (E &&element)
template<typename E >
hash_table< Element, Key, Val,
GetKey, GetVal, Hasher, Equals >
::iterator insert_equal (E &&element)
template<typename E >
hash_table< Element, Key, Val,
GetKey, GetVal, Hasher, Equals >
::element_type & find_or_insert (E &&element)
Private Member Functions
void init_buckets (size_type n)
size_type bucket_index (const key_type &key, size_type capacity) const
size_type hash (const key_type &key) const
void ensure_capacity ()
Private Attributes
node_type ** m_buckets
size_type m_size
size_type m_capacity
percent_type m_max_load
hash_function m_hash_function {}
key_equals m_key_equals {}
get_key m_get_key {}
Friends
struct HashTableIterator< Element, Key, Val, Val &, Val *, GetKey, GetVal, Hasher, Equals >
struct HashTableIterator< Element, Key, Val, const Val &, const Val *, GetKey, GetVal, Hasher, Equals >
Detailed Description
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals>
class wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >
Definition at line 18 of file HashTable.h.
Member Typedef Documentation
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef HashTableIterator< Element, Key, Val, const Val &, const Val *, GetKey, GetVal, Hasher, Equals > wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::const_iterator
Definition at line 177 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef Element wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::element_type
Definition at line 179 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef GetKey wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::get_key
Definition at line 182 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef GetVal wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::get_value
Definition at line 183 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef Hasher wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::hash_function
Definition at line 188 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef HashTableIterator< Element, Key, Val, Val &, Val *, GetKey, GetVal, Hasher, Equals > wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::iterator
Definition at line 171 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef Equals wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::key_equals
Definition at line 189 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef Key wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::key_type
Definition at line 180 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef HashTableNode<Element> wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::node_type
Definition at line 165 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef uint8_t wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::percent_type
Definition at line 186 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef wlp::size_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::size_type
Definition at line 185 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef hash_table<Element, Key, Val, GetKey, GetVal, Hasher, Equals> wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::table_type
Definition at line 164 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> typedef Val wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::val_type
Definition at line 181 of file HashTable.h.
Constructor & Destructor Documentation
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::hash_table (size_type n = 12, percent_type max_load = 75) inline explicit
Definition at line 238 of file HashTable.h.
                 : m_size(0),
                   m_capacity(n),
                   m_max_load(max_load) {
             init_buckets(n);
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::hash_table (const table_type &) delete
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::hash_table (table_type && table) inline
Definition at line 247 of file HashTable.h.
                 : m_buckets(table.m_buckets),
                   m_size(table.m_size),
                   m_capacity(table.m_capacity),
                   m_max_load(table.m_max_load) {
             table.m_buckets = nullptr;
             table.m_size = 0;
             table.m_capacity = 0;
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::~hash_table () inline
Definition at line 257 of file HashTable.h.
                       {
             if (!m_buckets) {
                 return;
             }
             clear();
             free<node_type *>(m_buckets);
             m_buckets = nullptr;
         }
Member Function Documentation
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> iterator wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::begin () inline
Definition at line 296 of file HashTable.h.
Referenced by wlp::hash_map< Key, Val, Hasher, Equals >::begin(), and wlp::hash_set< Key, Hasher, Equals >::begin().
{
             for (size_type n = 0; n < m_capacity; ++n) {
                 if (m_buckets[n]) {
                     return iterator(m_buckets[n], this);
                 }
             }
             return end();
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> const_iterator wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::begin () const inline
Definition at line 305 of file HashTable.h.
{
             for (size_type n = 0; n < m_capacity; ++n) {
                 if (m_buckets[n]) {
                     return const_iterator(m_buckets[n], this);
                 }
             }
             return end();
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> size_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::bucket_index (const key_type & key, size_type capacity) const inline private
Definition at line 269 of file HashTable.h.
{
             return m_hash_function(key) % capacity;
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> size_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::capacity () const inline
Definition at line 284 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::bucket_index(), wlp::hash_set< Key, Hasher, Equals >::capacity(), and wlp::hash_map< Key, Val, Hasher, Equals >::capacity().
{
             return m_capacity;
         }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Hasher , typename Equals > void wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::clear () noexcept
Definition at line 615 of file HashTable.h.
References wlp::HashTableNode< Element >::m_next.
Referenced by wlp::hash_map< Key, Val, Hasher, Equals >::clear(), wlp::hash_set< Key, Hasher, Equals >::clear(), wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::operator=(), and wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::~hash_table().
                      {
         for (size_type i = 0; i < m_capacity; ++i) {
             node_type *cur = m_buckets[i];
             node_type *next;
             while (cur) {
                 next = cur->m_next;
                 free<node_type>(cur);
                 cur = next;
             }
             m_buckets[i] = nullptr;
         }
         m_size = 0;
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> size_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::count (const key_type & key) const inline
Definition at line 349 of file HashTable.h.
{
             size_type n = hash(key);
             size_type result = 0;
             for (const node_type *cur = m_buckets[n]; cur; cur = cur->m_next) {
                 if (m_key_equals(m_get_key(cur->m_element), key)) {
                     ++result;
                 }
             }
             return result;
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> bool wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::empty () const inline
Definition at line 292 of file HashTable.h.
Referenced by wlp::hash_set< Key, Hasher, Equals >::empty(), and wlp::hash_map< Key, Val, Hasher, Equals >::empty().
{
             return m_size == 0;
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> iterator wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::end () inline
Definition at line 314 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::begin(), wlp::hash_set< Key, Hasher, Equals >::contains(), wlp::hash_map< Key, Val, Hasher, Equals >::contains(), wlp::hash_set< Key, Hasher, Equals >::end(), wlp::hash_map< Key, Val, Hasher, Equals >::end(), and wlp::hash_map< Key, Val, Hasher, Equals >::insert_or_assign().
{
             return iterator(nullptr, this);
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> const_iterator wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::end () const inline
Definition at line 318 of file HashTable.h.
{
             return const_iterator(nullptr, this);
         }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Hasher , typename Equals > void wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::ensure_capacity () private
Definition at line 642 of file HashTable.h.
References wlp::HashTableNode< Element >::m_element, and wlp::HashTableNode< Element >::m_next.
                       {
         if (m_size * 100 < m_max_load * m_capacity) {
             return;
         }
         size_type new_capacity = static_cast<size_type>(m_capacity * 2);
         node_type **new_buckets = malloc<node_type *[]>(new_capacity);
         memset(new_buckets, 0, new_capacity * sizeof(node_type *));
         for (size_type i = 0; i < m_capacity; ++i) {
             if (!m_buckets[i]) {
                 continue;
             }
             node_type *cur = m_buckets[i];
             while (cur) {
                 size_type k = bucket_index(m_get_key(cur->m_element), new_capacity);
                 node_type *first = new_buckets[k];
                 node_type *next = cur->m_next;
                 cur->m_next = first;
                 new_buckets[k] = cur;
                 cur = next;
             }
         }
         free<node_type *>(m_buckets);
         m_buckets = new_buckets;
         m_capacity = new_capacity;
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Hasher , typename Equals > pair< typename hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::iterator, typename hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::iterator > wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::equal_range (const key_type & key)
Definition at line 500 of file HashTable.h.
References wlp::end(), and wlp::HashTableNode< Element >::m_next.
{
         typedef pair<iterator, iterator> ret_type;
         const size_type n = hash(key);
         for (node_type *first = m_buckets[n]; first; first = first->m_next) {
             if (m_key_equals(m_get_key(first->m_element), key)) {
                 for (node_type *cur = first->m_next; cur; cur = cur->m_next) {
                     if (!m_key_equals(m_get_key(cur->m_element), key)) {
                         return ret_type(iterator(first, this), iterator(cur, this));
                     }
                 }
                 for (size_type m = static_cast<unsigned short>(n + 1); m < m_size; ++m) {
                     if (m_buckets[m]) {
                         return ret_type(iterator(first, this), iterator(m_buckets[m], this));
                     }
                 }
                 return ret_type(iterator(first, this), end());
             }
         }
         return ret_type(end(), end());
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Hasher , typename Equals > pair< typename hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::const_iterator, typename hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::const_iterator > wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::equal_range (const key_type & key) const
Definition at line 527 of file HashTable.h.
References wlp::end(), and wlp::HashTableNode< Element >::m_next.
{
         typedef pair<const_iterator, const_iterator> ret_type;
         const size_type n = hash(key);
         for (node_type *first = m_buckets[n]; first; first = first->m_next) {
             if (m_key_equals(m_get_key(first->m_element), key)) {
                 for (node_type *cur = first->m_next; cur; cur = cur->m_next) {
                     if (!m_key_equals(m_get_key(cur->m_element), key)) {
                         return ret_type(const_iterator(first, this), const_iterator(cur, this));
                     }
                 }
                 for (size_type m = static_cast<unsigned short>(n + 1); m < m_size; ++m) {
                     if (m_buckets[m]) {
                         return ret_type(const_iterator(first, this), const_iterator(m_buckets[m], this));
                     }
                 }
                 return ret_type(const_iterator(first, this), end());
             }
         }
         return ret_type(end(), end());
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Hasher , typename Equals > void wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::erase (const iterator & pos)
Definition at line 552 of file HashTable.h.
References wlp::HashTableNode< Element >::m_element, wlp::HashTableNode< Element >::m_next, and wlp::HashTableIterator< Element, Key, Val, Ref, Ptr, GetKey, GetVal, Hasher, Equals >::m_node.
Referenced by wlp::hash_map< Key, Val, Hasher, Equals >::erase(), and wlp::hash_set< Key, Hasher, Equals >::erase().
{
         node_type *node = it.m_node;
         if (node) {
             const size_type n = hash(m_get_key(node->m_element));
             node_type *cur = m_buckets[n];
             if (cur == node) {
                 m_buckets[n] = cur->m_next;
                 free<node_type>(cur);
                 --m_size;
                 return;
             }
             node_type *next = cur->m_next;
             while (next) {
                 if (next == node) {
                     cur->m_next = next->m_next;
                     free<node_type>(next);
                     --m_size;
                     break;
                 }
                 cur = next;
                 next = cur->m_next;
             }
         }
     }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Hasher , typename Equals > hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::size_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::erase (const key_type & key)
Definition at line 582 of file HashTable.h.
References wlp::HashTableNode< Element >::m_element, and wlp::HashTableNode< Element >::m_next.
{
         const size_type n = hash(key);
         node_type *first = m_buckets[n];
         size_type erased = 0;
         if (first) {
             node_type *cur = first;
             node_type *next = cur->m_next;
             while (next) {
                 if (m_key_equals(m_get_key(next->m_element), key)) {
                     cur->m_next = next->m_next;
                     free<node_type>(next);
                     next = cur->m_next;
                     ++erased;
                     --m_size;
                 } else {
                     cur = next;
                     next = cur->m_next;
                 }
             }
             if (m_key_equals(m_get_key(first->m_element), key)) {
                 m_buckets[n] = first->m_next;
                 free<node_type>(first);
                 ++erased;
                 --m_size;
             }
         }
         return erased;
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> iterator wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find (const key_type & key) inline
Definition at line 331 of file HashTable.h.
Referenced by wlp::hash_map< Key, Val, Hasher, Equals >::at(), wlp::hash_set< Key, Hasher, Equals >::contains(), wlp::hash_map< Key, Val, Hasher, Equals >::contains(), wlp::hash_set< Key, Hasher, Equals >::find(), wlp::hash_map< Key, Val, Hasher, Equals >::find(), and wlp::hash_map< Key, Val, Hasher, Equals >::insert_or_assign().
{
             size_type n = hash(key);
             node_type *first;
             for (first = m_buckets[n];
                  first && !m_key_equals(m_get_key(first->m_element), key);
                  first = first->m_next) {}
             return iterator(first, this);
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> const_iterator wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find (const key_type & key) const inline
Definition at line 340 of file HashTable.h.
{
             size_type n = hash(key);
             node_type *first;
             for (first = m_buckets[n];
                  first && !m_key_equals(m_get_key(first->m_element), key);
                  first = first->m_next) {}
             return const_iterator(first, this);
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> template<typename E > element_type& wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find_or_insert (E && element)
Referenced by wlp::hash_map< Key, Val, Hasher, Equals >::operator[]().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> template<typename E > hash_table<Element, Key, Val, GetKey, GetVal, Hasher, Equals>::element_type& wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::find_or_insert (E && element)
Definition at line 477 of file HashTable.h.
References wlp::HashTableNode< Element >::m_element, and wlp::HashTableNode< Element >::m_next.
{
         ensure_capacity();
         size_type n = hash(m_get_key(element));
         node_type *first = m_buckets[n];
         for (node_type *cur = first; cur; cur = cur->m_next) {
             if (m_key_equals(m_get_key(cur->m_element), m_get_key(element))) {
                 return cur->m_element;
             }
         }
         node_type *tmp = malloc<node_type>();
         tmp->m_element = forward<E>(element);
         tmp->m_next = first;
         m_buckets[n] = tmp;
         ++m_size;
         return tmp->m_element;
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> size_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::hash (const key_type & key) const inline private
Definition at line 273 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::count(), and wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::find().
{
             return m_hash_function(key) % m_capacity;
         }
template<typename Element , typename Key , typename Val , typename GetKey , typename GetVal , typename Hasher , typename Equals > void wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::init_buckets (size_type n) private
Definition at line 633 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::hash_table().
{
         m_buckets = malloc<node_type *[]>(n);
         memset(m_buckets, 0, n * sizeof(node_type *));
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> template<typename E > iterator wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::insert_equal (E && element)
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> template<typename E > hash_table<Element, Key, Val, GetKey, GetVal, Hasher, Equals>::iterator wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::insert_equal (E && element)
Definition at line 449 of file HashTable.h.
References wlp::HashTableNode< Element >::m_element, and wlp::HashTableNode< Element >::m_next.
{
         ensure_capacity();
         const size_type n = hash(m_get_key(element));
         node_type *first = m_buckets[n];
         for (node_type *cur = first; cur; cur = cur->m_next) {
             if (m_key_equals(m_get_key(cur->m_element), m_get_key(element))) {
                 node_type *tmp = malloc<node_type>();
                 tmp->m_element = forward<E>(element);
                 tmp->m_next = cur->m_next;
                 cur->m_next = tmp;
                 ++m_size;
                 return iterator(tmp, this);
             }
         }
         node_type *tmp = malloc<node_type>();
         tmp->m_element = forward<E>(element);
         tmp->m_next = first;
         m_buckets[n] = tmp;
         ++m_size;
         return iterator(tmp, this);
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> template<typename E > pair<iterator, bool> wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::insert_unique (E && element)
Referenced by wlp::hash_map< Key, Val, Hasher, Equals >::insert(), wlp::hash_set< Key, Hasher, Equals >::insert(), and wlp::hash_map< Key, Val, Hasher, Equals >::insert_or_assign().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> template<typename E > pair<typename hash_table<Element, Key, Val, GetKey, GetVal, Hasher, Equals>::iterator, bool> wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::insert_unique (E && element)
Definition at line 426 of file HashTable.h.
References wlp::HashTableNode< Element >::m_element, and wlp::HashTableNode< Element >::m_next.
{
         ensure_capacity();
         const size_type n = hash(m_get_key(element));
         node_type *first = m_buckets[n];
         for (node_type *cur = first; cur; cur = cur->m_next) {
             if (m_key_equals(m_get_key(cur->m_element), m_get_key(element))) {
                 return pair<iterator, bool>(iterator(cur, this), false);
             }
         }
         node_type *tmp = malloc<node_type>();
         tmp->m_element = forward<E>(element);
         tmp->m_next = first;
         m_buckets[n] = tmp;
         ++m_size;
         return pair<iterator, bool>(iterator(tmp, this), true);
     }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> percent_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::max_load () const inline
Definition at line 288 of file HashTable.h.
Referenced by wlp::hash_set< Key, Hasher, Equals >::max_load(), and wlp::hash_map< Key, Val, Hasher, Equals >::max_load().
{
             return m_max_load;
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> table_type& wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::operator= (const table_type &) delete
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> table_type& wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::operator= (table_type && table) inline
Definition at line 372 of file HashTable.h.
{
             if (m_buckets) {
                 clear();
                 free<node_type *>(m_buckets);
             }
             m_buckets = table.m_buckets;
             m_size = table.m_size;
             m_capacity = table.m_capacity;
             table.m_buckets = nullptr;
             table.m_size = 0;
             table.m_capacity = 0;
             return *this;
         }
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> size_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::size () const inline
Definition at line 280 of file HashTable.h.
Referenced by wlp::hash_set< Key, Hasher, Equals >::size(), and wlp::hash_map< Key, Val, Hasher, Equals >::size().
{
             return m_size;
         }
Friends And Related Function Documentation
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> friend struct HashTableIterator< Element, Key, Val,const Val &, const Val *,GetKey, GetVal,Hasher, Equals > friend
Definition at line 202 of file HashTable.h.
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> friend struct HashTableIterator< Element, Key, Val,Val &, Val *,GetKey, GetVal,Hasher, Equals > friend
Definition at line 196 of file HashTable.h.
Field Documentation
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> node_type** wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::m_buckets private
Hash map backing array.
Definition at line 208 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::begin(), wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::count(), wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::find(), wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::operator=(), and wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::~hash_table().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> size_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::m_capacity private
The maximum size of the hash table. This number represents the current capacity of the backing array.
Definition at line 218 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::begin(), wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::capacity(), wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::hash(), and wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::operator=().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> get_key wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::m_get_key {} private
Functor instance to obtain key;
Definition at line 235 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::count(), and wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::find().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> hash_function wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::m_hash_function {} private
Hash function functor instance.
Definition at line 227 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::bucket_index(), and wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::hash().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> key_equals wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::m_key_equals {} private
Key equals functor instance.
Definition at line 231 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::count(), and wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::find().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> percent_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::m_max_load private
The max load factor of the hash table before rehashing.
Definition at line 222 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::max_load().
template<typename Element, typename Key, typename Val, typename GetKey, typename GetVal, typename Hasher, typename Equals> size_type wlp::hash_table< Element, Key, Val, GetKey, GetVal, Hasher, Equals >::m_size private
Number of elements currently in the map.
Definition at line 213 of file HashTable.h.
Referenced by wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::empty(), wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::operator=(), and wlp::hash_table< Key, Key, Key, SetGetKey< Key >, SetGetVal< Key >, Hasher, Equals >::size().
The documentation for this class was generated from the following file:
wlib/stl/HashTable.h