Waterloop Wlib: wlp::ChainHashSet< Key, Hash, Equal > Class Template Reference
wlp::ChainHashSet< Key, Hash, Equal > Class Template Reference
#include <ChainSet.h>
Public Types
typedef ChainHashSet< Key,
Hash, Equal > set_type
typedef ChainHashMap< Key, Key,
Hash, Equal > table_type
typedef ChainHashMap< Key, Key,
Hash, Equal >::iterator iterator
typedef ChainHashMap< Key, Key,
Hash, Equal >::const_iterator const_iterator
typedef table_type::size_type size_type
typedef table_type::percent_type percent_type
typedef table_type::key_type key_type
Public Member Functions
ChainHashSet (size_type n=12, percent_type max_load=75)
ChainHashSet (const set_type &)=delete
ChainHashSet (set_type &&set)
size_type size () const
size_type capacity () const
percent_type max_load () const
bool empty () const
const table_type * get_backing_table () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void clear () noexcept
template<typename K >
Pair< iterator, bool > insert (K &&key)
bool contains (const key_type &key) const
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
iterator erase (const iterator &pos)
bool erase (const key_type &key)
set_type & operator= (const set_type &)=delete
set_type & operator= (set_type &&set)
Private Attributes
table_type m_hash_map
Detailed Description
template<class Key, class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>>
class wlp::ChainHashSet< Key, Hash, Equal >
Hash set implementation using separate chaining. This implementation supports removal operations, unlike the open addressed set.
Template Parameters
Key the element type
Hash the hash function
Equal the equality function
Definition at line 32 of file ChainSet.h.
Member Typedef Documentation
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef ChainHashMap<Key, Key, Hash, Equal>::const_iterator wlp::ChainHashSet< Key, Hash, Equal >::const_iterator
Definition at line 37 of file ChainSet.h.
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef ChainHashMap<Key, Key, Hash, Equal>::iterator wlp::ChainHashSet< Key, Hash, Equal >::iterator
Definition at line 36 of file ChainSet.h.
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef table_type::key_type wlp::ChainHashSet< Key, Hash, Equal >::key_type
Definition at line 40 of file ChainSet.h.
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef table_type::percent_type wlp::ChainHashSet< Key, Hash, Equal >::percent_type
Definition at line 39 of file ChainSet.h.
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef ChainHashSet<Key, Hash, Equal> wlp::ChainHashSet< Key, Hash, Equal >::set_type
Definition at line 34 of file ChainSet.h.
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef table_type::size_type wlp::ChainHashSet< Key, Hash, Equal >::size_type
Definition at line 38 of file ChainSet.h.
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> typedef ChainHashMap<Key, Key, Hash, Equal> wlp::ChainHashSet< Key, Hash, Equal >::table_type
Definition at line 35 of file ChainSet.h.
Constructor & Destructor Documentation
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> wlp::ChainHashSet< Key, Hash, Equal >::ChainHashSet (size_type n = 12, percent_type max_load = 75) inline explicit
Construct a chained hash set, which creates the backing chain hash map instance.
Parameters
n the initial size of the backing array
max_load the maximum load factor before rehash
Definition at line 52 of file ChainSet.h.
                 : m_hash_map(n, max_load) {
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> wlp::ChainHashSet< Key, Hash, Equal >::ChainHashSet (const set_type &) delete
Disable copy constructor.
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> wlp::ChainHashSet< Key, Hash, Equal >::ChainHashSet (set_type && set) inline
Move constructor.
Parameters
set hash set to move
Definition at line 68 of file ChainSet.h.
                 : m_hash_map(move(set.m_hash_map)) {
         }
Member Function Documentation
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> iterator wlp::ChainHashSet< Key, Hash, Equal >::begin () inline
An iterator instance to the beginning of the hash set. The iterator order of the set is not guaranteed to be in any particular order.
Returns
iterator to the first element, or
end
if the set is empty
Definition at line 114 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::begin(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.begin();
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> const_iterator wlp::ChainHashSet< Key, Hash, Equal >::begin () const inline
Returns
a constant iterator to the first element
Definition at line 131 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::begin(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.begin();
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> size_type wlp::ChainHashSet< Key, Hash, Equal >::capacity () const inline
Returns
the size of the backing array
Definition at line 82 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::capacity(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.capacity();
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> void wlp::ChainHashSet< Key, Hash, Equal >::clear () inline noexcept
Empty the elements in the set, such that its size is now zero.
Definition at line 146 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::clear(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             m_hash_map.clear();
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> bool wlp::ChainHashSet< Key, Hash, Equal >::contains (const key_type & key) const inline
Check if an element is in the set.
Parameters
key element whose existence to check
Returns
true if the element is contained in the set
Definition at line 169 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::contains(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.contains(key);
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> bool wlp::ChainHashSet< Key, Hash, Equal >::empty () const inline
Returns
whether the hash map is empty
Definition at line 96 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::empty(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.empty();
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> iterator wlp::ChainHashSet< Key, Hash, Equal >::end () inline
A pass-the-end iterator instance. This iterator means that an iterator has read past the end of the set and has become invalid.
Returns
a pass-the-end iterator
Definition at line 124 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::end(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.end();
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> const_iterator wlp::ChainHashSet< Key, Hash, Equal >::end () const inline
Returns
a constant pass-the-end iterator
Definition at line 138 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::end(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.end();
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> iterator wlp::ChainHashSet< Key, Hash, Equal >::erase (const iterator & pos) inline
Erase an element pointed to be an iterator. This function will move the provided iterator to the next element and return a copy of that iterator.
Parameters
pos the iterator whose element to erase
Returns
an iterator to the next element, or pass the end if the iteration has reached the end
Definition at line 202 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::erase(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.erase(pos);
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> bool wlp::ChainHashSet< Key, Hash, Equal >::erase (const key_type & key) inline
Remove a value from the set.
Parameters
key the value to remove
Returns
true if the value was removed, false if the value was never in the set
Definition at line 212 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::erase(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.erase(key);
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> iterator wlp::ChainHashSet< Key, Hash, Equal >::find (const key_type & key) inline
Obtain an iterator to an element in the set.
Parameters
key the element to find
Returns
iterator to the element or pass-the-end if the element is not in the set
Definition at line 179 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::find(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.find(key);
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> const_iterator wlp::ChainHashSet< Key, Hash, Equal >::find (const key_type & key) const inline
Obtain a const iterator to an element in the set
Parameters
key the element to find
Returns
const iterator to the element or pass-the-end if the element is not in the set
Definition at line 189 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::find(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.find(key);
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> const table_type* wlp::ChainHashSet< Key, Hash, Equal >::get_backing_table () const inline
Returns
a pointer to the backing hash map
Definition at line 103 of file ChainSet.h.
References wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return &m_hash_map;
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> template<typename K > Pair<iterator, bool> wlp::ChainHashSet< Key, Hash, Equal >::insert (K && key) inline
Insert an element into the set. This function returns a pair consistent of the iterator to the element that was inserted or to the element that prevented insertion. The second boolean value indicates whether insertion took place.
Parameters
key the element to insert
Returns
a pair of an iterator and boolean
Definition at line 160 of file ChainSet.h.
References wlp::ChainHashMap< Key, Val, Hasher, Equals >::insert(), and wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map.
{
             return m_hash_map.insert(forward<K>(key), forward<K>(key));
         };
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> percent_type wlp::ChainHashSet< Key, Hash, Equal >::max_load () const inline
Returns
the maximum load factor
Definition at line 89 of file ChainSet.h.
References wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map, and wlp::ChainHashMap< Key, Val, Hasher, Equals >::max_load().
{
             return m_hash_map.max_load();
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> set_type& wlp::ChainHashSet< Key, Hash, Equal >::operator= (const set_type &) delete
Disable copy assignment.
Returns
reference to this set
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> set_type& wlp::ChainHashSet< Key, Hash, Equal >::operator= (set_type && set) inline
Move assignment operator.
Parameters
set hash set to move
Returns
reference to this set
Definition at line 229 of file ChainSet.h.
References wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map, and wlp::move().
{
             m_hash_map = move(set.m_hash_map);
             return *this;
         }
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> size_type wlp::ChainHashSet< Key, Hash, Equal >::size () const inline
Returns
the current number of elements in the set
Definition at line 75 of file ChainSet.h.
References wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map, and wlp::ChainHashMap< Key, Val, Hasher, Equals >::size().
{
             return m_hash_map.size();
         }
Field Documentation
template<class Key , class Hash = Hash<Key, uint16_t>, class Equal = Equal<Key>> table_type wlp::ChainHashSet< Key, Hash, Equal >::m_hash_map private
Definition at line 43 of file ChainSet.h.
Referenced by wlp::ChainHashSet< Key, Hash, Equal >::begin(), wlp::ChainHashSet< Key, Hash, Equal >::capacity(), wlp::ChainHashSet< Key, Hash, Equal >::clear(), wlp::ChainHashSet< Key, Hash, Equal >::contains(), wlp::ChainHashSet< Key, Hash, Equal >::empty(), wlp::ChainHashSet< Key, Hash, Equal >::end(), wlp::ChainHashSet< Key, Hash, Equal >::erase(), wlp::ChainHashSet< Key, Hash, Equal >::find(), wlp::ChainHashSet< Key, Hash, Equal >::get_backing_table(), wlp::ChainHashSet< Key, Hash, Equal >::insert(), wlp::ChainHashSet< Key, Hash, Equal >::max_load(), wlp::ChainHashSet< Key, Hash, Equal >::operator=(), and wlp::ChainHashSet< Key, Hash, Equal >::size().
The documentation for this class was generated from the following file:
stl/ChainSet.h