Waterloop Wlib: wlp::static_string< tSize > Class Template Reference
wlp::static_string< tSize > Class Template Reference
#include <String.h>
Public Types
typedef StringIterator
< static_string< tSize >, char
&, char * > iterator
typedef StringIterator< const
static_string< tSize >, const
char &, const char * > const_iterator
typedef wlp::size_type size_type
typedef wlp::diff_type diff_type
Public Member Functions
static_string ()
static_string (const static_string< tSize > &str)
static_string (const char *str)
static_string (const dynamic_string &str)
static_string (const char *str, size_type len)
static_string< tSize > & operator= (const static_string< tSize > &str)
static_string< tSize > & operator= (const dynamic_string &str)
static_string< tSize > & operator= (static_string< tSize > &&str) noexcept
static_string< tSize > & operator= (const char *str)
static_string< tSize > & operator= (const char c)
size_type length () const
size_type capacity () const
bool empty () const
void clear () noexcept
char & operator[] (size_type pos)
const char & operator[] (size_type pos) const
char & at (size_type pos)
const char & at (size_type pos) const
char & back ()
const char & back () const
char & front ()
const char & front () const
static_string< tSize > & operator+= (const static_string< tSize > &other)
static_string< tSize > & operator+= (const dynamic_string &str)
static_string< tSize > & operator+= (const char *val)
static_string< tSize > & operator+= (char c)
static_string< tSize > operator+ (const dynamic_string &str) const
static_string< tSize > operator+ (const static_string< tSize > &str) const
static_string< tSize > operator= (const static_string< tSize > &str) const
static_string< tSize > & append (const static_string< tSize > &str)
static_string< tSize > & append (const dynamic_string &str)
static_string< tSize > & append (const char *str)
static_string< tSize > & append (const char *str, size_type len)
void push_back (char c)
void erase (size_type pos=0)
void pop_back ()
char * c_str ()
const char * c_str () const
static_string< tSize > substr (size_type pos, size_type length) const
diff_type compare (const static_string< tSize > &str) const
diff_type compare (const dynamic_string &str) const
diff_type compare (const char *str) const
diff_type compare (char c) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool operator== (const static_string< tSize > &str) const
bool operator!= (const static_string< tSize > &str) const
bool operator> (const static_string< tSize > &str) const
bool operator>= (const static_string< tSize > &str) const
bool operator< (const static_string< tSize > &str) const
bool operator<= (const static_string< tSize > &str) const
bool operator== (const dynamic_string &str) const
bool operator!= (const dynamic_string &str) const
bool operator> (const dynamic_string &str) const
bool operator>= (const dynamic_string &str) const
bool operator< (const dynamic_string &str) const
bool operator<= (const dynamic_string &str) const
Private Member Functions
static_string (const char *str1, const char *str2, size_type len1, size_type len2)
Private Attributes
char m_buffer [tSize+1]
size_type m_len
Friends
template<size_type size>
static_string< size > operator+ (const static_string< size > &, const char *)
template<size_type size>
static_string< size > operator+ (const char *, const static_string< size > &)
template<size_type size>
static_string< size > operator+ (const static_string< size > &, char)
template<size_type size>
static_string< size > operator+ (char, const static_string< size > &)
Detailed Description
template<size_type tSize>
class wlp::static_string< tSize >
Definition at line 25 of file String.h.
Member Typedef Documentation
template<size_type tSize> typedef StringIterator<const static_string<tSize>, const char &, const char *> wlp::static_string< tSize >::const_iterator
Definition at line 34 of file String.h.
template<size_type tSize> typedef wlp::diff_type wlp::static_string< tSize >::diff_type
Definition at line 38 of file String.h.
template<size_type tSize> typedef StringIterator<static_string<tSize>, char &, char *> wlp::static_string< tSize >::iterator
Definition at line 33 of file String.h.
template<size_type tSize> typedef wlp::size_type wlp::static_string< tSize >::size_type
Definition at line 37 of file String.h.
Constructor & Destructor Documentation
template<size_type tSize> wlp::static_string< tSize >::static_string () inline
Default constructor creates string with no character
Definition at line 43 of file String.h.
References wlp::static_string< tSize >::clear().
{
             clear();
         }
template<size_type tSize> wlp::static_string< tSize >::static_string (const static_string< tSize > & str) inline
Constructor creates string using static string object
Parameters
str@code StaticString object
Definition at line 52 of file String.h.
References wlp::static_string< tSize >::c_str().
                 : static_string{str.c_str()} {}
template<size_type tSize> wlp::static_string< tSize >::static_string (const char * str) inline explicit
Constructor creates string using character array
Parameters
str char string
Definition at line 60 of file String.h.
                 : static_string(str, static_cast<size_type>(strlen(str))) {}
template<size_type tSize> wlp::static_string< tSize >::static_string (const dynamic_string & str) explicit
Construct a Static String from a Dynamic String.
Parameters
str dynamic string
Definition at line 1198 of file String.h.
             : static_string(str.c_str(), str.length()) {
     }
template<size_type tSize> wlp::static_string< tSize >::static_string (const char * str, size_type len) inline
Construct a Static String from a character array and a known length.
Parameters
str character array
len length of the array
Definition at line 76 of file String.h.
References wlp::static_string< tSize >::m_buffer, wlp::static_string< tSize >::m_len, and MIN.
{
             m_len = MIN(len, tSize);
             memcpy(m_buffer, str, m_len);
             m_buffer[m_len] = '\0';
         }
template<size_type tSize> wlp::static_string< tSize >::static_string (const char * str1, const char * str2, size_type len1, size_type len2) inline private
Definition at line 584 of file String.h.
References wlp::static_string< tSize >::m_buffer, wlp::static_string< tSize >::m_len, and MIN.
{
             m_len = MIN(static_cast<size_type>(len1 + len2), tSize);
             size_type min_len = MIN(m_len, len1);
             memcpy(m_buffer, str1, min_len);
             memcpy(m_buffer + min_len, str2, m_len - min_len);
             m_buffer[m_len] = '\0';
         }
Member Function Documentation
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::append (const static_string< tSize > & str) inline
Appends a
StaticString
string to the current string. If String cannot hold the given string, it does not add it
Parameters
str@code StaticString string to add
Returns
the current string
Definition at line 338 of file String.h.
References wlp::static_string< tSize >::c_str(), and wlp::static_string< tSize >::length().
Referenced by wlp::static_string< tSize >::append(), and wlp::static_string< tSize >::operator+=().
{
             return append(str.c_str(), str.length());
         }
template<size_type tSize> static_string< tSize > & wlp::static_string< tSize >::append (const dynamic_string & str)
Append the contents of a Dynamic String to this string. Function truncates excess elements.
Parameters
str dynamic string to append
Returns
reference to this string
Definition at line 1216 of file String.h.
References wlp::dynamic_string::c_str(), and wlp::dynamic_string::length().
{
         return append(str.c_str(), str.length());
     }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::append (const char * str) inline
Append a character array with unknown length.
Parameters
str character array
Returns
reference to this string
Definition at line 357 of file String.h.
References wlp::static_string< tSize >::append().
{
             return append(str, static_cast<size_type>(strlen(str)));
         }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::append (const char * str, size_type len) inline
Appends a character string to the current string. The function truncates excess elements.
Parameters
str character string to add
Returns
the current string
Definition at line 368 of file String.h.
References wlp::static_string< tSize >::m_buffer, wlp::static_string< tSize >::m_len, and MIN.
{
             char *start = m_buffer + m_len;
             size_type new_len = MIN(tSize, static_cast<size_type>(m_len + len));
             memcpy(start, str, new_len - m_len);
             m_len = new_len;
             m_buffer[m_len] = '\0';
             return *this;
         }
template<size_type tSize> char& wlp::static_string< tSize >::at (size_type pos) inline
Provides access to character at pos. If the pos is out of bounds, last element is returned
Parameters
pos the position of the character
Returns
character at pos
Definition at line 207 of file String.h.
References wlp::static_string< tSize >::back(), wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
Referenced by wlp::operator!=(), wlp::operator==(), and wlp::static_string< tSize >::operator[]().
{
             if (pos >= m_len) { return back(); }
             return m_buffer[pos];
         }
template<size_type tSize> const char& wlp::static_string< tSize >::at (size_type pos) const inline
Provides access to character at pos. If the pos is out of bounds, last element is returned
Parameters
pos the position of the character
Returns
character at pos
Definition at line 220 of file String.h.
References wlp::static_string< tSize >::back(), wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             if (pos >= m_len) { return back(); }
             return m_buffer[pos];
         }
template<size_type tSize> char& wlp::static_string< tSize >::back () inline
Provides access to the last character in the string
Returns
the last character
Definition at line 231 of file String.h.
References wlp::static_string< tSize >::empty(), wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
Referenced by wlp::static_string< tSize >::at().
                      {
             if (empty()) { return m_buffer[0]; }
             return m_buffer[m_len - 1];
         }
template<size_type tSize> const char& wlp::static_string< tSize >::back () const inline
Provides access to the last character in the string. Character is constant
Returns
the last character
Definition at line 241 of file String.h.
References wlp::static_string< tSize >::empty(), wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             if (empty()) { return m_buffer[0]; }
             return m_buffer[m_len - 1];
         }
template<size_type tSize> iterator wlp::static_string< tSize >::begin () inline
Returns
iterator to the first character in the string
Definition at line 509 of file String.h.
{
             return iterator(0, this);
         }
template<size_type tSize> const_iterator wlp::static_string< tSize >::begin () const inline
Returns
const iterator to the first character in the string
Definition at line 523 of file String.h.
{
             return const_iterator(0, this);
         }
template<size_type tSize> char* wlp::static_string< tSize >::c_str () inline
Provides access to the backing character array.
Returns
character array
Definition at line 419 of file String.h.
References wlp::static_string< tSize >::m_buffer.
Referenced by wlp::comparator< static_string< tSize > >::__eq__(), wlp::comparator< static_string< tSize > >::__ge__(), wlp::comparator< static_string< tSize > >::__gt__(), wlp::comparator< static_string< tSize > >::__le__(), wlp::comparator< static_string< tSize > >::__lt__(), wlp::comparator< static_string< tSize > >::__ne__(), wlp::static_string< tSize >::append(), wlp::static_string< tSize >::compare(), wlp::equals< static_string< tSize > >::operator()(), wlp::equals< const static_string< tSize > >::operator()(), wlp::operator+(), and wlp::static_string< tSize >::static_string().
                       {
             return m_buffer;
         }
template<size_type tSize> const char* wlp::static_string< tSize >::c_str () const inline
Provides access to the backing character array.
Returns
character array
Definition at line 428 of file String.h.
References wlp::static_string< tSize >::m_buffer.
{
             return m_buffer;
         }
template<size_type tSize> size_type wlp::static_string< tSize >::capacity () const inline
Provides the maximum capacity of string
Returns
string capacity
Definition at line 157 of file String.h.
{
             return tSize;
         }
template<size_type tSize> void wlp::static_string< tSize >::clear () inline noexcept
Clears the string such that there are no characters left in it
Definition at line 173 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
Referenced by wlp::static_string< tSize >::static_string().
{
             m_buffer[0] = '\0';
             m_len = 0;
         }
template<size_type tSize> diff_type wlp::static_string< tSize >::compare (const static_string< tSize > & str) const inline
Compares two strings and return 0 if they are equal, less than 0 if given string is less than current string and greater than 0 if given string is greater than current string
Parameters
str@code StaticString string to compare against current string
Returns
a signed number based on how strings compare
Definition at line 462 of file String.h.
References wlp::static_string< tSize >::c_str().
Referenced by wlp::static_string< tSize >::operator!=(), wlp::operator!=(), wlp::static_string< tSize >::operator<(), wlp::static_string< tSize >::operator<=(), wlp::static_string< tSize >::operator==(), wlp::operator==(), wlp::static_string< tSize >::operator>(), wlp::operator>(), wlp::static_string< tSize >::operator>=(), and wlp::operator>=().
{
             return compare(str.c_str());
         }
template<size_type tSize> diff_type wlp::static_string< tSize >::compare (const dynamic_string & str) const
Compare with a Dynamic String. Returns 0 if equal, negative if this string is less, and positive if this string is greater.
Parameters
str dynamic string with which to compare
Returns
signed difference number
Definition at line 1221 of file String.h.
References wlp::dynamic_string::c_str().
{
         return compare(str.c_str());
     }
template<size_type tSize> diff_type wlp::static_string< tSize >::compare (const char * str) const inline
Compares two strings and return 0 if they are equal, less than 0 if given string is less than current string and greater than 0 if given string is greater than current string
Parameters
str character string to compare against current string
Returns
a signed number based on how strings compare
Definition at line 483 of file String.h.
References wlp::static_string< tSize >::c_str().
{
             return static_cast<diff_type>(strcmp(this->c_str(), str));
         }
template<size_type tSize> diff_type wlp::static_string< tSize >::compare (char c) const inline
Compares a string and a char and return 0 if they are equal, less than 0 if given char is less than current string and greater than 0 if given char is greater than current string
Parameters
c character to compare against current string
Returns
a signed number based on how strings compare
Definition at line 495 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             if (!m_len) {
                 return -1;
             }
             diff_type first = static_cast<diff_type>(m_buffer[0] - c);
             if (!first) {
                 return m_len > 1;
             }
             return first;
         }
template<size_type tSize> bool wlp::static_string< tSize >::empty () const inline
Checks if string is empty or not
Returns
if string is empty or not
Definition at line 166 of file String.h.
References wlp::static_string< tSize >::m_len.
Referenced by wlp::static_string< tSize >::back().
{
             return m_len == 0;
         }
template<size_type tSize> iterator wlp::static_string< tSize >::end () inline
Returns
pass-the-end iterator
Definition at line 516 of file String.h.
References wlp::static_string< tSize >::m_len.
{
             return iterator(m_len, this);
         }
template<size_type tSize> const_iterator wlp::static_string< tSize >::end () const inline
Returns
pass-the-end iterator
Definition at line 530 of file String.h.
References wlp::static_string< tSize >::m_len.
{
             return const_iterator(m_len, this);
         }
template<size_type tSize> void wlp::static_string< tSize >::erase (size_type pos = 0) inline
Deletes the element pos from the String
Parameters
pos position of the element to be deleted
Returns
the modified String
Definition at line 398 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             if (m_len == 0 || pos >= m_len) { return; }
             --m_len;
             memmove(m_buffer + pos, m_buffer + pos + 1, m_len - pos);
             m_buffer[m_len] = '\0';
         }
template<size_type tSize> char& wlp::static_string< tSize >::front () inline
Provides access to the first character in the string
Returns
the first character
Definition at line 251 of file String.h.
References wlp::static_string< tSize >::m_buffer.
                       {
             return m_buffer[0];
         }
template<size_type tSize> const char& wlp::static_string< tSize >::front () const inline
Provides access to the first character in the string. Character is constant
Returns
the first character
Definition at line 260 of file String.h.
References wlp::static_string< tSize >::m_buffer.
{
             return m_buffer[0];
         }
template<size_type tSize> size_type wlp::static_string< tSize >::length () const inline
Provides current length of string
Returns
string length
Definition at line 148 of file String.h.
References wlp::static_string< tSize >::m_len.
Referenced by wlp::static_string< tSize >::append(), wlp::hash_static_string(), wlp::operator!=(), wlp::operator+(), wlp::operator==(), and wlp::static_string< tSize >::substr().
{
             return m_len;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator!= (const static_string< tSize > & str) const inline
Definition at line 539 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) != 0;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator!= (const dynamic_string & str) const inline
Definition at line 563 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) != 0;
         }
template<size_type tSize> static_string< tSize > wlp::static_string< tSize >::operator+ (const dynamic_string & str) const
Add a static string to a dynamic string.
Parameters
str dynamic string to add
Returns
a new static string containing the most contents of both strings
Definition at line 1211 of file String.h.
References wlp::dynamic_string::c_str(), and wlp::dynamic_string::length().
{
         return {m_buffer, str.c_str(), m_len, str.length()};
     }
template<size_type tSize> static_string<tSize> wlp::static_string< tSize >::operator+ (const static_string< tSize > & str) const inline
Definition at line 317 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             return {m_buffer, str.m_buffer, m_len, str.m_len};
         }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::operator+= (const static_string< tSize > & other) inline
Modifier operator adds
StaticString
object to the current string. If String cannot hold the given object string, it does not add it
Parameters
other@code StaticString string to add
Returns
the current string
Definition at line 271 of file String.h.
References wlp::static_string< tSize >::append().
{
             return append(other);
         }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::operator+= (const dynamic_string & str) inline
Append the contents of a Dynamic String. Excess characters will be truncated.
Parameters
str dynamic string to append
Returns
reference to this string
Definition at line 282 of file String.h.
References wlp::static_string< tSize >::append().
{
             return append(str);
         }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::operator+= (const char * val) inline
Modifier operator adds char string to the current string. If String cannot hold the given string, it does not add it
Parameters
val char string to add
Returns
the current string
Definition at line 293 of file String.h.
References wlp::static_string< tSize >::append().
{
             return append(val, static_cast<size_type>(strlen(val)));
         }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::operator+= (char c) inline
Modifier operator adds character to the current string. If String cannot hold the character, it does not add it
Parameters
c character to add
Returns
the current string
Definition at line 304 of file String.h.
References wlp::static_string< tSize >::push_back().
{
             push_back(c);
             return *this;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator< (const static_string< tSize > & str) const inline
Definition at line 551 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) < 0;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator< (const dynamic_string & str) const inline
Definition at line 575 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) < 0;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator<= (const static_string< tSize > & str) const inline
Definition at line 555 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) <= 0;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator<= (const dynamic_string & str) const inline
Definition at line 579 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) <= 0;
         }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::operator= (const static_string< tSize > & str) inline
Assign operator assigns current object to given object
Parameters
str@code StaticString object
Returns
current object
Definition at line 88 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             m_len = str.m_len;
             memcpy(m_buffer, str.m_buffer, m_len + 1);
             return *this;
         }
template<size_type tSize> static_string< tSize > & wlp::static_string< tSize >::operator= (const dynamic_string & str)
Assignment operator to copy a Dynamic String
Parameters
str dynamic string to copy
Returns
reference to this string
Definition at line 1203 of file String.h.
References wlp::dynamic_string::c_str(), wlp::dynamic_string::length(), and MIN.
{
         m_len = MIN(str.length(), tSize);
         memcpy(m_buffer, str.c_str(), m_len);
         m_buffer[m_len] = '\0';
         return *this;
     }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::operator= (static_string< tSize > && str) inline noexcept
The move assignment operator for a StaticString must do a copy of the static array. This function exists for string concept.
Parameters
str string to move
Returns
reference to this string
Definition at line 110 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             m_len = str.m_len;
             memcpy(m_buffer, str.m_buffer, m_len + 1);
             return *this;
         }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::operator= (const char * str) inline
Assign operator assigns current object to a given character string
Parameters
str character string
Returns
current object
Definition at line 122 of file String.h.
References wlp::static_string< tSize >::m_buffer, wlp::static_string< tSize >::m_len, and MIN.
{
             m_len = MIN(static_cast<size_type>(strlen(str)), tSize);
             memcpy(m_buffer, str, m_len + 1);
             return *this;
         }
template<size_type tSize> static_string<tSize>& wlp::static_string< tSize >::operator= (const char c) inline
Assign operator assigns current object to given character
Parameters
c given character
Returns
current object
Definition at line 134 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             if (tSize == 0) {
                 return *this;
             }
             m_len = 1;
             reinterpret_cast<uint16_t *>(m_buffer)[0] = static_cast<uint16_t>(c);
             return *this;
         }
template<size_type tSize> static_string<tSize> wlp::static_string< tSize >::operator= (const static_string< tSize > & str) const inline
Add a static string to a static string.
Parameters
str static string to add
Returns
a new static string containing the most contents of both strings
Definition at line 327 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             return {m_buffer, str.m_buffer, m_len, str.m_len};
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator== (const static_string< tSize > & str) const inline
Definition at line 535 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) == 0;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator== (const dynamic_string & str) const inline
Definition at line 559 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) == 0;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator> (const static_string< tSize > & str) const inline
Definition at line 543 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) > 0;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator> (const dynamic_string & str) const inline
Definition at line 567 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) > 0;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator>= (const static_string< tSize > & str) const inline
Definition at line 547 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) >= 0;
         }
template<size_type tSize> bool wlp::static_string< tSize >::operator>= (const dynamic_string & str) const inline
Definition at line 571 of file String.h.
References wlp::static_string< tSize >::compare().
{
             return compare(str) >= 0;
         }
template<size_type tSize> char& wlp::static_string< tSize >::operator[] (size_type pos) inline
Element access operator gives access to character at pos
Parameters
pos the position of the character
Returns
character at pos
Definition at line 184 of file String.h.
References wlp::static_string< tSize >::at().
{
             return at(pos);
         }
template<size_type tSize> const char& wlp::static_string< tSize >::operator[] (size_type pos) const inline
Element access operator gives access to character at pos. Character is constant
Parameters
pos the position of the character
Returns
character at pos
Definition at line 195 of file String.h.
References wlp::static_string< tSize >::at().
{
             return at(pos);
         }
template<size_type tSize> void wlp::static_string< tSize >::pop_back () inline
Deletes the last character in the String
Definition at line 408 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             if (m_len == 0) { return; }
             --m_len;
             m_buffer[m_len] = '\0';
         }
template<size_type tSize> void wlp::static_string< tSize >::push_back (char c) inline
Appends a character to the current string. The function truncates excess elements.
Parameters
c character to add
Returns
the current string
Definition at line 384 of file String.h.
References wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
Referenced by wlp::static_string< tSize >::operator+=().
{
             if (m_len == tSize) {
                 return;
             }
             reinterpret_cast<uint16_t *>(m_buffer + m_len)[0] = static_cast<uint16_t>(c);
             ++m_len;
         }
template<size_type tSize> static_string<tSize> wlp::static_string< tSize >::substr (size_type pos, size_type length) const inline
Makes substring of the current string. If the pos is out of bounds, same String is returned. If the length of substring is too long, then a substring from pos to the end is returned;
Parameters
pos starting position
length length of the new string
Returns
new string which is a substring of current string
Definition at line 441 of file String.h.
References wlp::static_string< tSize >::length(), wlp::static_string< tSize >::m_buffer, and wlp::static_string< tSize >::m_len.
{
             if (pos >= m_len) {
                 return *this;
             }
             if (pos + length >= m_len) {
                 length = static_cast<size_type>(m_len - pos);
             }
             static_string<tSize> sub;
             memcpy(sub.m_buffer, m_buffer + pos, length);
             sub.m_buffer[length] = '\0';
             return sub;
         }
Friends And Related Function Documentation
template<size_type tSize> template<size_type size> static_string<size> operator+ (const static_string< size > & , const char *) friend
template<size_type tSize> template<size_type size> static_string<size> operator+ (const char * , const static_string< size > &) friend
template<size_type tSize> template<size_type size> static_string<size> operator+ (const static_string< size > & , char) friend
template<size_type tSize> template<size_type size> static_string<size> operator+ (char , const static_string< size > &) friend
Field Documentation
template<size_type tSize> char wlp::static_string< tSize >::m_buffer[tSize+1] private
Definition at line 592 of file String.h.
Referenced by wlp::static_string< tSize >::append(), wlp::static_string< tSize >::at(), wlp::static_string< tSize >::back(), wlp::static_string< tSize >::c_str(), wlp::static_string< tSize >::clear(), wlp::static_string< tSize >::compare(), wlp::static_string< tSize >::erase(), wlp::static_string< tSize >::front(), wlp::static_string< tSize >::operator+(), wlp::static_string< tSize >::operator=(), wlp::static_string< tSize >::pop_back(), wlp::static_string< tSize >::push_back(), wlp::static_string< tSize >::static_string(), and wlp::static_string< tSize >::substr().
template<size_type tSize> size_type wlp::static_string< tSize >::m_len private
Definition at line 593 of file String.h.
Referenced by wlp::static_string< tSize >::append(), wlp::static_string< tSize >::at(), wlp::static_string< tSize >::back(), wlp::static_string< tSize >::clear(), wlp::static_string< tSize >::compare(), wlp::static_string< tSize >::empty(), wlp::static_string< tSize >::end(), wlp::static_string< tSize >::erase(), wlp::static_string< tSize >::length(), wlp::static_string< tSize >::operator+(), wlp::static_string< tSize >::operator=(), wlp::static_string< tSize >::pop_back(), wlp::static_string< tSize >::push_back(), wlp::static_string< tSize >::static_string(), and wlp::static_string< tSize >::substr().
The documentation for this class was generated from the following file:
wlib/strings/String.h