Waterloop Wlib: comm/PacketConstructor.cpp File Reference
PacketConstructor.cpp File Reference
Creates a packet for sending data from the slave systems to the main computer.
#include "PacketConstructor.h"
Functions
uint32_t __encode_float18 (float val)
uint64_t __join_data (uint32_t bits1, uint32_t bits2, uint32_t bits3)
void __set_start_and_end (packet64 &packet)
void __set_packet_type (packet64 &packet, const packet_type &type)
void __set_packet_name (packet64 &packet, packet_name name)
void __set_bulk_data (packet64 &packet, uint64_t joined_bits)
Detailed Description
Creates a packet for sending data from the slave systems to the main computer.
Implements the functions defined in PacketConstructor.h.
Author
Heather D'Souza
Jeff Niu
Date
December 2, 2017
Bug:
No known bugs
Definition in file PacketConstructor.cpp.
Function Documentation
uint32_t __encode_float18 (float val) inline
Definition at line 17 of file PacketConstructor.cpp.
Referenced by wlp::__packet_maker::build().
{
     uint32_t sign = 0;
     if (val < 0) {
         sign = 1;
         val = -val;
     }
     uint16_t int_part = static_cast<uint16_t>(val);
     uint16_t float_part = static_cast<uint16_t>(floorf(((val - int_part) * 100) + 0.5f));
     uint32_t res = (sign << 17) | (int_part << 7) | float_part;
     return res;
 }
uint64_t __join_data (uint32_t bits1, uint32_t bits2, uint32_t bits3) inline
Definition at line 29 of file PacketConstructor.cpp.
Referenced by wlp::__packet_maker::build().
{
     return static_cast<uint64_t>(bits1) | (static_cast<uint64_t>(bits2) << 18) | (static_cast<uint64_t>(bits3) << 36);
 }
void __set_bulk_data (packet64 & packet, uint64_t joined_bits) inline
Definition at line 46 of file PacketConstructor.cpp.
Referenced by wlp::__packet_maker::build().
{
     *packet.data() |= static_cast<uint32_t>(joined_bits << 9);
     *(packet.data() + 1) |= static_cast<uint32_t>(joined_bits >> 23);
 }
void __set_packet_name (packet64 & packet, packet_name name) inline
Definition at line 42 of file PacketConstructor.cpp.
Referenced by wlp::__packet_maker::build().
{
     *packet.data() |= *name.data() << 3;
 }
void __set_packet_type (packet64 & packet, const packet_type & type) inline
Definition at line 38 of file PacketConstructor.cpp.
Referenced by wlp::__packet_maker::build().
{
     *packet.data() |= *type.data() << 1;
 }
void __set_start_and_end (packet64 & packet) inline
Definition at line 33 of file PacketConstructor.cpp.
Referenced by wlp::__packet_maker::build().
{
     packet.set(0);
     packet.set(63);
 }