Waterloop Wlib: wlp::WeakPtr< T > Class Template Reference
wlp::WeakPtr< T > Class Template Reference
#include <SharedPtr.h>
Public Types
typedef T val_type
typedef ReferenceCount< T * >::ptr_use_count ptr_use_count
Public Member Functions
constexpr WeakPtr ()
template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type>
WeakPtr (const WeakPtr< U > &wp)
template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type>
WeakPtr (const SharedPtr< U > &sp)
template<typename U >
WeakPtr & operator= (const WeakPtr< U > &wp)
template<typename U >
WeakPtr & operator= (const SharedPtr< U > &sp)
SharedPtr< T > lock () const
ptr_use_count use_count () const
bool expired () const
template<typename U >
bool owner_before (const SharedPtr< U > &sp)
template<typename U >
bool owner_before (const WeakPtr< U > &wp)
void reset ()
void swap (WeakPtr< T > &wp)
Private Attributes
val_type * m_ptr
WeakCount< T * > m_refcount
Friends
template<typename U >
class SharedPtr
template<typename U >
class WeakPtr
Detailed Description
template<typename T>
class wlp::WeakPtr< T >
Definition at line 183 of file SharedPtr.h.
Member Typedef Documentation
ptr_use_count
template<typename T> typedef ReferenceCount<T *>::ptr_use_count wlp::WeakPtr< T >::ptr_use_count
Definition at line 662 of file SharedPtr.h.
val_type
template<typename T> typedef T wlp::WeakPtr< T >::val_type
Definition at line 661 of file SharedPtr.h.
Constructor & Destructor Documentation
WeakPtr() [1/3]
template<typename T> constexpr wlp::WeakPtr< T >::WeakPtr () inline
Definition at line 674 of file SharedPtr.h.
           :
         constexpr WeakPtr()
                 : m_ptr(nullptr),
WeakPtr() [2/3]
template<typename T> template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type> wlp::WeakPtr< T >::WeakPtr (const WeakPtr< U > & wp) inline
Definition at line 682 of file SharedPtr.h.
References wlp::WeakPtr< T >::lock().
                 : m_refcount(wp.m_refcount) {
WeakPtr() [3/3]
template<typename T> template<typename U , typename = typename enable_if< is_convertible<U *, T *>::value >::type> wlp::WeakPtr< T >::WeakPtr (const SharedPtr< U > & sp) inline
Definition at line 690 of file SharedPtr.h.
                 : m_ptr(sp.m_ptr),
Member Function Documentation
expired()
template<typename T> bool wlp::WeakPtr< T >::expired () const inline
Definition at line 717 of file SharedPtr.h.
References wlp::WeakCount< Ptr >::use_count().
{
lock()
template<typename T> SharedPtr<T> wlp::WeakPtr< T >::lock () const inline
Definition at line 709 of file SharedPtr.h.
Referenced by wlp::WeakPtr< T >::operator=(), and wlp::WeakPtr< T >::WeakPtr().
{
operator=() [1/2]
template<typename T> template<typename U > WeakPtr& wlp::WeakPtr< T >::operator= (const WeakPtr< U > & wp) inline
Definition at line 696 of file SharedPtr.h.
References wlp::WeakPtr< T >::lock(), and wlp::WeakPtr< T >::m_refcount.
{
             m_ptr = wp.lock().get();
             m_refcount = wp.m_refcount;
operator=() [2/2]
template<typename T> template<typename U > WeakPtr& wlp::WeakPtr< T >::operator= (const SharedPtr< U > & sp) inline
Definition at line 703 of file SharedPtr.h.
References wlp::SharedPtr< T >::m_ptr, and wlp::SharedPtr< T >::m_refcount.
{
             m_ptr = sp.m_ptr;
             m_refcount = sp.m_refcount;
owner_before() [1/2]
template<typename T> template<typename U > bool wlp::WeakPtr< T >::owner_before (const SharedPtr< U > & sp) inline
Definition at line 722 of file SharedPtr.h.
References wlp::WeakCount< Ptr >::less(), and wlp::SharedPtr< T >::m_refcount.
{
owner_before() [2/2]
template<typename T> template<typename U > bool wlp::WeakPtr< T >::owner_before (const WeakPtr< U > & wp) inline
Definition at line 727 of file SharedPtr.h.
References wlp::WeakCount< Ptr >::less(), and wlp::WeakPtr< T >::m_refcount.
{
reset()
template<typename T> void wlp::WeakPtr< T >::reset () inline
Definition at line 731 of file SharedPtr.h.
References wlp::WeakPtr< T >::swap().
                      {
swap()
template<typename T> void wlp::WeakPtr< T >::swap (WeakPtr< T > & wp) inline
Definition at line 735 of file SharedPtr.h.
References wlp::WeakPtr< T >::m_ptr, wlp::WeakPtr< T >::m_refcount, wlp::WeakCount< Ptr >::swap(), and wlp::swap().
Referenced by wlp::WeakPtr< T >::reset(), and wlp::swap().
{
             wlp::swap(m_ptr, wp.m_ptr);
use_count()
template<typename T> ptr_use_count wlp::WeakPtr< T >::use_count () const inline
Definition at line 713 of file SharedPtr.h.
References wlp::WeakCount< Ptr >::use_count().
{
Friends And Related Function Documentation
SharedPtr
template<typename T> template<typename U > friend class SharedPtr friend
Definition at line 666 of file SharedPtr.h.
WeakPtr
template<typename T> template<typename U > friend class WeakPtr friend
Definition at line 668 of file SharedPtr.h.
Field Documentation
m_ptr
template<typename T> val_type* wlp::WeakPtr< T >::m_ptr private
Definition at line 670 of file SharedPtr.h.
Referenced by wlp::WeakPtr< T >::swap().
m_refcount
template<typename T> WeakCount<T *> wlp::WeakPtr< T >::m_refcount private
Definition at line 671 of file SharedPtr.h.
Referenced by wlp::WeakPtr< T >::operator=(), wlp::SharedPtr< T >::owner_before(), wlp::WeakPtr< T >::owner_before(), and wlp::WeakPtr< T >::swap().
The documentation for this class was generated from the following file:
stl/SharedPtr.h