Waterloop Wlib: wlp::UniquePtr< T[]> Class Template Reference
wlp::UniquePtr< T[]> Class Template Reference
#include <UniquePtr.h>
Public Types
typedef T * pointer
typedef T val_type
Public Member Functions
UniquePtr ()
UniquePtr (pointer ptr)
~UniquePtr ()
unique_ptr & operator= (unique_ptr &&ptr)
template<typename U >
unique_ptr & operator= (UniquePtr< U > &&ptr)
unique_ptr & operator= (unspecified_pointer_type)
add_lvalue_reference< val_type >
::type operator[] (size_type i) const
pointer get () const
operator unspecified_bool_type () const
pointer release ()
void reset (pointer ptr=pointer())
template<typename U >
void reset (U)=delete
void swap (unique_ptr &&u)
Private Types
typedef T *UniquePtr::* unspecified_bool_type
typedef T *UniquePtr::* unspecified_pointer_type
typedef UniquePtr< T > unique_ptr
Private Member Functions
UniquePtr (const unique_ptr &)=delete
template<typename U >
UniquePtr (U *, typename enable_if< is_convertible< U *, pointer >::value >::type *=0)=delete
unique_ptr & operator= (const unique_ptr &)=delete
template<typename U , typename U_Deleter >
unique_ptr & operator= (const UniquePtr< U > &)=delete
Private Attributes
val_type * m_ptr
Detailed Description
template<typename T>
class wlp::UniquePtr< T[]>
Definition at line 148 of file UniquePtr.h.
Member Typedef Documentation
template<typename T > typedef T* wlp::UniquePtr< T[]>::pointer
Definition at line 154 of file UniquePtr.h.
template<typename T > typedef UniquePtr<T> wlp::UniquePtr< T[]>::unique_ptr private
Definition at line 151 of file UniquePtr.h.
template<typename T > typedef T* UniquePtr::* wlp::UniquePtr< T[]>::unspecified_bool_type private
Definition at line 149 of file UniquePtr.h.
template<typename T > typedef T* UniquePtr::* wlp::UniquePtr< T[]>::unspecified_pointer_type private
Definition at line 150 of file UniquePtr.h.
template<typename T > typedef T wlp::UniquePtr< T[]>::val_type
Definition at line 155 of file UniquePtr.h.
Constructor & Destructor Documentation
template<typename T > wlp::UniquePtr< T[]>::UniquePtr () inline
Definition at line 161 of file UniquePtr.h.
                 : m_ptr(pointer()) {
         }
template<typename T > wlp::UniquePtr< T[]>::UniquePtr (pointer ptr) inline explicit
Definition at line 166 of file UniquePtr.h.
                 : m_ptr(ptr) {
         }
template<typename T > wlp::UniquePtr< T[]>::~UniquePtr () inline
Definition at line 170 of file UniquePtr.h.
References wlp::UniquePtr< T >::reset().
                      {
             reset();
         }
template<typename T > wlp::UniquePtr< T[]>::UniquePtr (const unique_ptr &) private delete
template<typename T > template<typename U > wlp::UniquePtr< T[]>::UniquePtr (U * , typename enable_if< is_convertible< U *, pointer >::value >::type * = 0) explicit private delete
Member Function Documentation
template<typename T > pointer wlp::UniquePtr< T[]>::get () const inline
Definition at line 194 of file UniquePtr.h.
References wlp::UniquePtr< T >::m_ptr.
{
             return m_ptr;
         }
template<typename T > wlp::UniquePtr< T[]>::operator unspecified_bool_type () const inline
Definition at line 198 of file UniquePtr.h.
References wlp::UniquePtr< T >::m_ptr.
{
             return m_ptr == nullptr ? 0 : &unique_ptr::m_ptr;
         };
template<typename T > unique_ptr& wlp::UniquePtr< T[]>::operator= (unique_ptr && ptr) inline
Definition at line 174 of file UniquePtr.h.
References wlp::UniquePtr< T >::reset().
{
             reset(ptr.release());
             return *this;
         }
template<typename T > template<typename U > unique_ptr& wlp::UniquePtr< T[]>::operator= (UniquePtr< U > && ptr) inline
Definition at line 180 of file UniquePtr.h.
References wlp::UniquePtr< T >::reset().
{
             reset(ptr.release());
             return *this;
         };
template<typename T > unique_ptr& wlp::UniquePtr< T[]>::operator= (unspecified_pointer_type) inline
Definition at line 185 of file UniquePtr.h.
References wlp::UniquePtr< T >::reset().
{
             reset();
             return *this;
         }
template<typename T > unique_ptr& wlp::UniquePtr< T[]>::operator= (const unique_ptr &) private delete
template<typename T > template<typename U , typename U_Deleter > unique_ptr& wlp::UniquePtr< T[]>::operator= (const UniquePtr< U > &) private delete
template<typename T > add_lvalue_reference<val_type>::type wlp::UniquePtr< T[]>::operator[] (size_type i) const inline
Definition at line 190 of file UniquePtr.h.
References wlp::UniquePtr< T >::m_ptr.
{
             return m_ptr[i];
         }
template<typename T > pointer wlp::UniquePtr< T[]>::release () inline
Definition at line 202 of file UniquePtr.h.
References wlp::UniquePtr< T >::m_ptr.
{
             pointer ptr = m_ptr;
             m_ptr = nullptr;
             return ptr;
         }
template<typename T > void wlp::UniquePtr< T[]>::reset (pointer ptr = pointer()) inline
Definition at line 208 of file UniquePtr.h.
References wlp::UniquePtr< T >::m_ptr.
{
             if (ptr != m_ptr) {
                 free<val_type>(m_ptr);
                 m_ptr = ptr;
             }
         }
template<typename T > template<typename U > void wlp::UniquePtr< T[]>::reset (U) delete
template<typename T > void wlp::UniquePtr< T[]>::swap (unique_ptr && u) inline
Definition at line 218 of file UniquePtr.h.
References wlp::UniquePtr< T >::m_ptr, and wlp::swap().
{
             wlp::swap(m_ptr, u.m_ptr);
         }
Field Documentation
template<typename T > val_type* wlp::UniquePtr< T[]>::m_ptr private
Definition at line 158 of file UniquePtr.h.
The documentation for this class was generated from the following file:
stl/UniquePtr.h