Waterloop Wlib: wlp::state_machine Class Reference
wlp::state_machine Class Reference abstract
#include <StateMachine.h>
Public Types
enum { EVENT_IGNORED = 0xfe, CANNOT_HAPPEN }
Public Member Functions
state_machine (state_type maxStates, state_type initialState=0)
virtual ~state_machine ()
state_type current_state ()
state_type max_states ()
Protected Member Functions
template<typename sm_event_dataType >
void external_event (state_type newState, sm_event_dataType *pData=nullptr)
template<typename sm_event_dataType >
void internal_event (state_type newState, sm_event_dataType *pData=nullptr)
Private Member Functions
virtual const state_map_row * state_map ()=0
virtual const state_map_row_ex * state_map_ex ()=0
void set_current_state (state_type newState)
template<typename sm_event_dataType >
void state_engine ()
template<typename sm_event_dataType >
void state_engine (const state_map_row *const pStateMap)
template<typename sm_event_dataType >
void state_engine (const state_map_row_ex *const pStateMapEx)
Private Attributes
const state_type m_max_states
state_type m_current_state
state_type m_new_state
bool m_event_generated
sm_event_data * m_event_data
sm_event_data m_dataless
Detailed Description
state_machine implements a software-based state machine.
Definition at line 239 of file StateMachine.h.
Member Enumeration Documentation
anonymous enum
Enumerator
EVENT_IGNORED
CANNOT_HAPPEN
Definition at line 241 of file StateMachine.h.
              {
             EVENT_IGNORED = 0xfe, CANNOT_HAPPEN
         };
Constructor & Destructor Documentation
wlp::state_machine::state_machine (state_type maxStates, state_type initialState = 0) inline
Constructor for the state machine defines the maximum number of states the machine may occupy and the initial state of the machine
There can be at most 254 states whose ordinal values range from 0 to 253 inclusive. If the number of states exceeds this range, behaviour is undefined.
Parameters
maxStates machine number of states
initialState initial machine state
Definition at line 257 of file StateMachine.h.
References BAD_STATE_EXCEPTION, EVENT_IGNORED, m_max_states, and THROW.
                 : m_max_states(maxStates),
                   m_current_state(initialState),
                   m_new_state(0),
                   m_event_generated(false),
                   m_event_data(nullptr) {
             /* assert(m_max_states < EVENT_IGNORED) */
             if (m_max_states >= EVENT_IGNORED) {
                 THROW(BAD_STATE_EXCEPTION("Max states cannot equal or exceed EVENT_IGNORED"))
             }
         }
virtual wlp::state_machine::~state_machine () inline virtual
Definition at line 269 of file StateMachine.h.
 {}
Member Function Documentation
state_type wlp::state_machine::current_state () inline
Returns
the current state machine state as an ordinal value
Definition at line 275 of file StateMachine.h.
References m_current_state.
 { return m_current_state; }
template<typename sm_event_dataType > void wlp::state_machine::external_event (state_type newState, sm_event_dataType * pData = nullptr) inline protected
Trigger an external state machine event.
Parameters
newState the state machine state to which the machine should transition
pData the event data to send to the new state
Definition at line 293 of file StateMachine.h.
References CANNOT_HAPPEN, EVENT_IGNORED, ILLEGAL_TRANSITION_EXCEPTION, and THROW.
{
             if (newState == CANNOT_HAPPEN) {
                 THROW(ILLEGAL_TRANSITION_EXCEPTION("Transition cannot occur"))
             }
             if (newState != EVENT_IGNORED) {
                 internal_event<sm_event_dataType>(newState, pData);
                 state_engine<sm_event_dataType>();
             }
         }
template<typename sm_event_dataType > void wlp::state_machine::internal_event (state_type newState, sm_event_dataType * pData = nullptr) inline protected
Trigger an interval state machine event. These events are geneated while executing a state machine state.
Parameters
newState the state machine state to which the machine should transition
pData the event data to send to the new state
Definition at line 314 of file StateMachine.h.
References m_dataless, m_event_data, m_event_generated, and m_new_state.
{
             if (pData == nullptr) {
                 pData = static_cast<sm_event_dataType *>(&m_dataless);
             }
             m_event_data = pData;
             m_event_generated = true;
             m_new_state = newState;
         }
state_type wlp::state_machine::max_states () inline
Returns
the maximum ordinal value that a state may have
Definition at line 281 of file StateMachine.h.
References m_max_states.
 { return m_max_states; }
void wlp::state_machine::set_current_state (state_type newState) inline private
Set a new current state.
Parameters
newState the new state of the machine
Definition at line 389 of file StateMachine.h.
References m_current_state.
Referenced by state_engine().
 { m_current_state = newState; }
template<typename sm_event_dataType > void wlp::state_machine::state_engine () inline private
The state machine engine that executes the external events and, optionally, all internal events generated during state execution.
This function will pull the state map from the state map definition. If both the state map and the extended state map are undefined, no execution occurs.
Definition at line 400 of file StateMachine.h.
References BAD_STATE_EXCEPTION, state_map(), state_map_ex(), and THROW.
{
             const state_map_row *pStateMap = state_map();
             if (pStateMap != nullptr) {
                 state_engine<sm_event_dataType>(pStateMap);
             } else {
                 const state_map_row_ex *pStateMapEx = state_map_ex();
                 if (pStateMapEx != nullptr) {
                     state_engine<sm_event_dataType>(pStateMapEx);
                 } else {
                     /* fail() */
                     THROW(BAD_STATE_EXCEPTION("Unable to find state map"))
                 }
             }
         }
template<typename sm_event_dataType > void wlp::state_machine::state_engine (const state_map_row *const pStateMap) private
Execute the state transition as per the state map.
If at any moment an invalid state is provided, that is its ordinal value is not strictly less than the maximum number of states, or a state in the map is undefined, results are undefined.
Parameters
pStateMap the state machine state map
Definition at line 446 of file StateMachine.h.
References wlp::state_base::invoke_state_action(), m_event_data, m_event_generated, m_max_states, m_new_state, set_current_state(), wlp::state_map_row::state, THROW, and UNEXPECTED_STATE_EXCEPTION.
{
         sm_event_dataType *pDataTemp = nullptr;
         while (m_event_generated) {
             /* assert(m_new_state < m_max_states) */
             if (m_new_state >= m_max_states) {
                 THROW(UNEXPECTED_STATE_EXCEPTION("New state ordinal exceeds maximum states"))
             }
             const state_base *state = pStateMap[m_new_state].state;
             pDataTemp = static_cast<sm_event_dataType *>(m_event_data);
             m_event_data = nullptr;
             m_event_generated = false;
             set_current_state(m_new_state);
             /* assert(state != nullptr) */
             if (state == nullptr) {
                 THROW(UNEXPECTED_STATE_EXCEPTION("Target state does not exist"))
             }
             state->invoke_state_action(this, pDataTemp);
         }
     }
template<typename sm_event_dataType > void wlp::state_machine::state_engine (const state_map_row_ex *const pStateMapEx) private
Execute the state transition as per the state map. This function also checks against guards and executes entry and exit actions.
If at any moment an invalid state is provided, that is its ordinal value is not strictly less than the maximum number of states, or a state in the map is undefined, or an entry/exit action makes a call to interval event, results are undefined.
Parameters
pStateMapEx the state machine extended state map
Definition at line 467 of file StateMachine.h.
References wlp::state_map_row_ex::entry, wlp::state_map_row_ex::exit, wlp::state_map_row_ex::guard, wlp::entry_base::invoke_entry_action(), wlp::exit_base::invoke_exit_action(), wlp::guard_base::invoke_guard_action(), wlp::state_base::invoke_state_action(), m_current_state, m_event_data, m_event_generated, m_max_states, m_new_state, set_current_state(), wlp::state_map_row_ex::state, THROW, and UNEXPECTED_STATE_EXCEPTION.
{
         sm_event_dataType *pDataTemp = nullptr;
         while (m_event_generated) {
             /* assert(m_new_state < m_max_states) */
             if (m_new_state >= m_max_states) {
                 THROW(UNEXPECTED_STATE_EXCEPTION("New state ordinal exceeds maximum states"))
             }
             const state_base *state = pStateMapEx[m_new_state].state;
             const guard_base *guard = pStateMapEx[m_new_state].guard;
             const entry_base *entry = pStateMapEx[m_new_state].entry;
             const exit_base *exit = pStateMapEx[m_current_state].exit;
             pDataTemp = static_cast<sm_event_dataType *>(m_event_data);
             m_event_data = nullptr;
             m_event_generated = false;
             bool guardResult = true;
             if (guard != nullptr) {
                 guardResult = guard->invoke_guard_action(this, pDataTemp);
             }
             if (pDataTemp == nullptr) {
                 return;
             }
             if (guardResult) {
                 if (m_new_state != m_current_state) {
                     if (exit != nullptr) {
                         exit->invoke_exit_action(this);
                     }
                     if (entry != nullptr) {
                         entry->invoke_entry_action(this, pDataTemp);
                     }
                     /* assert(m_event_generated == false) */
                     if (m_event_generated) {
                         THROW(UNEXPECTED_STATE_EXCEPTION("Entry or Exit action cannot generate events"))
                     }
                 }
                 set_current_state(m_new_state);
                 /* assert(state != nullptr) */
                 if (state == nullptr) {
                     THROW(UNEXPECTED_STATE_EXCEPTION("Target state does not exist"))
                 }
                 state->invoke_state_action(this, pDataTemp);
             }
         }
     }
virtual const state_map_row* wlp::state_machine::state_map () private pure virtual
Get the state map as defined in a derived class of State Machine. The
BEGIN_STATE_MAP
,
STATE_MAP_ENTRY
, and
END_STATE_MAP
macros are used to assist in constructing the map. Derived classes only need to implement one of
state_map
and
state_map_ex
.
Returns
an array of state map rows with an array size of
MAX_STATES
or nullptr if the state machine uses
state_map_ex
Referenced by state_engine().
virtual const state_map_row_ex* wlp::state_machine::state_map_ex () private pure virtual
Get the extended state map as defined in the derived class of State Machine. The
BEGIN_STATE_MAP_EX
,
STATE_MAP_ENTRY_EX
,
STATE_MAP_ENTRY_ALL_EX
, and
END_STATE_MAP_EX
are used to assist in constructing the map.
Returns
an array of extended state map rows of size
MAX_STATES
or nullptr if the state machine uses
state_map
Referenced by state_engine().
Field Documentation
state_type wlp::state_machine::m_current_state private
The current state machine state as an ordinal value.
Definition at line 335 of file StateMachine.h.
Referenced by current_state(), set_current_state(), and state_engine().
sm_event_data wlp::state_machine::m_dataless private
Class-level event data instance used to represent an event with no data.
Definition at line 358 of file StateMachine.h.
Referenced by internal_event().
sm_event_data* wlp::state_machine::m_event_data private
The state event data pointer.
Definition at line 352 of file StateMachine.h.
Referenced by internal_event(), and state_engine().
bool wlp::state_machine::m_event_generated private
This value is set to true when an event is generated.
Definition at line 347 of file StateMachine.h.
Referenced by internal_event(), and state_engine().
const state_type wlp::state_machine::m_max_states private
The maximum number of state machine states, which also corresponds to the strict upper bound on the machine state ordinal value.
Definition at line 329 of file StateMachine.h.
Referenced by max_states(), state_engine(), and state_machine().
state_type wlp::state_machine::m_new_state private
The new state machine state to which the machine has yet to make the transition.
Definition at line 341 of file StateMachine.h.
Referenced by internal_event(), and state_engine().
The documentation for this class was generated from the following file:
wlib/fsm/StateMachine.h